import { Device } from '../../types/index.ts';
import { CameraConfigurationOperation,CameraConfigurationProposal } from '../../shared/camera_configuration.ts';
import { CameraDriverError,DriverCapability,DriverHttpTransport,DriverValues,HttpCameraVendorDriver,boundedReverify,escapeXml,normalizeMac,xmlText } from './camera_driver.ts';
export class HikvisionIsapiDriver extends HttpCameraVendorDriver{
 readonly id='HIKVISION_ISAPI'as const;readonly label='Hikvision ISAPI';readonly vendorTokens=['hikvision','hangzhou hikvision'];
 constructor(transport?:DriverHttpTransport,timeoutMs?:number){super(transport,timeoutMs)}
 capabilities():DriverCapability[]{const supported:DriverCapability[]=(['DEVICE_NAME','NTP','TIME_ZONE','ONVIF_ENABLE','REBOOT']as CameraConfigurationOperation[]).map(operation=>({operation,state:'SUPPORTED',detail:'Authenticated Hikvision ISAPI endpoint'}));return[...supported,{operation:'PASSWORD',state:'UNSUPPORTED',detail:'Password change remains manual until a safe endpoint is validated'},{operation:'IDENTITY',state:'SUPPORTED',detail:'ISAPI deviceInfo'},{operation:'NETWORK',state:'UNKNOWN',detail:'ISAPI network fallback is not enabled until read/write reverification is integrated'}]}
 private parseInfo(xml:string){if(!/<(?:\w+:)?DeviceInfo\b/i.test(xml))throw new CameraDriverError('Malformed Hikvision deviceInfo response.','MALFORMED_RESPONSE');return{manufacturer:xmlText(xml,'manufacturer'),model:xmlText(xml,'model'),serial:xmlText(xml,'serialNumber'),firmware:xmlText(xml,'firmwareVersion'),macAddress:normalizeMac(xmlText(xml,'macAddress')),hostname:xmlText(xml,'deviceName')}}
 async inspect(d:Device,c:{username:string;password:string},s?:AbortSignal){const info=this.parseInfo(await this.request(d,c,'/ISAPI/System/deviceInfo','GET',undefined,s));const values:DriverValues={deviceName:info.hostname};for(const[path,key]of[['/ISAPI/System/time/ntpServers/1','ntp'],['/ISAPI/System/time','time'],['/ISAPI/System/Network/ONVIF','onvif']]as const)try{const xml=await this.request(d,c,path,'GET',undefined,s);if(key==='ntp')values.ntp={fromDhcp:false,servers:[xmlText(xml,'hostName')||xmlText(xml,'ipAddress')].filter(Boolean)as string[]};else if(key==='time')values.timeZone=xmlText(xml,'timeZone');else values.onvifEnabled=/<(?:\w+:)?enabled>\s*true/i.test(xml)}catch(e){if(!(e instanceof CameraDriverError)||e.code!=='UNSUPPORTED')throw e}return{identity:info,values}}
 async apply(d:Device,c:{username:string;password:string},o:CameraConfigurationOperation,p:CameraConfigurationProposal,s?:AbortSignal){let path='',body='';if(o==='DEVICE_NAME'){path='/ISAPI/System/deviceInfo';body=`<DeviceInfo xmlns="http://www.hikvision.com/ver20/XMLSchema"><deviceName>${escapeXml(p.deviceName!)}</deviceName></DeviceInfo>`}else if(o==='NTP'){path='/ISAPI/System/time/ntpServers/1';const server=p.ntp?.servers[0];body=`<NTPServer xmlns="http://www.hikvision.com/ver20/XMLSchema"><id>1</id><addressingFormatType>${server&&/^\d+\./.test(server)?'ipaddress':'hostname'}</addressingFormatType>${server&&/^\d+\./.test(server)?`<ipAddress>${escapeXml(server)}</ipAddress>`:`<hostName>${escapeXml(server||'')}</hostName>`}<portNo>123</portNo></NTPServer>`}else if(o==='TIME_ZONE'){path='/ISAPI/System/time';body=`<Time xmlns="http://www.hikvision.com/ver20/XMLSchema"><timeMode>NTP</timeMode><timeZone>${escapeXml(p.timeZone!)}</timeZone></Time>`}else if(o==='ONVIF_ENABLE'){path='/ISAPI/System/Network/ONVIF';body=`<ONVIF xmlns="http://www.hikvision.com/ver20/XMLSchema"><enabled>${p.enabled===true}</enabled></ONVIF>`}else if(o==='REBOOT'){await this.request(d,c,'/ISAPI/System/reboot','PUT','',s);return}else throw new CameraDriverError('Hikvision operation unsupported.','UNSUPPORTED');await this.request(d,c,path,'PUT',body,s,{'Content-Type':'application/xml'})}
 async verify(d:Device,c:{username:string;password:string},o:CameraConfigurationOperation,p:CameraConfigurationProposal,s?:AbortSignal){if(o==='REBOOT')return boundedReverify(s,()=>this.inspect(d,c,s));const v=(await this.inspect(d,c,s)).values;return o==='DEVICE_NAME'?v.deviceName===p.deviceName:o==='NTP'?v.ntp?.servers[0]===p.ntp?.servers[0]:o==='TIME_ZONE'?v.timeZone===p.timeZone:o==='ONVIF_ENABLE'?false:false}
}
