import { canonicalMac } from '../../shared/identity_policy.ts';
import{Device}from'../../types/index.ts';import{CameraCapability,CameraConfigurationOperation,CameraConfigurationProposal}from'../../shared/camera_configuration.ts';import{CameraConfigurationError,CameraConfigurationProvider,CameraDeviceValues,OnvifDeviceConfigurationProvider}from'../network/camera_configuration_service.ts';import{CameraDriverError,CameraDriverResolver,CameraVendorDriver,DriverCapabilityState}from'./camera_driver.ts';import{HikvisionIsapiDriver}from'./hikvision.ts';import{DahuaDriver}from'./dahua.ts';import{HanwhaSunapiDriver}from'./hanwha.ts';import{AxisDriver}from'./axis.ts';
const operations:CameraConfigurationOperation[]=['DEVICE_NAME','NTP','TIME_ZONE','ONVIF_ENABLE','REBOOT','PASSWORD'];
const state=(value:DriverCapabilityState):CameraCapability['state']=>value==='SUPPORTED'?'SUPPORTED':value==='REQUIRES_AUTHENTICATION'?'REQUIRES_AUTHENTICATION':value==='TRANSPORT_UNAVAILABLE'?'TRANSPORT_UNAVAILABLE':value==='UNKNOWN'?'UNKNOWN':'UNSUPPORTED';
const normalized=(error:unknown)=>{if(error instanceof CameraConfigurationError)return error;if(error instanceof CameraDriverError){const code=error.code==='AUTHENTICATION_FAILED'?'UNAUTHORIZED':error.code;return new CameraConfigurationError(error.message,code)}return new CameraConfigurationError('Vendor provider failed.','VENDOR_ERROR')};
export class VendorCameraConfigurationProvider implements CameraConfigurationProvider{readonly kind='VENDOR_RESOLVER'as const;private selected=new Map<string,CameraVendorDriver>();constructor(private readonly resolver=new CameraDriverResolver([new HikvisionIsapiDriver(),new DahuaDriver(),new HanwhaSunapiDriver(),new AxisDriver()])){}
 async inspect(device:Device,credential:{username:string;password:string},signal?:AbortSignal){for(const operation of operations)this.selected.delete(`${device.id}:${operation}`);const selection=this.resolver.resolve(device);if(!selection.driver)return{capabilities:operations.map(operation=>({operation,state:'UNSUPPORTED'as const,detail:'Vendor support not available.',editable:false})),values:{},providers:Object.fromEntries(operations.map(o=>[o,selection.provider]))};try{const result=await selection.driver.inspect(device,credential,signal);this.resolver.confirm(device,selection.driver,result.identity);this.enrich(device,result.identity,selection.driver.label);const caps=selection.driver.capabilities();const capabilities=operations.map(operation=>{const cap=caps.find(x=>x.operation===operation);const capability:CameraCapability={operation,state:cap?state(cap.state):'UNKNOWN',detail:cap?.detail||'Capability was not reported by the vendor.',editable:cap?.state==='SUPPORTED'};if(capability.editable)this.selected.set(`${device.id}:${operation}`,selection.driver!);return capability});return{capabilities,values:result.values,providers:Object.fromEntries(operations.map(o=>[o,selection.driver!.label]))}}catch(error){throw normalized(error)}}
 async apply(device:Device,credential:{username:string;password:string},operation:CameraConfigurationOperation,proposal:CameraConfigurationProposal,signal?:AbortSignal){const driver=this.selected.get(`${device.id}:${operation}`);if(!driver)throw new CameraConfigurationError('No confirmed vendor provider is selected for this operation.','UNSUPPORTED');try{await driver.apply(device,credential,operation,proposal,signal)}catch(error){throw normalized(error)}}
 async verify(device:Device,credential:{username:string;password:string},operation:CameraConfigurationOperation,proposal:CameraConfigurationProposal,signal?:AbortSignal){const driver=this.selected.get(`${device.id}:${operation}`);if(!driver)return false;try{return await driver.verify(device,credential,operation,proposal,signal)}catch(error){throw normalized(error)}}
 private enrich(device:Device,identity:{manufacturer?:string;model?:string;serial?:string;firmware?:string;macAddress?:string;hostname?:string},label:string){if(identity.manufacturer)device.anchor.vendor=identity.manufacturer;if(identity.model)device.anchor.model=identity.model;if(identity.serial)device.anchor.serialNumber=identity.serial;if(identity.firmware)device.anchor.firmwareVersion=identity.firmware;if(identity.macAddress&&!device.anchor.macAddress)device.anchor.macAddress=canonicalMac(identity.macAddress);device.manufacturerParams={...device.manufacturerParams,activeDriver:label,driverEvidence:'Authenticated vendor identity response'};}
}
export class PreferredCameraConfigurationProvider implements CameraConfigurationProvider{readonly kind='RESOLVED'as const;private chosen=new Map<string,CameraConfigurationProvider>();constructor(private readonly onvif:CameraConfigurationProvider=new OnvifDeviceConfigurationProvider(),private readonly vendor:CameraConfigurationProvider=new VendorCameraConfigurationProvider()){}
 async inspect(device:Device,credential:{username:string;password:string},signal?:AbortSignal){for(const operation of operations)this.chosen.delete(`${device.id}:${operation}`);const primary=await this.onvif.inspect(device,credential,signal);const providers:Record<string,string>=Object.fromEntries(operations.map(o=>[o,'ONVIF']));let fallback:Awaited<ReturnType<CameraConfigurationProvider['inspect']>>|undefined;const needs=primary.capabilities.some(c=>c.state==='UNSUPPORTED'||c.state==='VENDOR_NATIVE_REQUIRED'||c.state==='UNKNOWN');if(needs)try{fallback=await this.vendor.inspect(device,credential,signal)}catch(error){if(['IDENTITY_CONFLICT','INSUFFICIENT_IDENTITY'].includes((error as CameraConfigurationError).code))throw error;fallback=undefined}const capabilities=primary.capabilities.map(cap=>{if(cap.state==='SUPPORTED'){this.chosen.set(`${device.id}:${cap.operation}`,this.onvif);return cap}const alternate=fallback?.capabilities.find(x=>x.operation===cap.operation);if(alternate?.state==='SUPPORTED'){this.chosen.set(`${device.id}:${cap.operation}`,this.vendor);providers[cap.operation]=fallback?.providers?.[cap.operation]||this.vendor.kind;return alternate}return cap});return{capabilities,values:{...fallback?.values,...primary.values},providers}}
 async apply(d:Device,c:{username:string;password:string},o:CameraConfigurationOperation,p:CameraConfigurationProposal,s?:AbortSignal){const provider=this.chosen.get(`${d.id}:${o}`);if(!provider)throw new CameraConfigurationError('No supported provider was selected before preview.','UNSUPPORTED');return provider.apply(d,c,o,p,s)}
 async verify(d:Device,c:{username:string;password:string},o:CameraConfigurationOperation,p:CameraConfigurationProposal,s?:AbortSignal){return(await this.chosen.get(`${d.id}:${o}`)?.verify(d,c,o,p,s))===true}
}
