import { readFileSync } from 'node:fs';
import { SiteProjectDatabase } from '../core/storage/project_db.ts';
import { BatchExecutionPipeline } from '../core/engine/pipeline.ts';
import { Phase4IdentityReconciliation } from '../core/engine/phase4_reconcile.ts';
import * as monitoring from '../core/engine/incremental_discovery_monitor.ts';
import { ReportService } from '../core/reporting/report_service.ts';
import { ProjectReverificationEngine } from '../core/engine/reverification.ts';
import { TaskManager } from '../core/tasks/task_manager.ts';
import { OperationTasks } from '../core/tasks/operation_tasks.ts';
import { Device, PairSessionState } from '../types/index.ts';
let passed=0,failed=0;const check=(v:unknown,n:string)=>{if(v){passed++;console.log('PASS: '+n)}else{failed++;console.error('FAIL: '+n)}};
const now=()=>new Date().toISOString();
const camera=(id:string,ip='192.168.1.100'):Device=>({id,anchor:{macAddress:id==='A'?'00:50:f9:63:fb:0f':id==='B'?'e4:30:22:cd:68:85':`00:11:22:33:44:${id==='C'?'66':'88'}`,onvifEndpointUuid:'uuid-'+id,vendor:'Camera'},network:{ipAddress:ip,subnetMask:'255.255.255.0',port:80,protocol:'ONVIF'},status:'ONLINE',sessionVerification:'VERIFIED',discoveredPhase:3,firstSeenAt:now(),lastSeenAt:now(),reachability:{wsDiscoveryRespondedAt:now(),lastSuccessfulResponseAt:now(),subnetClassification:'LOCAL'},technician:{name:id,notes:'preserve'}});
const active=(db:SiteProjectDatabase)=>db.getCollisions().filter(c=>!c.resolved);
const report=(db:SiteProjectDatabase)=>new ReportService().build(db.getSession(),[],{type:'DEVICE_INVENTORY',scope:'ALL',columns:['STATUS','DUPLICATE_STATE']});
function pipeline(db:SiteProjectDatabase,observations:Device[],neighbors:Device[]=[]){
 const engine=new BatchExecutionPipeline({passiveDiscovery:{discover:async()=>neighbors} as any,onvifDiscovery:{discover:async(_n:any,o:any)=>{for(const d of observations)o.onDevice(structuredClone(d));return{devices:observations,interfaceErrors:[],cancelled:false}}} as any,deviceEnricher:{enrich:async(d:Device)=>d} as any});
 engine.runPhase1=async()=>{(engine as any).currentInterfaces=[{name:'Ethernet',ipAddress:'192.168.1.137',netmask:'255.255.255.0',interfaceIndex:8,isInternal:false,mac:'',broadcast:''}]};
 return engine;
}
async function cycle(db:SiteProjectDatabase,devices:Device[],origin:'MONITORING'|'MANUAL'='MONITORING',neighbors:Device[]=[]){const engine=pipeline(db,devices,neighbors);const tasks=new TaskManager(),projection=new OperationTasks(tasks);let terminal=0;engine.subscribe(e=>{if(e.type==='SCAN_COMPLETE')terminal++;if(e.context?.origin==='MANUAL')projection.foreground({epoch:'fixture',revision:1,session:{origin:e.context?.origin,sessionId:'cycle',state:'RUNNING'}} as any,()=>true)});const result=await new monitoring.IncrementalDiscoveryMonitor({canRun:()=>({allowed:true}),runCycle:id=>engine.runDiscoveryScan({database:db,context:{origin,sessionId:id},emitTerminalEvent:origin!=='MONITORING'})}).runNow();return{result,tasks:tasks.snapshot(),terminal}}
async function run(){
 const db=new SiteProjectDatabase();db.createNewProject('Phase 4');db.upsertDevice(camera('A'));db.upsertDevice(camera('B'));db.exportProjectJsonForSave();
 await cycle(db,[camera('A'),camera('B')]);check(active(db).length===1,'T01 one active collision');check(db.getDevices().length===2,'T02 separate physical identities');const collisionId=db.getCollisions()[0].id;
 check(db.getDevices().every(d=>d.status==='COLLISION'),'both current participants duplicate');
 const repeat=await cycle(db,[camera('A'),camera('B')]);check(active(db).length===1&&db.getCollisions().length===1&&db.getCollisions()[0].id===collisionId,'T03 repeated monitoring idempotent');check(!db.getSession().dirty,'T23 live refresh leaves clean project clean');check(repeat.tasks.tasks.length===0&&repeat.terminal===0,'T24 normal monitoring creates no Tasks or foreground completion');
 await cycle(db,[camera('A','192.168.1.168'),camera('B')]);check(db.getDeviceById('A')?.network.ipAddress==='192.168.1.168','T04 background reconciles trustworthy identity move');check(db.getDeviceById('A')?.network.ipAddressHistory?.includes('192.168.1.100'),'move preserves IP history');
 check(db.getCollisions()[0].resolved&&db.getCollisions()[0].state==='RESOLVED','T05 collision resolves');check(active(db).length===0,'T06 resolved excluded from count');check(db.getDevices().every(d=>d.status!=='COLLISION'),'T07 duplicate status cleared');check(report(db).rows.every(r=>!r.values.STATUS.includes('Duplicate IP')),'T08 current reports clear unresolved label');check(db.getCollisions().length===1&&db.getCollisions()[0].id===collisionId,'T09 history retained');check(!db.getSession().dirty,'resolution is runtime evidence, not project edit');
 await cycle(db,[camera('A'),camera('B')]);check(active(db).length===1&&db.getCollisions().length===1&&db.getCollisions()[0].id===collisionId,'T10 reopen same logical record');check(db.getDeviceById('A')?.anchor.macAddress==='00:50:f9:63:fb:0f'&&db.getDeviceById('B')?.anchor.macAddress==='e4:30:22:cd:68:85','T11 reopening preserves identities');
 await cycle(db,[camera('C','192.168.1.200'),camera('D','192.168.1.200')]);check(active(db).length===2,'T12 two simultaneous groups');await cycle(db,[camera('A','192.168.1.168'),camera('B')]);check(active(db).length===1,'T13 resolve only one group');
 const gate=(monitoring as any).pairBlocksMonitoring;
 for(const [pair,expected,label] of [[{state:'PAIRED',recoveryDisposition:'HEALTHY_RETAINED',adapterMutationActive:false},false,'T14 healthy retained allows monitoring'],[{state:'PAIRED',adapterMutationActive:false},false,'T15 historical PAIRED alone does not block'],[{state:'PAIRED',adapterMutationActive:true},true,'T16 actual mutation blocks'],[{state:'RESTORING',adapterMutationActive:true},true,'T17 restore blocks'],[{state:'APPLYING',adapterMutationActive:true},true,'T17 apply blocks'],[{state:'ROLLBACK_REQUIRED',recoveryDisposition:'ATTENTION_REQUIRED',adapterMutationActive:false},true,'unsafe recovery remains blocked']] as const)check(typeof gate==='function'&&gate(pair as PairSessionState)===expected,label);
 const src=readFileSync(new URL('../core/engine/pipeline.ts',import.meta.url),'utf8');const run=src.slice(src.indexOf('public async runDiscoveryScan'),src.indexOf('public async runFullPipeline'));
 check(!/applyTemporary|\.restore\(|confirmAndApply/.test(run),'T18 monitoring discovery has no adapter write');check(!/runPhase5|runPhase6|credential|configure/i.test(run),'T19 monitoring invokes no camera writes or credentials');
 const before=db.getDeviceById('B')!.network.ipAddress;await cycle(db,[],'MONITORING',[{...camera('B','192.168.1.222'),anchor:{macAddress:null,vendor:'Unknown'},network:{ipAddress:'192.168.1.222',subnetMask:null,port:0,protocol:'PASSIVE_SNIFF'},discoveredPhase:2}]);check(db.getDeviceById('B')!.network.ipAddress===before,'T21 ambiguous ARP cannot reassign established identity');
 await cycle(db,[camera('A'),camera('B')]);const arp={...camera('A','192.168.1.168'),anchor:{macAddress:camera('A').anchor.macAddress,vendor:'Unknown'},network:{ipAddress:'192.168.1.168',subnetMask:null,port:0,protocol:'PASSIVE_SNIFF'},discoveredPhase:2} as Device;await cycle(db,[],'MONITORING',[arp]);check(db.getDeviceById('A')?.network.ipAddress==='192.168.1.100'&&active(db).some(c=>c.ipAddress==='192.168.1.100'),'T21 neighbor-only ownership cannot resolve a conflicted participant');
 await cycle(db,[{...camera('A','192.168.1.177'),anchor:{...camera('A').anchor,macAddress:camera('B').anchor.macAddress}}]);check(db.getDeviceById('A')?.network.ipAddress==='192.168.1.100'&&db.getDeviceById('B')?.network.ipAddress==='192.168.1.100','T20 conflicting anchors cannot silently reassign');check(db.getDeviceById('A')!==db.getDeviceById('B'),'T22 same IP never merges distinct MACs');
 const fg=new SiteProjectDatabase();fg.createNewProject('foreground');fg.upsertDevice(camera('A'));fg.upsertDevice(camera('B'));await cycle(fg,[camera('A'),camera('B')],'MANUAL');await cycle(fg,[camera('A','192.168.1.168'),camera('B')],'MANUAL');check(active(fg).length===0&&fg.getDevices().every(d=>d.status==='ONLINE'),'T25 foreground resolves collision');
 const plan=ProjectReverificationEngine.plan(fg.getDevices(),[camera('A','192.168.1.168'),camera('B')]);fg.applyReverification(plan.projectDevices,plan.newDevices||[],plan.persistentChanged,false);check(plan.collisionCount===active(fg).length,'T26 Reverify agrees with active collisions');check(report(fg).rows.every(r=>!r.values.STATUS.includes('Duplicate'))&&active(fg).length===0,'T27 footer/API active count and reports agree');
 const reopened=new SiteProjectDatabase();reopened.importProjectJson(fg.exportProjectJson());check(reopened.getCollisions().length===1&&active(reopened).length===0,'T28 persisted resolved history stays resolved');
 const evidence=new SiteProjectDatabase();evidence.createNewProject('status');evidence.upsertDevice(camera('A'));evidence.upsertDevice(camera('B'));await Phase4IdentityReconciliation.execute(evidence);const a=evidence.getDeviceById('A')!;a.network.ipAddress='192.168.1.168';a.reachability={subnetClassification:'LOCAL',lastSuccessfulResponseAt:'2020-01-01T00:00:00Z'};a.diagnostics={lastRunStartedAt:now(),checks:[{type:'HTTP',targetIp:a.network.ipAddress,success:false,timestamp:now()},{type:'TCP',targetIp:a.network.ipAddress,success:false,timestamp:now()}]};await Phase4IdentityReconciliation.execute(evidence);check(a.status==='OFFLINE'||a.status==='UNREACHABLE','resolved status uses current failures, not stale successful contact');
 const historical=new SiteProjectDatabase();historical.createNewProject('history');historical.upsertDevice(camera('A'));historical.upsertDevice(camera('B'));await Phase4IdentityReconciliation.execute(historical);historical.getCollisions()[0].resolved=true;historical.getCollisions()[0].state='RESOLVED';const restart=new SiteProjectDatabase();restart.importProjectJson(historical.exportProjectJson());await cycle(restart,[]);check(active(restart).length===0,'historical saved shared addresses alone cannot reopen resolved collision');
 const quiet=new SiteProjectDatabase();quiet.createNewProject('quiet');quiet.upsertDevice(camera('A'));quiet.upsertDevice(camera('B'));await cycle(quiet,[camera('A'),camera('B')]);await cycle(quiet,[]);check(active(quiet).length===1,'absence of discovery responses does not resolve known collision');
 const reverify=new SiteProjectDatabase();reverify.createNewProject('reverify');reverify.upsertDevice(camera('A'));reverify.upsertDevice(camera('B'));await Phase4IdentityReconciliation.execute(reverify);const rp=ProjectReverificationEngine.plan(reverify.getDevices(),[camera('A','192.168.1.168'),camera('B')]);reverify.applyReverification(rp.projectDevices,rp.newDevices||[],rp.persistentChanged,false);check(active(reverify).length===rp.collisionCount&&active(reverify).length===0,'Reverify directly resolves existing collision with current identity evidence');
 const subnet=quiet.getDeviceById('A')!;subnet.network.ipAddress='192.168.9.100';subnet.reachability={subnetClassification:'DIFFERENT_SUBNET'};await Phase4IdentityReconciliation.execute(quiet);check(subnet.status==='DIFFERENT_SUBNET','resolved collision uses current subnet evidence');
 const stale=camera('A');const address=fg.getDeviceById('A')!.network.ipAddress;check(!fg.applyDiagnosticRefresh(stale)&&fg.getDeviceById('A')?.network.ipAddress===address,'late diagnostic result cannot undo current identity/IP reconciliation');fg.exportProjectJsonForSave();fg.applyDiagnosticRefresh(camera('B'));check(!fg.getSession().dirty,'diagnostic-only refresh leaves clean project clean');
 const weak=new SiteProjectDatabase();weak.startQuickWork();weak.upsertDevice(camera('A'));weak.upsertDevice({...camera('unknown'),anchor:{macAddress:null,vendor:'Unknown'},network:{...camera('A').network,protocol:'MANUAL'}});await Phase4IdentityReconciliation.execute(weak);check(active(weak).length===0,'IP-only unknown row cannot establish a second physical identity');
 console.log(`Background collision summary: ${passed} passed, ${failed} failed`);if(failed)process.exitCode=1;
}
run().catch(e=>{console.error(e);process.exitCode=1});
