import{BulkNetworkConfigurationService}from'../core/engine/bulk_reip.ts';
import{CameraNetworkError,NetworkPreview,NetworkTarget}from'../core/network/camera_network_service.ts';
import{SiteProjectDatabase}from'../core/storage/project_db.ts';
import{InMemoryCredentialStore,OSCredentialVault}from'../core/storage/vault.ts';
import{Device}from'../types/index.ts';

const camera=(id:string,ip:string,status:Device['status']='ONLINE'):Device=>({id,anchor:{macAddress:`00:40:8c:00:00:${id.slice(-2).padStart(2,'0')}`,onvifEndpointUuid:`uuid-${id}`,serialNumber:`serial-${id}`,vendor:'Axis',model:'P3265'},network:{ipAddress:ip,subnetMask:'255.255.255.0',gateway:'192.168.1.1',port:80,protocol:'ONVIF',xAddr:`http://${ip}/onvif/device_service`,ipAddressHistory:[ip]},status,discoveredPhase:3,firstSeenAt:new Date().toISOString(),lastSeenAt:new Date().toISOString(),technician:{name:`Camera ${id}`,notes:'Preserve'}});
class FakeSingleService{
  previews=new Map<string,{deviceId:string;target:NetworkTarget}>();writes:string[]=[];active=0;maxActive=0;outcomes=new Map<string,'SUCCESS'|'AUTH'|'ATTENTION'>();
  async preview(deviceId:string,credentialId:string,target:NetworkTarget){if(deviceId==='unsupported')throw new CameraNetworkError('Unsupported ONVIF network operation.','UNSUPPORTED');if(!credentialId)throw new CameraNetworkError('Credential missing.','CREDENTIAL_NOT_FOUND');const last=Number(target.ipAddress.split('.').at(-1));if(!target.dhcp&&[0,1,2,3,4,5,6,255].includes(last))throw new CameraNetworkError('Target has positive conflict evidence.','IP_CONFLICT');const planId=`single-${deviceId}-${target.ipAddress}`;this.previews.set(planId,{deviceId,target});return{planId,state:'READY_FOR_CONFIRMATION',deviceId,identity:{},current:{interfaceToken:'eth0',ipAddress:deviceId==='one'?'192.168.1.20':'192.168.1.21',prefixLength:24,dhcp:false,gateway:'192.168.1.1'},proposed:target,credentialId,protocol:'ONVIF',expectedEffect:'temporary',warning:'No automatic Pair',pcNetworkChange:false,createdAt:new Date().toISOString()}as NetworkPreview}
  async apply(planId:string,confirmed:boolean){if(!confirmed)throw new CameraNetworkError('Confirmation required.','CONFIRMATION_REQUIRED');const plan=this.previews.get(planId)!;this.writes.push(plan.deviceId);this.active++;this.maxActive=Math.max(this.maxActive,this.active);await new Promise(r=>setTimeout(r,4));this.active--;const outcome=this.outcomes.get(plan.deviceId)||'SUCCESS';if(outcome==='AUTH')throw new CameraNetworkError('Camera authentication failed.','UNAUTHORIZED');if(outcome==='ATTENTION')return{state:'PARTIAL_SUCCESS',verified:false,acknowledged:true,recoveryGuidance:'Manually choose Pair if needed.'};return{state:'SUCCESS',verified:true,acknowledged:true}}
}
class DeferredSingleService extends FakeSingleService{release!:()=>void;gate=new Promise<void>(resolve=>this.release=resolve);override async apply(planId:string,confirmed:boolean){if(!confirmed)throw Error('confirmation');const plan=this.previews.get(planId)!;this.writes.push(plan.deviceId);await this.gate;return{state:'SUCCESS',verified:true,acknowledged:true}}}

async function run(){let passed=0,failed=0;const check=(value:unknown,name:string)=>{if(value){console.log(`  PASS: ${name}`);passed++}else{console.error(`  FAIL: ${name}`);failed++}};
  const db=new SiteProjectDatabase();db.createNewProject('Bulk');for(const d of [camera('one','192.168.1.20'),camera('two','192.168.1.21'),camera('three','192.168.1.22'),camera('duplicate','192.168.1.30','COLLISION'),camera('unsupported','192.168.1.31'),camera('missing','192.168.1.32')])db.upsertDevice(d);
  const vault=new OSCredentialVault(new InMemoryCredentialStore());for(const id of ['one','two','three','duplicate','unsupported']){const ref=await vault.saveCredential({label:`Credential ${id}`,username:'tech',password:'fixture-secret',deviceIdentity:id});check(vault.getAssociation(id)===ref.id,`credential associated with stable ID ${id}`)}
  const fake=new FakeSingleService(),service=new BulkNetworkConfigurationService(db,vault,fake,2,32);const plan=await service.createPlan({deviceIds:['one','two','three','duplicate','unsupported','missing'],startIp:'192.168.1.0',prefixLength:24,gateway:'192.168.1.1'});
  check(plan.items.length===6,'multi-select planning retains every selected device');check(plan.items.every((x,i)=>x.deviceId===['one','two','three','duplicate','unsupported','missing'][i]),'plan uses stable device IDs and preserves order');check(plan.items.find(x=>x.deviceId==='duplicate')?.errors.includes('Duplicate IP must be resolved first'),'duplicate-IP device is visibly blocked');check(plan.items.find(x=>x.deviceId==='unsupported')?.errors.some(x=>x.includes('Unsupported')),'unsupported transport is blocked');check(plan.items.find(x=>x.deviceId==='missing')?.errors.some(x=>x.includes('credential')),'missing credential blocks only that device');
  const targets=plan.items.filter(x=>x.validation==='READY').map(x=>x.targetIp);check(new Set(targets).size===targets.length,'target assignment is unique');check(targets[0]==='192.168.1.7','bounded allocation skips network, gateway, local, discovered, collision, neighbor, and occupied addresses');check(targets.every(x=>!['192.168.1.0','192.168.1.1','192.168.1.2','192.168.1.3','192.168.1.4','192.168.1.5','192.168.1.6','192.168.1.255'].includes(x)),'unsafe target evidence is avoided');check(plan.readyCount===3&&plan.blockedCount===3,'batch summary separates ready and blocked devices');check(plan.estimatedOperationCount===9,'estimated operation count reflects apply and verification work');check(!JSON.stringify(plan).includes('fixture-secret'),'plan contains credential metadata but no secret');
  let confirmation=false;try{await service.execute(plan.batchId,false)}catch(e){confirmation=(e as CameraNetworkError).code==='CONFIRMATION_REQUIRED'}check(confirmation,'explicit confirmation is required');check(fake.writes.length===0,'no camera write occurs before confirmation');
  fake.outcomes.set('two','AUTH');fake.outcomes.set('three','ATTENTION');const result=await service.execute(plan.batchId,true);check(fake.maxActive<=2,'execution concurrency is bounded');check(fake.writes.length===3,'single-camera service executes every ready item once');check(result.items.find(x=>x.deviceId==='one')?.state==='VERIFIED','per-device success is recorded');check(result.items.find(x=>x.deviceId==='two')?.state==='FAILED','authentication failure is isolated per device');check(result.items.find(x=>x.deviceId==='three')?.state==='NEEDS_ATTENTION','unreachable-after-write remains needs attention');check(result.state==='PARTIAL_FAILURE','mixed outcomes produce partial failure');check(result.items.find(x=>x.deviceId==='three')?.resultMessage?.includes('Pair'),'Pair is suggested but never automatic');
  const retry=await service.retry(plan.batchId);check(retry.items.map(x=>x.deviceId).sort().join(',')==='three,two','retry includes failed/needs-attention devices only');check(!retry.items.some(x=>x.deviceId==='one'),'verified devices are never retried');
  const duplicateTargets=await service.createPlan({deviceIds:['one','two'],startIp:'192.168.1.7',prefixLength:24,gateway:'192.168.1.1',manualTargets:{one:'192.168.1.9',two:'192.168.1.9'}});check(duplicateTargets.readyCount===1&&duplicateTargets.items[1].errors.includes('Duplicate target IP in batch'),'duplicate manual target is rejected');const badManual=await service.createPlan({deviceIds:['one','two'],startIp:'192.168.1.7',prefixLength:24,gateway:'192.168.1.1',manualTargets:{one:'192.168.1.1',two:'192.168.1.10'}});check(badManual.items[0].validation==='BLOCKED','manual override receives full conflict validation');
  const scarce=new BulkNetworkConfigurationService(db,vault,new FakeSingleService(),1,2);const insufficient=await scarce.createPlan({deviceIds:['one','two'],startIp:'192.168.1.0',prefixLength:24,gateway:'192.168.1.1'});check(insufficient.readyCount===0&&insufficient.items.every(x=>x.errors.some(e=>e.includes('bounded'))),'insufficient bounded candidates block the plan');
  const deferred=new DeferredSingleService(),cancelService=new BulkNetworkConfigurationService(db,vault,deferred,1,32);const cancelPlan=await cancelService.createPlan({deviceIds:['one','two','three'],startIp:'192.168.1.7',prefixLength:24,gateway:'192.168.1.1'});const running=cancelService.execute(cancelPlan.batchId,true);await new Promise(r=>setTimeout(r,1));check(cancelService.cancel(cancelPlan.batchId),'cancellation request accepted at safe boundary');deferred.release();const cancelled=await running;check(cancelled.state==='CANCELLED','executing batch reaches cancelled state');check(cancelled.items.filter(x=>x.state==='VERIFIED').length===1,'completed result is preserved after cancellation');check(cancelled.items.filter(x=>x.state==='SKIPPED').length===2,'cancellation stops scheduling future devices');
  check(db.getSession().mode==='PROJECT'&&db.getSession().dirty,'verified project changes remain project-owned and dirty');check(!db.exportProjectJson().includes('fixture-secret'),'project export stays secret-free');check(!JSON.stringify(db.getProject().auditLogs).includes('fixture-secret'),'project audit stays secret-free');check(!('adapters' in service),'bulk service exposes no Windows adapter mutation or automatic Pair path');
  console.log(`\nBulk network configuration summary: ${passed} passed, ${failed} failed`);if(failed)process.exit(1)
}run().catch(error=>{console.error(error);process.exit(1)});
