import{readFileSync}from'node:fs';
import{CameraConfigurationError,CameraConfigurationProvider,CameraConfigurationService,CameraDeviceValues}from'../core/network/camera_configuration_service.ts';
import{SiteProjectDatabase}from'../core/storage/project_db.ts';
import{InMemoryCredentialStore,OSCredentialVault}from'../core/storage/vault.ts';
import{V1_BULK_CAPABILITIES,BULK_EXECUTABLE_CONFIG_OPERATIONS}from'../shared/bulk_capabilities.ts';
import{CameraCapability,CameraConfigurationOperation,CameraConfigurationProposal}from'../shared/camera_configuration.ts';
import{Device}from'../types/index.ts';
import{appStateDb}from'../core/storage/app_db.ts';

const now='2026-09-05T12:00:00.000Z';
const camera=(id:string,ip:string,mac:string):Device=>({id,anchor:{macAddress:mac,onvifEndpointUuid:`uuid-${id}`,serialNumber:`serial-${id}`,vendor:'Axis',model:'P3265'},network:{ipAddress:ip,subnetMask:'255.255.255.0',gateway:'192.168.1.1',port:80,protocol:'ONVIF',xAddr:`http://${ip}/onvif/device_service`,ipAddressHistory:[ip]},status:'ONLINE',discoveredPhase:3,firstSeenAt:now,lastSeenAt:now,technician:{name:`Local ${id}`},configuredState:{inferred:false}});
const capability=(operation:CameraConfigurationOperation,editable=true):CameraCapability=>({operation,state:editable?'SUPPORTED':'UNSUPPORTED',detail:editable?'Authenticated provider support':'Camera does not support this operation.',editable});
class MixedProvider implements CameraConfigurationProvider{readonly kind='ONVIF'as const;writes:string[]=[];active=0;maxActive=0;unsupported=new Set<string>();unverified=new Set<string>();fail=new Set<string>();values=new Map<string,CameraDeviceValues>();async inspect(d:Device,c:{username:string;password:string}){if(!c.username||!c.password)throw new CameraConfigurationError('A saved credential is required.','UNAUTHORIZED');const operations=(['DEVICE_NAME','NTP','TIME_ZONE','REBOOT']as CameraConfigurationOperation[]).map(op=>capability(op,!this.unsupported.has(`${d.id}:${op}`)));return{capabilities:operations,values:this.values.get(d.id)||{deviceName:d.id,ntp:{fromDhcp:true,servers:[]},timeZone:'UTC'},providers:Object.fromEntries(operations.map(x=>[x.operation,'ONVIF']))}}async apply(d:Device,_c:{username:string;password:string},operation:CameraConfigurationOperation,_p:CameraConfigurationProposal){this.active++;this.maxActive=Math.max(this.maxActive,this.active);this.writes.push(d.id);await new Promise(r=>setTimeout(r,2));this.active--;if(this.fail.has(`${d.id}:${operation}`))throw new CameraConfigurationError('Provider command failed safely.','PROVIDER_FAILED')}async verify(d:Device,_c:{username:string;password:string},operation:CameraConfigurationOperation){return!this.unverified.has(`${d.id}:${operation}`)}}

async function run(){let passed=0,failed=0;const a=(v:unknown,n:string)=>{if(v){passed++;console.log(`  PASS: ${n}`)}else{failed++;console.error(`  FAIL: ${n}`)}};
const classifications=Object.fromEntries(V1_BULK_CAPABILITIES.map(x=>[x.id,x.classification]));a(V1_BULK_CAPABILITIES.length===10,'capability matrix covers every V1 bulk candidate');a(classifications.NETWORK_IP==='PRODUCTION_READY'&&classifications.SUBNET_MASK==='PRODUCTION_READY'&&classifications.GATEWAY==='PRODUCTION_READY'&&classifications.DEVICE_NAME==='IMPLEMENTABLE_EXISTING_PROVIDER','network fields and physical name classifications are deterministic');a(classifications.ONVIF_ENABLE==='PROVIDER_HARDWARE_DEPENDENT'&&classifications.PASSWORD==='PROVIDER_HARDWARE_DEPENDENT','high-risk capabilities are formally narrowed');a(classifications.REPORT_SELECTED==='NOT_BULK_CONFIGURATION','report selection remains outside physical configuration');a(BULK_EXECUTABLE_CONFIG_OPERATIONS.join(',')==='DEVICE_NAME,NTP,TIME_ZONE,REBOOT','only truthful production operations are executable');a(V1_BULK_CAPABILITIES.every(x=>typeof x.reason==='string'&&x.reason.length>10),'every capability has a technician-explainable contract');
const ui=readFileSync(new URL('../ui/components/BulkDeviceConfigurationModal.tsx',import.meta.url),'utf8');a(ui.includes('BULK_EXECUTABLE_CONFIG_OPERATIONS')&&!ui.includes('<option value="PASSWORD"')&&!ui.includes('<option value="ONVIF_ENABLE"'),'UI consumes the authoritative executable matrix');a(ui.includes('Physical camera hostname')&&ui.includes('technician-local Name'),'physical camera name is distinguished from local metadata');
const db=new SiteProjectDatabase();db.createNewProject('Bulk Scope');const ids=Array.from({length:10},(_,i)=>`cam-${i+1}`);for(let i=0;i<10;i++)db.upsertDevice(camera(ids[i],`192.168.1.${20+i}`,`00:40:8c:00:00:${String(i+1).padStart(2,'0')}`));db.upsertDevice({...db.getDeviceById('cam-7')!,network:{...db.getDeviceById('cam-7')!.network,ipAddress:'192.168.1.220',ipAddressHistory:['192.168.1.26','192.168.1.220']}});db.upsertDevice({...db.getDeviceById('cam-8')!,reachability:{subnetClassification:'DIFFERENT_SUBNET'}});db.upsertDevice({...db.getDeviceById('cam-9')!,network:{...db.getDeviceById('cam-9')!.network,ipAddress:'192.168.1.250'}});db.upsertDevice({...db.getDeviceById('cam-10')!,network:{...db.getDeviceById('cam-10')!.network,ipAddress:'192.168.1.250'}});
const store=new InMemoryCredentialStore(),vault=new OSCredentialVault(store);for(const id of ids.filter(id=>id!=='cam-3'))await vault.saveCredential({label:`Explicit ${id}`,username:'technician',password:'vault-only-secret',deviceIdentity:id});const provider=new MixedProvider();provider.unsupported.add('cam-6:NTP');provider.unverified.add('cam-5:NTP');provider.fail.add('cam-4:NTP');const service=new CameraConfigurationService(db,vault,provider,2);const selected=['cam-1','cam-2','cam-3','cam-4','cam-5','cam-6','cam-7','cam-8','cam-9','cam-10'];const plan=await service.createBulkPlan(selected,{},'NTP',{ntp:{fromDhcp:true,servers:[]}});
a(plan.totalSelected===10&&plan.items.map(x=>x.deviceId).join(',')===selected.join(','),'mixed fixture preserves exact stable selection');a(plan.items.find(x=>x.deviceId==='cam-7')?.eligibility==='READY'&&db.getDeviceById('cam-7')?.network.ipAddress==='192.168.1.220','changed IP remains the same stable selected device');a(plan.items.find(x=>x.deviceId==='cam-6')?.eligibility==='UNSUPPORTED','provider-unsupported camera is preflight Unsupported');a(plan.items.find(x=>x.deviceId==='cam-8')?.eligibility==='NEEDS_ATTENTION'&&plan.items.find(x=>x.deviceId==='cam-8')?.errors[0].includes('Different Network'),'Different Network remains a truthful preflight classification');a(['cam-9','cam-10'].every(id=>plan.items.find(x=>x.deviceId===id)?.eligibility==='NEEDS_ATTENTION'),'both duplicate-IP identities are blocked from ambiguous commands');a(plan.items.find(x=>x.deviceId==='cam-3')?.errors[0].includes('saved credential'),'missing explicit credential is blocked without guessing');a(provider.writes.length===0,'preview performs zero physical writes');let noConfirm=false;try{await service.applyBulk(plan.batchId,false)}catch(e){noConfirm=(e as CameraConfigurationError).code==='CONFIRMATION_REQUIRED'}a(noConfirm&&provider.writes.length===0,'explicit confirmation is required');const result=await service.applyBulk(plan.batchId,true);a(provider.writes.every(id=>plan.items.find(x=>x.deviceId===id)?.eligibility==='READY'),'only Ready devices execute');a(!provider.writes.includes('cam-3')&&!provider.writes.includes('cam-6')&&!provider.writes.includes('cam-8')&&!provider.writes.includes('cam-9'),'Unsupported and blocked devices are never attempted');a(result.items.find(x=>x.deviceId==='cam-1')?.state==='VERIFIED'&&result.items.find(x=>x.deviceId==='cam-4')?.state==='FAILED'&&result.items.find(x=>x.deviceId==='cam-5')?.state==='UNKNOWN','SUCCESS, FAILED, and UNKNOWN remain distinct per device');a(result.state==='PARTIAL_FAILURE','mixed outcomes produce truthful partial failure');a(result.completedCount===result.readyCount&&result.totalSelected===10,'completed/total progress is item-based and accurate');a(provider.maxActive<=2,'bulk provider execution has bounded concurrency');a(db.listProjectHistory('CONFIGURATION').length===result.readyCount,'Project History records attempted devices only');a(!db.exportProjectJson().includes('vault-only-secret')&&!JSON.stringify(appStateDb.getAuditLogs()).includes('vault-only-secret'),'credential secrets remain absent from Project and support evidence');a(appStateDb.getAuditLogs().some(x=>x.details?.batchId===plan.batchId),'support evidence includes safe batch correlation');
const cancelPlan=await service.createBulkPlan(['cam-1','cam-2'],{},'TIME_ZONE',{timeZone:'UTC'});const beforeCancel=provider.writes.length;a(service.cancelBulk(cancelPlan.batchId)&&provider.writes.length===beforeCancel,'cancelling preview performs zero writes');a(cancelPlan.items.every(x=>x.deviceId!=='cam-3'),'subset selection never includes an unselected device');let passwordBlocked=false;try{await service.createBulkPlan(['cam-1','cam-2'],{},'PASSWORD',{newPassword:'do-not-execute'})}catch(e){passwordBlocked=(e as CameraConfigurationError).code==='BULK_OPERATION_NOT_EXECUTABLE'}a(passwordBlocked&&!JSON.stringify(provider.writes).includes('do-not-execute'),'bulk password change is rejected before provider access');let onvifBlocked=false;try{await service.createBulkPlan(['cam-1','cam-2'],{},'ONVIF_ENABLE',{enabled:true})}catch(e){onvifBlocked=(e as CameraConfigurationError).code==='BULK_OPERATION_NOT_EXECUTABLE'}a(onvifBlocked,'unsupported ONVIF enablement cannot fabricate a provider request');const quick=new SiteProjectDatabase();quick.startQuickWork();quick.upsertDevice(camera('q1','10.0.0.2','00:40:8c:00:10:01'));quick.upsertDevice(camera('q2','10.0.0.3','00:40:8c:00:10:02'));const qVault=new OSCredentialVault(new InMemoryCredentialStore());for(const id of['q1','q2'])await qVault.saveCredential({label:id,username:'tech',password:'secret',deviceIdentity:id});const qService=new CameraConfigurationService(quick,qVault,new MixedProvider(),2),qPlan=await qService.createBulkPlan(['q1','q2'],{},'REBOOT',{});await qService.applyBulk(qPlan.batchId,true);a(quick.getProject().auditLogs.length===0,'Quick Work writes no persistent Project History');a(db.getDevices().length===10&&db.getDeviceById('cam-7')?.id==='cam-7','bulk execution neither re-adds nor replaces Project identities');console.log(`\nBulk scope summary: ${passed} passed, ${failed} failed`);if(failed)process.exit(1)}run().catch(e=>{console.error(e);process.exit(1)});
