import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { CameraRendererService } from '../core/connect/camera_renderer_service.ts';
import { CameraBrowserSessions } from '../core/connect/camera_browser_sessions.ts';
import { NativeProofProtocol } from '../core/connect/native_camera_proof.ts';
import { NativeCapability } from '../core/connect/native_camera_capability.ts';
import { NativeCameraRenderer } from '../shared/camera_renderer.ts';
import { Device, IPCollisionRecord } from '../types/index.ts';

function setup(fixture = true, capability: NativeCapability = { available: true, code: 'AVAILABLE' }) {
  const devices: Device[] = ['A', 'B'].map((id, i) => ({ id, anchor: { macAddress: i ? '00:50:F9:63:FB:10' : '00:50:F9:63:FB:0F', onvifEndpointUuid: 'uuid-' + id, vendor: 'Fixture', model: 'Controlled' }, technician: { name: 'Camera ' + id }, network: { ipAddress: `192.0.2.${i + 1}`, subnetMask: '255.255.255.0', port: 80, protocol: 'ONVIF' }, status: 'ONLINE', sessionVerification: 'VERIFIED', discoveredPhase: 3, firstSeenAt: 'now', lastSeenAt: 'now' }));
  const collisions: IPCollisionRecord[] = [];
  const sessions = new CameraBrowserSessions(() => ({ key: 'fixture', devices, collisions }), id => 'http://' + devices.find(d => d.id === id)!.network.ipAddress);
  const hosts: { protocol: NativeProofProtocol; event: (code: string) => void; message: (type: string, extra?: object) => any; commands: string[]; stop: () => void; closed: boolean }[] = [];
  let probes = 0;
  const service = new CameraRendererService(sessions, {
    capability: async () => { probes++; return capability; },
    ...(fixture ? { fixtureAuthority: { permits: (id: string, origin: string) => ['A', 'B'].includes(id) && origin === `http://192.0.2.${id === 'A' ? 1 : 2}` } } : {}),
    launch: (authority, id, options = {}) => {
      const protocol = new NativeProofProtocol(authority, id, options.onEvent);
      const offer = protocol.receive({ v: 1, type: 'BROKER_READY', elevated: false }) as any;
      const grant = protocol.receive({ ...offer, type: 'REDEEM' }) as any;
      let finish!: (r: { closed: boolean }) => void;
      const done = new Promise<{ closed: boolean }>(resolve => finish = resolve);
      const host = { protocol, commands: [] as string[], closed: false,
        message: (type: string, extra = {}) => protocol.receive({ v: 1, type: 'MESSAGE', message: { type, sessionId: grant.session.sessionId, deviceId: id, token: grant.token, ...extra }, event: 'NONE', runtime: '' }) as any,
        event: (code: string) => options.onEvent?.({ code }),
        stop: () => { protocol.close(); host.closed = true; finish({ closed: true }); },
      };
      hosts.push(host);
      return { done, close: host.stop, command: command => { host.commands.push(command); protocol.command(command); }, processId: 123 };
    },
  });
  return { service, sessions, devices, collisions, hosts, probes: () => probes };
}
const args = (r: Awaited<ReturnType<CameraRendererService['open']>>) => [r.session.sessionId, r.session.deviceId, r.controlToken] as const;
test('authorized fixture prefers native after real Phase 6/17C policy', async () => { const s = setup(); const r = await s.service.open('A'); assert.equal(r.session.renderer, 'WINDOWS_WEBVIEW2'); assert.equal(s.hosts.length, 1); assert.equal(s.hosts[0].message('STATUS').state, 'ACTIVE'); s.service.dispose(); });
test('real camera stays intentionally gated despite available host', async () => { const s = setup(false); const r = await s.service.open('A'); assert.equal(r.snapshot.code, 'GATED'); assert.equal(r.session.renderer, 'IFRAME'); assert.equal(s.hosts.length, 0); s.service.dispose(); });
test('an IP cannot bypass stable-ID authorization or production gate', async () => { const s = setup(false); await assert.rejects(s.service.open('192.0.2.1')); assert.equal(s.probes(), 0); assert.equal(s.hosts.length, 0); });
test('device-supplied fixture flag cannot bypass production gate', async () => { const s = setup(false); Object.assign(s.devices[0], { fixture: true, nativeEnabled: true }); assert.equal((await s.service.open('A')).snapshot.code, 'GATED'); assert.equal(s.hosts.length, 0); s.service.dispose(); });
test('unverified identity is rejected before capability or launch', async () => { const s = setup(); s.devices[0].sessionVerification = 'NOT_VERIFIED'; await assert.rejects(s.service.open('A')); assert.equal(s.probes(), 0); });
for (const code of ['HOST_UNAVAILABLE', 'RUNTIME_UNAVAILABLE', 'UNSUPPORTED_PLATFORM'] as const) test(`${code} permits existing iframe compatibility`, async () => { const s = setup(true, { available: false, code }); const r = await s.service.open('A'); assert.equal(r.session.renderer, 'IFRAME'); assert.equal(s.hosts.length, 0); assert.notEqual(r.snapshot.code, 'FAILED'); s.service.dispose(); });
for (const code of ['PROTOCOL_UNAVAILABLE', 'UNELEVATED_REQUIRED'] as const) test(`${code} never iframe-bypasses security`, async () => { const s = setup(true, { available: false, code }); const r = await s.service.open('A'); assert.equal(r.session.renderer, 'WINDOWS_WEBVIEW2'); assert.equal(s.hosts.length, 0); assert.ok(['SECURITY_BLOCKED', 'UNELEVATED_REQUIRED'].includes(r.snapshot.code)); s.service.dispose(); });
test('same-camera concurrent open creates one host and repeated open focuses it', async () => { const s = setup(); const [a, b] = await Promise.all([s.service.open('A'), s.service.open('A')]); assert.equal(a.session.sessionId, b.session.sessionId); const c = await s.service.open('A'); assert.equal(c.session.sessionId, a.session.sessionId); assert.equal(s.hosts.length, 1); assert.deepEqual(s.hosts[0].commands, ['FOCUS']); s.service.dispose(); });
test('different cameras use isolated authorization and commands', async () => { const s = setup(); const a = await s.service.open('A'), b = await s.service.open('B'); s.service.command(...args(a), 'REFRESH'); assert.deepEqual(s.hosts[0].commands, ['REFRESH']); assert.deepEqual(s.hosts[1].commands, []); assert.throws(() => s.service.status(a.session.sessionId, 'B', b.controlToken)); assert.equal(s.hosts[1].message('STATUS').state, 'ACTIVE'); s.service.dispose(); });
test('refresh arrives only through authenticated ack', async () => { const s = setup(); const a = await s.service.open('A'); s.service.command(...args(a), 'REFRESH'); assert.equal(s.hosts[0].message('STATUS').command, 'REFRESH'); assert.equal(s.hosts[0].message('STATUS').command, 'NONE'); s.service.dispose(); });
test('history booleans drive Back and Forward authorization', async () => { const s = setup(); const a = await s.service.open('A'); assert.throws(() => s.service.command(...args(a), 'BACK')); s.hosts[0].message('NAVIGATION', { canGoBack: true, canGoForward: false }); assert.equal(s.service.status(...args(a)).snapshot.canGoBack, true); s.service.command(...args(a), 'BACK'); assert.throws(() => s.service.command(...args(a), 'FORWARD')); s.hosts[0].message('NAVIGATION', { canGoBack: false, canGoForward: true }); s.service.command(...args(a), 'FORWARD'); s.service.dispose(); });
test('arbitrary script/URL command is rejected', async () => { const s = setup(); const a = await s.service.open('A'); assert.throws(() => s.service.command(...args(a), 'http://evil' as any)); assert.throws(() => s.hosts[0].protocol.command('SCRIPT' as any)); s.service.dispose(); });
for (const [event, code] of [['INITIALIZED', 'OPENING'], ['NAVIGATED', 'ACTIVE'], ['CERTIFICATE_REJECTED', 'CERTIFICATE_REJECTED'], ['NAVIGATION_BLOCKED', 'NAVIGATION_BLOCKED'], ['RENDERER_FAILED', 'FAILED'], ['BOOTSTRAP_FAILED', 'SECURITY_BLOCKED'], ['RUNTIME_UNAVAILABLE', 'RUNTIME_UNAVAILABLE']]) test(`workspace receives ${code} without changing renderer`, async () => { const s = setup(); const a = await s.service.open('A'); s.hosts[0].event(event); const r = s.service.status(...args(a)); assert.equal(r.snapshot.code, code); assert.equal(r.session.renderer, 'WINDOWS_WEBVIEW2'); s.service.dispose(); });
test('native close reports closure and reopen gets fresh authorization', async () => { const s = setup(); const a = await s.service.open('A'); s.hosts[0].stop(); await Promise.resolve(); assert.equal(s.service.status(...args(a)).snapshot.code, 'CLOSED'); const b = await s.service.open('A'); assert.notEqual(a.session.sessionId, b.session.sessionId); assert.notEqual(a.controlToken, b.controlToken); s.service.dispose(); });
test('closing one workspace leaves the other host authorized', async () => { const s = setup(); const a = await s.service.open('A'), b = await s.service.open('B'); s.service.close(...args(a)); assert.equal(s.hosts[0].closed, true); assert.equal(s.hosts[1].closed, false); s.service.status(...args(b)); s.service.dispose(); });
for (const reason of ['duplicate', 'conflict', 'stale', 'ip-change', 'removed'] as const) test(`${reason} revokes native access, never retargets`, async () => { const s = setup(); const a = await s.service.open('A'); if (reason === 'duplicate') s.devices[1].network.ipAddress = s.devices[0].network.ipAddress; if (reason === 'conflict') s.devices[0].identityConflicts = [{ kind: 'conflict' }] as any; if (reason === 'stale') s.devices[0].sessionVerification = 'NOT_VERIFIED'; if (reason === 'ip-change') s.devices[0].network.ipAddress = '192.0.2.90'; if (reason === 'removed') s.devices.shift(); s.service.reconcile(); assert.equal(s.hosts[0].closed, true); assert.throws(() => s.service.status(...args(a))); assert.equal(a.session.origin, 'http://192.0.2.1'); s.service.dispose(); });
test('resolved evidence cannot revive revoked control token', async () => { const s = setup(); const a = await s.service.open('A'); s.devices[0].sessionVerification = 'NOT_VERIFIED'; s.service.reconcile(); s.devices[0].sessionVerification = 'VERIFIED'; assert.throws(() => s.service.status(...args(a))); const b = await s.service.open('A'); assert.notEqual(a.session.sessionId, b.session.sessionId); s.service.dispose(); });
test('display identity is sanitized and contains MAC context, no credentials', async () => { const s = setup(); s.devices[0].technician!.name = 'Lobby\n\u202e'; Object.assign(s.devices[0], { password: 'never-send' }); const a = await s.service.open('A'); assert.equal(a.session.display.name, 'Lobby'); assert.equal(a.session.display.identity, 'MAC Last 6: 63FB0F'); assert.ok(!JSON.stringify(a.session).includes('never-send')); assert.equal(JSON.stringify(s.service), '{}'); s.service.dispose(); });
test('native model presents real history; iframe confirmation cannot claim native success', async () => { const s = setup(); const a = await s.service.open('A'); const model = new NativeCameraRenderer(); model.open(a.session); model.displayed(); assert.equal(model.state, 'LOADING'); model.accept({ code: 'ACTIVE', canGoBack: true, canGoForward: false }); assert.equal(model.state, 'DISPLAYED'); assert.equal(model.canGoBack, true); model.block(); assert.equal(model.state, 'BLOCKED'); s.service.dispose(); });
test('production composition has no fixture switch or test import', () => { const server = readFileSync('src/server/index.ts', 'utf8'); assert.match(server, /new CameraRendererService\(cameraBrowserSessions\)/); assert.ok(!server.includes('fixtureAuthority')); const routes = readFileSync('src/server/camera_browser_routes.ts', 'utf8'); assert.ok(!routes.includes('process.env')); assert.match(routes, /Object.keys\(req.body \|\| \{\}\).join\(','\) !== 'deviceId'/); });
test('native ack revalidates authorization before delivering queued commands', async () => { const s = setup(); await s.service.open('A'); s.hosts[0].protocol.command('REFRESH'); s.devices[0].sessionVerification = 'NOT_VERIFIED'; assert.throws(() => s.hosts[0].message('STATUS')); s.service.dispose(); });
