import assert from 'node:assert/strict';
import {factoryCredentialGuidance as guidance, factoryCredentialHint, FACTORY_CREDENTIAL_HINTS} from '../shared/factory_credentials.ts';
import {SiteProjectDatabase} from '../core/storage/project_db.ts';
import {ReportService} from '../core/reporting/report_service.ts';
import {SupportBundleBuilder} from '../core/readiness/support_bundle.ts';
let passed=0;
const check=(value:unknown,label:string)=>{assert.ok(value,label);passed++;console.log('PASS: '+label)};
const first=(vendor:string,model='',firmware='')=>guidance(vendor,model,firmware)[0];
check(first('Hanwha Vision','QND-7082R').id==='hanwha-qnd7082r','exact model outranks manufacturer');
check(guidance('Hanwha Vision','QND-7082R').length===1,'strong model suppresses weaker suggestions');
check(first('Unknown','QND-7082R').passwordState==='INITIAL_SETUP','partial identity preserves model first-login evidence');
check(!first('Unknown','QND-7082R').passwordValue,'QND password is never invented');
check(first('Samsung Techwin',' wisenet QND–7082R ').id==='hanwha-qnd7082r','lineage and model normalization');
check(first('AXIS Communications',' axis 2120 ').id==='axis-2120-legacy','Axis prefix and whitespace normalization');
check(first('Hikvision','','V5.2.0 build 140721').confidence==='FAMILY','documented firmware generation outranks manufacturer');
check(guidance('Hikvision','','5.1.9').length===1,'family suppresses contradictory activation fallback');
check(first('Hikvision','','5.2.1').passwordState==='INITIAL_SETUP','later firmware does not inherit historical password');
check(first('Hikvision','','unknown').confidence==='MANUFACTURER','absent family evidence uses manufacturer guidance');
check(first('Dahua Technology').passwordState==='INITIAL_SETUP','Dahua initialization guidance');
check(first('UNV').passwordState==='UNKNOWN'&&!first('UNV').passwordValue,'Uniview username only');
check(!first('UNV').source.url&&!!first('UNV').source.title,'missing verified URL keeps textual provenance');
check(first('Axis','P3265').passwordState==='INITIAL_SETUP','new Axis model never inherits legacy model password');
check(guidance('Hikvision','2120').length===0,'conflicting manufacturer suppresses exact-model credential');
check(guidance('Unsupported vendor').length===0,'unsupported known manufacturer does not receive generic guesses');
const generic=guidance('Unknown','Unknown');
check(generic.length===2,'generic historical list remains bounded');
check(new Set(generic.map(x=>x.id)).size===2,'multiple historical suggestions independently identified');
check(generic.every(x=>x.scope==='Generic legacy camera'&&x.confidence==='LOW'),'generic applicability always explicit');
check(generic.every(x=>x.notes.includes('not evidence about this camera')),'generic entries do not infer camera vendor');
check(factoryCredentialHint('Unknown','Unknown')===null,'compatibility accessor does not turn generic into device evidence');
check(FACTORY_CREDENTIAL_HINTS.every(x=>!!x.source.title&&!!x.source.reviewed),'every catalog entry retains provenance');
check(first('Axis','2120').source.url?.startsWith('https://www.axis.com/'),'existing official manual link preserved');
check(FACTORY_CREDENTIAL_HINTS.filter(x=>x.passwordState!=='VALUE').every(x=>!x.passwordValue),'non-value states carry no password');
const before=JSON.stringify(FACTORY_CREDENTIAL_HINTS);guidance('Unknown');
check(JSON.stringify(FACTORY_CREDENTIAL_HINTS)===before,'generic lookup never rewrites catalog evidence');
const db=new SiteProjectDatabase();db.createNewProject('Guidance boundary');
db.upsertDevice({id:'guidance-camera',anchor:{macAddress:null,vendor:'Unknown'},network:{ipAddress:'192.0.2.1',port:80,protocol:'ONVIF',subnetMask:null},status:'UNKNOWN',discoveredPhase:3,firstSeenAt:'now',lastSeenAt:'now'});
const snapshot=JSON.stringify(db.getProject());
for(const hint of FACTORY_CREDENTIAL_HINTS)guidance(hint.manufacturer,hint.models?.[0],hint.firmwareMax);
guidance('Unknown');
check(JSON.stringify(db.getProject())===snapshot,'generation leaves device identity status Configured and history unchanged');
const values=FACTORY_CREDENTIAL_HINTS.flatMap(h=>h.passwordValue?[JSON.stringify(h.passwordValue)]:[]);
const clean=(text:string)=>values.every(value=>!text.includes(value));
check(clean(db.exportProjectJson()),'all catalog password values excluded from project serialization');
const reports=new ReportService();
check(clean(reports.json(reports.build(db.getSession(),[],{type:'DEVICE_INVENTORY',scope:'ALL'}))),'all catalog password values excluded from reports');
check(clean(JSON.stringify(db.getProject().auditLogs)),'all catalog password values excluded from audit history');
const bundle=new SupportBundleBuilder().build({application:{name:'test',version:'test',runtime:'test',platform:'test'},readiness:{},network:[],monitoring:{},discovery:{},projectSession:db.getSession(),events:[],pair:null});
check(clean(JSON.stringify(bundle)),'all catalog password values excluded from support bundle');
console.log(`Credential guidance: ${passed} passed, 0 failed, 0 skipped`);
