import {SiteProjectDatabase} from '../core/storage/project_db.ts';
import {ReportSet} from '../core/reporting/report_set.ts';
import {ReportService} from '../core/reporting/report_service.ts';
import {Phase4IdentityReconciliation} from '../core/engine/phase4_reconcile.ts';
import {ProjectReverificationWorkflow} from '../core/engine/reverification.ts';
import {duplicateAssistantView} from '../shared/duplicate_assistant.ts';
import {decideCameraAccess} from '../shared/camera_access.ts';
import {Device} from '../types/index.ts';
let passed=0,failed=0;const check=(v:unknown,n:string)=>{if(v){passed++;console.log('PASS: '+n)}else{failed++;console.error('FAIL: '+n)}};
const camera=(id='A',ip='192.168.1.100'):Device=>({id,anchor:{macAddress:id==='A'?'E4-30-22-CD-68-85':'00:50:f9:63:fb:0f',onvifEndpointUuid:'uuid-'+id,serialNumber:'serial-'+id,vendor:'Camera',model:'Model'},network:{ipAddress:ip,subnetMask:'255.255.255.0',port:80,protocol:'ONVIF'},technician:{name:id,notes:'Field notes'},status:'ONLINE',sessionVerification:'VERIFIED',discoveredPhase:3,firstSeenAt:'now',lastSeenAt:'now'});
async function run(){
 const db=new SiteProjectDatabase();db.startQuickWork();db.upsertDevice(camera());db.removeDeviceFromCurrentList('A');check(!db.getProject().devices.length,'T01 current row hidden');const observe=(d:Device)=>{const stored=db.upsertDevice(d,'DEVICE_ADDED',true);db.restoreDiscoveredDevice(stored)};
 observe(camera());check(!db.getProject().devices.length,'T03/T07 foreground ONVIF rediscovery stays hidden');for(let i=0;i<3;i++)observe(camera());check(!db.getProject().devices.length,'T04/T05 repeated monitoring stays hidden');observe(camera('A','192.168.1.120'));check(!db.getProject().devices.length,'T10 changed IP stays hidden');
 if(typeof (db as any).rediscoverManuallyRemoved!=='function'){check(false,'session suppression API absent on baseline');console.log(`Phase 11 suppression: ${passed} passed, ${failed} failed`);process.exitCode=1;return;}
 const count=()=>db.getSession().currentListSuppression!.count;check(count()===1,'T02 one session suppression');observe(camera('B','192.168.1.100'));check(db.getProject().devices.length===1&&db.getProject().devices[0].id==='B','T11 same-IP replacement stays visible');
 const weak=camera('weak');weak.anchor={macAddress:null,vendor:'Camera',model:'Model'};observe(weak);check(db.getProject().devices.some(d=>d.id==='weak'),'T12-T14 IP/vendor/model never suppress');
 const conflict=camera();conflict.anchor.macAddress='00:11:22:33:44:55';observe(conflict);check(db.getProject().devices.some(d=>d.anchor.macAddress==='00:11:22:33:44:55'),'T15/T17 conflicting MAC not hidden');check(count()===1,'conflict never merges registry');
 db.rediscoverManuallyRemoved();check(count()===0,'T33 registry clears explicitly');check(!db.getProject().devices.some(d=>d.id==='A'),'T34 clearing never resurrects stale row');observe(camera('A','192.168.1.125'));check(db.getProject().devices.some(d=>d.id==='A'&&d.network.ipAddress==='192.168.1.125'),'T35/T36 fresh changed-IP discovery returns');db.rediscoverManuallyRemoved();check(count()===0,'T37 empty rediscover idempotent');
 db.startQuickWork();const partial=camera();partial.anchor.macAddress=null;db.upsertDevice(partial);db.removeDeviceFromCurrentList('A');observe(camera());check(!db.getProject().devices.length&&count()===1,'T16 stronger compatible evidence stays hidden');db.startQuickWork();const macOnly=camera('different-row');macOnly.anchor={macAddress:'E43022CD6885',vendor:'Camera'};observe(macOnly);check(!db.getProject().devices.length,'strengthened MAC survives row/session-project identity changes');
 db.rediscoverManuallyRemoved();db.startQuickWork();db.createNewProject('Saved');db.upsertDevice(camera());db.restoreDiscoveredDevice(db.getDeviceById('A')!);db.exportProjectJsonForSave();const report=new ReportSet(()=>db.getSession());report.add(['A']);const history=JSON.stringify(db.listProjectHistory());db.removeDeviceFromCurrentList('A');check(db.getProjectMemberDevices().length===1&&!db.getSession().dirty,'T18/T19 project member and clean state remain');check(JSON.stringify(db.listProjectHistory())===history,'T60 no project/report history from suppression');check(report.snapshot().members.length===1&&!report.snapshot().members[0].current,'T23 retained Report Set independent');check(new ReportService().build(report.reportSession(),[],{type:'DEVICE_INVENTORY',scope:'REPORT_SET'}).rows.length===1&&count()===1,'T24/T25 retained report does not clear suppression');
 const flow=new ProjectReverificationWorkflow(db,async staging=>{staging.upsertDevice(camera());return 'COMPLETED'});await flow.run();check(count()===1&&!db.getProject().devices.length,'T20 Reverify preserves hiding');check(db.getProjectMemberDevices()[0].sessionVerification==='VERIFIED'&&!db.getSession().dirty,'T21 verified project remains clean');
 const json=db.exportProjectJson();check(!json.includes('suppression')&&!json.includes('awaitingRediscovery')&&JSON.parse(json).project.devices.length===1,'T44 no project persistence');db.importProjectJson(json);check(count()===1&&!db.getProject().devices.length,'T22 project open preserves suppression');const restarted=new SiteProjectDatabase();restarted.importProjectJson(json);check(!restarted.getSession().currentListSuppression?.count&&restarted.getProject().devices.length===1,'T43 new backend loads saved camera without suppression');check(!JSON.stringify(report.reportSession()).includes('currentListSuppression'),'T45 Report Set input contains no suppression state');check(!db.getSession().project.devices.length,'T42 repeated frontend session reads stay hidden');
 report.remove({memberIds:[report.snapshot().members[0].id]});check(count()===1,'T27 Remove from Report leaves suppression');report.clear(true);check(count()===1,'T26 Clear Report Set leaves suppression');db.removeDeviceFromProject('A');check(db.getProjectMemberDevices().length===0&&count()===1,'T49 explicit Project removal independent');
 db.startQuickWork();db.upsertDevice(camera());db.upsertDevice(camera('B'));await Phase4IdentityReconciliation.execute(db);db.removeDeviceFromCurrentList('A');check(db.getDevices().length===2&&db.getProject().devices.length===1,'T28/T29 same-IP identities independent');await Phase4IdentityReconciliation.execute(db);const collision=db.getCollisions()[0];check(collision&&!collision.resolved,'T30/T32 hidden participant does not resolve collision');check(duplicateAssistantView(db.getCollisions(),db.getDevices(),collision.id!)?.participants.length===2,'T31 Duplicate Assistant retains both participants');check(!decideCameraAccess('B',db.getDevices(),db.getCollisions()).allowed,'T65 suppression cannot bypass access safety');

 for(const reverse of [false,true]){const ambiguous=new SiteProjectDatabase(),a=camera(),b=camera('B');a.anchor.serialNumber=b.anchor.serialNumber='same-serial';for(const d of reverse?[b,a]:[a,b])ambiguous.upsertDevice(d);ambiguous.removeDeviceFromCurrentList('A');const w=camera('weak');w.anchor={macAddress:null,vendor:'Camera',serialNumber:'same-serial'};ambiguous.upsertDevice(w);ambiguous.restoreDiscoveredDevice(w);check(ambiguous.getProject().devices.some(d=>d.id==='weak')&&ambiguous.getProject().devices.some(d=>d.id==='B'),'ambiguous serial never hides new identity order='+reverse);}
 const safety=new SiteProjectDatabase();safety.upsertDevice(camera());safety.removeDeviceFromCurrentList('A');safety.removeDeviceFromCurrentList('A');check(safety.getSuppressionDiagnostics().count===1,'repeated removal idempotent');const uuidConflict=camera('A');uuidConflict.anchor.onvifEndpointUuid='conflicting-uuid';safety.upsertDevice(uuidConflict);check(safety.getProject().devices.some(d=>d.anchor.onvifEndpointUuid==='conflicting-uuid'),'conflicting UUID never hidden');
 const unidentified=new SiteProjectDatabase();const weakDevice=camera('unidentified');weakDevice.anchor={macAddress:null,vendor:'Unknown'};unidentified.upsertDevice(weakDevice);unidentified.removeDeviceFromCurrentList(weakDevice.id);check(unidentified.getSuppressionDiagnostics().count===0&&!unidentified.getProject().devices.length,'weak row hide makes no physical suppression claim');unidentified.restoreDiscoveredDevice(weakDevice);check(unidentified.getProject().devices.length===1,'weak evidence may return truthfully without IP blacklist');
 const state=db.getSuppressionDiagnostics();check(state.count===1&&!JSON.stringify(state).includes('Field notes'),'support state is non-sensitive');
 console.log(`Phase 11 suppression: ${passed} passed, ${failed} failed`);if(failed)process.exitCode=1;
}run().catch(e=>{console.error(e);process.exitCode=1});
