import { readFileSync } from 'node:fs';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { Device } from '../types/index.ts';
import { SiteProjectDatabase } from '../core/storage/project_db.ts';
import { BatchExecutionPipeline } from '../core/engine/pipeline.ts';
import { Phase4IdentityReconciliation } from '../core/engine/phase4_reconcile.ts';
import { IncrementalDiscoveryMonitor } from '../core/engine/incremental_discovery_monitor.ts';
import { ConnectService } from '../core/connect/connect_service.ts';
import { CameraNetworkConfigurationService } from '../core/network/camera_network_service.ts';
import * as shared from '../shared/duplicate_assistant.ts';
import { DuplicateAssistantService } from '../core/edge_cases/duplicate_assistant_service.ts';
import { DuplicateDrawer } from '../ui/components/DuplicateDrawer.tsx';

let passed=0,failed=0;const check=(v:unknown,n:string)=>{if(v){passed++;console.log('PASS: '+n)}else{failed++;console.error('FAIL: '+n)}};
const now=()=>new Date().toISOString();
const camera=(id='A',ip='192.168.1.100'):Device=>({id,anchor:{macAddress:id==='A'?'00:50:f9:63:fb:0f':id==='B'?'e4:30:22:cd:68:85':`00:11:22:33:44:${id==='C'?'03':'04'}`,onvifEndpointUuid:'uuid-'+id,vendor:id==='B'?'Hanwha Vision':'Fixture',model:id==='B'?'QND-7082R':undefined},network:{ipAddress:ip,subnetMask:'255.255.255.0',port:80,protocol:'ONVIF'},technician:{name:id==='A'?'IFS02-C10-OIB4':id},status:'ONLINE',sessionVerification:'VERIFIED',discoveredPhase:3,firstSeenAt:now(),lastSeenAt:now(),reachability:{wsDiscoveryRespondedAt:now(),discoveryInterface:{name:'Ethernet',ipAddress:'192.168.1.205',netmask:'255.255.255.0',interfaceIndex:8}}});
async function run(){
 const db=new SiteProjectDatabase();db.createNewProject('Assistant');[camera(),camera('B')].forEach(d=>db.upsertDevice(d));await Phase4IdentityReconciliation.execute(db);db.exportProjectJsonForSave();
 const key=db.getCollisions()[0].id!;let observations=[camera(),camera('B')],cycles=0,allowed=true;
 const monitor=new IncrementalDiscoveryMonitor({canRun:()=>({allowed,reason:'Technician operation active'}),runCycle:async sessionId=>{cycles++;const pipeline=new BatchExecutionPipeline({passiveDiscovery:{discover:async()=>[]} as any,onvifDiscovery:{discover:async(_n:any,o:any)=>{observations.forEach(d=>o.onDevice(structuredClone(d)));return{devices:observations,interfaceErrors:[],cancelled:false}}} as any,deviceEnricher:{enrich:async d=>d}});pipeline.runPhase1=async()=>{(pipeline as any).currentInterfaces=[{name:'Ethernet',ipAddress:'192.168.1.205',netmask:'255.255.255.0',interfaceIndex:8,isInternal:false,broadcast:'',mac:''}]};await pipeline.runDiscoveryScan({database:db,context:{origin:'MONITORING',sessionId},emitTerminalEvent:false})}});
 const service=new DuplicateAssistantService(db,monitor);
 const view=()=>shared?.duplicateAssistantView(db.getCollisions(),db.getDevices(),key);
 const initial=JSON.stringify(db.getSession()),first=view();
 check(first?.active&&first.participants.length===2,'T01 one active logical collision');check(first?.participants.map((p:any)=>p.id).join(',')==='A,B','T02 separate stable identities');
 check(first?.participants[0].name==='IFS02-C10-OIB4'&&first?.participants[1].manufacturer==='Hanwha Vision','T03 identity belongs to correct participant');
 check(first?.participants[0].mac==='00:50:f9:63:fb:0f'&&first?.participants[0].macLastSix==='63FB0F'&&first?.participants[1].macLastSix==='CD6885','T04 full MAC / Last 6');
 check(first?.participants[0].serial===undefined,'T05 missing optional evidence stays absent');
 check(first?.participants.every((p:any)=>!p.access.allowed),'T06/T28 no shared-IP access permission');
 let launches=0;const connect=new ConnectService(db,{available:async()=>['SYSTEM'],launch:async()=>{launches++;return{used:'SYSTEM',fallback:false}}});try{await connect.open('A','SYSTEM')}catch{}check(launches===0,'T07 Phase 6 blocks opening');
 service?.get(key);check(JSON.stringify(db.getSession())===initial,'T12/T33 inspection changes no project or identity');
 const outcome=await service?.recheck(key);check(outcome?.outcome==='COMPLETED'&&cycles===1,'T08 Refresh invokes existing discovery');check(!db.getSession().dirty,'T12 refresh stays clean');
 observations=[];await service?.recheck(key);check(view()?.active,'failed/absent response never proves resolution');
 observations=[camera('A','192.168.1.168'),camera('B')];const result=await service?.recheck(key);
 check(result?.view?.active===false,'T14 trusted identity move resolves');check(db.getDevices().every(d=>d.status!=='COLLISION'),'T15 Duplicate IP status clears');check(db.getCollisions().filter(c=>!c.resolved).length===0,'T16 active count clears');check(db.getDevices().map(d=>d.id).join(',')==='A,B','T17 stable identities retained');
 check(view()?.participants.every((p:any)=>p.access.allowed),'T18 safe current Open restored');check(view()?.active===false,'T20 historical record not active');check(db.getCollisions()[0].id===key&&db.getCollisions()[0].collidingDevices.length===2,'T35 historical evidence intact');check(!db.getSession().dirty,'resolved runtime state stays clean');
 observations=[camera(),camera('B')];await service?.recheck(key);check(view()?.active&&view()?.participants.every((p:any)=>!p.access.allowed),'T21 reopened collision blocks');
 observations=[camera(),camera('B'),camera('C','192.168.1.200'),camera('D','192.168.1.200')];await service?.recheck(key);const second=db.getCollisions().find(c=>c.ipAddress==='192.168.1.200');const secondView=shared?.duplicateAssistantView(db.getCollisions(),db.getDevices(),second?.id||'missing');check(view()?.participants.length===2&&secondView?.participants.map((p:any)=>p.id).join(',')==='C,D','T22 multiple collisions remain separate');check(db.getProjectMemberDevices().map(d=>d.id).join(',')==='A,B','T34 read-only discovery never adds Project membership');
 observations=[camera(),camera('B'),camera('C')];await service?.recheck(key);check(view()?.participants.length===3,'T23 three participants visible');check(db.getCollisions().filter(c=>!c.resolved&&c.ipAddress==='192.168.1.100').length===1,'T24 one logical collision for three');
 check(shared?.collisionKeyForDevice(db.getDeviceById('A')!,db.getCollisions())===key,'T25/T26 correct selected collision key');check(!shared?.duplicateAssistantView(db.getCollisions(),db.getDevices(),'missing'),'missing selected record never falls back to unrelated collision');
 const beforeCycles=cycles;await Promise.all([service?.recheck(key),service?.recheck(key)]);check(cycles===beforeCycles+1,'concurrent same-collision checks coalesce');allowed=false;const blocked=await service?.recheck(key);check(blocked?.outcome==='SKIPPED'&&cycles===beforeCycles+1,'existing operation guard blocks overlapping discovery');
 const network=new CameraNetworkConfigurationService(db);for(const id of ['A','B']){let denied=false;try{await network.readCurrent(id,'unused')}catch(e){denied=(e as any).code==='DUPLICATE_AMBIGUOUS'}check(denied,'T29/T30 known MAC/UUID does not authorize ambiguous configuration '+id)}
 db.getDeviceById('A')!.diagnostics={checks:[{type:'HTTPS',targetIp:'192.168.1.100',success:true,timestamp:now()}]};check(view()?.participants[0].access.allowed===false,'T31 diagnostic success cannot grant ownership');
 const props={isOpen:true,onClose:()=>{},collisions:db.getCollisions(),devices:db.getDevices(),selectedCollisionId:key,onChanged:async()=>{},onDetails:()=>{},onDiagnose:async()=>{},onOpen:()=>{}};
 const markup=renderToStaticMarkup(React.createElement(DuplicateDrawer,props as any));
 check(markup.includes('MAC Last 6')&&markup.includes('Not available'),'UI exposes identity and honest missing fields');check(markup.includes('bg-white')&&markup.includes('overflow-y-auto')&&markup.includes('max-h-'),'T37 light, bounded scrolling surface');check(!/Credential|Password|credentialId|secret-value/.test(markup),'T38 no credential material rendered');
 const ui=readFileSync('src/ui/components/DuplicateDrawer.tsx','utf8');check(!/\/apply|\/preview|\/candidates|credentialId|authorizeIsolated/.test(ui),'T09-T11/T29-T32 no adapter/camera/credential operation in assistant');check(ui.includes('/recheck')&&!ui.includes('/rescan'),'Refresh calls functional read-only route');
 const server=readFileSync('src/server/index.ts','utf8');check(server.includes('duplicateAssistantService.recheck')&&server.includes('new DuplicateAssistantService(projectDb,incrementalMonitor)'),'T13 recheck reuses monitor without a new Task');
 check(readFileSync('src/ui/components/BrowserModal.tsx','utf8').includes('onOpenDuplicateAssistant'),'T27 blocked access offers assistant route');
 const historyId=db.getCollisions()[0].id;
 db.upsertDevice(camera('A','192.168.1.168'),'DEVICE_ADDED',true);db.upsertDevice(camera('C','192.168.1.169'),'DEVICE_ADDED',true);
 const fg=new BatchExecutionPipeline();await fg.runPhase4(db);
 check(view()?.active===false&&view()?.participants.every(p=>p.access.allowed)&&db.getCollisions()[0].id===historyId,'T36 actual foreground final reconciliation resolves same assistant record');
 check(db.getDeviceById('A')!.network.ipAddressHistory?.includes('192.168.1.100')&&db.getDeviceById('A')!.technician?.name==='IFS02-C10-OIB4','identity move preserves address history and technician metadata');
 const failureMonitor=new IncrementalDiscoveryMonitor({canRun:()=>({allowed:true}),runCycle:async()=>{throw Error('secret-value')}});
 const failure=await new DuplicateAssistantService(db,failureMonitor).recheck(key);
 check(failure.outcome==='FAILED'&&failure.view.active===false&&!failure.reason?.includes('secret-value'),'failed refresh exposes safe error and preserves current lifecycle');
 const row=db.getDeviceById('A')!;row.manufacturerParams={credentialId:'secret-value',password:'secret-value'};
 check(!JSON.stringify(service.get(key)).includes('secret-value'),'safe projection excludes raw provider secrets');
 const missing=shared.duplicateAssistantView(db.getCollisions(),db.getDevices().filter(d=>d.id!=='A'),key)!;
 check(missing.participants.find(p=>p.id==='A')?.current===false&&!missing.participants.find(p=>p.id==='A')?.access.allowed,'historical absent participant cannot acquire current actions');
 const wrong=renderToStaticMarkup(React.createElement(DuplicateDrawer,{...props,selectedCollisionId:'missing'}));
 check(wrong.includes('no longer available')&&!wrong.includes('63FB0F'),'stale unknown selection never renders another group');
 const memberBefore=db.getProjectMemberDevices().map(d=>d.id).join(',');
 check(memberBefore==='A,B'&&!db.isProjectMember('C'),'new runtime participants stay outside saved project membership');
 db.upsertDevice(db.getDeviceById('C')!);check(db.isProjectMember('C')&&db.getSession().dirty,'explicit project addition still promotes runtime participant');

 console.log(`Phase 7 assistant: ${passed} passed, ${failed} failed`);if(failed)process.exitCode=1;
}
run().catch(e=>{console.error(e);process.exitCode=1});
