import { readFileSync } from 'node:fs';
import { presentTechnicianError, sanitizeTechnicalDetail, technicianErrorResponse } from '../shared/error_presentation.ts';
import { sanitizeSupportEvidence, SupportBundleBuilder } from '../core/readiness/support_bundle.ts';
import { AuditLogEntry, Device, ProjectSession } from '../types/index.ts';
import { IncrementalDiscoveryMonitor } from '../core/engine/incremental_discovery_monitor.ts';

let passed=0,failed=0;const assert=(value:unknown,name:string)=>{if(value){console.log(`  PASS: ${name}`);passed++}else{console.error(`  FAIL: ${name}`);failed++}};
const error=(message:string,code?:string)=>Object.assign(new Error(message),code?{code}:{});
const device:Device={id:'camera-stable-1',anchor:{macAddress:'aa:bb:cc:dd:ee:ff',onvifEndpointUuid:'uuid-camera-1',serialNumber:'SERIAL-1',vendor:'Fixture Camera',model:'First Camera',firmwareVersion:'1.2.3'},network:{ipAddress:'192.168.1.80',subnetMask:'255.255.255.0',port:80,protocol:'ONVIF',ipAddressHistory:['192.168.1.64','192.168.1.80']},status:'ONLINE',sessionVerification:'VERIFIED',discoveredPhase:3,firstSeenAt:'2026-09-04T10:01:02.000Z',lastSeenAt:'2026-09-04T10:04:23.000Z',diagnostics:{checks:[{type:'HTTP',targetIp:'192.168.1.64',port:80,protocol:'http',success:true,responseTimeMs:18,httpStatus:200,timestamp:'2026-09-04T10:01:04.000Z'}]},connectionHistory:[{id:'connect-1',timestamp:'2026-09-04T10:02:00.000Z',mode:'SYSTEM',url:'http://192.168.1.64',statusBeforeOpen:'ONLINE',event:'OPEN_ATTEMPT',result:'Technician initiated camera access.'}],configurationEvidence:{verifiedOperations:['NTP'],updatedAt:'2026-09-04T10:04:23.000Z'}};
const session:ProjectSession={mode:'PROJECT',dirty:true,project:{id:'project-1',name:'First Camera Field Test',siteLocation:'Lab',technicianName:'Tech',createdAt:'2026-09-04T10:00:00.000Z',updatedAt:'2026-09-04T10:05:00.000Z',totalDevices:1,devices:[device],collisions:[],rogueDhcpEvents:[],auditLogs:[]}};
const audit=(timestamp:string,message:string,category:AuditLogEntry['category']='DISCOVERY',level:AuditLogEntry['level']='INFO',details?:Record<string,unknown>):AuditLogEntry=>({id:crypto.randomUUID(),timestamp,category,level,message,deviceId:'camera-stable-1',details});

async function run(){
  let shown=presentTechnicianError(error('connect ECONNREFUSED 192.168.1.64','CONNECTION_FAILED'),{deviceId:device.id});assert(shown.code==='UNREACHABLE'&&shown.title==='Camera could not be reached'&&shown.action?.includes('power'),'A unreachable has practical message/action');assert(!shown.message.includes('ECONNREFUSED')&&shown.technicalDetails?.includes('ECONNREFUSED'),'A raw socket detail is secondary');
  shown=presentTechnicianError(error('request ETIMEDOUT','TIMEOUT'));assert(shown.code==='TIMEOUT'&&shown.technicalDetails?.includes('ETIMEDOUT'),'B timeout categorized with safe technical detail');
  shown=presentTechnicianError(error('Saved credential not found','CREDENTIAL_NOT_FOUND'));assert(shown.code==='AUTHENTICATION_REQUIRED'&&shown.action?.includes('credential')&&!JSON.stringify(shown).includes('hunter2'),'C authentication required suggests credential without secret');
  shown=presentTechnicianError(error('Camera returned 401 unauthorized','UNAUTHORIZED'));assert(shown.code==='AUTHENTICATION_FAILED'&&shown.title.includes('failed'),'D authentication failed differs from unreachable');
  shown=presentTechnicianError(error('Vendor-native operation unsupported','UNSUPPORTED'));assert(shown.code==='UNSUPPORTED'&&shown.message.includes('provider'),'E unsupported explains provider limitation');
  shown=presentTechnicianError(error('DIFFERENT_SUBNET','DIFFERENT_SUBNET'));assert(shown.code==='DIFFERENT_NETWORK'&&shown.action?.includes('Pair'),'F different network suggests Pair without invoking it');
  shown=presentTechnicianError(error('Duplicate collision','DUPLICATE_AMBIGUOUS'));assert(shown.code==='DUPLICATE_IP'&&shown.action?.includes('Duplicate Assistant'),'G duplicate IP suggests safe remediation');
  shown=presentTechnicianError(error('spawn powershell.exe ENOENT','ADMIN_REQUIRED'));assert(shown.code==='WINDOWS_PERMISSION_REQUIRED'&&!shown.message.includes('powershell'),'H Windows permission has practical primary text');
  shown=presentTechnicianError(new TypeError('Cannot read properties of undefined\n at secret stack'));assert(shown.code==='UNKNOWN'&&!shown.message.includes('TypeError')&&!shown.message.includes('stack')&&Boolean(shown.technicalDetails),'I unknown error is truthful with secondary detail');
  shown=presentTechnicianError(error('Technician cancelled scan','CANCELLED'));assert(shown.code==='CANCELLED'&&!shown.message.includes('failed'),'J cancellation is not failure');
  shown=presentTechnicianError(error('Write accepted; final verification unavailable','VERIFICATION_UNKNOWN'));assert(shown.code==='UNKNOWN'&&!shown.message.includes('failed'),'K unknown result remains distinct from failed');
  const response=technicianErrorResponse(error('fetch failed bearer abc.def','CONNECTION_FAILED'),{operation:'CONNECT',deviceId:device.id});assert(typeof response.error==='string'&&response.presentation.action&&response.presentation.reference.startsWith('OP-'),'L API keeps safe compatibility string and structured error');assert(!response.error.includes('fetch failed')&&response.presentation.context?.deviceId===device.id,'L raw exception is not primary and stable ID context retained');
  const technical=sanitizeTechnicalDetail('POST /x?password=hunter2 Authorization: Bearer abc.def');assert(!technical?.includes('hunter2')&&!technical?.includes('abc.def'),'technical details redact query/auth secrets');
  let cycles=0;const monitor=new IncrementalDiscoveryMonitor({runCycle:async()=>{cycles++;if(cycles===1)throw Error('ETIMEDOUT raw')},canRun:()=>({allowed:true}),setTimer:()=>({unref(){}} as any),clearTimer:()=>{}});monitor.start();assert(await monitor.runNow()==='FAILED'&&monitor.getState().lastError?.includes('will retry'),'O monitoring failure is sanitized and retryable');assert(await monitor.runNow()==='COMPLETED'&&cycles===2,'O later monitoring cycle still runs without alert behavior');monitor.stop();
  const events=[audit('2026-09-04T10:01:02.000Z','Quick Scan discovered ONVIF camera.'),audit('2026-09-04T10:01:03.000Z','MAC enriched for stable device.','DISCOVERY','INFO',{macAddress:device.anchor.macAddress}),audit('2026-09-04T10:02:10.000Z','Camera authentication required.','PROVISIONING','WARNING',{reference:'OP-AUTH0001',result:'UNKNOWN'}),audit('2026-09-04T10:04:10.000Z','Network configuration requested.','PROVISIONING','INFO',{reference:'OP-NET00001',result:'UNKNOWN'}),audit('2026-09-04T10:04:23.000Z','Same MAC verified at changed IP.','EDGE_CASE','SUCCESS',{oldIp:'192.168.1.64',newIp:'192.168.1.80',result:'VERIFIED'})];
  const builder=new SupportBundleBuilder(),bundle=builder.build({application:{name:'CCTV Network Assistant',version:'1.6.0',runtime:'v24',platform:'win32'},readiness:{overall:'READY'},network:[{interfaceAlias:'Ethernet',mediaType:'ETHERNET',operationalStatus:'Up',ipv4Addresses:[{address:'192.168.1.10',prefixLength:24}]}],monitoring:{incrementalDiscovery:{enabled:true,lastRunAt:'2026-09-04T10:05:00.000Z'}},discovery:{running:false,scanType:'QUICK'},projectSession:session,events,pair:null}) as any;
  assert(['manifest','application','readiness','network','monitoring','discovery','project','devices','deviceTimelines','globalTimeline','recentErrors'].every(key=>key in bundle),'W support bundle has expected logical sections');
  const timeline=bundle.deviceTimelines[device.id];assert(timeline.length>=events.length&&timeline.every((item:any)=>item.deviceId===device.id)&&timeline.every((item:any,index:number)=>!index||timeline[index-1].timestamp<=item.timestamp),'X per-device timeline is chronological and stable-ID keyed');
  assert(bundle.globalTimeline.every((item:any,index:number)=>!index||bundle.globalTimeline[index-1].timestamp<=item.timestamp),'Y global timeline is chronological');
  const dirty=sanitizeSupportEvidence({nested:{password:'hunter2',authorization:'Bearer abc',cookie:'sid=x',safe:{mac:'aa:bb',serial:'SERIAL-1',uuid:'uuid-1'}},url:'http://x/?token=abc'});const encoded=JSON.stringify(dirty);assert(!encoded.includes('hunter2')&&!encoded.includes('Bearer abc')&&!encoded.includes('sid=x')&&!encoded.includes('token=abc'),'Z nested secret fields and strings are redacted');assert(encoded.includes('aa:bb')&&encoded.includes('SERIAL-1')&&encoded.includes('uuid-1'),'AB safe MAC/serial/UUID evidence is preserved');
  assert(!encoded.includes('username')&&!encoded.includes('vault'),'AA support evidence does not enumerate vault contents');assert(bundle.devices[0].identity.manufacturer==='Fixture Camera'&&bundle.devices[0].identity.firmwareVersion==='1.2.3','AB real manufacturer/model/firmware evidence is retained');
  const unknownDevice={...device,id:'unknown',anchor:{macAddress:null,vendor:'Unknown'},configurationEvidence:undefined};const unknownBundle=builder.build({application:{name:'x',version:'x',runtime:'x',platform:'x'},readiness:{},network:[],monitoring:{},discovery:{},projectSession:{...session,project:{...session.project,devices:[unknownDevice]}},events:[],pair:null})as any;assert(unknownBundle.devices[0].identity.model===undefined&&unknownBundle.devices[0].identity.firmwareVersion===undefined,'AC missing evidence remains absent');
  assert(timeline.some((item:any)=>item.reference==='OP-NET00001'),'AD correlation reference connects operation evidence to device timeline');
  const many=Array.from({length:300},(_,index)=>audit(new Date(Date.UTC(2026,8,4,11,0,index)).toISOString(),`Event ${index}`));const bounded=builder.build({application:{name:'x',version:'x',runtime:'x',platform:'x'},readiness:{},network:[],monitoring:{},discovery:{},projectSession:session,events:many,pair:null})as any;assert(bounded.globalTimeline.length===250&&bounded.deviceTimelines[device.id].length===100&&bounded.manifest.truncated.globalTimeline&&bounded.manifest.truncated.deviceTimelines[device.id],'AE bundle caps and truncation metadata are correct');
  assert(timeline.some((item:any)=>item.category==='DISCOVERY')&&timeline.some((item:any)=>item.category==='DIAGNOSTIC')&&timeline.some((item:any)=>item.category==='CONFIGURATION')&&timeline.some((item:any)=>item.category==='IDENTITY'),'first-camera fixture reconstructs discovery, diagnostics, configuration, and identity change');
  const server=readFileSync('src/server/index.ts','utf8'),advanced=readFileSync('src/core/engine/advanced_scan.ts','utf8'),reverify=readFileSync('src/core/engine/reverification.ts','utf8'),settings=readFileSync('src/ui/components/SettingsMenu.tsx','utf8');assert(server.includes('technicianErrorResponse')&&server.includes('safeError(res'),'M/R/Q/S/T/U/V critical API paths share safe presentation boundary');assert(advanced.includes('catch (error)')&&advanced.includes('errors.push'),'N Advanced Scan retains recoverable provider error isolation');assert(reverify.includes('discovery stopped unexpectedly')&&reverify.includes('finally { this.running = false; }'),'P Reverify remains valid and retryable after failure');assert(settings.includes('Support bundle created. Credentials and passwords are excluded.'),'AF support generation remains recognizable with safe confirmation');assert(server.includes('incrementalMonitor')&&server.includes('ProjectReverificationWorkflow')&&server.includes('LegacyConfigurationBoundary'),'AG/AH/AI completed milestone architectures remain integrated');
  console.log(`\nError and support evidence summary: ${passed} passed, ${failed} failed`);if(failed)process.exit(1)
}run().catch(reason=>{console.error(reason);process.exit(1)});
