import { readFileSync } from 'node:fs';
import { fieldCamera, fieldEthernet, fieldNic } from './support/first_camera_field.ts';
import { applyNetworkRelationship, canOfferPair } from '../shared/network_relationship.ts';
import { normalizeIPv4, normalizeManualMac, addressRelationship } from '../shared/address_validation.ts';
import { sortDevices, nextDeviceSort, DeviceSortColumn } from '../shared/device_sort.ts';
import { LegacyHardwareOnboarding } from '../core/edge_cases/legacy_hardware.ts';
import { projectDb, SiteProjectDatabase } from '../core/storage/project_db.ts';
import { PairService } from '../core/network/pair_service.ts';
import { DeviceDiagnosticEngine } from '../core/engine/diagnostic_engine.ts';
import { AdvancedScanService, matchesAdvancedScanFilters } from '../core/engine/advanced_scan.ts';
import { WindowsNeighborDiscoveryProvider } from '../core/engine/phase2_passive.ts';
import { emptyAdvancedScanRequest } from '../shared/advanced_scan.ts';
import { SupportBundleBuilder } from '../core/readiness/support_bundle.ts';
import { Device, PairSessionState } from '../types/index.ts';

let passed=0,failed=0;
const a=(condition:unknown,name:string)=>{if(condition){passed++;console.log(`  PASS: ${name}`)}else{failed++;console.error(`  FAIL: ${name}`)}};
const rejects=async(fn:()=>unknown)=>{try{await fn();return false}catch{return true}};
async function run(){
  const topology=[fieldEthernet()]; projectDb.startQuickWork();
  const manual=LegacyHardwareOnboarding.onboardLegacyDevice({ipAddress:' 192.168.1.100 ',macAddress:' E4-30-22-CD-68-85 ',manufacturer:'Hanwha Vision'},topology);
  a(manual.status==='DIFFERENT_SUBNET','field manual address classified Different Network');
  a(manual.sessionVerification==='NOT_VERIFIED','network relationship does not verify manual identity');
  a(manual.anchor.macAddress==='e4:30:22:cd:68:85'&&manual.id===fieldCamera().id,'manual identity canonical MAC and stable ID');
  a(canOfferPair(manual),'Pair available before any camera response');
  a(!manual.reachability?.lastSuccessfulResponseAt&&!manual.reachability?.wsDiscoveryRespondedAt&&!manual.diagnostics,'no ping, HTTP, ONVIF or diagnostics needed');
  a(projectDb.upsertDevice(manual).sessionVerification==='NOT_VERIFIED','storage update cannot promote topology to verification');
  a(!canOfferPair(applyNetworkRelationship({...fieldCamera(),network:{...fieldCamera().network,ipAddress:'192.168.0.124'}},topology,[])),'local-host Pair unavailable');
  a(!canOfferPair(applyNetworkRelationship(fieldCamera(),topology,[{...fieldCamera(),id:'other'}])),'duplicate-IP Pair unavailable');
  a(!canOfferPair(applyNetworkRelationship({...fieldCamera(),identityConflicts:[{detectedAt:'now',reason:'conflict'}]},topology,[])),'conflicting identity Pair unavailable');
  let mutations=0,restores=0,saves=0; let current=fieldEthernet(); let saved:PairSessionState|null=null;
  const adapters={inspectAdapters:async()=>[structuredClone(current)],isAdministrator:async()=>true,applyTemporary:async(index:number,ip:string,prefix:number)=>{mutations++;a(index===8,'only selected Ethernet adapter mutated on explicit apply');current={...current,dhcpEnabled:false,ipv4Addresses:[{address:ip,prefixLength:prefix}]};return structuredClone(current)},restore:async(snapshot:any)=>{restores++;current=structuredClone(snapshot);return current}};
  const failure={check:async(ip:string)=>({type:'PING' as const,targetIp:ip,success:false,timestamp:'now'})};
  const diagnostics=new DeviceDiagnosticEngine({ping:failure,http:failure,tcp:failure});
  await diagnostics.diagnose(manual);
  a(manual.status==='DIFFERENT_SUBNET'&&manual.statusMessage?.includes('Pair/Match Network'),'Diagnose explains off-subnet without Offline/Failed');
  a(manual.sessionVerification==='NOT_VERIFIED'&&mutations===0,'Diagnose and manual add cause no adapter mutation');
  const checked:string[]=[];
  const checker={check:async(ip:string)=>{checked.push(ip);return {availability:ip==='192.168.1.137'?'OCCUPIED' as const:'AVAILABLE' as const,evidence:['Deterministic software check']}}};
  projectDb.upsertDevice({...fieldCamera(),id:'known',anchor:{macAddress:'00:11:22:33:44:88',vendor:'Unknown'},network:{...fieldCamera().network,ipAddress:'192.168.1.174'}});
  const recovery={load:async()=>saved,save:async(value:PairSessionState)=>{saves++;saved=structuredClone(value)},clear:async()=>{saved=null}};
  const pair=new PairService(adapters,checker,diagnostics,recovery,projectDb);
  const eligible=await pair.getEligibility(manual.id);
  a(canOfferPair(eligible)&&eligible.sessionVerification==='NOT_VERIFIED'&&mutations===0,'fresh Pair eligibility is read-only and needs no live verification');
  const preview=await pair.prepare(manual.id,8);
  a(preview.state==='READY_FOR_CONFIRMATION'&&mutations===0&&saves===0,'Pair preview has no mutation or recovery write');
  a(preview.subnetSource==='ADAPTER_PREFIX_PROPOSAL'&&preview.cameraSubnetMask==='255.255.255.0','unknown camera mask is explicit adapter-prefix proposal');
  a(manual.network.subnetMask===null,'Pair proposal does not invent camera mask');
  a(JSON.stringify(preview.originalAdapter)===JSON.stringify(fieldEthernet()),'complete original adapter snapshot preserved');
  a(preview.candidates.length>0&&preview.candidates.length<=3&&checked.length<=32,'bounded candidate search remains usable');
  a(preview.candidates.every(c=>addressRelationship(c.ipAddress,'192.168.1.100',24)==='LOCAL'),'candidates compatible with field /24');
  a(preview.candidates.every(c=>!['192.168.1.0','192.168.1.255','192.168.1.100','192.168.1.137','192.168.1.174','192.168.0.124'].includes(c.ipAddress)),'camera, network, broadcast, local and occupied addresses excluded');
  a(await rejects(()=>pair.confirmAndApply(preview.id,false))&&mutations===0,'explicit confirmation required');
  const paired=await pair.confirmAndApply(preview.id,true);
  a(paired.recoveryAvailable&&saves>0&&!paired.cameraReachabilityVerified,'recovery retained even when camera does not respond');
  a(manual.network.ipAddress==='192.168.1.100'&&!manual.onvifConfig,'Pair never changes camera IP or configuration');
  const restored=await pair.restore();
  a(restored.state==='RESTORED'&&restores===1&&saved===null,'explicit Restore clears recovery after verification');
  a(JSON.stringify(current)===JSON.stringify(fieldEthernet()),'original Ethernet restored');
  a(projectDb.getDeviceById(manual.id)?.status==='DIFFERENT_SUBNET','Restore refreshes network relationship');
  const blockedDb=new SiteProjectDatabase();blockedDb.startQuickWork();
  blockedDb.upsertDevice({...fieldCamera(),network:{...fieldCamera().network,ipAddress:'192.168.0.124'}});
  const blockedPair=new PairService(adapters,checker,diagnostics,recovery,blockedDb);
  a(await rejects(()=>blockedPair.prepare(fieldCamera().id,8)),'backend rejects local-host Pair preparation');
  blockedDb.startQuickWork();blockedDb.upsertDevice(fieldCamera());
  const duplicatePreview=await blockedPair.prepare(fieldCamera().id,8);
  blockedDb.upsertDevice({...fieldCamera(),id:'second',anchor:{macAddress:'00:11:22:33:44:88',vendor:'Unknown'}});
  a(await rejects(()=>blockedPair.confirmAndApply(duplicatePreview.id,true))&&mutations===1,'new duplicate after preview blocks apply');
  a(await rejects(()=>blockedPair.prepare(fieldCamera().id,8)),'backend rejects ambiguous Pair preparation');
  for(const ip of ['1.2.3','1..2.3','1.2.3.256','1.2.3.-1','1.2.3.1e2','192.168.001.100']) a(normalizeIPv4(ip)===null,`reject malformed IPv4 ${ip}`);
  a(normalizeIPv4(' 192.168.1.100 ')==='192.168.1.100','IPv4 whitespace normalized');
  for(const mac of ['E4:30:22:CD:68:85','E4-30-22-CD-68-85','E43022CD6885']) a(normalizeManualMac(mac)==='e4:30:22:cd:68:85',`normalize MAC ${mac}`);
  for(const mac of ['E4:30:22:CD:68','E4:30-22:CD:68:85','E4!30!22!CD!68!85','zz:30:22:CD:68:85']) a(normalizeManualMac(mac)===null,`reject malformed MAC ${mac}`);
  a(await rejects(()=>LegacyHardwareOnboarding.onboardLegacyDevice({ipAddress:'1..2.3'})),'backend rejects malformed manual IP');
  a(await rejects(()=>LegacyHardwareOnboarding.onboardLegacyDevice({ipAddress:'192.168.1.100',macAddress:'invalid'})),'backend rejects malformed manual MAC');
  a(LegacyHardwareOnboarding.onboardLegacyDevice({ipAddress:'192.168.1.90'}).anchor.macAddress===null,'optional MAC remains absent');
  const db=new SiteProjectDatabase();db.startQuickWork();
  const scan=new AdvancedScanService(adapters,{check:async(ip)=>({type:'PING',targetIp:ip,success:ip.endsWith('.9'),timestamp:'now'})},{check:async(ip,options)=>({type:'TCP',targetIp:ip,port:options.port,success:['192.168.1.100','192.168.1.200'].includes(ip),timestamp:'now'})},db);
  const request=emptyAdvancedScanRequest();request.adapterIndexes=[8];request.targets=[{type:'RANGE',start:'192.168.1.1',end:'192.168.1.254'}];request.methods=['PING','TCP'];request.customPorts=[80];
  const emitted:string[]=[];const status=await scan.execute(await scan.validate(request),{onDevice:d=>emitted.push(d.id),onComplete:()=>{}});
  a(status.completedTargets===254&&status.findings===3&&db.getDevices().length===3,'254 checked targets produce exactly three evidence-backed candidates');
  a(emitted.length===3,'three progressive device events, none for silent targets');
  a(db.getDevices().some(d=>d.network.ipAddress==='192.168.1.9'),'positive ICMP can surface unknown device');
  a(db.getDevices().some(d=>d.network.ipAddress==='192.168.1.100'),'positive TCP can surface unknown device');
  a(db.getDevices().every(d=>!d.anchor.macAddress&&!d.anchor.serialNumber&&d.anchor.vendor==='Unknown'),'transport does not invent camera identity');
  a(db.getDevices().every(d=>matchesAdvancedScanFilters(d,{includeUnknownDevices:true,onlyLikelyCameras:false})),'Include Unknown ON includes evidenced devices');
  a(db.getDevices().every(d=>!matchesAdvancedScanFilters(d,{includeUnknownDevices:false,onlyLikelyCameras:false})),'Include Unknown OFF filters unknown types');
  const before=db.getDevices().length;const original=db.getDevices()[0]; db.upsertDevice({...original,id:'separate',anchor:{macAddress:'00:11:22:33:44:aa',vendor:'Other'}});
  await scan.execute(await scan.validate(request),{onDevice:()=>{},onComplete:()=>{}});
  a(db.getDevices().length===before+1,'duplicate-IP stable identities remain separate after transport scan');
  a(db.getDevices().filter(d=>d.network.ipAddress===original.network.ipAddress).every(d=>d.diagnostics?.checks.at(-1)?.ambiguousIdentity),'shared-IP transport evidence remains ambiguous');
  const neighbor=new WindowsNeighborDiscoveryProvider({list:async()=>[{ipAddress:'192.168.1.100',macAddress:'E4:30:22:CD:68:85',interfaceIndex:8,state:'Stale'},{ipAddress:'192.168.1.101',macAddress:'00:00:00:00:00:00',interfaceIndex:8,state:'Incomplete'}]});
  const found=await neighbor.discover([fieldNic()]);
  a(found.length===1&&found[0].id===fieldCamera().id,'safe neighbor mapping surfaces a stable identity');
  a(found[0].sessionVerification==='NOT_VERIFIED','cached neighbor evidence does not assert live verification');
  const rows:Device[]=[{...fieldCamera(),id:'b',technician:{name:'Beta'},anchor:{macAddress:'00:11:22:aa:00:02',vendor:'Unknown',serialNumber:'B'},network:{...fieldCamera().network,ipAddress:'192.168.1.100'},status:'ONLINE',configuredState:{inferred:true}}, {...fieldCamera(),id:'a',technician:{name:'Alpha'},anchor:{macAddress:'00:11:22:aa:00:01',vendor:'Unknown',serialNumber:'A'},network:{...fieldCamera().network,ipAddress:'192.168.1.9'},status:'DIFFERENT_SUBNET',configuredState:{inferred:false}}];
  for(const column of ['NAME','STATUS','IP','LAST_6','CONFIGURED','SERIAL'] as DeviceSortColumn[]){
    a(sortDevices(rows,{column,direction:'asc'})[0].id==='a',`${column} ascending sort`);
    a(sortDevices(rows,{column,direction:'desc'})[0].id==='b',`${column} descending sort`);
  }
  a(rows[0].id==='b','sorting does not mutate source inventory');
  a(nextDeviceSort(null,'IP').direction==='asc'&&nextDeviceSort({column:'IP',direction:'asc'},'IP').direction==='desc','header toggles ascending then descending');
  const selected=new Set(['b']);a(sortDevices(rows,{column:'IP',direction:'asc'}).filter(d=>selected.has(d.id))[0].network.ipAddress==='192.168.1.100','selection preserves stable identity after sort');
  a(sortDevices(rows.filter(d=>d.technician?.name==='Beta'),{column:'NAME',direction:'asc'})[0].id==='b','sorting coexists with search and filtering');
  a(sortDevices([...rows,{...rows[1],id:'c',network:{...rows[1].network,ipAddress:'192.168.1.10'}}],{column:'IP',direction:'asc'}).map(d=>d.id).join()==='a,c,b','progressive rows retain numeric IP ordering');
  a(sortDevices([{...rows[0],id:'z',anchor:{vendor:'Unknown',macAddress:null}},...rows],{column:'SERIAL',direction:'desc'}).at(-1)?.id==='z','unknown values remain last in descending order');
  const table=readFileSync('src/ui/components/MasterDeviceTable.tsx','utf8');
  a(table.includes('device={actionDevice}')&&table.includes('device.id === openActionMenu?.device.id'),'Actions resolves current device by stable ID');
  a(table.includes('aria-sort=')&&!table.includes("sortHeader('ACTIONS'"),'accessible sort indication and nonsortable Actions');
  const server=readFileSync('src/server/index.ts','utf8'),pipeline=readFileSync('src/core/engine/pipeline.ts','utf8');
  a(!pipeline.includes('pairService')&&!server.slice(server.indexOf("app.post('/api/edge/legacy-onboard'"),server.indexOf('// Section 13.4')).includes('confirmAndApply'),'discovery/monitoring/manual entry do not invoke Pair');
  const bundle=new SupportBundleBuilder().build({application:{name:'Test',version:'16',runtime:'test',platform:'test'},readiness:{},network:topology,monitoring:{},discovery:status,projectSession:projectDb.getSession(),events:[],pair:preview});
  const output=JSON.stringify(bundle);a(output.includes('networkRelationship')&&output.includes('pairEligibility')&&output.includes('ADAPTER_PREFIX_PROPOSAL'),'support includes bounded field relationship and preview evidence');
  a(!output.includes('authorization')&&!output.includes('password'),'field support evidence contains no secrets');
  projectDb.startQuickWork();console.log(`First camera field summary: ${passed} passed, ${failed} failed, 0 skipped`);if(failed)process.exitCode=1;
}
run().catch(error=>{console.error(error);process.exitCode=1});
