import { strict as assert } from 'node:assert';
import { EventEmitter } from 'node:events';
import dgram, { RemoteInfo } from 'node:dgram';
import { readFileSync } from 'node:fs';
import { hanwhaHello } from './support/hanwha_hello.ts';
import { fieldNic,fieldEthernet } from './support/first_camera_field.ts';
import { OnvifDriver } from '../core/drivers/onvif.ts';
import { inspectDiscoveryHello, discoveryMessageKind } from '../core/drivers/ws_discovery_hello.ts';
import { NodeOnvifWsDiscoveryTransport, UdpSocketLike, DEFAULT_DISCOVERY_WINDOW_MS } from '../core/drivers/ws_discovery_transport.ts';
import { NoopDeviceEnricher, WindowsDeviceEnricher } from '../core/engine/device_enrichment.ts';
import { Phase3ActiveProbing } from '../core/engine/phase3_probing.ts';
import { SiteProjectDatabase } from '../core/storage/project_db.ts';
import { appStateDb } from '../core/storage/app_db.ts';
import { LocalHostIdentity } from '../core/network/local_host_identity.ts';
import { AdvancedScanService } from '../core/engine/advanced_scan.ts';
import { emptyAdvancedScanRequest } from '../shared/advanced_scan.ts';
import { hasCctvEvidence, matchesAdvancedScanFilters } from '../shared/discovery_evidence.ts';
import { canOfferPair } from '../shared/network_relationship.ts';
let passed=0;const check=(value:unknown,name:string)=>{assert.ok(value,name);passed++;console.log(`PASS: ${name}`)};
class Socket extends EventEmitter implements UdpSocketLike {
 closed=false;memberships:string[]=[];bound?:{port:number;address:string};sent=0;
 constructor(public packets:Array<string|Buffer>=[],public failMembership=false,public failBind=false){super()}
 bind(options:{port:number;address:string},callback:()=>void){if(this.failBind)throw Error('private-socket-detail');this.bound=options;callback()}
 addMembership(group:string,local:string){if(this.failMembership)throw Error('private-membership-detail');this.memberships.push(`${group}@${local}`);for(const packet of this.packets)queueMicrotask(()=>this.deliver(packet))}
 setMulticastInterface(){}
 send(_message:unknown,_port:number,_address:string,callback:(error?:Error|null)=>void){this.sent++;callback()}
 close(){this.closed=true}
 deliver(packet:string|Buffer){const bytes=Buffer.isBuffer(packet)?packet:Buffer.from(packet);this.emit('message',bytes,{address:'192.168.1.100',port:3702,family:'IPv4',size:bytes.length} as RemoteInfo)}
}
async function receive(packets:Array<string|Buffer>,nics=[fieldNic()]){const multicast=new Socket(packets),probes:Socket[]=[];const result=await new NodeOnvifWsDiscoveryTransport().discover(nics,{timeoutMs:8,multicastSocketFactory:()=>multicast,socketFactory:()=>{const socket=new Socket();probes.push(socket);return socket}});return {result,multicast,probes}}
async function run(){
 const minimal=hanwhaHello(),parsed=inspectDiscoveryHello(minimal,'192.168.1.100');
 check(parsed.device,'observed SOAP/Addressing/Discovery namespace URIs accepted');check(discoveryMessageKind(minimal)==='HELLO','Action classifies Hello');check(parsed.stages.includes('HELLO_IDENTIFIED'),'namespace-qualified Body Hello located');check(parsed.device?.network?.xAddr==='http://192.168.1.100/onvif/device_service','full advertised XAddr preserved');check(parsed.device?.network?.ipAddress==='192.168.1.100','IPv4 extracted from XAddr');
 check(!parsed.device?.anchor?.macAddress&&!parsed.device?.anchor?.onvifEndpointUuid,'missing physical identity is not fabricated');check(parsed.device?.id?.startsWith('session:'),'identity-less evidence gets temporary session key, not permanent IP anchor');check(parsed.device?.anchor?.vendor==='Unknown ONVIF Device','physical label does not fabricate advertised manufacturer');
 for(const prefix of ['different','device-discovery','d.xml'])check(inspectDiscoveryHello(hanwhaHello({prefix}),'192.168.1.100').device,`arbitrary valid prefix ${prefix} accepted`);
 check(inspectDiscoveryHello(minimal.replaceAll('wsd:','').replace('xmlns:wsd=','xmlns='),'192.168.1.100').device,'default discovery namespace accepted');
 check(!inspectDiscoveryHello(minimal+'<extra/>','192.168.1.100').device,'multiple document roots rejected');
 check(!inspectDiscoveryHello(hanwhaHello({uuid:true}).replace('urn:uuid:aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee','URN:UUID:invalid'),'192.168.1.100').device,'invalid endpoint UUID rejected regardless of scheme casing');
 check(!inspectDiscoveryHello(hanwhaHello({xaddrs:'http://192.168.1.100:0/onvif/device_service'}),'192.168.1.100').device,'zero XAddr port rejected');
 const alias=minimal.replaceAll('SOAP-ENV','env-alias').replaceAll('wsa:','addr-alias:').replace('xmlns:wsa=','xmlns:addr-alias=');check(inspectDiscoveryHello(alias,'192.168.1.100').device,'SOAP and addressing aliases independent of literals');
 check(inspectDiscoveryHello(hanwhaHello({uuid:true,metadata:true}),'192.168.1.100').metadataVersion===7,'optional MetadataVersion extracted safely');check(inspectDiscoveryHello(hanwhaHello({uuid:true}),'192.168.1.100').device?.id==='onvif:aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee','EndpointReference UUID supplies stable identity without MAC');
 check(inspectDiscoveryHello(hanwhaHello({types:true,xaddrs:'http://192.168.1.100/service'}),'192.168.1.100').device,'ONVIF Types QName resolved by namespace URI');
 check(inspectDiscoveryHello(hanwhaHello({xaddrs:''}),'192.168.1.100').reason==='MISSING_XADDR','missing XAddr rejected with reason');
 for(const uri of ['not-a-url','ftp://192.168.1.100/onvif/device_service','http://user:secret@192.168.1.100/onvif/device_service','http://127.0.0.1/onvif/device_service','http://239.1.1.1/onvif/device_service','http://192.168.1.100:99999/onvif/device_service','http://2130706433/onvif/device_service'])check(!inspectDiscoveryHello(hanwhaHello({xaddrs:uri}),'192.168.1.100').device,`unsafe or unsupported XAddr rejected: ${uri.split('@').at(-1)}`);
 const multi=inspectDiscoveryHello(hanwhaHello({xaddrs:'http://[fe80::1]/onvif/device_service https://192.168.1.100:8443/onvif/device_service http://192.168.1.100/onvif/device_service'}),'192.168.1.101').device;
 check(multi?.network?.port===8443&&multi.network.xAddrs?.length===2,'IPv6 skipped and multiple valid IPv4 XAddrs selected deterministically');check(multi?.network?.ipAddress==='192.168.1.100'&&multi.network.senderIp==='192.168.1.101','XAddr host and UDP sender remain separate');
 for(const [xml,reason] of [[minimal.replace('/Hello</wsa:Action>','/Bye</wsa:Action>'),'UNSUPPORTED_ACTION'],[minimal.slice(0,-10),'INVALID_SOAP'],[minimal.replace('wsd:Hello','wsd:ProbeMatch'),'INVALID_SOAP'],[hanwhaHello({xaddrs:'http://192.168.1.100/printer'}),'NOT_ONVIF'],[minimal.replace('http://schemas.xmlsoap.org/ws/2005/04/discovery"','urn:wrong"'),'MISSING_HELLO']] as const)check(inspectDiscoveryHello(xml,'192.168.1.100').reason===reason,`invalid message classified ${reason}`);
 const exact=hanwhaHello({padding:1483-Buffer.byteLength(minimal)});check(Buffer.byteLength(exact)===1483&&inspectDiscoveryHello(exact,'192.168.1.100').device,'reconstructed 1483-byte complete datagram accepted');
 const local=await receive([hanwhaHello({ip:'192.168.0.124'})]);check(local.result.devices.length===0&&local.result.trace?.events.some(e=>e.reason==='LOCAL_HOST'),'local-host XAddr rejected before inventory');
 const packet=hanwhaHello({uuid:true,padding:3500}),received=await receive([packet]);const camera=received.result.devices[0];
 check(camera?.status==='DIFFERENT_SUBNET','complete large UDP Hello produces off-subnet camera candidate');check(camera.sessionVerification==='NOT_VERIFIED'&&!camera.reachability?.lastSuccessfulResponseAt,'Hello does not imply Online or verified response');check(camera.status!=='OFFLINE'&&camera.status!=='UNREACHABLE','Different Network remains distinct from Offline/Unreachable');check(camera.reachability?.discoverySource?.payloadBytes===Buffer.byteLength(packet)&&Buffer.byteLength(packet)>1500,'transport accepts whole payload larger than Ethernet MTU');check(camera.reachability?.discoverySource?.port===3702&&camera.reachability.discoveryInterface?.interfaceIndex===8,'UDP source port and known selected-adapter metadata retained');
 check(received.multicast.memberships.join()==='239.255.255.250@192.168.0.124','multicast membership setup deterministic');check(received.multicast.closed&&received.probes.every(s=>s.closed),'bounded window closes every socket');check(received.result.trace?.events.some(e=>e.stage==='WINDOW_OPENED')&&received.result.trace.events.some(e=>e.stage==='CANDIDATE_ACCEPTED'),'trace records receive window and candidate acceptance');check(received.result.messageCounts?.acceptedHellos===1&&received.result.messageCounts.acceptedProbeMatches===0,'Hello accepted independently of active ProbeMatch');
 const rejected=await receive([Buffer.from([0xff,0xfe]),minimal.slice(0,-10)]);check(rejected.result.trace?.events.some(e=>e.reason==='INVALID_UTF8')&&rejected.result.trace.events.some(e=>e.reason==='INVALID_SOAP'),'invalid UTF8 and truncated XML have distinct safe trace reasons');
 const broken=new Socket([],true),probe=new Socket();const failure=await new NodeOnvifWsDiscoveryTransport().discover([fieldNic()],{timeoutMs:3,multicastSocketFactory:()=>broken,socketFactory:()=>probe});check(failure.trace?.events.some(e=>e.stage==='MEMBERSHIP_FAILED')&&probe.sent===1,'membership failure recorded while probe remains available');check(!JSON.stringify(failure).includes('private-'),'socket diagnostics contain no raw exception detail');
 const badBind=new Socket([],false,true),bindFailure=await new NodeOnvifWsDiscoveryTransport().discover([fieldNic()],{timeoutMs:3,multicastSocketFactory:()=>badBind,socketFactory:()=>new Socket()});check(bindFailure.trace?.events.some(e=>e.reason==='BIND_OR_RECEIVE_FAILED'),'bind exception recorded without poisoning other sockets');
 let attempts=0;const isolated=await new NodeOnvifWsDiscoveryTransport().discover([fieldNic(),{...fieldNic(),name:'Wi-Fi',ipAddress:'192.168.40.166'}],{timeoutMs:3,multicastSocketFactory:()=>new Socket([minimal]),socketFactory:()=>{if(attempts++===0)throw Error('private');return new Socket()}});check(isolated.devices.length===1&&isolated.trace?.events.some(e=>e.reason==='CREATE_FAILED'),'one adapter factory failure preserves announcement discovery');check(isolated.devices[0].status==='DIFFERENT_SUBNET'&&!isolated.devices[0].reachability?.discoveryInterface,'outside all adapter subnets is Different Network without invented ingress');
 const bounded=await receive(Array.from({length:100},()=>minimal));check(bounded.result.trace?.events.length===128&&bounded.result.trace.droppedEvents>0,'receive evidence bounded with dropped-event count');check(bounded.result.devices.length===1,'repeated identity-less Hello merges only its temporary evidence key');check(!JSON.stringify(bounded.result.trace).includes('<SOAP')&&!JSON.stringify(bounded.result.trace).includes('device_service'),'trace never logs raw XML or full advertised URL');
 const cancelled=new AbortController();cancelled.abort();const cancelledResult=await new NodeOnvifWsDiscoveryTransport().discover([fieldNic()],{signal:cancelled.signal,timeoutMs:5,multicastSocketFactory:()=>{throw Error('should not open')},socketFactory:()=>new Socket()});check(cancelledResult.cancelled,'pre-cancelled operation does not start announcement listener');check(DEFAULT_DISCOVERY_WINDOW_MS===10000,'default receive window explicit and bounded at ten seconds');
 const db=new SiteProjectDatabase();db.startQuickWork();const transport={discover:async(_nics:any,options:any)=>{for(const device of received.result.devices)options.onDevice?.(structuredClone(device),true);return received.result}};
 await Phase3ActiveProbing.execute([fieldNic()],transport,new NoopDeviceEnricher(),{},LocalHostIdentity.fromInterfaces([fieldNic()]),db);check(db.getDevices().length===1&&db.getDevices()[0].status==='DIFFERENT_SUBNET','monitoring/Quick pipeline promotes Hello without unicast enrichment');await Phase3ActiveProbing.execute([fieldNic()],transport,new NoopDeviceEnricher(),{},LocalHostIdentity.fromInterfaces([fieldNic()]),db);check(db.getDevices().length===1,'repeated stable Hello does not duplicate inventory');
 const moved=(await receive([hanwhaHello({uuid:true,ip:'192.168.1.101'})])).result.devices[0];db.upsertDevice(moved);check(db.getDevices().length===1&&db.getDevices()[0].network.ipAddress==='192.168.1.101','same UUID with new XAddr reconciles without IP identity');
 const enricher=new WindowsDeviceEnricher({lookup:async()=>({ipAddress:'192.168.1.101',macAddress:'e4:30:22:cd:68:85',interfaceIndex:8})},{probe:async()=>[]});await enricher.enrich(db.getDevices()[0],{onUpdate:device=>db.upsertDevice(device)});check(db.getDeviceByMac('e4:30:22:cd:68:85')?.anchor.onvifEndpointUuid===camera.anchor.onvifEndpointUuid,'later MAC enriches same UUID identity without duplicate row');check(db.getDevices()[0].sessionVerification==='NOT_VERIFIED','MAC enrichment does not fabricate live verification');check(canOfferPair(db.getDevices()[0]),'manual Pair remains offered for discovered off-subnet candidate');
 const second={...moved,id:'onvif:other',anchor:{macAddress:null,onvifEndpointUuid:'bbbbbbbb-bbbb-cccc-dddd-eeeeeeeeeeee',vendor:'Unknown'}};db.upsertDevice(second);check(db.getDevices().length===2,'different stable identities at same IP remain separate');
 check(hasCctvEvidence(camera)&&matchesAdvancedScanFilters(camera,{onlyLikelyCameras:true,includeUnknownDevices:false}),'valid Hello retains CCTV eligibility with unknown hosts excluded');
 const advancedDb=new SiteProjectDatabase();advancedDb.startQuickWork();let inspections=0;const service=new AdvancedScanService({inspectAdapters:async()=>{inspections++;return [fieldEthernet()]}} as any,{check:async(ip:string)=>({type:'PING',targetIp:ip,success:false,timestamp:'now'})} as any,undefined,advancedDb);const request=emptyAdvancedScanRequest();request.adapterIndexes=[8];request.targets=[{type:'RANGE',start:'192.168.1.100',end:'192.168.1.100'}];request.methods=['ONVIF','PING'];
 const preparation=await service.prepare(request);check(inspections===1&&preparation.timings.adapterInspectionMs>=0,'preflight uses one snapshot and records enumeration/planning timing');await service.execute(preparation.plan,{onDevice(){},onComplete(){}});check(advancedDb.getDevices().length===0,'silent target alone still creates no row');await Phase3ActiveProbing.execute([fieldNic()],transport,new NoopDeviceEnricher(),{},LocalHostIdentity.fromInterfaces([fieldNic()]),advancedDb);await service.execute(preparation.plan,{onDevice(){},onComplete(){}});check(advancedDb.getDevices().length===1&&advancedDb.getDevices()[0].sessionVerification==='NOT_VERIFIED','targeted Hello survives unsuccessful unicast checks');
 const lookupStages:string[]=[];await new WindowsDeviceEnricher({lookup:async()=>{throw Error('private')}},{probe:async()=>[]}).enrich(structuredClone(camera),{onEvidence:stage=>lookupStages.push(stage)});check(lookupStages.includes('NEIGHBOR_LOOKUP_UNAVAILABLE'),'failed optional neighbor enrichment has explicit evidence');
 const support=appStateDb.getAuditLogs().find(log=>(log.details as any)?.receiveTrace);check((support?.details as any).reconciliation.some((event:any)=>event.stage==='INVENTORY_RECONCILED'),'Support links receive trace to inventory reconciliation');
 const modal=readFileSync('src/ui/components/AdvancedScanModal.tsx','utf8');check(modal.includes('Preparing scan...')&&modal.includes('startPending.current = true'),'Preparing state and synchronous duplicate-submit latch wired');check(modal.includes('finally { startPending.current = false; setBusy(false); }'),'preflight failure releases preparing state');check(modal.includes('disabled={busy} onClick={onClose}'),'Cancel does not falsely promise preflight cancellation');
 const receiver=dgram.createSocket('udp4'),sender=dgram.createSocket('udp4');try{const receivedBytes=new Promise<Buffer>((resolve,reject)=>{receiver.once('message',resolve);receiver.once('error',reject)});await new Promise<void>(resolve=>receiver.bind(0,'127.0.0.1',resolve));await new Promise<void>((resolve,reject)=>sender.send(Buffer.from(packet),receiver.address().port,'127.0.0.1',error=>error?reject(error):resolve()));const payload=await Promise.race([receivedBytes,new Promise<never>((_,reject)=>{const timer=setTimeout(()=>reject(Error('Loopback receive timeout')),1000);timer.unref()})]);check(payload.equals(Buffer.from(packet)),'real local UDP callback receives complete large XML payload');check(inspectDiscoveryHello(payload.toString('utf8'),'192.168.1.100').device,'received full payload parses without application fragment reconstruction')}finally{receiver.close();sender.close()}
 console.log(`Hanwha Hello: ${passed} passed, 0 failed, 0 skipped`);
}
run().catch(error=>{console.error(error);process.exitCode=1});
