import { readFileSync } from 'node:fs';
import { BatchExecutionPipeline } from '../core/engine/pipeline.ts';
import { DEFAULT_MONITORING_INTERVAL_MS, IncrementalDiscoveryMonitor } from '../core/engine/incremental_discovery_monitor.ts';
import { LocalHostIdentity } from '../core/network/local_host_identity.ts';
import { projectDb } from '../core/storage/project_db.ts';
import { Device, NICInfo } from '../types/index.ts';

let passed=0,failed=0;const assert=(value:unknown,name:string)=>{if(value){console.log(`  PASS: ${name}`);passed++}else{console.error(`  FAIL: ${name}`);failed++}};
const nic: NICInfo={name:'Wi-Fi',ipAddress:'192.168.40.165',netmask:'255.255.255.0',broadcast:'192.168.40.255',mac:'00:aa:bb:cc:dd:ee',isInternal:false,interfaceIndex:10};
const device=(id:string,ip:string,mac:string):Device=>({id,anchor:{macAddress:mac,vendor:'Axis'},network:{ipAddress:ip,ipAddressHistory:[ip],subnetMask:'255.255.255.0',port:80,protocol:'ONVIF'},status:'ONLINE',sessionVerification:'VERIFIED',discoveredPhase:2,firstSeenAt:'now',lastSeenAt:'now',technician:{name:id,location:'',notes:''},configuredState:{inferred:null}});
const makePipeline=(responses:Device[][])=>{const provider={discover:async()=>responses.shift()||[]} as any;const pipeline=new BatchExecutionPipeline({passiveDiscovery:provider});(pipeline as any).currentInterfaces=[nic];(pipeline as any).localHost=LocalHostIdentity.fromInterfaces([nic]);return pipeline};

async function run(){
  projectDb.startQuickWork();const a=device('mac:a','192.168.40.10','00:00:00:00:00:0a'),b=device('mac:b','192.168.40.11','00:00:00:00:00:0b');projectDb.upsertDevice(a);
  const pipeline=makePipeline([[b],[b],[]]);let newEvents=0;pipeline.subscribe(event=>{if(event.type==='DEVICE_DISCOVERED'&&event.data?.isNew)newEvents++});
  const monitor=new IncrementalDiscoveryMonitor({runCycle:async()=>{await pipeline.runPhase2();await pipeline.runPhase4()},canRun:()=>({allowed:true})});
  await monitor.runNow();assert(projectDb.getDevices().length===2&&projectDb.getDeviceById(a.id)&&projectDb.getDeviceById(b.id),'new device after initial inventory is added without manual scan');assert(newEvents===1,'genuinely new device creates one normal discovery event');
  await monitor.runNow();assert(projectDb.getDevices().length===2&&newEvents===1,'known rediscovery creates no duplicate row or repeated notification');
  const moved=device('incoming:b','192.168.40.21','00:00:00:00:00:0b');const movedPipeline=makePipeline([[moved]]);let movedNew=false;movedPipeline.subscribe(event=>{if(event.type==='DEVICE_DISCOVERED')movedNew=event.data.isNew});await new IncrementalDiscoveryMonitor({runCycle:()=>movedPipeline.runPhase2(),canRun:()=>({allowed:true})}).runNow();const retained=projectDb.getDeviceByMac(moved.anchor.macAddress!);assert(retained?.id===b.id&&retained.network.ipAddress==='192.168.40.21'&&retained.network.ipAddressHistory?.includes('192.168.40.11'),'changed IP retains stable identity and address history');assert(!movedNew,'changed IP is not a new physical-camera event');

  const self=device('mac:self','192.168.40.165','00:00:00:00:00:cc'),selfPipeline=makePipeline([[self]]);let selfEvents=0;selfPipeline.subscribe(event=>{if(event.type==='DEVICE_DISCOVERED')selfEvents++});await new IncrementalDiscoveryMonitor({runCycle:()=>selfPipeline.runPhase2(),canRun:()=>({allowed:true})}).runNow();assert(!projectDb.getDeviceById(self.id)&&selfEvents===0,'local-host discovery creates no row or notification');

  projectDb.startQuickWork();const dupA=device('mac:dup-a','192.168.40.30','00:00:00:00:00:31'),dupB=device('mac:dup-b','192.168.40.30','00:00:00:00:00:32'),dupPipeline=makePipeline([[dupA,dupB]]);await new IncrementalDiscoveryMonitor({runCycle:async()=>{await dupPipeline.runPhase2();await dupPipeline.runPhase4()},canRun:()=>({allowed:true})}).runNow();assert(projectDb.getDevices().length===2&&projectDb.getCollisions().some(c=>c.ipAddress==='192.168.40.30'&&!c.resolved),'duplicate IP identities stay separate and collision remains active');

  projectDb.startQuickWork();projectDb.upsertDevice(a);projectDb.removeDeviceFromCurrentList(a.id);const restorePipeline=makePipeline([[a]]);restorePipeline.subscribe(event=>{if(event.type==='DEVICE_DISCOVERED'&&event.data?.device)projectDb.restoreDiscoveredDevice(event.data.device)});await new IncrementalDiscoveryMonitor({runCycle:()=>restorePipeline.runPhase2(),canRun:()=>({allowed:true})}).runNow();assert(projectDb.getProject().devices.some(value=>value.id===a.id),'genuine monitoring evidence restores a current-list removal without a blacklist');

  projectDb.createNewProject('Monitor Project');projectDb.upsertDevice(a);projectDb.removeDeviceFromProject(a.id);const projectPipeline=makePipeline([[a]]);projectPipeline.subscribe(event=>{if(event.type==='DEVICE_DISCOVERED'&&event.data?.device)projectDb.restoreDiscoveredDevice(event.data.device)});await new IncrementalDiscoveryMonitor({runCycle:()=>projectPipeline.runPhase2(),canRun:()=>({allowed:true})}).runNow();assert(projectDb.getProject().devices.some(value=>value.id===a.id)&&!JSON.parse(projectDb.exportProjectJson()).project.devices.some((value:Device)=>value.id===a.id),'Project-removed device may return live but is not silently restored to Project membership');

  projectDb.startQuickWork();projectDb.upsertDevice(a);let quietEvents=0;const quietPipeline=makePipeline([[]]);quietPipeline.subscribe(event=>{if(event.type==='SCAN_COMPLETE'||event.type==='SCAN_CANCELLED')quietEvents++});await new IncrementalDiscoveryMonitor({runCycle:()=>quietPipeline.runPhase2(),canRun:()=>({allowed:true})}).runNow();assert(projectDb.getDevices().length===1&&quietEvents===0,'zero-result monitoring preserves inventory and emits no manual-scan terminal state');

  let release!:()=>void,cycles=0;const pending=new Promise<void>(resolve=>{release=resolve});const overlap=new IncrementalDiscoveryMonitor({runCycle:async()=>{cycles++;await pending},canRun:()=>({allowed:true})});const first=overlap.runNow();assert(await overlap.runNow()==='SKIPPED'&&cycles===1,'overlapping scheduled tick cannot start a second cycle');release();await first;
  let yieldRelease!:()=>void,cancelled=false,yieldFinished=false;const yieldPending=new Promise<void>(resolve=>{yieldRelease=resolve});const yielding=new IncrementalDiscoveryMonitor({runCycle:()=>yieldPending,canRun:()=>({allowed:true}),cancelCycle:()=>{cancelled=true;yieldRelease()}});const background=yielding.runNow();await yielding.yieldToTechnician();yieldFinished=true;await background;assert(cancelled&&yieldFinished&&!yielding.getState().running,'technician scan cancels and waits for background discovery to yield its pipeline slot');
  for(const [reason,label] of [['manual','manual Quick Scan'],['advanced','Advanced Scan'],['network','network-changing operation']] as const){let ran=false;const blocked=new IncrementalDiscoveryMonitor({runCycle:async()=>{ran=true},canRun:()=>({allowed:false,reason})});assert(await blocked.runNow()==='SKIPPED'&&!ran,`${label} safely defers incremental discovery`)}

  let timerCallback:(()=>void)|undefined,clearCount=0,scheduled=0;const lifecycle=new IncrementalDiscoveryMonitor({runCycle:async()=>{scheduled++},canRun:()=>({allowed:true}),setTimer:callback=>{timerCallback=callback;return{unref(){}} as any},clearTimer:()=>{clearCount++}});lifecycle.start();lifecycle.start();assert(lifecycle.getState().enabled&&lifecycle.getState().intervalMs===DEFAULT_MONITORING_INTERVAL_MS,'monitor starts once with shared 30-second cadence');lifecycle.stop();timerCallback?.();await Promise.resolve();assert(clearCount===1&&!lifecycle.getState().enabled&&scheduled===0,'monitor stop clears its schedule and stale timer callbacks do no work');lifecycle.start();assert(lifecycle.getState().enabled,'monitor can restart without duplicate timer state');lifecycle.stop();

  let attempts=0;const recovery=new IncrementalDiscoveryMonitor({runCycle:async()=>{attempts++;if(attempts===1)throw Error('raw transport secret detail')},canRun:()=>({allowed:true})});assert(await recovery.runNow()==='FAILED'&&recovery.getState().lastError?.includes('retry')&&!recovery.getState().lastError?.includes('secret'),'monitoring failure is sanitized and does not disable future cycles');assert(await recovery.runNow()==='COMPLETED'&&attempts===2,'later cycle runs after a failed discovery cycle');

  const diagnostic=readFileSync('src/core/engine/diagnostic_engine.ts','utf8'),server=readFileSync('src/server/index.ts','utf8');assert(diagnostic.includes('intervalMs = DEFAULT_MONITORING_INTERVAL_MS')&&diagnostic.includes('if (this.running) return'),'known-device diagnostic refresh remains bounded and shares the monitoring cadence');assert(server.includes("emitTerminalEvent: false")&&server.includes('pipelineEngine.runDiscoveryScan'),'incremental monitoring reuses Quick Scan pipeline without manual terminal events');assert(server.includes('yieldToTechnician()')&&server.includes("plan.mode==='QUICK_FALLBACK'")&&server.includes('pipelineEngine.runDiscoveryScan({ context, signal,'),'manual Quick Scan and Advanced Scan fallback retain priority and existing behavior');assert(server.includes('hasActiveOperation()')&&server.includes('duplicateRemediationService.isActive()'),'server coordination covers consequential camera and network operations');assert(server.includes("'/api/monitoring/status'")&&server.includes('diagnosticRefresh')&&server.includes('incrementalDiscovery'),'status API distinguishes diagnostic refresh and incremental discovery');
  console.log(`\nIncremental monitoring summary: ${passed} passed, ${failed} failed`);if(failed)process.exit(1)
}
run().catch(error=>{console.error(error);process.exit(1)});
