import express from 'express';
import cors from 'cors';
import { createServer } from 'node:http';
import { createReportRouter, REPORT_RENDERER_ID } from '../server/report_routes.ts';
import { Device, ProjectSession, SiteProject } from '../types/index.ts';

let passed=0,failed=0;const assert=(value:unknown,name:string)=>{if(value){console.log(`  PASS: ${name}`);passed++}else{console.error(`  FAIL: ${name}`);failed++}};
const device=(i:number):Device=>({id:`route-${i}`,anchor:{macAddress:`00:40:8c:00:00:${i.toString(16).padStart(2,'0')}`,onvifEndpointUuid:`uuid-${i}`,serialNumber:`SERIAL-${i}`,model:'Field Camera',vendor:'Axis'},network:{ipAddress:`192.168.50.${i+10}`,ipAddressHistory:[`192.168.50.${i+10}`],subnetMask:'255.255.255.0',gateway:'192.168.50.1',port:80,protocol:'ONVIF'},status:'ONLINE',discoveredPhase:3,firstSeenAt:'2026-09-01T12:00:00Z',lastSeenAt:'2026-09-01T12:00:00Z',sessionVerification:'VERIFIED',technician:{name:`Camera ${i}`,location:'Fort Myers',notes:'Route test'},configuredState:{inferred:true,manualOverride:false}});
const session=(count:number):ProjectSession=>{const devices=Array.from({length:count},(_,i)=>device(i+1)),project:SiteProject={id:'route-project',name:'test 1',siteLocation:'fort myers',technicianName:'Technician',createdAt:'2026-09-01T12:00:00Z',updatedAt:'2026-09-01T12:00:00Z',totalDevices:count,devices,collisions:[],rogueDhcpEvents:[],auditLogs:[]};return{mode:'QUICK_WORK',project,dirty:false}};
const request={type:'DEVICE_INVENTORY',scope:'ALL',columns:['NAME','STATUS','IP','MAC_LAST_6','MANUFACTURER','MODEL','SERIAL','CONFIGURED','LOCATION'],orientation:'PORTRAIT',sortBy:'NAME',title:'Device Inventory Report',generatedAt:'2026-09-02T00:56:28.677Z'};

async function run(){let active=session(0);const app=express();app.use(cors({exposedHeaders:['X-CCTV-Report-Renderer','Content-Disposition']}));app.use(express.json());app.use('/api/reports',createReportRouter({getSession:()=>active,getAuditLogs:()=>[]}));const server=createServer(app);await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));try{const address=server.address();if(!address||typeof address==='string')throw Error('Integration server did not bind.');const endpoint=`http://127.0.0.1:${address.port}/api/reports`,post=(path:string)=>fetch(endpoint+path,{method:'POST',headers:{'Content-Type':'application/json','Origin':'http://127.0.0.1:5173'},body:JSON.stringify(request)});
  const previewResponse=await post('/preview'),preview=await previewResponse.json() as any,zeroResponse=await post('/export/pdf'),zero=Buffer.from(await zeroResponse.arrayBuffer()),zeroText=zero.toString('ascii');
  assert(previewResponse.ok&&zeroResponse.ok&&zeroResponse.headers.get('x-cctv-report-renderer')===REPORT_RENDERER_ID&&zeroResponse.headers.get('access-control-expose-headers')?.includes('X-CCTV-Report-Renderer'),'production PDF route exposes the field-document renderer identity to the browser');
  assert(preview.metadata.projectName==='test 1'&&preview.metadata.siteLocation==='fort myers'&&preview.rows.length===0&&preview.metadata.liveEvidence===true,'preview model carries project, location, count, and evidence semantics');
  assert(zeroText.includes('CCTV Network Assistant')&&zeroText.includes('Device Inventory Report')&&zeroText.includes('Project:')&&zeroText.includes('test 1')&&zeroText.includes('Location:')&&zeroText.includes('fort myers'),'actual route PDF agrees on report identity and site');
  assert(zeroText.includes('Devices detected: 0')&&zeroText.includes('Current session evidence')&&zeroText.includes('No devices were detected in the selected report scope.'),'actual route PDF agrees on zero-device and evidence state');
  assert(request.columns.every((_,i)=>zeroText.includes(['Technician Name','Status','IP','MAC Last 6','Manufacturer','Model','Serial','Configured','Location'][i])),'actual route PDF uses the requested columns');
  assert(!zeroText.includes('Technician Name | Status')&&!zeroText.includes('--------------------------------------------------------------------------------'),'legacy pseudo-table output is absent from actual route bytes');
  active=session(10);const tenResponse=await post('/export/pdf'),ten=Buffer.from(await tenResponse.arrayBuffer()).toString('ascii');assert(tenResponse.headers.get('x-cctv-report-renderer')===REPORT_RENDERER_ID&&(ten.match(/\/Type \/Page\b/g)||[]).length===1&&ten.includes('Camera 10'),'10-device production route uses the native table renderer');
  active=session(50);const fiftyResponse=await post('/export/pdf'),fifty=Buffer.from(await fiftyResponse.arrayBuffer()).toString('ascii');assert(fiftyResponse.headers.get('x-cctv-report-renderer')===REPORT_RENDERER_ID&&(fifty.match(/\/Type \/Page\b/g)||[]).length===3&&(fifty.match(/Technician Name/g)||[]).length===3&&fifty.includes('Page 2 of 3'),'50-device production route paginates with repeated headers and footers');
  const csvResponse=await post('/export/csv'),jsonResponse=await post('/export/json');assert(csvResponse.ok&&jsonResponse.ok&&(await csvResponse.text()).startsWith('"Technician Name"')&&JSON.parse(await jsonResponse.text()).format==='CCTV_SAFE_REPORT','CSV and JSON routes remain intact');
}finally{await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()))}console.log(`\nReport route integration summary: ${passed} passed, ${failed} failed`);if(failed)process.exit(1)}
run().catch(error=>{console.error(error);process.exit(1)});
