import {ReportService,DEFAULT_REPORT_COLUMNS} from '../core/reporting/report_service.ts';
import {ReportSet} from '../core/reporting/report_set.ts';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {Device,ProjectSession} from '../types/index.ts';
let passed=0,failed=0;const check=(v:unknown,n:string)=>{if(v){passed++;console.log('PASS: '+n)}else{failed++;console.error('FAIL: '+n)}};
const d:Device={id:'camera',anchor:{macAddress:'E4-30-22-CD-68-85',vendor:'Hanwha Vision',model:'QND-7082R',serialNumber:'SERIAL',onvifEndpointUuid:'uuid'},network:{ipAddress:'192.168.1.100',subnetMask:'255.255.255.0',port:80,protocol:'ONVIF'},technician:{name:'Entrance',location:'Door',notes:'Technician notes'},status:'ONLINE',sessionVerification:'VERIFIED',discoveredPhase:3,firstSeenAt:'now',lastSeenAt:'now',diagnostics:{checks:[{type:'PING',targetIp:'192.168.1.100',success:true,timestamp:'now'}]}};
const session:ProjectSession={mode:'QUICK_WORK',dirty:false,project:{id:'p',name:'Site',siteLocation:'Building',technicianName:'Alex',createdAt:'now',updatedAt:'now',devices:[d],totalDevices:1,collisions:[],rogueDhcpEvents:[],auditLogs:[]}};
const service=new ReportService();const build=(extra:any={})=>service.build(session,[],{type:'DEVICE_INVENTORY',scope:'ALL',...extra});
const defaults=['NAME','STATUS','IP','MAC_LAST_6','MANUFACTURER_MODEL','SERIAL','NOTES'];
check(DEFAULT_REPORT_COLUMNS.join()===defaults.join(),'T09/T10/T22 exact inventory defaults');
for(const [instant,zone,date] of [['2026-09-20T03:59:00Z','America/New_York','2026-09-19'],['2026-09-20T04:01:00Z','America/New_York','2026-09-20'],['2026-09-19T16:00:00Z','Asia/Tokyo','2026-09-20'],['2026-01-20T04:59:00Z','America/New_York','2026-01-19'],['2026-03-08T07:01:00Z','America/New_York','2026-03-08']]){
 const m=build({generatedAt:instant,timeZone:zone});check(service.filename(m,'pdf').endsWith('_'+date+'.pdf'),'T02-T06 local filename '+instant);check((m as any).generation?.localDate===date&&(m as any).generation?.instant===new Date(instant).toISOString(),'T01 shared instant/date '+instant);
}
const m=build(),pdf=service.pdf(m).toString('ascii');check(m.columns[0].label==='Camera Name','T11 camera label not report technician');check(m.metadata.technician==='Alex'&&pdf.includes('(Technician:)'),'T11 report technician in PDF metadata');check(pdf.includes('(Site Location:)'),'T12 site metadata label');check(build({columns:['LOCATION']}).columns[0].label==='Camera Location','T13 optional camera location');check(!m.columns.some(c=>c.key==='CONFIGURED')&&build({columns:['CONFIGURED']}).columns[0].key==='CONFIGURED','T14 configured optional');check(m.rows[0].values.MAC_LAST_6==='CD6885','T15 canonical MAC last six');
for(const mac of ['ff:ff:ff:ff:ff:ff','00:00:00:00:00:00','01:22:33:44:55:66','bad']){d.anchor.macAddress=mac;check(build().rows[0].values.MAC_LAST_6==='Unknown','T16 invalid MAC '+mac)}d.anchor.macAddress='E4:30:22:CD:68:85';
for(const [vendor,model,expected] of [['Hanwha Vision','QND-7082R','Hanwha Vision QND-7082R'],['Hanwha Vision','','Hanwha Vision'],['Unknown','QND-7082R','QND-7082R'],['','','Unknown']]){d.anchor.vendor=vendor;d.anchor.model=model;check((build().rows[0].values as any).MANUFACTURER_MODEL===expected,'T17-T20 manufacturer/model '+expected)}d.anchor.vendor='Hanwha Vision';d.anchor.model='QND-7082R';
d.anchor.serialNumber=undefined;check(build().rows[0].values.SERIAL==='Unknown','T21 no serial substitution');d.anchor.serialNumber='SERIAL';
check(build({columns:['NOTES','NAME','MAC']}).columns.map(c=>c.key).join()==='NOTES,NAME,MAC','T24/T25 custom order preserved');check(pdf.includes('(Devices: 1)')&&!pdf.includes('Devices detected'),'T26 truthful count');
const diag=build({type:'DIAGNOSTIC_SUMMARY'});check(diag.metadata.technician==='Alex'&&diag.metadata.siteLocation==='Building','T37/T38 diagnostic metadata');check(diag.columns[0].key==='NAME','T39 diagnostic camera first');check(diag.rows[0].values.DIAGNOSTIC_SUMMARY?.includes('Ping: Responded'),'T40 diagnostic defaults include actual evidence');check(diag.columns.some(c=>c.key==='LAST_VERIFIED'),'T41 diagnostic purpose-specific defaults');
check(!/undefined|null|\[object Object\]/.test(service.json(build())),'T42 no malformed unknowns');
d.technician!.notes=Array.from({length:300},(_,i)=>'note'+i).join(' ');const long=service.pdf(build()).toString('ascii');check(Array.from({length:300},(_,i)=>'note'+i).every(note=>long.includes(note))&&!long.includes('...'),'T43 no ordinary note truncation');check((long.match(/\/Type \/Page\b/g)||[]).length>1,'T44 long row continues across pages');check(long.includes('/MediaBox [0 0 612 792]'),'T45 portrait default');d.technician!.notes='Technician notes';
for(const type of ['DEVICE_INVENTORY','DIAGNOSTIC_SUMMARY']){d.technician!.notes='password=private-value';let blocked=false;try{service.pdf(build({type,columns:['NOTES']}))}catch{blocked=true}check(blocked,'T46/T47 sensitive report rejected '+type)}d.technician!.notes='Technician notes';
check(build({columns:['TECHNICIAN_NAME','NAME','MANUFACTURER','MODEL']}).columns.map(c=>c.key).join()==='NAME,MANUFACTURER,MODEL','T50-T52 legacy device name corrected, separate fields retained');
d.technician!.notes='https://user:private@camera/';let urlBlocked=false;try{build()}catch{urlBlocked=true}check(urlBlocked,'credential-bearing URL excluded');d.technician!.notes='Technician notes';
const before=JSON.stringify(session);build();check(JSON.stringify(session)===before,'T53/T54 report leaves project/schema clean');

check(!readFileSync('src/core/reporting/report_service.ts','utf8').includes('generatedAt.slice(0,10)'),'T07 no UTC filename slicing');
let invalid=false;try{build({timeZone:'Invalid/Timezone'})}catch{invalid=true}check(invalid,'invalid timezone does not silently fall back');
const set=new ReportSet(()=>session);set.add(['camera']);check(set.reportSession().project.devices.length===1,'T27 current member exported');const stable=set.snapshot().members[0].id;d.network.ipAddress='192.168.1.101';set.add(['camera']);check(set.snapshot().members.length===1&&set.snapshot().members[0].id===stable,'T35 IP change retains membership');
const second=structuredClone(d);second.id='other';second.anchor.macAddress='00:50:f9:63:fb:0f';second.anchor.onvifEndpointUuid='other-uuid';session.project.devices.push(second);set.add(['other']);check(set.snapshot().members.length===2,'T36 same IP distinct cameras');session.project.devices=[];const retained=service.build(set.reportSession(),[],{type:'DEVICE_INVENTORY',scope:'REPORT_SET'});check(retained.rows.length===2,'T28/T29 absent retained cameras export');
for(const [key,expected] of [['NAME','Entrance'],['MAC_LAST_6','CD6885'],['MANUFACTURER_MODEL','Hanwha Vision QND-7082R'],['SERIAL','SERIAL'],['NOTES','Technician notes']])check(retained.rows.some(r=>(r.values as any)[key]===expected),'T30-T34 retained '+key);
service.pdf(retained);service.csv(retained);service.json(retained);check(set.snapshot().members.length===2,'T58 generation retains membership');
if(process.env.PDF_QA_DIR){const dir=process.env.PDF_QA_DIR;mkdirSync(dir,{recursive:true});writeFileSync(dir+'/inventory.pdf',service.pdf(m));writeFileSync(dir+'/long-notes.pdf',Buffer.from(long,'ascii'));writeFileSync(dir+'/diagnostic.pdf',service.pdf(diag));}
console.log(`Phase 10 report architecture: ${passed} passed, ${failed} failed`);if(failed)process.exitCode=1;
