import { readFileSync } from 'node:fs';
import { IncrementalDiscoveryMonitor } from '../core/engine/incremental_discovery_monitor.ts';
import { projectDb } from '../core/storage/project_db.ts';
import { ReportService } from '../core/reporting/report_service.ts';
import { APPLICATION_PREFERENCES_KEY, DEFAULT_APPLICATION_PREFERENCES, DEFAULT_VISIBLE_COLUMNS, persistApplicationPreferences, readApplicationPreferences, resolveOpenPreference, shouldNotifyForDiscovery, updateApplicationPreferences, validateApplicationPreferences } from '../ui/preferences.ts';

let passed=0,failed=0;const assert=(value:unknown,name:string)=>{if(value){console.log(`  PASS: ${name}`);passed++}else{console.error(`  FAIL: ${name}`);failed++}};
class MemoryStorage{data=new Map<string,string>();getItem(key:string){return this.data.get(key)??null}setItem(key:string,value:string){this.data.set(key,value)}}
const app=readFileSync('src/ui/App.tsx','utf8'),settings=readFileSync('src/ui/components/SettingsMenu.tsx','utf8'),table=readFileSync('src/ui/components/MasterDeviceTable.tsx','utf8'),server=readFileSync('src/server/index.ts','utf8'),diagnostic=readFileSync('src/core/engine/diagnostic_engine.ts','utf8'),projectSource=readFileSync('src/core/storage/project_db.ts','utf8'),reports=readFileSync('src/ui/components/SiteSurveyReportModal.tsx','utf8'),support=readFileSync('src/core/readiness/support_bundle.ts','utf8');
async function run(){
 const defaults=readApplicationPreferences(null);assert(defaults.monitoringEnabled&&defaults.monitoringCadenceMs===30000&&defaults.newDeviceNotifications&&defaults.browserPreference==='SYSTEM','A/E/I/M/Z authoritative V1 defaults');assert(JSON.stringify(defaults.visibleColumns)===JSON.stringify(['NAME','STATUS','IP','LAST_6','CONFIGURED','SERIAL','NOTES']),'S/V accepted columns and separate Last 6 default');
 const storage=new MemoryStorage();const changed=updateApplicationPreferences(defaults,{monitoringEnabled:false,monitoringCadenceMs:60000,browserPreference:'CHROME',visibleColumns:['NAME','IP']});persistApplicationPreferences(changed,storage);assert(readApplicationPreferences(storage as any).browserPreference==='CHROME'&&readApplicationPreferences(storage as any).monitoringCadenceMs===60000,'B preferences survive reinitialization');
 storage.setItem(APPLICATION_PREFERENCES_KEY,'{broken');assert(readApplicationPreferences(storage as any).monitoringCadenceMs===30000,'C corrupted JSON safely defaults');storage.setItem(APPLICATION_PREFERENCES_KEY,JSON.stringify({monitoringCadenceMs:1,browserPreference:'SAFARI',visibleColumns:['BOGUS'],monitoringEnabled:'yes'}));const corrupt=readApplicationPreferences(storage as any);assert(corrupt.monitoringCadenceMs===30000&&corrupt.browserPreference==='SYSTEM'&&corrupt.monitoringEnabled&&JSON.stringify(corrupt.visibleColumns)===JSON.stringify(DEFAULT_VISIBLE_COLUMNS),'C/Q invalid types, cadence, browser, and columns fall back');
 const legacy=new MemoryStorage();legacy.setItem('cctv-network-assistant-theme','DARK');assert(readApplicationPreferences(legacy as any).appearance==='DARK','D legacy Appearance is preserved');assert(validateApplicationPreferences({appearance:'SYSTEM',future:true}).appearance==='SYSTEM','C future fields are ignored');
 let schedules:number[]=[];let clears=0;let cycleRelease:()=>void=()=>{};const monitor=new IncrementalDiscoveryMonitor({runCycle:()=>new Promise<void>(resolve=>{cycleRelease=resolve}),canRun:()=>({allowed:true}),setTimer:((_callback,ms)=>{schedules.push(ms);return{unref(){}}as any}),clearTimer:()=>{clears++}});monitor.start();monitor.start();assert(schedules.length===1&&schedules[0]===30000,'G/I monitoring starts once at 30 seconds');monitor.setIntervalMs(15000);assert(schedules.at(-1)===15000&&clears===1&&monitor.getState().enabled,'H cadence 15 seconds reschedules without duplicate timer');monitor.setIntervalMs(60000);monitor.setIntervalMs(120000);assert(schedules.slice(-2).join(',')==='60000,120000','J/K 60-second and 2-minute cadence reschedule');const active=monitor.runNow();monitor.setIntervalMs(30000);assert(monitor.getState().running&&schedules.at(-1)===30000,'L cadence change does not interrupt active cycle');cycleRelease();await active;monitor.stop();assert(!monitor.getState().enabled,'F monitoring stop clears future incremental discovery');assert(server.includes('diagnosticMonitor.stop();incrementalMonitor.stop()')&&server.includes('diagnosticMonitor.start();incrementalMonitor.start()'),'F/G one API controls both existing monitoring responsibilities');assert(diagnostic.includes('setIntervalMs')&&server.includes('diagnosticMonitor.setIntervalMs(cadence);incrementalMonitor.setIntervalMs(cadence)'),'H–L both monitors receive shared cadence');assert(server.includes("status:!enabled?'OFF':running?'ACTIVE':deferred?'DEFERRED':'WAITING'"),'8 monitoring status distinguishes active, waiting, deferred, and off');assert(app.includes('/api/discovery/start')&&!app.includes('diagnosticMonitor.stop'),'AE monitoring preference cannot cancel manual Quick Scan');assert(app.includes('<AdvancedScanModal')&&app.includes('/api/monitoring/preferences'),'AF Advanced Scan remains separate from settings coordination');
 assert(resolveOpenPreference('SYSTEM','EDGE')==='EDGE'&&resolveOpenPreference('SYSTEM','CHROME')==='CHROME'&&resolveOpenPreference('SYSTEM','EMBEDDED')==='EMBEDDED','N/O/P saved browser drives normal Open path');assert(resolveOpenPreference('EDGE','CHROME')==='EDGE','browser modal explicit choice remains explicit');assert(corrupt.browserPreference==='SYSTEM'&&!settings.includes('Safari'),'Q legacy Safari never becomes a Windows launch choice');assert(app.includes('resolveOpenPreference(mode,preferences.browserPreference)')&&table.includes("onOpenBrowser(dev, 'SYSTEM')"),'13 Open/IP link uses saved preference through existing Connect path');assert(server.includes("safeError(res,error,400,'CONNECT'")&&readFileSync('src/core/connect/connect_service.ts','utf8').includes("fallback: used !== preference"),'R unavailable browser remains truthful and technician-safe');
 const noNotes=updateApplicationPreferences(defaults,{visibleColumns:defaults.visibleColumns.filter(value=>value!=='NOTES')});assert(!noNotes.visibleColumns.includes('NOTES')&&table.includes("visible('NOTES')"),'T hiding Notes changes presentation only');const noSerial=updateApplicationPreferences(defaults,{visibleColumns:defaults.visibleColumns.filter(value=>value!=='SERIAL')});assert(!noSerial.visibleColumns.includes('SERIAL')&&table.includes("visible('SERIAL')"),'U hiding Serial changes presentation only');assert(table.includes("visible('LAST_6')")&&table.includes('lastSix(dev)'),'V Last 6 remains its own presentation');assert(settings.includes('Reset to Defaults')&&settings.includes('[...DEFAULT_VISIBLE_COLUMNS]'),'W Reset Columns restores exact defaults');assert(app.includes('visibleColumns={preferences.visibleColumns}')&&projectSource.indexOf(APPLICATION_PREFERENCES_KEY)<0,'X columns apply in Quick Work and Projects as application state');assert(!reports.includes('visibleColumns')&&readFileSync('src/core/reporting/report_service.ts','utf8').indexOf(APPLICATION_PREFERENCES_KEY)<0,'Y report selection is independent');assert(table.includes('selectedDeviceIds')&&table.includes('visibleColumns'),'AG column changes retain stable selected identities');
 assert(shouldNotifyForDiscovery(defaults,true)&&!shouldNotifyForDiscovery(updateApplicationPreferences(defaults,{newDeviceNotifications:false}),true),'AA notification preference suppresses notice without discovery');assert(!shouldNotifyForDiscovery(defaults,false),'AB known rediscovery never notifies');assert(app.includes("data.type === 'DEVICE_DISCOVERED'")&&app.includes('data.data?.isNew === true'),'AC stable changed-IP identity relies on authoritative isNew event');assert(app.includes('setNewDeviceDetected(null)')&&shouldNotifyForDiscovery(defaults,true),'AD re-enabled notifications affect future genuine events without retroactive state');
 projectDb.createNewProject('Settings Isolation');const exported=projectDb.exportProjectJson();assert(!exported.includes(APPLICATION_PREFERENCES_KEY)&&!exported.includes('monitoringCadenceMs'),'AI application preferences are excluded from .cctvproj');assert(app.includes('saveProjectDownload({')&&app.includes('handleSaveProject(true)'),'AJ Save and Save As remain integrated');assert(server.includes('incrementalMonitor')&&server.includes('ProjectReverificationWorkflow'),'AK/AL monitoring and Reverify architecture preserved');assert(server.includes('LegacyConfigurationBoundary'),'AM truthful configuration boundary preserved');assert(server.includes('technicianErrorResponse')&&support.includes('sanitizeSupportEvidence'),'AN error and support evidence preserved');assert(settings.includes("['LIGHT','DARK','SYSTEM']")&&settings.includes('Diagnostics & Support')&&settings.includes('About'),'F/G/H existing Settings areas preserved');assert(support.includes('monitoring:input.monitoring'),'AH support bundle contains safe backend monitoring preference evidence');const report=new ReportService();assert(typeof report.build==='function','Y report architecture remains independently functional');
 console.log(`\nSettings completeness summary: ${passed} passed, ${failed} failed`);if(failed)process.exit(1)
}
run().catch(error=>{console.error(error);process.exit(1)});
