import { readFileSync } from 'node:fs';
import { Phase5BatchProvisioning } from '../core/engine/phase5_provision.ts';
import { DiagnosticRefreshMonitor, DeviceDiagnosticEngine } from '../core/engine/diagnostic_engine.ts';
import { isEligibleDiscoveryInterface } from '../core/engine/phase1_topology.ts';
import { ShutdownCoordinator, WindowsPreflightService } from '../core/readiness/field_readiness.ts';
import { ReportService } from '../core/reporting/report_service.ts';
import { SiteProjectDatabase, projectDb } from '../core/storage/project_db.ts';
import { Device } from '../types/index.ts';

const device = (index:number):Device => ({ id:`stable-${index}`, anchor:{ macAddress:index%3?`00:40:8c:00:${Math.floor(index/256).toString(16).padStart(2,'0')}:${(index%256).toString(16).padStart(2,'0')}`:null, onvifEndpointUuid:`uuid-${index}`, serialNumber:index%4?`serial-${index}`:undefined, vendor:index%5?'Axis Communications':'Hanwha Vision', model:`Camera ${index}`, firmwareVersion:`${index}.0` }, network:{ ipAddress:`10.0.${Math.floor(index/240)}.${10+(index%240)}`, subnetMask:'255.255.255.0', gateway:'10.0.0.1', port:80, protocol:'ONVIF', ipAddressHistory:[`10.1.0.${10+(index%240)}`,`10.0.${Math.floor(index/240)}.${10+(index%240)}`] }, status:index%7?'ONLINE':'UNKNOWN', discoveredPhase:3, firstSeenAt:'2026-01-01T00:00:00Z', lastSeenAt:'2026-01-02T00:00:00Z', sessionVerification:index%7?'VERIFIED':'NOT_VERIFIED', technician:{name:`Camera ${index}`,location:`Floor ${index%4}`,notes:`Field note, row ${index}\nverified only when tested`}, configuredState:{inferred:index%2===0,manualOverride:false}, manufacturerParams:{activeDriver:index%5?'Axis VAPIX':'Hanwha SUNAPI'} });

async function run(){let passed=0,failed=0;const a=(condition:unknown,name:string)=>{if(condition){console.log(`  PASS: ${name}`);passed++}else{console.error(`  FAIL: ${name}`);failed++}};
  const ready=new WindowsPreflightService({platform:'win32',runtime:'v22.18.0',enumerateAdapters:async()=>2,commandAvailable:async()=>true,credentialStoreAvailable:async()=>true,portAvailable:async()=>true,udpSocketAvailable:async()=>true,writable:async()=>true});const result=await ready.run();a(result.overall==='READY'&&result.checks.every(check=>check.state==='READY'),'pre-flight reports Ready only when all injected checks pass');
  const warning=await new WindowsPreflightService({platform:'win32',runtime:'v24.19.0',enumerateAdapters:async()=>1,commandAvailable:async()=>true,credentialStoreAvailable:async()=>false,portAvailable:async()=>true,udpSocketAvailable:async()=>true,writable:async()=>true}).run();a(warning.overall==='WARNING'&&warning.checks.some(check=>check.id==='runtime'&&/Node 24/.test(check.detail)),'pre-flight surfaces Node 24 and credential-provider warnings without blocking');
  const unavailable=await new WindowsPreflightService({platform:'linux',runtime:'v22.0.0',enumerateAdapters:async()=>0,commandAvailable:async()=>false,credentialStoreAvailable:async()=>false,portAvailable:async()=>false,udpSocketAvailable:async()=>false,writable:async()=>false}).run();a(unavailable.overall==='UNAVAILABLE','critical pre-flight failure is Unavailable');
  a(isEligibleDiscoveryInterface({name:'Ethernet',ipAddress:'169.254.10.2',netmask:'255.255.0.0',broadcast:'169.254.255.255',mac:'00:11:22:33:44:55',isInternal:false}),'physical APIPA adapter remains eligible for direct camera discovery');a(!isEligibleDiscoveryInterface({name:'Hyper-V Virtual Ethernet',ipAddress:'10.0.0.2',netmask:'255.255.255.0',broadcast:'10.0.0.255',mac:'00:11:22:33:44:55',isInternal:false}),'virtual adapter is excluded from discovery');
  let discoveryStops=0,monitorStops=0,wsCloses=0,httpCloses=0;const c1=new AbortController(),c2=new AbortController();const shutdown=new ShutdownCoordinator({stopDiscovery:()=>{discoveryStops++;return true}},{stop:()=>monitorStops++,cancelCurrent:()=>monitorStops++},[c1,c2],async()=>{wsCloses++},async()=>{httpCloses++});await Promise.all([shutdown.shutdown(),shutdown.shutdown()]);a(discoveryStops===1&&monitorStops===2&&wsCloses===1&&httpCloses===1&&c1.signal.aborted&&c2.signal.aborted,'graceful shutdown is idempotent and cleans active work');
  class CountingEngine extends DeviceDiagnosticEngine{calls=0;active=0;max=0;override async diagnose(d:Device){this.calls++;this.active++;this.max=Math.max(this.max,this.active);await new Promise(resolve=>setTimeout(resolve,2));this.active--;return d}}const engine=new CountingEngine(),monitorDevices=Array.from({length:20},(_,i)=>device(i+1)),eligibleMonitorDevices=monitorDevices.filter(item=>item.sessionVerification!=='NOT_VERIFIED'&&item.status!=='COLLISION').length,monitor=new DiagnosticRefreshMonitor(engine,()=>monitorDevices,()=>undefined,1000,3);monitor.start();monitor.start();await Promise.all([monitor.refreshNow(),monitor.refreshNow()]);monitor.stop();a(engine.calls===eligibleMonitorDevices&&engine.max<=3&&!monitor.getState().enabled,'monitor start/refresh/pause is duplicate-safe and bounded');
  const prototypeDevice=device(999);projectDb.upsertDevice(prototypeDevice);const before=JSON.stringify(projectDb.getDeviceById(prototypeDevice.id));const phase5=await Phase5BatchProvisioning.execute();a(phase5.provisionedDevices.length===0&&JSON.stringify(projectDb.getDeviceById(prototypeDevice.id))===before,'legacy phase 5 performs no simulated camera mutation');
  for(const count of [1,10,20,50]){const db=new SiteProjectDatabase();db.createNewProject(`Stress ${count}`);for(let i=1;i<=count;i++)db.upsertDevice(device(i));const json=db.exportProjectJson(),opened=new SiteProjectDatabase();opened.importProjectJson(json);const devices=opened.getDevices();a(devices.length===count&&new Set(devices.map(item=>item.id)).size===count&&devices.every(item=>item.status==='UNKNOWN'&&item.sessionVerification==='NOT_VERIFIED'),'project '+count+'-device round trip preserves identity and converts saved status to Not Verified');a(!/password|authorization|credentialId|token/i.test(json),'project '+count+'-device round trip contains no credential material');const report=new ReportService().build(opened.getSession(),[],{type:'DEVICE_INVENTORY',scope:'PROJECT',columns:['NAME','STATUS','IP','NOTES','DUPLICATE_STATE'],generatedAt:'2026-09-01T12:00:00Z'});const pdf=new ReportService().pdf(report),csv=new ReportService().csv(report);a(report.rows.length===count&&pdf.subarray(0,8).toString()==='%PDF-1.4'&&csv.includes('\\n'),'report '+count+'-device export preserves selection, pagination, and escaped notes');a(!/password|authorization|RTSP Active|Certified|PoE|VLAN/i.test(JSON.stringify(report)),'report '+count+'-device export contains no secrets or fabricated claims');}
  const app=readFileSync('src/ui/App.tsx','utf8'),table=readFileSync('src/ui/components/MasterDeviceTable.tsx','utf8'),server=readFileSync('src/server/index.ts','utf8');a(app.includes("data.type === 'DEVICE_DISCOVERED' && data.data?.isNew === true")&&!app.includes("import { TaskCenter")&&!app.includes('<TaskCenter'),'new-device notice requires a genuine discovery identity and obsolete activity UI is absent');a(table.includes("hasCompletedScan ? 'No devices found.' : 'No devices discovered.'")&&table.includes("Select Scan to scan again."),'zero-device post-scan state differs from first run');a(app.includes('Diagnostics:')&&app.includes('Active •')&&app.includes("'Unavailable'")&&app.includes("'Paused'"),'diagnostics UI exposes Active, Paused, and Unavailable truthfully');a(server.includes("status(501).json({ error: 'PTZ control is not implemented; no camera command was sent.'")&&server.includes("status(410).json({ error: 'The legacy automatic pipeline is unavailable."),'prototype success endpoints are isolated');a(!/FastScanHero|ExecutionPipeline|DeviceGrid|DeviceConfigModal|TaskCenter/.test(app.replace(/\/\/ Regression marker:.*/,'')),'dead legacy components are unreachable from the approved UI');
  console.log(`\nStabilization summary: ${passed} passed, ${failed} failed`);if(failed)process.exit(1)}run().catch(error=>{console.error(error);process.exit(1)});
