import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {readFileSync} from 'node:fs';
import {SiteProjectDatabase} from '../core/storage/project_db.ts';
import {TaskManager} from '../core/tasks/task_manager.ts';
import {DeviceInspectorDrawer} from '../ui/components/DeviceInspectorDrawer.tsx';
import * as policy from '../shared/technician_attention.ts';
import {Device} from '../types/index.ts';
import {decideCameraAccess} from '../shared/camera_access.ts';
let passed=0,failed=0;const check=(v:unknown,n:string)=>{if(v){passed++;console.log('PASS: '+n)}else{failed++;console.error('FAIL: '+n)}};
const now=new Date().toISOString();
const device:Device={id:'camera-a',anchor:{macAddress:'00:50:f9:63:fb:0f',vendor:'Fixture',onvifEndpointUuid:'uuid-a'},network:{ipAddress:'192.168.1.100',subnetMask:'255.255.255.0',port:80,protocol:'ONVIF'},status:'ONLINE',sessionVerification:'VERIFIED',discoveredPhase:3,firstSeenAt:now,lastSeenAt:now};
async function run(){
 const db=new SiteProjectDatabase();db.createNewProject('Attention');db.upsertDevice(structuredClone(device));db.exportProjectJsonForSave();
 const tasks=new TaskManager(),id=tasks.begin('DIAGNOSTICS');
 tasks.diagnosticTargets(id,[device.id,'camera-b']);tasks.update(id,{state:'RUNNING',phase:'WORKING',progress:{completed:0,total:2}});
 check(tasks.snapshot().tasks.length===1,'T01/T15 one operation observed in one Task');
 check(policy?.diagnosticPresentation(device,tasks.snapshot())?.state==='Running','T04 selected device running state');
 tasks.diagnosticResult(id,device.id,'COMPLETED');
 check(policy?.diagnosticPresentation(device,tasks.snapshot())?.state==='Completed','T05 per-device completion visible before batch ends');
 check(policy?.diagnosticPresentation({...device,id:'camera-b'},tasks.snapshot())?.state==='Running','bulk peer stays running independently');
 tasks.diagnosticResult(id,'camera-b','FAILED');tasks.update(id,{state:'FAILED',phase:'FAILED',progress:{completed:2,total:2}});
 check(policy?.diagnosticPresentation({...device,id:'camera-b'},tasks.snapshot())?.state==='Failed','T06 failed operation state visible');
 const cancel=tasks.begin('DIAGNOSTICS');tasks.diagnosticTargets(cancel,[device.id]);tasks.diagnosticResult(cancel,device.id,'CANCELLED');tasks.update(cancel,{state:'CANCELLED',phase:'CANCELLED'});
 check(policy?.diagnosticPresentation(device,tasks.snapshot())?.state==='Cancelled','cancelled operation is distinct');
 check(policy?.diagnosticPresentation({...device,id:'missing'},tasks.snapshot())?.state==='Unavailable','T17 missing evidence honest');
 const d={...device,diagnostics:{lastRunCompletedAt:now,checks:[{type:'PING' as const,targetIp:device.network.ipAddress,success:false,timestamp:now},{type:'HTTP' as const,targetIp:'192.168.1.99',success:true,timestamp:now}]}};
 const before=JSON.stringify(d);const presentation=policy?.diagnosticPresentation(d,{tasks:[],active:0,attention:0});check(JSON.stringify(d)===before&&d.status==='ONLINE','T07 presentation never derives Offline from failed ping');check(presentation?.checks.length===1,'old-IP checks cannot masquerade as current diagnostics');
 db.applyDiagnosticRefresh(d);check(!db.getSession().dirty,'T16 diagnostic runtime evidence preserves clean project');
 const props={isOpen:true,onClose:()=>{},device:d,onOpenConfigureModal:()=>{},onOpenBrowserModal:()=>{},onDiagnose:()=>{},diagnostic: presentation};const markup=renderToStaticMarkup(React.createElement(DeviceInspectorDrawer,props as any));
 check(markup.includes('Completed'),'T05 Inspector renders operation completion');check(markup.includes('reachability')&&!markup.includes('Login successful'),'T08 evidence does not imply browser/login success');check(markup.includes('role="dialog"')&&markup.includes('Device Inspector'),'T02/T41 accessible Inspector destination');
 const records:any[]=[{id:'one',ipAddress:'192.168.1.100',resolved:false,collidingDevices:[device,{...device,id:'b'},{...device,id:'c'}]},{id:'two',ipAddress:'192.168.1.200',resolved:false,collidingDevices:[{...device,id:'d'},{...device,id:'e'}]},{id:'old',ipAddress:'192.168.1.90',resolved:true,collidingDevices:[device]}];
 const choices=policy?.activeCollisionChoices(records);check(choices?.length===2,'T20/T21/T24 active groups only');check(choices?.[0].count===3,'T23 three participants count as one choice');check(choices?.[1].id==='two','T22 chooser preserves collision key');check(policy?.activeCollisionChoices([{...records[0],state:'RESOLVED'}]).length===0,'T25/T26 uses Phase 4 resolved predicate');
 check(policy?.hasUnsavedAttention(db.getSession())===false,'T37/T38 clean Project has no false Save attention');db.updateDeviceTechnicianFields(device.id,{notes:'field notes'});check(policy?.hasUnsavedAttention(db.getSession())===true,'T32 persistent Project edit shows Save attention');db.startQuickWork();check(policy?.hasUnsavedAttention({...db.getSession(),dirty:true})===false,'T39 Quick Work never fabricates Project Save attention');
 check(!decideCameraAccess(device.id,[device,{...device,id:'b',anchor:{...device.anchor,onvifEndpointUuid:'uuid-b',macAddress:'e4:30:22:cd:68:85'}}],records).allowed,'T12 diagnostic navigation cannot grant ambiguous access');
 const source=readFileSync('src/server/index.ts','utf8');check(source.includes('projectDb.applyDiagnosticRefresh(updated)'),'manual Diagnose route uses runtime diagnostic persistence');
 check(policy.diagnosticPresentation(device,{...tasks.snapshot(),unavailable:true}).state==='Unavailable','lost Tasks connection never presents stale operation state as current');
 const count=tasks.snapshot().tasks.length;tasks.diagnosticResult(cancel,device.id,'COMPLETED');check(tasks.get(cancel)?.diagnosticDevices?.[0].state==='CANCELLED'&&tasks.snapshot().tasks.length===count,'late completion cannot resurrect cancelled device result');
 const duplicate=tasks.begin('DIAGNOSTICS');tasks.diagnosticTargets(duplicate,[device.id,device.id]);check(tasks.get(duplicate)?.diagnosticDevices?.length===1,'duplicate input IDs have one diagnostic target');
 check(policy.diagnosticPresentation(device,tasks.snapshot(),{pending:true}).state==='Running','request preparation exposes progress before acceptance');
 check(policy.diagnosticPresentation(device,tasks.snapshot(),{failed:true}).message.includes('not acknowledged'),'unacknowledged request never claims underlying operation stopped');
 const rendered=renderToStaticMarkup(React.createElement(DeviceInspectorDrawer,{...props,device:{...device,diagnostics:undefined},diagnostic:policy.diagnosticPresentation({...device,id:'unknown'},{tasks:[],active:0,attention:0})}));
 check(rendered.includes('Unavailable')&&rendered.includes('No diagnostic checks'),'T17 partial device evidence renders safely');
 check(!rendered.includes('password')&&!rendered.includes('credentialId'),'Inspector diagnostic projection renders no credentials');
 console.log(`Phase 8 attention: ${passed} passed, ${failed} failed`);if(failed)process.exitCode=1;
}run().catch(e=>{console.error(e);process.exitCode=1});
