import { readFileSync } from 'node:fs';
import { applyTheme, persistTheme, readThemePreference, resolveTheme, THEME_STORAGE_KEY } from '../ui/theme.ts';
let passed=0,failed=0;const assert=(value:unknown,name:string)=>{if(value){console.log(`  PASS: ${name}`);passed++}else{console.error(`  FAIL: ${name}`);failed++}};
const root='src/ui/';const app=readFileSync(root+'App.tsx','utf8'),table=readFileSync(root+'components/MasterDeviceTable.tsx','utf8'),actions=readFileSync(root+'components/FloatingDeviceActionsMenu.tsx','utf8');
const fake=(value:string|null)=>({getItem:()=>value});
assert(readThemePreference(fake(null))==='LIGHT','Light is default with no preference');
assert(readThemePreference(fake('broken'))==='LIGHT','corrupt preference falls back to Light');
assert(readThemePreference(fake('DARK'))==='DARK','Dark preference is restored');
assert(resolveTheme('SYSTEM',true)==='DARK'&&resolveTheme('SYSTEM',false)==='LIGHT','System preference follows system appearance');
let stored='';persistTheme('DARK',{setItem:(key,value)=>stored=`${key}:${value}`});assert(stored===`${THEME_STORAGE_KEY}:DARK`,'Dark preference persists locally');
const classes=new Set<string>();applyTheme('DARK',{toggle:(name,force)=>{if(force)classes.add(name);else classes.delete(name);return Boolean(force)}},false);assert(classes.has('dark'),'Dark class applied deliberately');
assert(app.includes('CCTV Network Assistant'),'compact application identity');
assert(app.includes("openMenu==='PROJECT'")&&['New Project','Open Project','Save Project','Save As','Reverify'].every(x=>app.includes(x)),'Project menu contains project actions');
assert(app.includes("openMenu==='TOOLS'")&&['Available IPs','Add Device Manually','Reports'].every(x=>app.includes(x)),'Tools menu contains advanced actions');
assert(app.includes("openMenu==='SETTINGS'")&&app.includes('<Settings')&&app.includes('>Settings '),'Settings replaces permanent theme control');
assert(app.includes('Appearance')&&app.includes("['LIGHT','DARK','SYSTEM']"),'Settings contains Appearance choices');
assert(!app.includes('<Sun')&&!app.includes('<Moon'),'permanent Light control removed');
assert(app.includes('aria-label="Scan choices"')&&app.includes('Quick Scan'),'Scan split-button exists');
assert(app.includes('onClick={handleScanNetwork}')&&app.includes('<Play className="w-4 h-4 fill-current"/>Scan'),'primary Scan invokes current workflow');
assert(app.includes('Quick Scan')&&app.includes('Default')&&app.includes('Fast discovery on local network'),'Quick Scan is the default current workflow');
assert(app.includes('Customize adapters, ranges, ports, and discovery methods')&&!app.includes('Advanced Scan — Coming Soon')&&!app.includes('Scan Options...'),'Advanced Scan is enabled and obsolete placeholders are removed');
assert(app.includes('<Filter')&&app.includes('>Filters</button>'),'Filters button exists');
assert(app.includes('Status:')&&app.includes('Type:'),'Status and Type filters remain');
assert(!app.includes('Config: Any')&&!app.includes('Configured: Any'),'top Config filter remains absent');
assert(!app.includes("interfaces[0]?.name || 'Ethernet'")&&!app.includes("'192.168.1.50'"),'fake adapter fallback removed');
const columns=['NAME','STATUS','IP','LAST_6','CONFIGURED','SERIAL','NOTES'];const positions=columns.map(x=>table.indexOf(`{visible('${x}')`));
assert(positions.every((value,index)=>value>=0&&(index===0||value>positions[index-1])),'approved default column order');
assert(table.includes('MAC ')&&table.includes('(Last 6)'),'MAC header includes Last 6 helper');
assert(table.includes('full MAC address is shown in Device Details'),'MAC help points to Device Details');
assert(table.includes("replace(/[^0-9a-f]/gi, '').toUpperCase()")&&table.includes('slice(-6)'),'Last 6 formatting uses legitimate MAC');
assert(table.includes("lastSix(dev) || 'Unknown'")&&!table.includes('onvifEndpointUuid ||'),'unknown MAC does not fabricate Last 6');
assert(table.includes('Config ')&&table.indexOf('getStatusBadge(dev.status)')!==table.indexOf('configured(dev)'),'Config remains separate from Status');
assert(table.includes('Actions</th>')&&table.includes('<MoreVertical'),'Actions overflow remains');
assert(table.includes('key={dev.id}')&&table.includes('{ device: dev, anchor: event.currentTarget.getBoundingClientRect() }'),'stable device action targeting unchanged');
assert(table.includes("onOpenBrowser(dev, 'SYSTEM')"),'IP remains clickable through Connect');
assert(table.includes('startEditName(dev, e)')&&table.includes("startEdit(dev,'name',e)")&&table.includes("if(e.key==='Enter'){e.preventDefault();saveEdit();}")&&table.includes('maxLength={100}'),'inline Name uses shared editor with Enter save and 100-character limit');
assert(table.includes('startEditNotes(dev, e)')&&table.includes("startEdit(dev,'notes',e)")&&table.includes('<textarea')&&table.includes('maxLength={1000}')&&table.includes('onBlur={saveEdit}')&&table.includes("if(e.key==='Escape'){e.preventDefault();cancelEdit();}"),'inline Notes uses shared multiline editor with blur save, Escape cancel and 1000-character limit');
assert(actions.includes('canOfferPair(pairTarget)')&&actions.includes('onPair'),'Pair remains conditional on topology and safe targeting');
assert(actions.includes('Device Configuration')&&!actions.includes('Credentials & Parameters'),'contextual Device Configuration label is accurate');
assert(!app.includes('Task Center\n')&&app.includes('useState<TaskItem[]>([])'),'seeded fake activity removed from primary UI');
assert(!app.includes('IP Finder (25)')&&!app.includes('Site Survey (15)')&&!app.includes('Consolidated Blueprint'),'development labels absent from main UI');
assert(app.includes('max-w-[1900px]'),'table workspace uses wide laptop viewport');
assert(!app.includes('themePreference')&&!readFileSync('src/core/storage/project_db.ts','utf8').includes(THEME_STORAGE_KEY),'theme preference stays outside projects');
console.log(`\nUI summary: ${passed} passed, ${failed} failed`);if(failed)process.exit(1);
