import assert from 'node:assert/strict';
import express from 'express';
import {mkdtempSync,writeFileSync,rmSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {startupFailureMessage,productionAssets,productionAssetRoot} from '../server/production_assets.ts';
import {SiteProjectDatabase} from '../core/storage/project_db.ts';
import {PairService} from '../core/network/pair_service.ts';
import {TaskManager} from '../core/tasks/task_manager.ts';
import {OperationTasks} from '../core/tasks/operation_tasks.ts';
import {ReportService} from '../core/reporting/report_service.ts';
import {PairSessionState} from '../types/index.ts';
import {fieldEthernet} from './support/first_camera_field.ts';
import {operationFeedback} from '../ui/operation_feedback.ts';
import {sortDevices} from '../shared/device_sort.ts';
import {fieldCamera} from './support/first_camera_field.ts';
let passed=0;const check=(value:unknown,name:string)=>{assert.ok(value,name);passed++;console.log('PASS: '+name)};
const db=new SiteProjectDatabase();
check(db.getSession().mode==='QUICK_WORK','fresh application domain starts in Quick Work');
check(db.getDevices().length===0,'fresh inventory contains no offline or synthetic records');
const tasks=new TaskManager(),projection=new OperationTasks(tasks);
check(tasks.snapshot().active===0&&tasks.snapshot().tasks.length===0,'no fake startup tasks');
let snapshot:PairSessionState|null=null,adapter=fieldEthernet(),writes=0;
const adapters={inspectAdapters:async()=>[structuredClone(adapter)],isAdministrator:async()=>true,applyTemporary:async(_index:number,ipAddress:string,prefixLength:number)=>{check(Boolean(snapshot?.recoveryAvailable),'snapshot exists before adapter mutation');writes++;adapter={...adapter,dhcpEnabled:false,ipv4Addresses:[{address:ipAddress,prefixLength}]};return structuredClone(adapter)},restore:async(original:typeof adapter)=>{adapter=structuredClone(original);return adapter}};
const recovery={load:async()=>snapshot,save:async(value:PairSessionState)=>{snapshot=structuredClone(value)},clear:async()=>{snapshot=null}};
const service=new PairService(adapters,{check:async()=>({availability:'AVAILABLE',evidence:['controlled fixture']})},undefined,recovery,db,{changed:state=>projection.pair(state)});
check(await service.initializeRecovery()===null,'recovery absent when authoritative store is empty');
const preview=await service.prepareNetwork({interfaceIndex:8,ipAddress:'192.168.1.130',prefixLength:24});projection.pair(preview);
check(writes===0&&tasks.snapshot().tasks[0].state==='NEEDS_ATTENTION','Match preview and Tasks wait for explicit confirmation');
let refused=false;try{await service.confirmAndApply(preview.id,false)}catch{refused=true}
check(refused&&writes===0,'Tasks integration cannot bypass confirmation');
const applied=await service.confirmAndApply(preview.id,true);
check(applied.state==='PAIRED'&&tasks.snapshot().active===0,'authoritative applied state ends active mutation');
check(tasks.snapshot().tasks[0].result==='NETWORK_RECOVERY','temporary network retains technician recovery action');
check(db.getDevices().length===0,'Match Network does not create a camera or scan');
const recoveredTasks=new TaskManager(),recoveredProjection=new OperationTasks(recoveredTasks);
const restartedService=new PairService(adapters,undefined,undefined,recovery,db);
const recovered=await restartedService.initializeRecovery();recoveredProjection.pair(recovered);
check(recovered?.state==='PAIRED'&&recovered?.recoveryDisposition==='HEALTHY_RETAINED'&&recoveredTasks.snapshot().attention===0,'restart Task recognizes healthy saved recovery without attention');
const restored=await service.restore();
check(restored.state==='RESTORED'&&snapshot===null,'successful Restore clears only verified recovery');
check(tasks.snapshot().tasks.some(t=>t.kind==='RESTORE'&&t.state==='COMPLETED'&&t.correlationId===preview.id),'Restore task links to original Pair session for navigation');
check(tasks.snapshot().attention===0,'Restore resolves current adapter attention');
const quickReport=new ReportService().build(db.getSession(),[],{type:'DEVICE_INVENTORY',scope:'ALL'});
check(quickReport.rows.length===0&&quickReport.orientation==='PORTRAIT','zero-camera report is intentional and portrait');
check(new ReportService().pdf(quickReport).subarray(0,4).toString()==='%PDF','empty evidence report still renders safely');
db.createNewProject('Integration');const camera=fieldCamera();camera.status='ONLINE';camera.technician={name:'Lobby',notes:'Technician note'};db.upsertDevice(camera);
const saved=db.exportProjectJson(),reopened=new SiteProjectDatabase();reopened.importProjectJson(saved);
check(reopened.getDevices()[0].status!=='ONLINE','saved Online snapshot is not live verification after reopen');
check(reopened.getDevices()[0].technician?.notes==='Technician note','project metadata survives integration round trip');
check(!saved.includes('recoveryAvailable')&&!saved.includes('temporaryGateway'),'project excludes adapter recovery state');
const devices=[{...fieldCamera(),id:'b',network:{...fieldCamera().network,ipAddress:'192.168.1.100'}},{...fieldCamera(),id:'a',network:{...fieldCamera().network,ipAddress:'192.168.1.2'}}];
check(sortDevices(devices,{column:'IP',direction:'asc'})[0].id==='a','table IP ordering is numeric');
check(sortDevices(devices,{column:'LAST_6',direction:'asc'}).length===2,'MAC Last 6 sorting preserves stable rows');
check(operationFeedback({error:'password=private',stack:'private stack'},'Safe failure')==='Safe failure','raw technical errors cannot enter ordinary feedback');
check(operationFeedback({presentation:{message:'Administrator privileges are required.',reference:'OP-ABCD1234'}},'Fallback').includes('OP-ABCD1234'),'safe actionable errors retain reference');

const temporary=mkdtempSync(join(tmpdir(),'cctv-v1-assets-'));
const app=express();app.get('/api/health',(_req,res)=>res.json({ok:true}));app.use(productionAssets(temporary));
const server=app.listen(0,'127.0.0.1');await new Promise<void>(done=>server.once('listening',done));const url=`http://127.0.0.1:${(server.address() as any).port}`;
try{
 check((await fetch(url)).status===503,'missing production UI returns actionable unavailable state');
 writeFileSync(join(temporary,'index.html'),'<main>release fixture</main>');writeFileSync(join(temporary,'asset.js'),'export const release=true;');
 check((await(await fetch(url)).text()).includes('release fixture'),'production backend serves built UI');
 check((await fetch(url+'/asset.js')).status===200,'production assets are available');
 check((await(await fetch(url+'/api/health')).json()).ok,'production assets do not intercept valid API');
 check((await fetch(url+'/api/not-an-endpoint')).status===404,'unknown API is not returned as frontend HTML');
 check((await fetch(url+'/src/test/fixture.ts')).status===404,'source/test fixtures are not exposed by static root');
 check(resolve(productionAssetRoot)===resolve('dist'),'asset root is anchored to application location');
}finally{server.closeAllConnections();await new Promise<void>(done=>server.close(()=>done()));assert.ok(resolve(temporary).startsWith(resolve(tmpdir()))&&temporary.includes('cctv-v1-assets-'));rmSync(temporary,{recursive:true,force:true});}
const pkg=JSON.parse(readFileSync('package.json','utf8'));
check(Boolean(pkg.dependencies.tsx)&&!pkg.devDependencies.tsx,'production TypeScript loader intentionally packaged');
check(pkg.scripts['start:production']==='node scripts/start-production.cjs','ordinary production startup does not invoke Vite/concurrently');
check(readFileSync('scripts/start-production.cjs','utf8').includes("cwd:root"),'production launcher anchors working directory');
const bulk=readFileSync('src/ui/components/BulkReIpModal.tsx','utf8');
check(bulk.includes('if(!plan||dirtyOverrides||!confirmed)return'),'Apply handler enforces revalidation after editing targets');
check(bulk.includes('disabled={busy||dirtyOverrides||!confirmed||plan.readyCount===0}'),'Apply control matches override safety guard');
check(bulk.includes("['EXECUTING','VERIFYING','CONFIRMED'].includes(current.state)"),'late poll cannot overwrite a terminal Bulk result');
check(startupFailureMessage('EACCES').includes('Windows denied'),'denied runtime port gives actionable feedback');
check(startupFailureMessage('EADDRINUSE').includes('Another process'),'occupied runtime port gives actionable feedback');
check(!startupFailureMessage('private failure').includes('private failure'),'unknown runtime errors do not expose raw detail');
console.log(`V1 integration: ${passed} passed, 0 failed, 0 skipped`);
