import { Device } from '../../types/index.ts';
import { LocalHostIdentity } from '../network/local_host_identity.ts';
import { ProjectValidationError, SiteProjectDatabase } from './project_db.ts';

export type AddProjectOutcome='NEW_TO_PROJECT'|'ALREADY_IN_PROJECT'|'WILL_UPDATE_EVIDENCE'|'NEEDS_ATTENTION'|'CANNOT_ADD';
export interface AddProjectPreviewItem{deviceId:string;name:string;ipAddress:string;macLastSix?:string;serialNumber?:string;manufacturer:string;model?:string;outcome:AddProjectOutcome;message:string}
export interface AddProjectPreview{planId:string;projectId:string;projectName:string;items:AddProjectPreviewItem[];counts:Record<AddProjectOutcome,number>}
interface PendingPlan{database:SiteProjectDatabase;items:AddProjectPreviewItem[];live:Map<string,Device>}
const norm=(value?:string|null)=>value?.trim().toLowerCase()||'';
const anchors=(device:Device)=>[norm(device.anchor.macAddress),norm(device.anchor.onvifEndpointUuid),norm(device.anchor.serialNumber)].filter(Boolean);
const matches=(left:Device,right:Device)=>Boolean((norm(left.anchor.macAddress)&&norm(left.anchor.macAddress)===norm(right.anchor.macAddress))||(norm(left.anchor.onvifEndpointUuid)&&norm(left.anchor.onvifEndpointUuid)===norm(right.anchor.onvifEndpointUuid))||(norm(left.anchor.serialNumber)&&norm(left.anchor.serialNumber)===norm(right.anchor.serialNumber)));
const conflict=(left:Device,right:Device)=>Boolean((norm(left.anchor.macAddress)&&norm(right.anchor.macAddress)&&norm(left.anchor.macAddress)!==norm(right.anchor.macAddress))||(norm(left.anchor.onvifEndpointUuid)&&norm(right.anchor.onvifEndpointUuid)&&norm(left.anchor.onvifEndpointUuid)!==norm(right.anchor.onvifEndpointUuid)));
const item=(device:Device,outcome:AddProjectOutcome,message:string):AddProjectPreviewItem=>({deviceId:device.id,name:device.technician?.name||device.anchor.model||device.anchor.vendor,ipAddress:device.network.ipAddress,macLastSix:device.anchor.macAddress?.replace(/[^0-9a-f]/gi,'').slice(-6).toUpperCase(),serialNumber:device.anchor.serialNumber,manufacturer:device.anchor.vendor,model:device.anchor.model,outcome,message});

export class AddToExistingProjectService{
 private plans=new Map<string,PendingPlan>();
 public preview(projectJson:string,selected:Device[],localHost=LocalHostIdentity.fromAddresses([])):AddProjectPreview{
  if(!selected.length)throw new ProjectValidationError('Select at least one current device to add.');
  const database=new SiteProjectDatabase();database.importProjectJson(projectJson);const known=database.getProjectMemberDevices(),items:AddProjectPreviewItem[]=[],live=new Map<string,Device>();
  for(const device of structuredClone(selected)){live.set(device.id,device);if(!localHost.isRemoteDevice(device)){items.push(item(device,'CANNOT_ADD','This address belongs to the local computer and cannot be added.'));continue}if(!anchors(device).length){items.push(item(device,'CANNOT_ADD','This device cannot be safely added because its identity is insufficient.'));continue}const found=known.filter(candidate=>matches(candidate,device));if(found.length>1){items.push(item(device,'NEEDS_ATTENTION','This device matches multiple Project identities. Review it with Project Reverify.'));continue}if(found.length===1&&conflict(found[0],device)){items.push(item(device,'NEEDS_ATTENTION','Identity evidence conflicts with the Project. Use Project Reverify for replacement review.'));continue}if(found.length===1){items.push(item(device,found[0].network.ipAddress===device.network.ipAddress?'ALREADY_IN_PROJECT':'WILL_UPDATE_EVIDENCE',found[0].network.ipAddress===device.network.ipAddress?'Already in Project; existing technician metadata will be preserved.':'Same physical identity with changed address; current evidence will update and prior IP will be retained.'));continue}const removed=database.getProject().auditLogs.some(entry=>entry.details?.operation==='REMOVE_FROM_PROJECT'&&anchors(device).some(anchor=>JSON.stringify(entry.details?.identity||{}).toLowerCase().includes(anchor)));items.push(item(device,'NEW_TO_PROJECT',removed?'Previously removed identity will be explicitly re-added after confirmation.':'New stable identity will be added to the Project.'))}
  const planId=crypto.randomUUID();this.plans.set(planId,{database,items,live});const counts=Object.fromEntries((['NEW_TO_PROJECT','ALREADY_IN_PROJECT','WILL_UPDATE_EVIDENCE','NEEDS_ATTENTION','CANNOT_ADD']as AddProjectOutcome[]).map(value=>[value,items.filter(entry=>entry.outcome===value).length]))as Record<AddProjectOutcome,number>;const project=database.getProject();return{planId,projectId:project.id,projectName:project.name,items,counts};
 }
 public confirm(planId:string,confirmed:boolean){const plan=this.plans.get(planId);if(!plan)throw new ProjectValidationError('This Add to Project preview is no longer available.');if(!confirmed)throw new ProjectValidationError('Confirm Add to Project before creating the updated file.');let added=0,updated=0;for(const outcome of plan.items){if(!['NEW_TO_PROJECT','ALREADY_IN_PROJECT','WILL_UPDATE_EVIDENCE'].includes(outcome.outcome))continue;const incoming=plan.live.get(outcome.deviceId)!;const existing=plan.database.getProjectMemberDevices().find(device=>matches(device,incoming));if(existing){const technician=structuredClone(existing.technician),configuredState=structuredClone(existing.configuredState);plan.database.upsertDevice({...incoming,id:existing.id,firstSeenAt:existing.firstSeenAt,technician,configuredState});updated++}else{plan.database.upsertDevice(incoming);added++}plan.database.recordProjectAudit({id:crypto.randomUUID(),timestamp:new Date().toISOString(),category:'SYSTEM',level:'SUCCESS',message:existing?'Explicit Add to Existing Project reconciled current identity evidence.':'Explicit Add to Existing Project added a stable device identity.',deviceId:existing?.id||incoming.id,details:{operation:'ADD_TO_EXISTING_PROJECT',result:existing?'RECONCILED':'ADDED'}})}this.plans.delete(planId);return{content:plan.database.exportProjectJson(),project:plan.database.getProject(),added,updated,blocked:plan.items.filter(value=>value.outcome==='NEEDS_ATTENTION'||value.outcome==='CANNOT_ADD').length};}
 public cancel(planId:string){return this.plans.delete(planId)}
}
