import { spawn } from 'node:child_process';
import { appStateDb } from './app_db.ts';
export interface CredentialMetadata{id:string;label:string;username:string;targetVendor?:string;deviceIdentity?:string;createdAt:string;updatedAt:string}
export interface CredentialReference{id:string;label:string;usernameHint:string;targetVendor?:string;deviceIdentity?:string}
export interface CredentialStore{list():Promise<CredentialMetadata[]>;save(m:CredentialMetadata,secret:string):Promise<void>;delete(id:string):Promise<void>;resolveSecret(id:string):Promise<string|null>}
const opaque=(id:string)=>/^[0-9a-f]{8}-[0-9a-f-]{27,}$/i.test(id);
const ps=`$ErrorActionPreference='Stop';$j=[Console]::In.ReadToEnd()|ConvertFrom-Json;Add-Type -AssemblyName System.Runtime.WindowsRuntime;$null=[Windows.Security.Credentials.PasswordVault,Windows.Security.Credentials,ContentType=WindowsRuntime];$v=[Windows.Security.Credentials.PasswordVault]::new();$n='CCTVDiscoveryTool/';if($j.op-eq'list'){@($v.RetrieveAll()|? Resource -like "$n*"|%{$_.RetrievePassword();($_.Password|ConvertFrom-Json).metadata})|ConvertTo-Json -Depth 6 -Compress}elseif($j.op-eq'save'){$t=$n+$j.metadata.id;try{$v.Remove($v.Retrieve($t,'camera'))}catch{};$p=@{metadata=$j.metadata;secret=$j.secret}|ConvertTo-Json -Compress -Depth 6;$v.Add([Windows.Security.Credentials.PasswordCredential]::new($t,'camera',$p))}elseif($j.op-eq'delete'){$v.Remove($v.Retrieve($n+$j.id,'camera'))}elseif($j.op-eq'resolve'){try{$c=$v.Retrieve($n+$j.id,'camera');$c.RetrievePassword();($c.Password|ConvertFrom-Json).secret}catch{''}}`;
export class WindowsCredentialStore implements CredentialStore{private run(x:unknown){return new Promise<string>((ok,no)=>{const c=spawn('powershell.exe',['-NoProfile','-NonInteractive','-Command',ps],{windowsHide:true,stdio:['pipe','pipe','pipe']});let o='';c.stdout.on('data',d=>o+=d);c.on('error',()=>no(new Error('Windows secure credential storage is unavailable.')));c.on('close',n=>n===0?ok(o.trim()):no(new Error('Windows secure credential storage operation failed.')));c.stdin.end(JSON.stringify(x));});}async list(){const o=await this.run({op:'list'});if(!o)return[];const v=JSON.parse(o);return Array.isArray(v)?v:[v]}async save(m:CredentialMetadata,s:string){if(!opaque(m.id))throw Error('Invalid credential ID.');await this.run({op:'save',metadata:m,secret:s})}async delete(id:string){await this.run({op:'delete',id})}async resolveSecret(id:string){return(await this.run({op:'resolve',id}))||null}}
export class InMemoryCredentialStore implements CredentialStore{records=new Map<string,{m:CredentialMetadata;s:string}>();async list(){return[...this.records.values()].map(x=>structuredClone(x.m))}async save(m:CredentialMetadata,s:string){this.records.set(m.id,{m:structuredClone(m),s})}async delete(id:string){this.records.delete(id)}async resolveSecret(id:string){return this.records.get(id)?.s||null}}
export class OSCredentialVault{private meta=new Map<string,CredentialMetadata>();private assoc=new Map<string,string>();constructor(private store:CredentialStore=new WindowsCredentialStore()){}async initialize(){for(const m of await this.store.list()){if(!opaque(m.id))continue;this.meta.set(m.id,m);if(m.deviceIdentity)this.assoc.set(m.deviceIdentity,m.id)}}getSafeReferences(v?:string){return[...this.meta.values()].filter(x=>!v||!x.targetVendor||x.targetVendor.toLowerCase()===v.toLowerCase()).map(x=>({id:x.id,label:x.label,usernameHint:x.username?x.username[0]+'•••':'',targetVendor:x.targetVendor,deviceIdentity:x.deviceIdentity}))}async saveCredential(x:{id?:string;label:string;username:string;password:string;targetVendor?:string;deviceIdentity?:string}){if(!x.username.trim()||!x.password)throw Error('Username and password are required.');const id=x.id||crypto.randomUUID();if(!opaque(id))throw Error('Invalid credential ID.');const now=new Date().toISOString(),old=this.meta.get(id),m={id,label:x.label.trim(),username:x.username.trim(),targetVendor:x.targetVendor,deviceIdentity:x.deviceIdentity,createdAt:old?.createdAt||now,updatedAt:now};await this.store.save(m,x.password);this.meta.set(id,m);if(m.deviceIdentity)this.assoc.set(m.deviceIdentity,id);this.audit(old?'updated':'created',id);return this.getSafeReferences().find(r=>r.id===id)!}async deleteCredential(id:string){if(!opaque(id)||!this.meta.has(id))throw Error('Credential reference not found.');await this.store.delete(id);this.meta.delete(id);for(const[k,v]of this.assoc)if(v===id)this.assoc.delete(k);this.audit('deleted',id)}associate(identity:string,id:string){if(!this.meta.has(id))throw Error('Credential reference not found.');this.assoc.set(identity,id)}removeAssociation(i:string){this.assoc.delete(i)}getAssociation(i:string){return this.assoc.get(i)}hasCredential(id:string){return opaque(id)&&this.meta.has(id)}async resolveCredentialSecret(id:string){return opaque(id)&&this.meta.has(id)?this.store.resolveSecret(id):null}private audit(a:string,id:string){appStateDb.logAudit({id:crypto.randomUUID(),timestamp:new Date().toISOString(),category:'SECURITY',level:'INFO',message:`Camera credential ${a}.`,details:{credentialId:id}})}}
export const osVault=new OSCredentialVault();
export interface OSCredentialVault{getCredential(id:string):CredentialMetadata|undefined;getCredentialsForVendor(v:string):CredentialMetadata[];checkLockoutStatus(id:string):{isLocked:boolean;waitSeconds:number};reportAuthFailure(id:string):void;flushTokens():void}
OSCredentialVault.prototype.getCredential=function(id){return this.getSafeReferences().find(x=>x.id===id) as any};
OSCredentialVault.prototype.getCredentialsForVendor=function(v){return this.getSafeReferences(v) as any};
OSCredentialVault.prototype.checkLockoutStatus=function(){return{isLocked:false,waitSeconds:0}};
OSCredentialVault.prototype.reportAuthFailure=function(){};
OSCredentialVault.prototype.flushTokens=function(){};
