import net from 'node:net';
import { execFile } from 'node:child_process';
import { createHash, randomBytes } from 'node:crypto';
import { Device, WindowsAdapterSnapshot } from '../../types/index.ts';
import { SiteProjectDatabase, projectDb } from '../storage/project_db.ts';
import { OSCredentialVault, osVault } from '../storage/vault.ts';
import { PowerShellWindowsNetworkAdapterService, WindowsNetworkAdapterService } from './windows_adapter_service.ts';
import { appStateDb } from '../storage/app_db.ts';

export type CameraNetworkState = 'IDLE'|'READING_CURRENT'|'CHECKING_TARGET'|'READY_FOR_CONFIRMATION'|'AUTHENTICATING'|'APPLYING'|'WAITING_FOR_DEVICE'|'REVERIFYING'|'SUCCESS'|'PARTIAL_SUCCESS'|'FAILED'|'RECOVERY_REQUIRED';
export interface CameraNetworkConfig { interfaceToken:string; ipAddress:string; prefixLength:number; dhcp:boolean; gateway?:string; dns?:string[]; hostname?:string }
export interface NetworkTarget { ipAddress:string; prefixLength:number; gateway?:string; dhcp?:boolean }
export interface IpCandidate { ipAddress:string; confidence:'AVAILABLE_CANDIDATE'|'UNCERTAIN'|'CONFLICT'; label:string; checkedAt:string; evidence:string[] }
export interface NetworkPreview { planId:string; state:'READY_FOR_CONFIRMATION'; deviceId:string; identity:Record<string,unknown>; current:CameraNetworkConfig; proposed:NetworkTarget; credentialId:string; credentialLabel?:string; protocol:'ONVIF'; expectedEffect:string; warning:string; pcNetworkChange:false; createdAt:string }
export interface CameraNetworkResult { state:CameraNetworkState; acknowledged:boolean; verified:boolean; deviceId:string; oldIp:string; requestedIp:string; recoveryGuidance?:string; pairAvailable:boolean }
export class CameraNetworkError extends Error { constructor(message:string,public readonly code:string){super(message)} }
export interface CameraConfigurationTransport { readCurrent(device:Device,endpoint:URL,credential:{username:string;password:string},signal?:AbortSignal):Promise<CameraNetworkConfig>; apply(device:Device,endpoint:URL,credential:{username:string;password:string},target:NetworkTarget,interfaceToken:string):Promise<{acknowledged:boolean}> }
export interface AddressEvidenceProvider { neighborIps(signal?:AbortSignal):Promise<Set<string>>; hasOccupant(ip:string,signal?:AbortSignal):Promise<boolean> }
export interface CameraReverifier { verify(device:Device,targetIp:string,signal?:AbortSignal):Promise<Partial<Device>|null> }

const xmlEscape=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));
const text=(xml:string,name:string)=>xml.match(new RegExp(`<(?:\\w+:)?${name}(?:\\s[^>]*)?>([^<]*)<\\/(?:\\w+:)?${name}>`,'i'))?.[1]?.trim();
const attr=(xml:string,name:string,key:string)=>xml.match(new RegExp(`<(?:\\w+:)?${name}[^>]*\\b${key}=["']([^"']+)["']`,'i'))?.[1];
function prefixFromMask(mask:string){const parts=mask.split('.').map(Number);if(parts.length!==4||parts.some(n=>!Number.isInteger(n)||n<0||n>255))throw new CameraNetworkError('Invalid subnet mask.','INVALID_SUBNET');const bits=parts.map(n=>n.toString(2).padStart(8,'0')).join('');if(!/^1*0*$/.test(bits))throw new CameraNetworkError('Subnet mask must contain contiguous bits.','INVALID_SUBNET');return bits.indexOf('0')<0?32:bits.indexOf('0')}
const maskFromPrefix=(p:number)=>Array.from({length:4},(_,i)=>{const n=Math.max(0,Math.min(8,p-i*8));return n?256-2**(8-n):0}).join('.');
const ipInt=(ip:string)=>ip.split('.').reduce((n,p)=>(n<<8)+Number(p),0)>>>0;
const intIp=(n:number)=>[24,16,8,0].map(s=>(n>>>s)&255).join('.');
const prefixMask=(prefix:number)=>(0xffffffff<<(32-prefix))>>>0;
function validateIp(ip:string){if(net.isIP(ip)!==4)throw new CameraNetworkError('A valid IPv4 address is required.','INVALID_IP')}

export class OnvifCameraConfigurationTransport implements CameraConfigurationTransport {
  constructor(private readonly timeoutMs=8000){}
  private async request(endpoint:URL,action:string,body:string,credential:{username:string;password:string},signal?:AbortSignal){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),this.timeoutMs);const abort=()=>controller.abort();signal?.addEventListener('abort',abort,{once:true});const nonce=randomBytes(16),created=new Date().toISOString(),digest=createHash('sha1').update(Buffer.concat([nonce,Buffer.from(created),Buffer.from(credential.password)])).digest('base64');const security=`<s:Header><wsse:Security s:mustUnderstand="1" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><wsse:UsernameToken><wsse:Username>${xmlEscape(credential.username)}</wsse:Username><wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">${digest}</wsse:Password><wsse:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">${nonce.toString('base64')}</wsse:Nonce><wsu:Created>${created}</wsu:Created></wsse:UsernameToken></wsse:Security></s:Header>`;try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':`application/soap+xml; charset=utf-8; action="${action}"`},body:`<?xml version="1.0"?><s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:tt="http://www.onvif.org/ver10/schema">${security}<s:Body>${body}</s:Body></s:Envelope>`,signal:controller.signal});const xml=await response.text();if(response.status===401||response.status===403)throw new CameraNetworkError('Camera authentication failed.','UNAUTHORIZED');if(/<(?:\w+:)?Fault\b/i.test(xml))throw new CameraNetworkError(text(xml,'Text')||text(xml,'faultstring')||'The camera returned an ONVIF SOAP fault.','SOAP_FAULT');if(!response.ok)throw new CameraNetworkError(`ONVIF request failed with HTTP ${response.status}.`,'HTTP_ERROR');if(!/<(?:\w+:)?Envelope\b/i.test(xml))throw new CameraNetworkError('The camera returned malformed ONVIF SOAP.','MALFORMED_SOAP');return xml}catch(error){if(error instanceof CameraNetworkError)throw error;if((error as Error).name==='AbortError')throw new CameraNetworkError('ONVIF request timed out or was cancelled.','TIMEOUT');throw new CameraNetworkError('The ONVIF device service could not be reached.','CONNECTION_FAILED')}finally{clearTimeout(timer);signal?.removeEventListener('abort',abort)}}
  async readCurrent(device:Device,endpoint:URL,credential:{username:string;password:string},signal?:AbortSignal){const xml=await this.request(endpoint,'http://www.onvif.org/ver10/device/wsdl/GetNetworkInterfaces','<tds:GetNetworkInterfaces/>',credential,signal);const block=xml.match(/<(?:\w+:)?NetworkInterfaces\b[\s\S]*?<\/(?:\w+:)?NetworkInterfaces>/i)?.[0];if(!block)throw new CameraNetworkError('This camera does not expose readable ONVIF network interfaces.','UNSUPPORTED');const token=attr(block,'NetworkInterfaces','token');const address=text(block,'Address');const prefix=Number(text(block,'PrefixLength'));if(!token||!address||net.isIP(address)!==4||!Number.isInteger(prefix))throw new CameraNetworkError('The camera returned incomplete network configuration.','MALFORMED_SOAP');const gateways=await this.request(endpoint,'http://www.onvif.org/ver10/device/wsdl/GetNetworkDefaultGateway','<tds:GetNetworkDefaultGateway/>',credential,signal).catch(e=>{if(e instanceof CameraNetworkError&&e.code==='SOAP_FAULT')return'';throw e});return{interfaceToken:token,ipAddress:address,prefixLength:prefix,dhcp:/<(?:\w+:)?DHCP>\s*true/i.test(block),gateway:text(gateways,'IPv4Address')}}
  async apply(device:Device,endpoint:URL,credential:{username:string;password:string},target:NetworkTarget,interfaceToken:string){const manual=target.dhcp?'':`<tt:Manual><tt:Address>${xmlEscape(target.ipAddress)}</tt:Address><tt:PrefixLength>${target.prefixLength}</tt:PrefixLength></tt:Manual>`;const body=`<tds:SetNetworkInterfaces><tds:InterfaceToken>${xmlEscape(interfaceToken)}</tds:InterfaceToken><tds:NetworkInterface><tt:IPv4><tt:Enabled>true</tt:Enabled><tt:Config>${manual}<tt:DHCP>${target.dhcp===true}</tt:DHCP></tt:Config></tt:IPv4></tds:NetworkInterface></tds:SetNetworkInterfaces>`;await this.request(endpoint,'http://www.onvif.org/ver10/device/wsdl/SetNetworkInterfaces',body,credential);if(target.gateway)await this.request(endpoint,'http://www.onvif.org/ver10/device/wsdl/SetNetworkDefaultGateway',`<tds:SetNetworkDefaultGateway><tds:IPv4Address>${xmlEscape(target.gateway)}</tds:IPv4Address></tds:SetNetworkDefaultGateway>`,credential);return{acknowledged:true}}
}

export class WindowsAddressEvidenceProvider implements AddressEvidenceProvider { async neighborIps(signal?:AbortSignal){return new Promise<Set<string>>((resolve,reject)=>execFile('powershell.exe',['-NoProfile','-NonInteractive','-Command',"@(Get-NetNeighbor -AddressFamily IPv4 -ErrorAction SilentlyContinue | Where-Object State -notin 'Unreachable','Incomplete' | Select-Object -ExpandProperty IPAddress) | ConvertTo-Json -Compress"],{windowsHide:true,timeout:5000,signal},(error,stdout)=>{if(error)return reject(new CameraNetworkError('Windows neighbor evidence is unavailable.','EVIDENCE_UNAVAILABLE'));try{const parsed=stdout.trim()?JSON.parse(stdout):[];resolve(new Set(Array.isArray(parsed)?parsed:[parsed]))}catch{reject(new CameraNetworkError('Windows neighbor evidence was malformed.','EVIDENCE_UNAVAILABLE'))}}))}async hasOccupant(ip:string,signal?:AbortSignal){return new Promise<boolean>(resolve=>{const socket=new net.Socket();let done=false;const finish=(v:boolean)=>{if(done)return;done=true;socket.destroy();resolve(v)};socket.setTimeout(350);socket.once('connect',()=>finish(true));socket.once('timeout',()=>finish(false));socket.once('error',()=>finish(false));signal?.addEventListener('abort',()=>finish(false),{once:true});socket.connect(80,ip)})} }
export class TargetedCameraReverifier implements CameraReverifier { async verify(device:Device,targetIp:string,signal?:AbortSignal){const advertised=[...(device.network.xAddrs||[]),device.network.xAddr].find(Boolean);if(!advertised)return null;try{const old=new URL(advertised),target=new URL(old.toString());target.hostname=targetIp;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),5000),abort=()=>controller.abort();signal?.addEventListener('abort',abort,{once:true});try{const response=await fetch(target,{method:'GET',signal:controller.signal});if(!response.ok&&![401,403,405].includes(response.status))return null}finally{clearTimeout(timer);signal?.removeEventListener('abort',abort)}}catch{return null}return null} }

export class CameraNetworkConfigurationService {
  private plans=new Map<string,NetworkPreview>(); private states=new Map<string,CameraNetworkState>(); private duplicateAuthorizations=new Map<string,number>();
  constructor(private db:SiteProjectDatabase=projectDb,private vault:OSCredentialVault=osVault,private transport:CameraConfigurationTransport=new OnvifCameraConfigurationTransport(),private adapters:WindowsNetworkAdapterService=new PowerShellWindowsNetworkAdapterService(),private evidence:AddressEvidenceProvider=new WindowsAddressEvidenceProvider(),private reverifier:CameraReverifier=new TargetedCameraReverifier()){}
  state(deviceId:string){return this.states.get(deviceId)||'IDLE'}
  hasActiveOperation(){return[...this.states.values()].some(state=>['AUTHENTICATING','APPLYING','WAITING_FOR_DEVICE','REVERIFYING'].includes(state))}
  private device(id:string){const d=this.db.getDeviceById(id);if(!d)throw new CameraNetworkError('Device not found.','DEVICE_NOT_FOUND');const peers=this.db.getDevices().filter(x=>x.id!==d.id&&x.network.ipAddress===d.network.ipAddress),active=(x:Device)=>!['UNREACHABLE','OFFLINE','UNKNOWN'].includes(x.status),uses=this.duplicateAuthorizations.get(d.id)||0,authorized=uses>0&&!peers.some(active);if((d.status==='COLLISION'||peers.length>0)&&!authorized)throw new CameraNetworkError('Configuration is blocked because this address belongs to ambiguous duplicate identities. Use Duplicate Assistant.','DUPLICATE_AMBIGUOUS');if(authorized){if(uses===1)this.duplicateAuthorizations.delete(d.id);else this.duplicateAuthorizations.set(d.id,uses-1)}return d}
  authorizeIsolatedDuplicate(deviceId:string){this.duplicateAuthorizations.set(deviceId,3)}
  revokeDuplicateAuthorization(deviceId:string){this.duplicateAuthorizations.delete(deviceId)}
  private endpoint(d:Device){const raw=[...(d.network.xAddrs||[]),d.network.xAddr].filter(Boolean) as string[];for(const value of raw){try{const u=new URL(value);if(['http:','https:'].includes(u.protocol)&&u.hostname===d.network.ipAddress)return u}catch{}}throw new CameraNetworkError('No validated ONVIF device-service endpoint is available for this camera.','INVALID_ENDPOINT')}
  private async credential(id:string){if(!this.vault.hasCredential(id))throw new CameraNetworkError('Credential reference not found.','CREDENTIAL_NOT_FOUND');const material=await this.vault.resolveCredentialMaterial(id);if(!material)throw new CameraNetworkError('The saved credential is unavailable on this computer.','CREDENTIAL_NOT_FOUND');return material}
  async readCurrent(deviceId:string,credentialId:string,signal?:AbortSignal){const d=this.device(deviceId);this.states.set(d.id,'READING_CURRENT');try{return await this.transport.readCurrent(d,this.endpoint(d),await this.credential(credentialId),signal)}catch(e){this.states.set(d.id,'FAILED');throw e}}
  async findCandidates(deviceId:string,prefixLength:number,gateway?:string,signal?:AbortSignal){const d=this.device(deviceId);validateIp(d.network.ipAddress);if(!Number.isInteger(prefixLength)||prefixLength<8||prefixLength>30)throw new CameraNetworkError('Prefix length must be between 8 and 30.','INVALID_SUBNET');this.states.set(d.id,'CHECKING_TARGET');const base=(ipInt(d.network.ipAddress)&prefixMask(prefixLength))>>>0;const broadcast=(base+(2**(32-prefixLength)-1))>>>0;if(broadcast-base>4095)throw new CameraNetworkError('Address search is limited to 4096 addresses. Narrow the subnet.','SUBNET_TOO_LARGE');const adapters=await this.adapters.inspectAdapters(signal);const local=new Set(adapters.flatMap(a=>a.ipv4Addresses.map(x=>x.address)));const neighbor=await this.evidence.neighborIps(signal);const known=new Set(this.db.getDevices().map(x=>x.network.ipAddress));const collisions=new Set(this.db.getCollisions().filter(x=>!x.resolved).map(x=>x.ipAddress));const out:IpCandidate[]=[];for(let n=base+1;n<broadcast&&out.length<3&&n<base+257;n++){if(signal?.aborted)throw new CameraNetworkError('Address check cancelled.','CANCELLED');const ip=intIp(n);if(ip===d.network.ipAddress||ip===gateway||local.has(ip)||known.has(ip)||collisions.has(ip)||neighbor.has(ip))continue;const occupied=await this.evidence.hasOccupant(ip,signal);if(occupied)continue;out.push({ipAddress:ip,confidence:'UNCERTAIN',label:'No occupant detected',checkedAt:new Date().toISOString(),evidence:['Not discovered or saved','Not locally assigned','Absent from neighbor table','Bounded targeted checks found no positive occupant; silence alone is not proof']})}return out}
  async validateTarget(deviceId:string,target:NetworkTarget,signal?:AbortSignal){const d=this.device(deviceId);validateIp(target.ipAddress);if(!Number.isInteger(target.prefixLength)||target.prefixLength<1||target.prefixLength>30)throw new CameraNetworkError('Invalid subnet prefix.','INVALID_SUBNET');const base=(ipInt(target.ipAddress)&prefixMask(target.prefixLength))>>>0;const broadcast=(base+(2**(32-target.prefixLength)-1))>>>0;const value=ipInt(target.ipAddress);if(target.gateway){validateIp(target.gateway);if(target.gateway===target.ipAddress)throw new CameraNetworkError('Target address cannot be the gateway.','IP_CONFLICT');if(((ipInt(target.gateway)&prefixMask(target.prefixLength))>>>0)!==base)throw new CameraNetworkError('Gateway is outside the target subnet.','INVALID_GATEWAY')}if(target.dhcp===true)return true;if(value===base||value===broadcast)throw new CameraNetworkError('Target cannot be the network or broadcast address.','RESERVED_IP');if(target.ipAddress===d.network.ipAddress)throw new CameraNetworkError('Target address is unchanged.','NO_OP');const adapters=await this.adapters.inspectAdapters(signal);if(adapters.some(a=>a.ipv4Addresses.some(x=>x.address===target.ipAddress)))throw new CameraNetworkError('Target address is assigned to this PC.','IP_CONFLICT');if(this.db.getDevices().some(x=>x.network.ipAddress===target.ipAddress)||this.db.getCollisions().some(x=>!x.resolved&&x.ipAddress===target.ipAddress)||(await this.evidence.neighborIps(signal)).has(target.ipAddress)||await this.evidence.hasOccupant(target.ipAddress,signal))throw new CameraNetworkError('Positive evidence indicates that the target address is occupied.','IP_CONFLICT');return true}
  async preview(deviceId:string,credentialId:string,target:NetworkTarget,signal?:AbortSignal){const d=this.device(deviceId);const current=await this.readCurrent(deviceId,credentialId,signal);await this.validateTarget(deviceId,target,signal);const ref=this.vault.getCredential(credentialId);const plan:NetworkPreview={planId:crypto.randomUUID(),state:'READY_FOR_CONFIRMATION',deviceId:d.id,identity:{name:d.technician?.name,vendor:d.anchor.vendor,model:d.anchor.model,mac:d.anchor.macAddress,uuid:d.anchor.onvifEndpointUuid},current,proposed:{...target,dhcp:target.dhcp??false},credentialId,credentialLabel:ref?.label,protocol:'ONVIF',expectedEffect:'The camera may temporarily disappear while applying its new IPv4 address.',warning:'The PC network will not automatically change. Pair is always technician-controlled.',pcNetworkChange:false,createdAt:new Date().toISOString()};this.plans.set(plan.planId,plan);this.states.set(d.id,'READY_FOR_CONFIRMATION');return plan}
  async apply(planId:string,confirmed:boolean){const plan=this.plans.get(planId);if(!plan)throw new CameraNetworkError('A current preview is required before applying.','PREVIEW_REQUIRED');if(!confirmed)throw new CameraNetworkError('Explicit technician confirmation is required.','CONFIRMATION_REQUIRED');const d=this.device(plan.deviceId);this.states.set(d.id,'AUTHENTICATING');const credential=await this.credential(plan.credentialId);this.states.set(d.id,'APPLYING');let acknowledged=false;try{acknowledged=(await this.transport.apply(d,this.endpoint(d),credential,plan.proposed,plan.current.interfaceToken)).acknowledged}catch(e){this.states.set(d.id,'FAILED');this.audit(plan,'FAILED',false);throw e}finally{this.plans.delete(planId)}this.states.set(d.id,'WAITING_FOR_DEVICE');this.states.set(d.id,'REVERIFYING');const found=await this.reverifier.verify(d,plan.proposed.ipAddress);if(found){const original={...d,network:{...d.network,ipAddress:plan.proposed.ipAddress,subnetMask:maskFromPrefix(plan.proposed.prefixLength),ipAddressHistory:Array.from(new Set([...(d.network.ipAddressHistory||[]),plan.current.ipAddress,plan.proposed.ipAddress]))},status:'ONLINE' as const,statusMessage:'Network configuration verified at the requested address.'};this.db.upsertDevice({...original,...found,id:d.id,technician:d.technician});this.states.set(d.id,'SUCCESS');this.audit(plan,'SUCCESS',true);return{state:'SUCCESS',acknowledged,verified:true,deviceId:d.id,oldIp:plan.current.ipAddress,requestedIp:plan.proposed.ipAddress,pairAvailable:false} as CameraNetworkResult}d.network.ipAddressHistory=Array.from(new Set([...(d.network.ipAddressHistory||[]),plan.current.ipAddress,plan.proposed.ipAddress]));d.statusMessage='Camera acknowledged the network write but could not yet be verified at the requested address.';this.db.upsertDevice(d);this.states.set(d.id,'PARTIAL_SUCCESS');this.audit(plan,'PARTIAL_SUCCESS',false);return{state:'PARTIAL_SUCCESS',acknowledged,verified:false,deviceId:d.id,oldIp:plan.current.ipAddress,requestedIp:plan.proposed.ipAddress,pairAvailable:true,recoveryGuidance:'Disconnect equipment and Rescan. If the camera is now on a different subnet, manually choose Pair PC to Camera Network.'} as CameraNetworkResult}
  cancel(deviceId:string){if(['APPLYING','WAITING_FOR_DEVICE','REVERIFYING'].includes(this.state(deviceId)))return false;for(const[id,p]of this.plans)if(p.deviceId===deviceId)this.plans.delete(id);this.states.set(deviceId,'IDLE');return true}
  private audit(plan:NetworkPreview,result:string,verified:boolean){appStateDb.logAudit({id:crypto.randomUUID(),timestamp:new Date().toISOString(),category:'PROVISIONING',level:result==='FAILED'?'ERROR':'INFO',message:'Single-camera ONVIF network configuration.',details:{deviceId:plan.deviceId,oldIp:plan.current.ipAddress,newIp:plan.proposed.ipAddress,prefixLength:plan.proposed.prefixLength,gateway:plan.proposed.gateway,protocol:'ONVIF',confirmed:true,result,verified}})}
}
