import net from'node:net';
import{createHash,randomBytes}from'node:crypto';
import{Device}from'../../types/index.ts';
import{appStateDb}from'../storage/app_db.ts';
import{SiteProjectDatabase,projectDb}from'../storage/project_db.ts';
import{OSCredentialVault,osVault}from'../storage/vault.ts';
import{BulkCameraConfigurationPlan,CameraCapability,CameraConfigurationOperation,CameraConfigurationPreview,CameraConfigurationProposal,CameraConfigurationResult,CameraConfigurationSnapshot}from'../../shared/camera_configuration.ts';
import{BULK_EXECUTABLE_CONFIG_OPERATIONS,bulkCapability}from'../../shared/bulk_capabilities.ts';

export class CameraConfigurationError extends Error{constructor(message:string,public readonly code:string){super(message)}}
export interface CameraDeviceValues{deviceName?:string;ntp?:{fromDhcp:boolean;servers:string[]};timeZone?:string;onvifEnabled?:boolean}
export interface CameraConfigurationProvider{
  readonly kind:string;
  inspect(device:Device,credential:{username:string;password:string},signal?:AbortSignal):Promise<{capabilities:CameraCapability[];values:CameraDeviceValues;providers?:Record<string,string>}>;
  apply(device:Device,credential:{username:string;password:string},operation:CameraConfigurationOperation,proposal:CameraConfigurationProposal,signal?:AbortSignal):Promise<void>;
  verify(device:Device,credential:{username:string;password:string},operation:CameraConfigurationOperation,proposal:CameraConfigurationProposal,signal?:AbortSignal):Promise<boolean>;
}
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));
const value=(xml:string,name:string)=>xml.match(new RegExp(`<(?:\\w+:)?${name}(?:\\s[^>]*)?>([^<]*)<\\/(?:\\w+:)?${name}>`,'i'))?.[1]?.trim();
const values=(xml:string,name:string)=>[...xml.matchAll(new RegExp(`<(?:\\w+:)?${name}(?:\\s[^>]*)?>([^<]*)<\\/(?:\\w+:)?${name}>`,'gi'))].map(x=>x[1].trim());
const endpoint=(device:Device)=>{for(const raw of[...(device.network.xAddrs||[]),device.network.xAddr].filter(Boolean)as string[]){try{const url=new URL(raw);if(['http:','https:'].includes(url.protocol)&&url.hostname===device.network.ipAddress)return url}catch{}}throw new CameraConfigurationError('No validated ONVIF device-service endpoint is available.','INVALID_ENDPOINT')};

export class OnvifDeviceConfigurationProvider implements CameraConfigurationProvider{
  readonly kind='ONVIF' as const;constructor(private timeoutMs=8000,private rebootAttempts=8,private rebootDelayMs=500){}
  private async request(device:Device,credential:{username:string;password:string},action:string,body:string,signal?:AbortSignal){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),this.timeoutMs),abort=()=>controller.abort();signal?.addEventListener('abort',abort,{once:true});const nonce=randomBytes(16),created=new Date().toISOString(),digest=createHash('sha1').update(Buffer.concat([nonce,Buffer.from(created),Buffer.from(credential.password)])).digest('base64');const security=`<s:Header><wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><wsse:UsernameToken><wsse:Username>${esc(credential.username)}</wsse:Username><wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">${digest}</wsse:Password><wsse:Nonce>${nonce.toString('base64')}</wsse:Nonce><wsu:Created>${created}</wsu:Created></wsse:UsernameToken></wsse:Security></s:Header>`;try{const response=await fetch(endpoint(device),{method:'POST',headers:{'Content-Type':`application/soap+xml; charset=utf-8; action="${action}"`},body:`<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:tt="http://www.onvif.org/ver10/schema">${security}<s:Body>${body}</s:Body></s:Envelope>`,signal:controller.signal});const xml=await response.text();if(response.status===401||response.status===403)throw new CameraConfigurationError('Camera authentication failed.','UNAUTHORIZED');if(/<(?:\w+:)?Fault\b/i.test(xml))throw new CameraConfigurationError(value(xml,'Text')||'The camera reports this operation as unsupported.','UNSUPPORTED');if(!response.ok)throw new CameraConfigurationError(`ONVIF request failed with HTTP ${response.status}.`,'HTTP_ERROR');return xml}catch(error){if(error instanceof CameraConfigurationError)throw error;if((error as Error).name==='AbortError')throw new CameraConfigurationError('ONVIF request timed out or was cancelled.','TIMEOUT');throw new CameraConfigurationError('The ONVIF device service could not be reached.','CONNECTION_FAILED')}finally{clearTimeout(timer);signal?.removeEventListener('abort',abort)}}
  async inspect(device:Device,credential:{username:string;password:string},signal?:AbortSignal){const capabilities:CameraCapability[]=[];const read=async(operation:CameraConfigurationOperation,action:string,body:string)=>{try{return await this.request(device,credential,action,body,signal)}catch(error){capabilities.push({operation,state:(error as CameraConfigurationError).code==='UNAUTHORIZED'?'REQUIRES_AUTHENTICATION':(error as CameraConfigurationError).code==='UNSUPPORTED'?'UNSUPPORTED':'UNKNOWN',detail:(error as Error).message,editable:false});return''}};const host=await read('DEVICE_NAME','http://www.onvif.org/ver10/device/wsdl/GetHostname','<tds:GetHostname/>');if(host)capabilities.push({operation:'DEVICE_NAME',state:'SUPPORTED',detail:'Standard ONVIF hostname service responded.',editable:true});const ntp=await read('NTP','http://www.onvif.org/ver10/device/wsdl/GetNTP','<tds:GetNTP/>');if(ntp)capabilities.push({operation:'NTP',state:'SUPPORTED',detail:'Standard ONVIF NTP service responded.',editable:true});const time=await read('TIME_ZONE','http://www.onvif.org/ver10/device/wsdl/GetSystemDateAndTime','<tds:GetSystemDateAndTime/>');if(time)capabilities.push({operation:'TIME_ZONE',state:'SUPPORTED',detail:'Standard ONVIF system time service responded.',editable:true});const users=await read('PASSWORD','http://www.onvif.org/ver10/device/wsdl/GetUsers','<tds:GetUsers/>');if(users){const blocks=[...users.matchAll(/<(?:\w+:)?User\b[\s\S]*?<\/(?:\w+:)?User>/gi)].map(x=>x[0]),current=blocks.find(x=>value(x,'Username')===credential.username);capabilities.push(current&&value(current,'UserLevel')==='Administrator'?{operation:'PASSWORD',state:'SUPPORTED',detail:'The authenticated administrator is exposed through the standard ONVIF user service.',editable:true}:{operation:'PASSWORD',state:'UNSUPPORTED',detail:'Password change is not enabled because the current ONVIF user role cannot be preserved safely.',editable:false})}capabilities.push({operation:'REBOOT',state:time?'SUPPORTED':'UNKNOWN',detail:time?'Authenticated ONVIF device service supports the standard reboot request.':'Reboot support could not be established.',editable:Boolean(time)});capabilities.push({operation:'ONVIF_ENABLE',state:'VENDOR_NATIVE_REQUIRED',detail:'Standard ONVIF does not define enabling its own service. Use a supported vendor-native provider or the camera interface.',editable:false});return{capabilities,values:{deviceName:value(host,'Name'),ntp:ntp?{fromDhcp:/<(?:\w+:)?FromDHCP>\s*true/i.test(ntp),servers:[...values(ntp,'IPv4Address'),...values(ntp,'DNSname')]}:undefined,timeZone:value(time,'TZ')}}}
  async apply(device:Device,credential:{username:string;password:string},operation:CameraConfigurationOperation,p:CameraConfigurationProposal,signal?:AbortSignal){if(operation==='DEVICE_NAME')await this.request(device,credential,'http://www.onvif.org/ver10/device/wsdl/SetHostname',`<tds:SetHostname><tds:Name>${esc(p.deviceName!)}</tds:Name></tds:SetHostname>`,signal);else if(operation==='NTP'){const manual=(p.ntp?.servers||[]).map(server=>net.isIP(server)===4?`<tds:NTPManual><tt:Type>IPv4</tt:Type><tt:IPv4Address>${esc(server)}</tt:IPv4Address></tds:NTPManual>`:`<tds:NTPManual><tt:Type>DNS</tt:Type><tt:DNSname>${esc(server)}</tt:DNSname></tds:NTPManual>`).join('');await this.request(device,credential,'http://www.onvif.org/ver10/device/wsdl/SetNTP',`<tds:SetNTP><tds:FromDHCP>${p.ntp?.fromDhcp===true}</tds:FromDHCP>${manual}</tds:SetNTP>`,signal)}else if(operation==='TIME_ZONE')await this.request(device,credential,'http://www.onvif.org/ver10/device/wsdl/SetSystemDateAndTime',`<tds:SetSystemDateAndTime><tds:DateTimeType>NTP</tds:DateTimeType><tds:DaylightSavings>false</tds:DaylightSavings><tds:TimeZone><tt:TZ>${esc(p.timeZone!)}</tt:TZ></tds:TimeZone></tds:SetSystemDateAndTime>`,signal);else if(operation==='REBOOT')await this.request(device,credential,'http://www.onvif.org/ver10/device/wsdl/SystemReboot','<tds:SystemReboot/>',signal);else if(operation==='PASSWORD')await this.request(device,credential,'http://www.onvif.org/ver10/device/wsdl/SetUser',`<tds:SetUser><tds:User><tt:Username>${esc(credential.username)}</tt:Username><tt:Password>${esc(p.newPassword!)}</tt:Password><tt:UserLevel>Administrator</tt:UserLevel></tds:User></tds:SetUser>`,signal);else throw new CameraConfigurationError('ONVIF enablement requires a real vendor-native provider.','VENDOR_NATIVE_REQUIRED')}
  async verify(device:Device,credential:{username:string;password:string},operation:CameraConfigurationOperation,p:CameraConfigurationProposal,signal?:AbortSignal){const auth=operation==='PASSWORD'?{username:credential.username,password:p.newPassword!}:credential;if(operation==='REBOOT'){for(let i=0;i<this.rebootAttempts;i++){if(signal?.aborted)return false;await new Promise(r=>setTimeout(r,this.rebootDelayMs));try{await this.request(device,auth,'http://www.onvif.org/ver10/device/wsdl/GetSystemDateAndTime','<tds:GetSystemDateAndTime/>',signal);return true}catch{}}return false}const state=await this.inspect(device,auth,signal);if(operation==='DEVICE_NAME')return state.values.deviceName===p.deviceName;if(operation==='NTP')return JSON.stringify(state.values.ntp)===JSON.stringify(p.ntp);if(operation==='TIME_ZONE')return state.values.timeZone===p.timeZone;if(operation==='PASSWORD')return true;return false}
}

export class CameraConfigurationService{
  private plans=new Map<string,{preview:CameraConfigurationPreview;proposal:CameraConfigurationProposal}>();private secrets=new Map<string,string>();private bulk=new Map<string,BulkCameraConfigurationPlan>();private bulkProposals=new Map<string,CameraConfigurationProposal>();private activeOperations=0;
  constructor(private db:SiteProjectDatabase=projectDb,private vault:OSCredentialVault=osVault,private provider:CameraConfigurationProvider=new OnvifDeviceConfigurationProvider(),private concurrency=2){}
  private auditBulk(plan:BulkCameraConfigurationPlan,event:string,details:Record<string,unknown>={}){appStateDb.logAudit({id:crypto.randomUUID(),timestamp:new Date().toISOString(),category:'PROVISIONING',level:'INFO',message:'Bulk camera configuration.',details:{batchId:plan.batchId,operation:plan.operation,event,total:plan.totalSelected,completed:plan.completedCount,...details}})}
  private device(id:string){const d=this.db.getDeviceById(id);if(!d)throw new CameraConfigurationError('Device not found.','DEVICE_NOT_FOUND');if(d.status==='COLLISION'||this.db.getDevices().some(x=>x.id!==d.id&&x.network.ipAddress===d.network.ipAddress))throw new CameraConfigurationError('Duplicate IP must be resolved first.','DUPLICATE_AMBIGUOUS');return d}
  private async credential(id:string){if(!this.vault.hasCredential(id))throw new CameraConfigurationError('A saved credential is required.','CREDENTIAL_NOT_FOUND');const c=await this.vault.resolveCredentialMaterial(id);if(!c)throw new CameraConfigurationError('The saved credential is unavailable.','CREDENTIAL_NOT_FOUND');return c}
  async inspect(deviceId:string,credentialId:string,signal?:AbortSignal):Promise<CameraConfigurationSnapshot>{const d=this.device(deviceId),credential=await this.credential(credentialId),read=await this.provider.inspect(d,credential,signal);this.db.upsertDevice(d);return{deviceId:d.id,provider:this.provider.kind,credentialId,credentialLabel:this.vault.getCredential(credentialId)?.label,capabilities:read.capabilities,values:read.values,providers:read.providers}}
  private validate(operation:CameraConfigurationOperation,p:CameraConfigurationProposal){if(operation==='DEVICE_NAME'&&(!p.deviceName?.trim()||p.deviceName.length>64))throw new CameraConfigurationError('Device name must be 1–64 characters.','INVALID_VALUE');if(operation==='NTP'){if(!p.ntp)throw new CameraConfigurationError('NTP settings are required.','INVALID_VALUE');if(!p.ntp.fromDhcp&&!p.ntp.servers.length)throw new CameraConfigurationError('Provide at least one NTP server or select DHCP-provided NTP.','INVALID_NTP');for(const server of p.ntp.servers)if(net.isIP(server)!==4&&!/^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)*[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/i.test(server))throw new CameraConfigurationError(`Invalid NTP server: ${server}`,'INVALID_NTP')}if(operation==='TIME_ZONE'&&(!p.timeZone||!/^(?:UTC(?:[+-]\d{1,2}(?::\d{2})?)?|[A-Z]{3,}[0-9].*)$/.test(p.timeZone)))throw new CameraConfigurationError('Use an explicit camera/ONVIF TZ value; Windows time-zone names are ambiguous.','AMBIGUOUS_TIMEZONE');if(operation==='PASSWORD'&&(!p.newPassword||p.newPassword.length<8))throw new CameraConfigurationError('New password must contain at least 8 characters.','INVALID_PASSWORD');if(operation==='ONVIF_ENABLE'&&typeof p.enabled!=='boolean')throw new CameraConfigurationError('An explicit ONVIF enabled state is required.','INVALID_VALUE');if(operation==='ONVIF_ENABLE'&&this.provider.kind==='ONVIF')throw new CameraConfigurationError('ONVIF enablement requires a supported vendor-native provider.','VENDOR_NATIVE_REQUIRED')}
  async preview(deviceId:string,credentialId:string,operation:CameraConfigurationOperation,proposal:CameraConfigurationProposal,signal?:AbortSignal){this.validate(operation,proposal);const snapshot=await this.inspect(deviceId,credentialId,signal),cap=snapshot.capabilities.find(x=>x.operation===operation);if(!cap||cap.state!=='SUPPORTED'||!cap.editable)throw new CameraConfigurationError(cap?.detail||'Capability is unsupported.','UNSUPPORTED');const planId=crypto.randomUUID(),current=operation==='DEVICE_NAME'?snapshot.values.deviceName:operation==='NTP'?snapshot.values.ntp:operation==='TIME_ZONE'?snapshot.values.timeZone:operation==='ONVIF_ENABLE'?snapshot.values.onvifEnabled:operation==='PASSWORD'?'Saved credential reference':operation==='REBOOT'?'Reachable authenticated device':undefined;const safeProposal=operation==='PASSWORD'?{password:'[secure value submitted]',rememberCredential:proposal.rememberCredential===true}:proposal;const selectedProvider=snapshot.providers?.[operation]||snapshot.provider;const preview:CameraConfigurationPreview={planId,deviceId,operation,provider:selectedProvider,credentialId,credentialLabel:snapshot.credentialLabel,current,proposed:safeProposal,expectedEffect:operation==='REBOOT'?'The camera will temporarily stop responding while it restarts.':operation==='PASSWORD'?'Existing sessions may stop authenticating after the password changes.':'The selected camera setting will be changed.',verificationPlan:operation==='REBOOT'?'Bounded authenticated retries will reverify the same stable device.':operation==='PASSWORD'?'The backend will authenticate with the new password before optionally updating Windows Credential Manager.':operation==='ONVIF_ENABLE'?'The vendor state will be reread; ONVIF availability must then be confirmed.':'The backend will reread the setting and compare it with the proposal.',strongConfirmation:['REBOOT','PASSWORD','ONVIF_ENABLE'].includes(operation),createdAt:new Date().toISOString()};this.plans.set(planId,{preview,proposal:{...proposal,newPassword:undefined}});if(operation==='PASSWORD')this.secrets.set(planId,proposal.newPassword!);return preview}
  async apply(planId:string,confirmed:boolean,signal?:AbortSignal):Promise<CameraConfigurationResult>{const stored=this.plans.get(planId);if(!stored)throw new CameraConfigurationError('A current preview is required.','PREVIEW_REQUIRED');if(!confirmed)throw new CameraConfigurationError('Explicit technician confirmation is required.','CONFIRMATION_REQUIRED');const{preview}=stored,d=this.device(preview.deviceId),credential=await this.credential(preview.credentialId),proposal={...stored.proposal};if(preview.operation==='PASSWORD')proposal.newPassword=this.secrets.get(planId);let applied=false;this.activeOperations++;try{await this.provider.apply(d,credential,preview.operation,proposal,signal);applied=true;const verified=await this.provider.verify(d,credential,preview.operation,proposal,signal);if(verified){if(preview.operation==='PASSWORD'&&proposal.rememberCredential){const ref=this.vault.getCredential(preview.credentialId);await this.vault.saveCredential({id:preview.credentialId,label:ref?.label||`${d.anchor.vendor} credential`,username:credential.username,password:proposal.newPassword!,targetVendor:d.anchor.vendor,deviceIdentity:d.id});this.vault.associate(d.id,preview.credentialId)}if(preview.operation==='PASSWORD')d.activationState='TECHNICIAN_REPORTED_COMPLETE';this.recordEvidence(d,preview.operation);this.db.upsertDevice(d);this.audit(preview,'VERIFIED',true);return{deviceId:d.id,operation:preview.operation,outcome:'VERIFIED',verified:true,message:'The camera setting was applied and verified.',pairAvailable:false}}this.audit(preview,'APPLIED_UNVERIFIED',false);return{deviceId:d.id,operation:preview.operation,outcome:preview.operation==='REBOOT'?'NEEDS_ATTENTION':'APPLIED_UNVERIFIED',verified:false,message:preview.operation==='REBOOT'?'The reboot request was accepted, but the camera did not return within the bounded verification window.':'The write was accepted but the value could not be verified.',pairAvailable:false}}catch(error){const code=(error as CameraConfigurationError).code;this.audit(preview,code==='UNAUTHORIZED'?'AUTHENTICATION_FAILED':applied?'NEEDS_ATTENTION':'FAILED',false);return{deviceId:d.id,operation:preview.operation,outcome:code==='UNAUTHORIZED'?'AUTHENTICATION_FAILED':applied?'NEEDS_ATTENTION':code==='UNSUPPORTED'?'UNSUPPORTED':'FAILED',verified:false,message:(error as Error).message,pairAvailable:false}}finally{this.activeOperations--;this.plans.delete(planId);this.secrets.delete(planId)}}
  hasActiveOperation(){return this.activeOperations>0||[...this.bulk.values()].some(plan=>plan.state==='EXECUTING')}
  cancel(planId:string){if(!this.plans.has(planId))return false;this.plans.delete(planId);this.secrets.delete(planId);return true}
  async createBulkPlan(deviceIds:string[],credentialIds:Record<string,string>,operation:CameraConfigurationOperation,proposal:CameraConfigurationProposal,allowSingleRetry=false){if(deviceIds.length<(allowSingleRetry?1:2))throw new CameraConfigurationError('Select at least two cameras.','SELECTION_REQUIRED');if(!BULK_EXECUTABLE_CONFIG_OPERATIONS.includes(operation))throw new CameraConfigurationError(bulkCapability(operation)?.reason||'This operation is not executable through Bulk Configure.','BULK_OPERATION_NOT_EXECUTABLE');const unique=[...new Set(deviceIds)],batchId=crypto.randomUUID(),items=[] as BulkCameraConfigurationPlan['items'];for(const id of unique){const d=this.db.getDeviceById(id);try{if(!d)throw new CameraConfigurationError('Device not found.','DEVICE_NOT_FOUND');if(d.reachability?.subnetClassification==='LOCAL')throw new CameraConfigurationError('The technician computer cannot be a camera configuration target.','LOCAL_HOST');if(d.reachability?.subnetClassification==='DIFFERENT_SUBNET'||d.status==='DIFFERENT_SUBNET')throw new CameraConfigurationError('Camera is on a Different Network. Pair remains technician-controlled.','DIFFERENT_NETWORK');const credentialId=credentialIds[id]||this.vault.getAssociation(id)||'',preview=await this.preview(id,credentialId,operation,proposal);items.push({deviceId:id,name:d.technician?.name||d.anchor.vendor||id,eligibility:'READY',errors:[],state:'PENDING',preview})}catch(error){const code=error instanceof CameraConfigurationError?error.code:'UNKNOWN',eligibility=code==='UNSUPPORTED'||code==='BULK_OPERATION_NOT_EXECUTABLE'?'UNSUPPORTED':code==='DUPLICATE_AMBIGUOUS'||code==='DIFFERENT_NETWORK'?'NEEDS_ATTENTION':'BLOCKED';items.push({deviceId:id,name:d?.technician?.name||d?.anchor.vendor||id,eligibility,errors:[error instanceof Error?error.message:'Capability could not be established.'],state:eligibility==='UNSUPPORTED'?'UNSUPPORTED':'PENDING'})}}const readyCount=items.filter(x=>x.eligibility==='READY').length,plan:BulkCameraConfigurationPlan={batchId,operation,state:readyCount?'READY':'FAILED',items,readyCount,blockedCount:items.length-readyCount,totalSelected:unique.length,completedCount:0};this.bulk.set(batchId,plan);this.bulkProposals.set(batchId,{...proposal,newPassword:undefined});this.auditBulk(plan,'PLAN_VALIDATED');return structuredClone(plan)}
  getBulk(batchId:string){const batch=this.bulk.get(batchId);return batch?structuredClone(batch):undefined}
  async applyBulk(batchId:string,confirmed:boolean){const plan=this.bulk.get(batchId);if(!plan)throw new CameraConfigurationError('Bulk plan not found.','PLAN_NOT_FOUND');if(!confirmed)throw new CameraConfigurationError('Explicit technician confirmation is required.','CONFIRMATION_REQUIRED');if(plan.state!=='READY')throw new CameraConfigurationError('The batch is not ready for execution.','PLAN_NOT_READY');plan.state='EXECUTING';plan.confirmedAt=new Date().toISOString();plan.startedAt=plan.confirmedAt;plan.completedCount=0;this.auditBulk(plan,'TECHNICIAN_CONFIRMED');let cursor=0;const ready=plan.items.filter(x=>x.eligibility==='READY');const worker=async()=>{while(cursor<ready.length){if(plan.cancellationRequested)break;const item=ready[cursor++];item.state='APPLYING';try{item.result=await this.apply(item.preview!.planId,true);item.state=item.result.verified?'VERIFIED':item.result.outcome==='APPLIED_UNVERIFIED'?'UNKNOWN':item.result.outcome==='NEEDS_ATTENTION'?'NEEDS_ATTENTION':item.result.outcome==='UNSUPPORTED'?'UNSUPPORTED':'FAILED'}catch(error){item.state='FAILED';item.errors.push(error instanceof Error?error.message:'Configuration failed safely.')}finally{plan.completedCount=(plan.completedCount||0)+1;this.auditBulk(plan,'DEVICE_RESULT',{deviceId:item.deviceId,result:item.state,verified:item.result?.verified===true})}}};await Promise.all(Array.from({length:Math.min(this.concurrency,ready.length)},()=>worker()));if(plan.cancellationRequested)for(const item of ready)if(item.state==='PENDING')item.state='CANCELLED';plan.completedAt=new Date().toISOString();plan.state=plan.cancellationRequested?'CANCELLED':plan.items.every(x=>x.state==='VERIFIED')?'COMPLETED':'PARTIAL_FAILURE';this.auditBulk(plan,'BATCH_COMPLETE');return structuredClone(plan)}
  cancelBulk(batchId:string){const plan=this.bulk.get(batchId);if(!plan)return false;if(plan.state==='READY'){plan.state='CANCELLED';for(const i of plan.items)if(i.state==='PENDING')i.state='CANCELLED';this.auditBulk(plan,'CANCELLATION_REQUESTED');return true}if(plan.state==='EXECUTING'){plan.cancellationRequested=true;this.auditBulk(plan,'CANCELLATION_REQUESTED');return true}return false}
  async retryBulk(batchId:string){const plan=this.bulk.get(batchId),proposal=this.bulkProposals.get(batchId);if(!plan||!proposal)throw new CameraConfigurationError('Bulk plan not found.','PLAN_NOT_FOUND');const failed=plan.items.filter(x=>['FAILED','NEEDS_ATTENTION','UNKNOWN'].includes(x.state));if(!failed.length)throw new CameraConfigurationError('No failed or unknown devices are available to retry.','NOTHING_TO_RETRY');return this.createBulkPlan(failed.map(x=>x.deviceId),Object.fromEntries(failed.flatMap(x=>x.preview?[[x.deviceId,x.preview.credentialId]]:[])),plan.operation,proposal,true)}
  private recordEvidence(d:Device,operation:CameraConfigurationOperation){const verified=new Set(d.configurationEvidence?.verifiedOperations||[]);verified.add(operation);d.configurationEvidence={verifiedOperations:[...verified],updatedAt:new Date().toISOString()};const existing=d.configuredState||{inferred:null};d.configuredState={...existing,inferred:verified.size>=2?true:existing.inferred,updatedAt:new Date().toISOString()}}
  private audit(p:CameraConfigurationPreview,result:string,verified:boolean){appStateDb.logAudit({id:crypto.randomUUID(),timestamp:new Date().toISOString(),category:'PROVISIONING',level:result==='FAILED'?'ERROR':'INFO',message:'Camera device configuration.',details:{deviceId:p.deviceId,operation:p.operation,current:p.current,proposed:p.operation==='PASSWORD'?'[redacted]':p.proposed,result,verified,provider:p.provider}});this.db.recordConfigurationHistory(p.deviceId,p.operation,result==='VERIFIED'?'SUCCESS':result==='FAILED'||result==='AUTHENTICATION_FAILED'?'FAILED':'UNKNOWN',{provider:p.provider,verified})}
}
