import React, { useEffect, useState } from 'react';
import { Check, PlusCircle, X } from 'lucide-react';

export interface ManualDevicePayload {
  ipAddress:string; macAddress?:string; manufacturer?:string; model?:string; serialNumber?:string; technicianName?:string; location?:string; notes?:string;
}
interface Props { isOpen:boolean; onClose:()=>void; onSubmit:(payload:ManualDevicePayload)=>Promise<void> }
const empty:ManualDevicePayload={ipAddress:'',macAddress:'',manufacturer:'',model:'',serialNumber:'',technicianName:'',location:'',notes:''};

export const LegacyOnboardModal:React.FC<Props>=({isOpen,onClose,onSubmit})=>{
  const [form,setForm]=useState<ManualDevicePayload>(empty),[submitting,setSubmitting]=useState(false),[error,setError]=useState('');
  useEffect(()=>{if(isOpen){setForm(empty);setError('')}},[isOpen]);
  if(!isOpen)return null;
  const field=(key:keyof ManualDevicePayload,label:string,required=false,placeholder='')=><label className="block text-xs font-semibold text-slate-700 dark:text-slate-300"><span>{label}{required&&<span className="text-rose-500"> *</span>}</span><input required={required} value={form[key]||''} placeholder={placeholder} onChange={event=>setForm(previous=>({...previous,[key]:event.target.value}))} className="mt-1 w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 outline-none placeholder:text-slate-400 focus:border-blue-500 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100"/></label>;
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setSubmitting(true);setError('');try{await onSubmit(Object.fromEntries(Object.entries(form).map(([key,value])=>[key,typeof value==='string'?value.trim():value])) as unknown as ManualDevicePayload);onClose()}catch(reason){setError(reason instanceof Error?reason.message:'Unable to add the device.')}finally{setSubmitting(false)}};
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-3 sm:p-5"><div role="dialog" aria-modal="true" aria-labelledby="manual-device-title" className="flex max-h-[94vh] w-full max-w-2xl flex-col overflow-hidden rounded-xl border border-slate-200 bg-white shadow-2xl dark:border-slate-700 dark:bg-slate-900"><header className="flex items-start justify-between border-b border-slate-200 px-5 py-4 dark:border-slate-800"><div className="flex gap-3"><span className="rounded-lg bg-blue-50 p-2 text-blue-600 dark:bg-blue-950/50 dark:text-blue-300"><PlusCircle className="h-5 w-5"/></span><div><h2 id="manual-device-title" className="font-bold text-slate-900 dark:text-white">Add Device Manually</h2><p className="mt-1 text-xs text-slate-500">Enter only information you know. The device remains Unknown and Not Verified until real evidence is collected.</p></div></div><button type="button" onClick={onClose} aria-label="Close manual device form" className="rounded p-1 text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800"><X className="h-5 w-5"/></button></header><form onSubmit={submit} className="overflow-y-auto p-5"><div className="grid gap-4 sm:grid-cols-2">{field('ipAddress','IP Address',true,'Required')}{field('macAddress','MAC Address (optional)',false,'Unknown')}{field('manufacturer','Manufacturer (optional)',false,'Unknown')}{field('model','Model (optional)',false,'Unknown')}{field('serialNumber','Serial (optional)')}{field('technicianName','Technician Name (optional)')}{field('location','Location (optional)')}<label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 sm:col-span-2"><span>Notes (optional)</span><textarea value={form.notes||''} onChange={event=>setForm(previous=>({...previous,notes:event.target.value}))} rows={3} className="mt-1 w-full resize-y rounded-md border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 outline-none focus:border-blue-500 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100"/></label></div>{error&&<p className="mt-4 rounded-md bg-rose-50 p-2 text-xs text-rose-700 dark:bg-rose-950/40 dark:text-rose-300">{error}</p>}<footer className="mt-5 flex items-center justify-end gap-2 border-t border-slate-200 pt-4 dark:border-slate-800"><button type="button" onClick={onClose} className="rounded-md px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800">Cancel</button><button type="submit" disabled={submitting||!form.ipAddress.trim()} className="inline-flex items-center gap-2 rounded-md bg-blue-600 px-4 py-2 text-sm font-bold text-white hover:bg-blue-700 disabled:cursor-not-allowed disabled:bg-slate-300 disabled:text-slate-500 dark:disabled:bg-slate-700"><Check className="h-4 w-4"/>{submitting?'Adding…':'Add Device'}</button></footer></form></div></div>;
};
