import {ModalViewport} from './ModalViewport.tsx';
import { requestJson } from '../bounded_request.ts';
import React, { useEffect, useState } from 'react';
import { Clock, X } from 'lucide-react';
import type { ProjectHistoryEvent, ProjectHistoryFilter } from '../../shared/project_history.ts';

const filters: Array<{value:ProjectHistoryFilter;label:string}> = [{value:'ALL',label:'All'},{value:'DEVICE',label:'Device'},{value:'VERIFICATION',label:'Verification'},{value:'CONFIGURATION',label:'Configuration'},{value:'PROJECT',label:'Project changes'}];
export function ProjectHistoryList({deviceId}:{deviceId?:string}) {
  const [filter,setFilter]=useState<ProjectHistoryFilter>('ALL'),[events,setEvents]=useState<ProjectHistoryEvent[]>([]),[error,setError]=useState('');
  useEffect(()=>{
    const controller=new AbortController(),query=new URLSearchParams({filter});if(deviceId)query.set('deviceId',deviceId);setEvents([]);setError('');
    void requestJson(`/api/project/history?${query}`,{signal:controller.signal},fetch,5000).then(({response,body})=>{
      if(!response.ok||!body||typeof body!=='object'||!('events' in body)||!Array.isArray(body.events))throw Error();
      if(!controller.signal.aborted){setEvents(body.events);setError('');}
    }).catch(()=>{if(!controller.signal.aborted)setError('Project history could not be loaded.');});
    return()=>controller.abort();
  },[filter,deviceId]);
  return <div className="space-y-3"><div className="flex flex-wrap gap-1">{filters.map(item=><button key={item.value} onClick={()=>setFilter(item.value)} className={`rounded-md border px-2 py-1 text-[11px] font-semibold ${filter===item.value?'border-blue-500 bg-blue-50 text-blue-700 dark:bg-blue-950/40 dark:text-blue-300':'border-slate-200 text-slate-500 dark:border-slate-700'}`}>{item.label}</button>)}</div>{error&&<p className="rounded border border-red-200 bg-red-50 p-3 text-xs text-red-700">{error}</p>}{!error&&events.length===0&&<p className="rounded border border-dashed border-slate-300 p-5 text-center text-xs text-slate-500 dark:border-slate-700">No Project history matches this view.</p>}<ol className="space-y-2">{events.map(event=><li key={event.id} className="rounded-lg border border-slate-200 bg-white p-3 text-xs dark:border-slate-700 dark:bg-slate-950"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-slate-800 dark:text-slate-100">{event.title}</p><p className="mt-1 text-slate-600 dark:text-slate-300">{event.summary}</p></div>{event.result&&<span className="shrink-0 rounded bg-slate-100 px-2 py-0.5 text-[10px] font-bold dark:bg-slate-800">{event.result}</span>}</div><p className="mt-2 flex items-center gap-1 text-[10px] text-slate-500"><Clock className="h-3 w-3"/>{new Date(event.timestamp).toLocaleString()}{event.deviceId&&<span> • Device {event.deviceId}</span>}</p>{event.details&&Object.keys(event.details).some(key=>!['historyType','title','source','result'].includes(key))&&<details className="mt-2 text-[10px] text-slate-500"><summary className="cursor-pointer">Technical details</summary><dl className="mt-1 space-y-1">{Object.entries(event.details).filter(([key])=>!['historyType','title','source','result'].includes(key)).map(([key,value])=><div key={key}><dt className="inline font-semibold">{key.replaceAll('_',' ')}: </dt><dd className="inline break-all">{typeof value==='object'?JSON.stringify(value):String(value)}</dd></div>)}</dl></details>}</li>)}</ol></div>;
}
export function ProjectHistoryModal({open,onClose}:{open:boolean;onClose:()=>void}) { if(!open)return null;return <ModalViewport className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"><section role="dialog" aria-label="Project History" className="flex max-h-[88vh] w-full max-w-2xl flex-col rounded-xl border border-slate-200 bg-slate-50 shadow-xl dark:border-slate-700 dark:bg-slate-900"><header className="flex items-center justify-between border-b border-slate-200 p-4 dark:border-slate-700"><div><h2 className="font-bold">Project History</h2><p className="text-xs text-slate-500">Saved technician-visible Project and device lifecycle events.</p></div><button aria-label="Close Project History" onClick={onClose}><X className="h-5 w-5"/></button></header><div className="modal-body overflow-y-auto p-4"><ProjectHistoryList/></div></section></ModalViewport> }
