import {ModalViewport} from './ModalViewport.tsx';
import React,{useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {ReportSetSnapshot} from '../../shared/report_set.ts';
import {useModalFocus} from '../use_modal_focus.ts';
export function ReportSetPanel({snapshot,error,onClose,onRemove,onClear,onReport}:{snapshot:ReportSetSnapshot;error?:string;onClose:()=>void;onRemove:(id:string)=>Promise<void>;onClear:()=>Promise<void>;onReport:()=>void}){
 const dialog=useRef<HTMLDivElement>(null),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[failure,setFailure]=useState('');
 useModalFocus(true,busy,dialog,onClose);
 const run=async(action:()=>Promise<void>)=>{setBusy(true);setFailure('');try{await action();setConfirm(false)}catch{setFailure('Report membership could not be updated. Retry when the backend is available.')}finally{setBusy(false)}};
 const button='rounded border border-slate-300 px-3 py-2 text-blue-800 hover:bg-blue-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-blue-600 disabled:opacity-50';
 return createPortal(<ModalViewport className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-900/30 p-3"><div ref={dialog} role="dialog" aria-modal="true" aria-label="Report Set" tabIndex={-1} className="flex max-h-[90vh] w-full max-w-2xl flex-col overflow-hidden rounded-xl border border-slate-300 bg-white text-sm text-slate-800 shadow-xl"><header className="flex shrink-0 items-center justify-between border-b p-4"><h2 className="font-bold">Report Set — {snapshot.members.length} members</h2><button className={button} disabled={busy} onClick={onClose}>Close Report Set</button></header><div className="modal-body min-h-0 flex-1 space-y-3 overflow-y-auto p-4"><p>Report membership is independent of the Current List and Project. Snapshots remain here until removed or the backend restarts.</p>{!snapshot.members.length&&<p>No devices have been added to Report Set. Use Add to Report from a device or selection.</p>}{snapshot.members.map(m=><article key={m.id} aria-label={`Report member ${m.device.technician?.name||m.device.anchor.model||m.device.anchor.vendor}`} className="rounded border border-slate-300 p-3"><div className="flex flex-wrap justify-between gap-2"><strong>{m.device.technician?.name||m.device.anchor.model||m.device.anchor.vendor}</strong><span>{m.current?'In Current List':'Retained snapshot — no longer in Current List'}</span></div><p>{m.device.anchor.vendor} · {m.device.anchor.model||'Model unavailable'}</p><p className="font-mono">IP: {m.device.network.ipAddress} · MAC Last 6: {m.macLastSix||'Unknown'}</p><p className="break-all text-xs">MAC: {m.device.anchor.macAddress||'Unknown'} · Serial: {m.device.anchor.serialNumber||'Unknown'} · UUID: {m.device.anchor.onvifEndpointUuid||'Unknown'}</p><p className="text-xs">Snapshot status: {m.device.status} · Captured: {new Date(m.updatedAt).toLocaleString()}</p><button className={button+' mt-2'} disabled={busy} onClick={()=>void run(()=>onRemove(m.id))}>Remove from Report</button></article>)}</div><footer className="shrink-0 space-y-2 border-t bg-slate-50 p-4">{(failure||error)&&<p role="alert">{failure||error}</p>}{confirm?<div><p>Clear all Report Set members? Current List and Project devices remain unchanged.</p><button className={button} disabled={busy} onClick={()=>void run(onClear)}>Confirm Clear Report Set</button><button className={button+' ml-2'} disabled={busy} onClick={()=>setConfirm(false)}>Cancel</button></div>:<div className="flex gap-2"><button className={button} disabled={busy||!snapshot.members.length||Boolean(error)} onClick={onReport}>Create Report</button><button className={button} disabled={busy||!snapshot.members.length} onClick={()=>setConfirm(true)}>Clear Report Set</button></div>}</footer></div></ModalViewport>,document.body);
}
