import {requestJson} from '../bounded_request.ts';
import React,{useState,useEffect}from'react';
import{ArrowLeft,Check,ChevronRight,Columns3,Download,Info,Palette,Settings2,Stethoscope}from'lucide-react';
import{BrowserPreference}from'../../types/index.ts';
import{ApplicationPreferences,DEFAULT_VISIBLE_COLUMNS,MONITORING_CADENCES,TableColumnId,TABLE_COLUMNS}from'../preferences.ts';
export interface UiPreflight{overall:'READY'|'WARNING'|'UNAVAILABLE';version:string;runtime:string;platform?:string;build?:{commit:string|null;dirty:boolean|null;sourceDigest:string|null;runtimeMode:string};checks?:Array<{id:string;label:string;state:'READY'|'WARNING'|'UNAVAILABLE';detail:string;critical:boolean}>}
export interface UiMonitoringStatus{incrementalDiscovery?:{pausedForForeground?:boolean;pausedForSupport?:boolean};enabled:boolean;running:boolean;intervalMs:number;status?:'OFF'|'ACTIVE'|'WAITING'|'DEFERRED'|'UNAVAILABLE'}
interface Props{preferences:ApplicationPreferences;onPreferences:(patch:Partial<Omit<ApplicationPreferences,'version'>>)=>void;monitoring:UiMonitoringStatus;preflight:UiPreflight|null;onClose:()=>void}
type View='ROOT'|'GENERAL'|'COLUMNS'|'APPEARANCE'|'DIAGNOSTICS'|'ABOUT';
const title=(value:string)=>value[0]+value.slice(1).toLowerCase(),labels:Record<TableColumnId,string>={NAME:'Name',STATUS:'Status',IP:'IP',LAST_6:'Last 6',CONFIGURED:'Configured',SERIAL:'Serial',NOTES:'Notes'},browserLabels:Record<BrowserPreference,string>={SYSTEM:'System Default',EDGE:'Microsoft Edge',CHROME:'Google Chrome',EMBEDDED:'Embedded'};
export const SettingsMenu:React.FC<Props>=({preferences,onPreferences,monitoring,preflight:initialPreflight,onClose})=>{
 const[preflight,setPreflight]=useState(initialPreflight);useEffect(()=>setPreflight(initialPreflight),[initialPreflight]);
 const[view,setView]=useState<View>('ROOT'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirmation,setConfirmation]=useState('');
 const support=async()=>{setBusy(true);setError('');setConfirmation('');try{const response=await fetch('http://localhost:3001/api/system/support-bundle');if(!response.ok)throw Error('Support bundle is unavailable.');const url=URL.createObjectURL(await response.blob()),anchor=document.createElement('a');anchor.href=url;anchor.download='CCTV_Safe_Support_Bundle.json';anchor.click();URL.revokeObjectURL(url);setConfirmation('Support bundle created. Credentials and passwords are excluded.')}catch(reason){setError(reason instanceof Error?reason.message:'Support bundle is unavailable.')}finally{setBusy(false)}};
 const refresh=async()=>{setBusy(true);setError('');try{const {response,body}=await requestJson('http://localhost:3001/api/system/preflight?refresh=1',{},fetch,30000);if(!response.ok||!isUiPreflight(body))throw Error();setPreflight(body);}catch{setError('Field readiness could not be refreshed. Check the backend and retry. Previous results may be stale.');}finally{setBusy(false)}};
 const nav=(next:View,label:string,Icon:React.ComponentType<{className?:string}>)=><button onClick={()=>setView(next)} className="!flex h-11 w-full items-center gap-2.5 px-3 py-0"><Icon className="h-4 w-4 text-slate-500"/><span className="flex-1 truncate text-left">{label}</span><ChevronRight className="h-4 w-4 text-slate-400"/></button>;
 const header=(label:string)=><div className="flex h-10 items-center border-b border-slate-200 px-1 dark:border-slate-700"><button aria-label="Back to Settings" onClick={()=>setView('ROOT')} className="!flex !w-auto items-center gap-1 !px-2 !py-1.5"><ArrowLeft className="h-3.5 w-3.5"/>Settings</button><span className="ml-auto pr-2 text-xs font-semibold">{label}</span></div>;
 const toggle=(checked:boolean,action:()=>void,label:string)=><button type="button" role="switch" aria-checked={checked} aria-label={label} onClick={action} className={`!h-5 !w-9 rounded-full !p-0 ${checked?'bg-blue-600':'bg-slate-300 dark:bg-slate-700'}`}><span className={`block h-4 w-4 rounded-full bg-white transition-transform ${checked?'translate-x-4':'translate-x-0.5'}`}/></button>;
 const changeColumn=(column:TableColumnId)=>onPreferences({visibleColumns:preferences.visibleColumns.includes(column)?preferences.visibleColumns.filter(item=>item!==column):TABLE_COLUMNS.filter(item=>item===column||preferences.visibleColumns.includes(item))});
 return <div role="menu" aria-label="Settings" className="ui-menu w-72 overflow-hidden p-0 sm:w-80">
  {view==='ROOT'&&<div className="p-1">{nav('GENERAL','General',Settings2)}{nav('COLUMNS','Device Table / Columns',Columns3)}{nav('APPEARANCE','Appearance',Palette)}{nav('DIAGNOSTICS','Diagnostics & Support',Stethoscope)}{nav('ABOUT','About',Info)}</div>}
  {view==='GENERAL'&&<>{header('General')}<div className="space-y-3 p-3 text-xs"><div className="flex items-center justify-between"><div><strong>Monitoring</strong><p className="text-[10px] text-slate-500">{monitoring.status?title(monitoring.status):monitoring.running?'Active':monitoring.enabled?'Waiting':'Off'}</p></div>{toggle(preferences.monitoringEnabled,()=>onPreferences({monitoringEnabled:!preferences.monitoringEnabled}),'Monitoring')}</div><label className="block"><span className="font-semibold">Monitoring cadence</span><select value={preferences.monitoringCadenceMs} onChange={event=>onPreferences({monitoringCadenceMs:Number(event.target.value)as ApplicationPreferences['monitoringCadenceMs']})} className="mt-1 block w-full rounded border border-slate-200 bg-white p-1.5 dark:border-slate-700 dark:bg-slate-900">{MONITORING_CADENCES.map(ms=><option key={ms} value={ms}>{ms===120000?'2 minutes':`${ms/1000} seconds`}</option>)}</select></label><div className="flex items-center justify-between"><div><strong>New-device notifications</strong><p className="text-[10px] text-slate-500">Genuine newly discovered devices only</p></div>{toggle(preferences.newDeviceNotifications,()=>onPreferences({newDeviceNotifications:!preferences.newDeviceNotifications}),'New-device notifications')}</div><label className="block"><span className="font-semibold">Browser preference</span><select value={preferences.browserPreference} onChange={event=>onPreferences({browserPreference:event.target.value as BrowserPreference})} className="mt-1 block w-full rounded border border-slate-200 bg-white p-1.5 dark:border-slate-700 dark:bg-slate-900">{(['SYSTEM','EDGE','CHROME','EMBEDDED']as BrowserPreference[]).map(browser=><option key={browser} value={browser}>{browserLabels[browser]}</option>)}</select></label></div></>}
  {view==='COLUMNS'&&<>{header('Device Table / Columns')}<div className="p-3 text-xs"><div className="space-y-1">{TABLE_COLUMNS.map(column=><label key={column} className="flex items-center gap-2 py-1"><input type="checkbox" checked={preferences.visibleColumns.includes(column)} onChange={()=>changeColumn(column)}/><span>{labels[column]}</span></label>)}</div><button onClick={()=>onPreferences({visibleColumns:[...DEFAULT_VISIBLE_COLUMNS]})} className="mt-2 !w-full rounded border border-slate-300 px-2 py-1.5 font-semibold dark:border-slate-700">Reset to Defaults</button><p className="mt-2 text-[10px] text-slate-500">Selection and Actions remain visible for safe workflows.</p></div></>}
  {view==='APPEARANCE'&&<>{header('Appearance')}<div className="p-1">{(['LIGHT','DARK','SYSTEM']as const).map(option=><button key={option} role="menuitemradio" aria-checked={preferences.appearance===option} onClick={()=>{onPreferences({appearance:option});onClose()}} className="!flex h-10 items-center gap-2 px-3 py-0"><span className="w-4">{preferences.appearance===option&&<Check className="h-4 w-4 text-blue-600"/>}</span><span>{title(option)}</span></button>)}</div></>}
  {view==='DIAGNOSTICS'&&<>{header('Diagnostics & Support')}<div className="max-h-80 overflow-y-auto p-3 text-xs"><div className="flex items-center justify-between"><strong>Environment status</strong><span className={`rounded px-2 py-0.5 text-[10px] font-bold ${preflight?.overall==='READY'?'bg-emerald-100 text-emerald-700':preflight?.overall==='WARNING'?'bg-amber-100 text-amber-700':'bg-rose-100 text-rose-700'}`}>{preflight?title(preflight.overall):'Checking'}</span></div><p className="mt-1 text-slate-500">Field Readiness: check this laptop before field work. Warnings apply to the named capability; they do not disable Scan.</p><button disabled={busy} onClick={refresh} className="mt-2 rounded border border-slate-300 px-2 py-1.5 disabled:opacity-50">{busy?'Checking readiness...':'Refresh Field Readiness'}</button><div className="mt-2 space-y-2">{preflight?.checks?.map(check=><div key={check.id} className="rounded border border-slate-200 p-2 dark:border-slate-700"><div className="flex justify-between gap-2 font-semibold"><span>{check.label}</span><span>{title(check.state)}</span></div><p className="mt-0.5 text-[10px] text-slate-500">{check.detail}</p></div>)}</div><button disabled={busy} onClick={support} className="mt-3 !flex w-full items-center justify-center gap-2 rounded bg-blue-600 px-3 py-2 font-bold text-white disabled:bg-slate-300"><Download className="h-3.5 w-3.5"/>{busy?'Preparing…':'Download Safe Support Bundle'}</button><p className="mt-2 text-[10px] text-slate-500">Excludes credentials, authorization material, project notes, cookies, and security audit entries.</p>{confirmation&&<p className="mt-2 text-emerald-600">{confirmation}</p>}{error&&<p className="mt-2 text-rose-600">{error}</p>}</div></>}
  {view==='ABOUT'&&<>{header('About')}<div className="space-y-2 p-3 text-xs"><div><strong>CCTV Network Assistant</strong><div className="text-slate-500">Version: {preflight?.version||'1.6.0'}</div></div><div><strong>Environment status: {preflight?title(preflight.overall):'Checking'}</strong><div className="text-slate-500">Runtime: {preflight?.runtime||'Pending'}{preflight?.platform?` on ${preflight.platform}`:''}</div></div>{preflight?.build&&<p className="break-all">Build: {preflight.build.commit||'Commit unavailable'}{preflight.build.dirty===true?' (working changes)':''}<br/>Source: {preflight.build.sourceDigest||'Unavailable'}<br/>Mode: {preflight.build.runtimeMode}</p>}{preflight?.checks?.filter(check=>check.state!=='READY').map(check=><p key={check.id} className="rounded bg-amber-50 p-2 text-[10px] text-amber-800 dark:bg-amber-950/30 dark:text-amber-200">{check.label}: {check.detail}</p>)}</div></>}
 </div>
};

export function isUiPreflight(value:unknown):value is UiPreflight {
 if(!value||typeof value!=='object')return false;const v=value as UiPreflight;
 return ['READY','WARNING','UNAVAILABLE'].includes(v.overall)&&typeof v.version==='string'&&typeof v.runtime==='string'&&(!v.build||((v.build.commit===null||typeof v.build.commit==='string')&&(v.build.sourceDigest===null||typeof v.build.sourceDigest==='string')&&typeof v.build.runtimeMode==='string'))&&Array.isArray(v.checks)&&v.checks.every(c=>c&&typeof c.id==='string'&&typeof c.label==='string'&&typeof c.detail==='string'&&['READY','WARNING','UNAVAILABLE'].includes(c.state));
}
