// UI-only Vite and the actual isolated Report Set/report HTTP routes. No physical operations.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),{mock}=require('./advanced_scan.cjs');let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++;console.log('PASS: '+n)};
(async()=>{let failRemoval=false;
 const {default:express}=await import('express'),{createServer}=await import('node:http'),{SiteProjectDatabase}=await import('../../core/storage/project_db.ts'),{ReportSet}=await import('../../core/reporting/report_set.ts'),{createReportSetRouter}=await import('../../server/report_set_routes.ts'),{createReportRouter}=await import('../../server/report_routes.ts'),{TaskManager}=await import('../../core/tasks/task_manager.ts'),{taskHttpIntegration}=await import('../../server/task_routes.ts');
 const db=new SiteProjectDatabase(),set=new ReportSet(()=>db.getSession()),tasks=new TaskManager(),requests=[];db.createNewProject('Bulk actions');const camera=(id)=>({id,anchor:{macAddress:id==='A'?'00:50:f9:63:fb:0f':id==='B'?'e4:30:22:cd:68:85':null,onvifEndpointUuid:'uuid-'+id,vendor:'Fixture',model:'Camera',serialNumber:'Serial-'+id},technician:{name:id,notes:'Installation notes'},network:{ipAddress:'192.168.1.100',subnetMask:'255.255.255.0',port:80,protocol:'ONVIF'},status:'ONLINE',sessionVerification:'VERIFIED',discoveredPhase:3,firstSeenAt:new Date().toISOString(),lastSeenAt:new Date().toISOString()});['A','B','Excluded'].forEach(id=>db.upsertDevice(camera(id)));
 const app=express();app.use(express.json());app.use(taskHttpIntegration(tasks,{refresh:()=>{},monitoring:()=>({}),bulk:()=>undefined,cancelBulk:()=>false,cancelReverify:()=>false}).middleware);app.use('/api/report-set',createReportSetRouter(set));app.use('/api/reports',createReportRouter({getSession:()=>db.getSession(),getAuditLogs:()=>[],reportSet:set}));const server=createServer(app);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({channel:'msedge',headless:true});try{
  const page=await browser.newPage({viewport:{width:1280,height:800},timezoneId:'America/New_York'}),errors=[];page.on('pageerror',e=>errors.push(String(e)));await mock(page);
  await page.exposeFunction('reportBackend',async(path,body,method)=>{requests.push({path,body,method});if(path.endsWith('/remove-current')&&failRemoval)return{status:500,body:{error:'Fixture removal failure'}};if(path==='/api/bulk/network/plan'||path==='/api/bulk/configuration/plan')return{status:400,body:{error:'Fixture: credentials required'}};if(path==='/api/reports/preview')body.generatedAt='2026-09-20T03:59:00Z';if(path.startsWith('/api/report-set')||path.startsWith('/api/reports/')){const response=await fetch(base+path,{method,headers:{'Content-Type':'application/json'},body:method==='POST'?JSON.stringify(body):undefined});return{status:response.status,headers:Object.fromEntries(response.headers.entries()),bytes:Array.from(new Uint8Array(await response.arrayBuffer()))}}if(path==='/api/project/session')return{body:db.getSession()};if(path==='/api/project')return{body:db.getProject()};if(path==='/api/tasks')return{body:tasks.snapshot()};if(path.endsWith('/remove-current')){set.snapshot();db.removeDeviceFromCurrentList(decodeURIComponent(path.split('/')[3]));return{body:db.getSession()}}if(path==='/api/pair/eligibility')return{body:db.getDevices()[0]};return{body:{}}});
  await page.addInitScript(()=>{const old=fetch;window.fetch=async(url,o={})=>{const path=new URL(url,location.href).pathname;if(path.startsWith('/api/bulk/')||path.startsWith('/api/report-set')||path.startsWith('/api/reports/')||['/api/project/session','/api/project','/api/tasks','/api/pair/eligibility'].includes(path)||path.endsWith('/remove-current')){const r=await reportBackend(path,o.body?JSON.parse(o.body):{},o.method||'GET');return new Response(r.bytes?new Uint8Array(r.bytes):JSON.stringify(r.body),{status:r.status||200,headers:r.headers||{'Content-Type':'application/json'}})}return old(url,o)}});
  await page.goto('http://127.0.0.1:5179/src/test/browser/advanced_scan.html?app');
  set.add(['Excluded']);
  const row=id=>page.locator('tbody tr').filter({has:page.getByRole('button',{name:'Actions for '+id,exact:true})});
  const bar=page.getByRole('region',{name:'Selected devices',exact:true}),menu=page.getByRole('menu',{name:'Configure selected devices',exact:true});
  await row('A').getByRole('checkbox').check();await bar.waitFor();check((await bar.textContent()).includes('1 device(s) selected'),'one-device selection');
  for(const name of ['Diagnose','Configure','Create Report','Remove'])check(await bar.getByRole('button',{name,exact:true}).count()===1,'primary '+name+' label');
  for(const name of ['Diagnose Selected','Configure Network','Configure Settings','Remove Selected'])check(await bar.getByRole('button',{name,exact:true}).count()===0,'old '+name+' label absent');
  await bar.getByRole('button',{name:'Configure',exact:true}).click();check(await menu.getByRole('menuitem',{name:'Network Configuration',exact:true}).isDisabled()&&await menu.getByRole('menuitem',{name:'Device Configuration',exact:true}).isDisabled(),'one-device bulk configuration limit preserved');await page.keyboard.press('Escape');check(await bar.getByRole('button',{name:'Configure',exact:true}).evaluate(el=>el===document.activeElement),'Escape returns focus');
  await row('B').getByRole('checkbox').check();check((await bar.textContent()).includes('2 device(s) selected'),'same-IP identities independently selected');db.getDeviceById('A').network.ipAddress='192.168.1.120';await page.evaluate(project=>__test.emit({type:'DEVICE_DISCOVERED',data:{project}}),{...db.getProject(),devices:[...db.getProject().devices].reverse()});check(await row('A').getByRole('checkbox').isChecked()&&await row('B').getByRole('checkbox').isChecked(),'selection survives IP update and table reordering');await bar.getByRole('button',{name:'Configure',exact:true}).focus();await page.keyboard.press('Enter');await menu.waitFor();check(await menu.getByRole('menuitem',{name:'Network Configuration',exact:true}).evaluate(el=>el===document.activeElement),'keyboard opens Configure and focuses first choice');await page.keyboard.press('ArrowDown');check(await menu.getByRole('menuitem',{name:'Device Configuration',exact:true}).evaluate(el=>el===document.activeElement),'arrow navigation focuses Device Configuration');check(await menu.evaluate(el=>getComputedStyle(el).backgroundColor==='rgb(255, 255, 255)'),'Configure uses light surface');check(await menu.getByRole('menuitem',{name:'Device Configuration',exact:true}).evaluate(el=>getComputedStyle(el).outlineStyle!=='none'),'keyboard focus visible');
  await page.keyboard.press('Enter');await page.getByRole('heading',{name:'Bulk Device Configuration',exact:true}).waitFor();await page.getByRole('button',{name:'Build & Validate Plan',exact:true}).click();await page.getByText('Fixture: credentials required', {exact:true}).waitFor();check(requests.find(r=>r.path==='/api/bulk/configuration/plan').body.deviceIds.slice().sort().join(',')==='A,B','Device choice uses existing bulk engine with stable IDs');check(await page.getByRole('button',{name:'Apply and Verify',exact:true}).count()===0,'blocked Device configuration cannot appear successful');await page.locator('.modal-viewport').getByRole('button').first().click();
  await bar.getByRole('button',{name:'Configure',exact:true}).click();await menu.getByRole('menuitem',{name:'Network Configuration',exact:true}).click();await page.getByRole('button',{name:'Build & Validate Plan',exact:true}).click();await page.getByText('Fixture: credentials required',{exact:true}).waitFor();check(requests.find(r=>r.path==='/api/bulk/network/plan').body.deviceIds.slice().sort().join(',')==='A,B','Network choice uses existing bulk engine with stable IDs');check(await page.getByRole('button',{name:'Apply Network Changes',exact:true}).count()===0,'blocked Network configuration remains blocked');await page.getByRole('button',{name:'Cancel',exact:true}).click();
  const members=JSON.stringify(set.snapshot().members.map(m=>m.id));await bar.getByRole('button',{name:'Create Report',exact:true}).click();const report=page.getByRole('dialog');await report.locator('tbody tr').first().waitFor();check(await report.getByLabel(/^Scope/).inputValue()==='SELECTED'&&await report.locator('tbody tr').count()===2,'Create Report uses selected identities');check(JSON.stringify(set.snapshot().members.map(m=>m.id))===members&&!requests.some(r=>r.path==='/api/report-set/add'),'Create Report preserves Report Set without implicit additions');await report.getByRole('button').first().click();
  await row('B').getByRole('checkbox').uncheck();const before=requests.length;let confirmation='';page.once('dialog',async d=>{confirmation=d.message();await d.dismiss()});await bar.getByRole('button',{name:'Remove',exact:true}).click();check(requests.length===before&&db.getProject().devices.length===3,'Remove cancel changes nothing');check(confirmation.includes('Current List')&&confirmation.includes('Project and Report Set membership stay unchanged')&&confirmation.includes('No physical camera'),'Remove confirmation explains session-only boundary');
  failRemoval=true;page.once('dialog',d=>d.accept());await bar.getByRole('button',{name:'Remove',exact:true}).click();await page.getByRole('status').filter({hasText:'Removed 0 of 1 selected'}).waitFor();check(db.getProject().devices.length===3&&await row('A').getByRole('checkbox').isChecked(),'failed removal reports failure and retains selection');failRemoval=false;
  page.once('dialog',d=>d.accept());await bar.getByRole('button',{name:'Remove',exact:true}).click();await row('A').waitFor({state:'detached'});check(await row('B').count()===1&&db.getSuppressionDiagnostics().count===1,'one same-IP removal suppresses only selected identity');db.restoreDiscoveredDevice(db.getDeviceById('A'));check(!db.getProject().devices.some(d=>d.id==='A'),'normal rediscovery preserves suppression');
  await row('B').getByRole('checkbox').check();await row('Excluded').getByRole('checkbox').check();page.once('dialog',d=>d.accept());await bar.getByRole('button',{name:'Remove',exact:true}).click();await row('Excluded').waitFor({state:'detached'});check(requests.filter(r=>r.path.endsWith('/remove-current')).slice(1).map(r=>decodeURIComponent(r.path.split('/')[3])).join(',')==='A,B,Excluded','bulk removal uses each captured stable ID');check(db.getProjectMemberDevices().length===3,'saved Project members retained');check(JSON.stringify(set.snapshot().members.map(m=>m.id))===members,'removal preserves Report Set');check(!requests.some(r=>r.path.endsWith('/remove-project')||r.path.endsWith('/apply')||r.path.includes('/credentials/')),'no physical or Project removal side effects');check(!errors.length,'no browser runtime errors');console.log(`Phase 13B bulk actions: ${passed} passed, 0 failed, 0 skipped`);
 }finally{await browser.close();await new Promise(resolve=>server.close(resolve))}
})().catch(e=>{console.error(e);process.exitCode=1});
