const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++;console.log('PASS: '+n)};
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:1280,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{window.__requests=[];window.fetch=async(url,options={})=>{window.__requests.push({path:String(url),method:options.method||'GET'});return new Response(JSON.stringify(String(url).endsWith('/credentials')?{references:[{id:'saved',label:'Technician saved',usernameHint:'t***'}],selectedCredentialId:'saved'}:{readiness:{status:'UNKNOWN'}}),{headers:{'Content-Type':'application/json'}})}});
 // Keep all test navigation local, including any accidentally exposed camera endpoint.
 await page.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());
 const load=async(query)=>{await page.goto('http://127.0.0.1:5179/src/test/browser/credential_guidance.html?'+query);await page.getByRole('option',{name:'Technician saved (t***)',exact:true}).waitFor({state:'attached'});await page.getByText('Factory credential suggestions',{exact:true}).click()};
 await load('vendor=Unknown&model=Unknown');
 check(await page.getByRole('heading',{name:'Common legacy camera credentials — generic historical references'}).isVisible(),'generic heading separated and explicit');
 const cards=page.getByRole('article');check(await cards.count()===2,'two independent historical cards');
 check(await cards.filter({hasText:'Not verified credentials.'}).count()===2,'historical references are not verified');
 check(await page.getByRole('option',{name:'Technician saved (t***)',exact:true}).count()===1,'saved reference remains separate');
 const before=await page.evaluate(()=>JSON.stringify(__guidanceDevice));const count=await page.evaluate(()=>__requests.length);
 await page.getByLabel('Remember this credential').check();
 const button=cards.first().getByRole('button',{name:'Use Credentials',exact:true});await page.keyboard.press('Tab');await button.focus();
 check(await button.evaluate(el=>el===document.activeElement&&getComputedStyle(el).outlineStyle!=='none'),'keyboard focus visible');
 await page.keyboard.press('Enter');
 const first=await page.getByLabel('Password',{exact:true}).inputValue();
 check(first.length>0&&await page.getByLabel('Username',{exact:true}).inputValue()==='root','keyboard selection fills documented fields');
 await cards.nth(1).getByRole('button',{name:'Use Credentials',exact:true}).click();
 check((await page.getByLabel('Password',{exact:true}).inputValue())!==first,'second historical suggestion selectable independently');
 check(await page.getByLabel('Password',{exact:true}).getAttribute('type')==='password','selected password stays masked');
 check(!await page.getByLabel('Remember this credential').isChecked(),'selection clears save intent');
 check(await page.getByRole('button',{name:'Update',exact:true}).isDisabled(),'selection does not overwrite saved reference');
 check(await page.evaluate(()=>__requests.length)===count,'selection sends no submit authentication save or verification request');
 check(await page.evaluate(()=>JSON.stringify(__guidanceDevice))===before,'selection leaves identity status Configured and device evidence unchanged');
 check(await cards.first().getByRole('link').getAttribute('href')==='https://www.axis.com/dam/public/c3/3a/f3/axis-2120-users-manual-en-US-30349.pdf','existing source destination preserved');
 check(await cards.first().evaluate(el=>{const s=getComputedStyle(el);return s.backgroundColor==='rgb(255, 255, 255)'&&s.color==='rgb(30, 41, 59)'}),'light-theme guidance uses readable dark text on white');
 await load('vendor=Unknown&model=QND-7082R');
 check(await cards.count()===1&&await page.getByText('First login: password creation required',{exact:true}).isVisible(),'QND exact first-login guidance suppresses generic');
 check(await page.getByRole('button',{name:'Use Credentials',exact:true}).count()===0,'QND offers no invented password');
 await page.getByRole('button',{name:'Use Username',exact:true}).click();
 check(await page.getByLabel('Password',{exact:true}).inputValue()==='','first-login selection leaves empty password');
 check(await page.getByLabel('Username',{exact:true}).inputValue()==='admin','first-login selection supplies supported username');
 await load('vendor=UNV');
 check(await cards.getByRole('link').count()===0&&await cards.getByText(/no verified link available/).isVisible(),'text provenance with no fabricated URL');
 await page.getByLabel('Password',{exact:true}).fill('technician-input');await page.getByRole('button',{name:'Use Username',exact:true}).click();
 check(await page.getByLabel('Password',{exact:true}).inputValue()==='technician-input','username-only guidance preserves technician input');
 check(await page.evaluate(()=>__requests.every(r=>r.method==='GET')),'username-only guidance cannot authenticate or save');
 await load('vendor=Hikvision&firmware=5.2.0');
 check(await cards.getByText(/Applicability: Product-family-specific/).isVisible(),'firmware evidence reaches actual Camera Access guidance');
 check(errors.length===0,'no browser runtime errors');
 console.log(`Credential guidance browser: ${passed} passed, 0 failed, 0 skipped`);
 }finally{await browser.close()}})().catch(e=>{console.error(e.message);process.exitCode=1});
