// UI-only Vite and the actual isolated Report Set/report HTTP routes. No physical operations.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),{mock}=require('./advanced_scan.cjs');let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++;console.log('PASS: '+n)};
(async()=>{
 const {default:express}=await import('express'),{createServer}=await import('node:http'),{SiteProjectDatabase}=await import('../../core/storage/project_db.ts'),{ReportSet}=await import('../../core/reporting/report_set.ts'),{createReportSetRouter}=await import('../../server/report_set_routes.ts'),{createReportRouter}=await import('../../server/report_routes.ts'),{TaskManager}=await import('../../core/tasks/task_manager.ts'),{taskHttpIntegration}=await import('../../server/task_routes.ts'),{createCurrentListRouter}=await import('../../server/current_list_routes.ts'),{Phase4IdentityReconciliation}=await import('../../core/engine/phase4_reconcile.ts');
 const db=new SiteProjectDatabase(),set=new ReportSet(()=>db.getSession()),tasks=new TaskManager(),requests=[];db.startQuickWork();const camera=(id)=>({id,anchor:{macAddress:id==='A'?'00:50:f9:63:fb:0f':id==='B'?'e4:30:22:cd:68:85':null,onvifEndpointUuid:'uuid-'+id,vendor:'Fixture',model:'Camera',serialNumber:'Serial-'+id},technician:{name:id,notes:'Installation notes'},network:{ipAddress:'192.168.1.100',subnetMask:'255.255.255.0',port:80,protocol:'ONVIF'},status:'ONLINE',sessionVerification:'VERIFIED',discoveredPhase:3,firstSeenAt:new Date().toISOString(),lastSeenAt:new Date().toISOString()});['A','B','Excluded'].forEach(id=>db.upsertDevice(camera(id)));
 const app=express();app.use(express.json());app.use(taskHttpIntegration(tasks,{refresh:()=>{},monitoring:()=>({}),bulk:()=>undefined,cancelBulk:()=>false,cancelReverify:()=>false}).middleware);app.use('/api/current-list',createCurrentListRouter(db,()=>{}));app.use('/api/report-set',createReportSetRouter(set));app.use('/api/reports',createReportRouter({getSession:()=>db.getSession(),getAuditLogs:()=>[],reportSet:set}));const server=createServer(app);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({channel:'msedge',headless:true});try{
  const page=await browser.newPage({viewport:{width:1280,height:800}}),errors=[];page.on('pageerror',e=>errors.push(String(e)));await mock(page);
  await page.exposeFunction('reportBackend',async(path,body,method)=>{requests.push({path,body,method});if(path.startsWith('/api/current-list')||path.startsWith('/api/report-set')||path.startsWith('/api/reports/')){const response=await fetch(base+path,{method,headers:{'Content-Type':'application/json'},body:method==='POST'?JSON.stringify(body):undefined});return{status:response.status,headers:Object.fromEntries(response.headers.entries()),bytes:Array.from(new Uint8Array(await response.arrayBuffer()))}}if(path==='/api/project/session')return{body:db.getSession()};if(path==='/api/project')return{body:db.getProject()};if(path==='/api/tasks')return{body:tasks.snapshot()};if(path.endsWith('/remove-current')){set.snapshot();db.removeDeviceFromCurrentList(decodeURIComponent(path.split('/')[3]));return{body:{...db.getSession(),removal:{message:'Removed from Current List. This camera stays hidden for this backend session until you choose Rediscover manually removed cameras. Project and Report Set membership are unchanged.'}}}}if(path==='/api/pair/eligibility')return{body:db.getDevices()[0]};return{body:{}}});
  await page.addInitScript(()=>{const old=fetch;window.fetch=async(url,o={})=>{const path=new URL(url,location.href).pathname;if(path.startsWith('/api/current-list')||path.startsWith('/api/report-set')||path.startsWith('/api/reports/')||['/api/project/session','/api/project','/api/tasks','/api/pair/eligibility'].includes(path)||path.endsWith('/remove-current')){const r=await reportBackend(path,o.body?JSON.parse(o.body):{},o.method||'GET');return new Response(r.bytes?new Uint8Array(r.bytes):JSON.stringify(r.body),{status:r.status||200,headers:r.headers||{'Content-Type':'application/json'}})}return old(url,o)}});
  await page.goto('http://127.0.0.1:5179/src/test/browser/advanced_scan.html?app');
  const row=id=>page.locator('tbody tr').filter({has:page.getByRole('button',{name:'Actions for '+id,exact:true})}),panel=page.getByRole('dialog',{name:'Report Set',exact:true});
  const action=async(id,name)=>{await page.getByRole('button',{name:'Actions for '+id,exact:true}).click();await page.getByRole('menuitem',{name,exact:true}).click()};
  const openSet=async()=>{await page.getByRole('button',{name:'Tools',exact:true}).click();await page.getByRole('button',{name:/^Report Set \(/}).click();await panel.waitFor()};
  const publish=async()=>page.evaluate(session=>{const s=__test.sockets.at(-1);s.readyState=1;s.onopen?.(new Event('open'));__test.emit({type:'PROJECT_SESSION_CHANGED',data:{session}})},db.getSession());

  await page.getByRole('button',{name:'Scan choices',exact:true}).click();check(await page.getByRole('button',{name:/^Rediscover manually removed cameras/}).isDisabled(),'T54 no suppression disables Rediscover');await page.getByRole('button',{name:'Scan choices',exact:true}).click();
  await action('A','Add to Report');await row('A').getByText('In Report',{exact:true}).waitFor();await action('A','Remove Device');const confirmation=page.getByRole('alertdialog');check((await confirmation.textContent()).includes('backend session')&&(await confirmation.textContent()).includes('Project and Report Set membership stay unchanged'),'T51 confirmation describes independent session hiding');await confirmation.getByRole('button',{name:'Remove Device',exact:true}).click();await row('A').waitFor({state:'detached'});check(await row('B').count()===1&&db.getSuppressionDiagnostics().count===1,'T01/T02/T29 hide one same-IP identity');check(await page.getByText(/This camera stays hidden for this backend session/).isVisible(),'T52 post-removal Rediscover feedback');
  await Phase4IdentityReconciliation.execute(db);await publish();await row('B').getByRole('button',{name:'Duplicate IP',exact:true}).click();const assistant=page.getByRole('dialog',{name:'Duplicate IP Assistant'});await assistant.getByText(/Hidden from Current List/).waitFor();check(await assistant.locator('article').count()===3,'T31 hidden participant remains explicitly labelled in collision evidence');await assistant.getByRole('button',{name:'Close Duplicate Assistant'}).click();
  const discover=()=>{const a=camera('A');a.network.ipAddress='192.168.1.120';const stored=db.upsertDevice(a,'DEVICE_ADDED',true);db.restoreDiscoveredDevice(stored)};for(let i=0;i<3;i++)discover();await publish();check(await row('A').count()===0&&set.snapshot().members.length===1,'T04/T05/T10/T23 repeated moved-camera observations stay hidden');
  await page.reload();await row('B').waitFor();check(await row('A').count()===0,'T42 frontend reload preserves backend suppression');await page.getByRole('button',{name:'Scan choices',exact:true}).click();const rediscover=page.getByRole('button',{name:/^Rediscover manually removed cameras/});check(await rediscover.isEnabled()&&(await rediscover.textContent()).includes('Manually removed: 1'),'T53 logical Scan menu action and count');await rediscover.focus();await page.keyboard.press('Enter');await page.getByRole('button',{name:'Stop',exact:true}).waitFor();check(db.getSuppressionDiagnostics().count===0,'T33/T55 keyboard Rediscover clears registry');check(await row('A').count()===0,'T34 action never fabricates stale row');check(await page.evaluate(()=>__test.requests.filter(r=>r.path==='/api/discovery/start').length)===1,'Rediscover requests exactly one existing normal scan');check(set.snapshot().members.length===1&&tasks.snapshot().tasks.length===0,'T39/T59 retained reports and no removal Tasks');
  discover();await publish();await row('A').waitFor();check((await row('A').textContent()).includes('192.168.1.120'),'T35/T36 fresh moved-camera evidence returns');await page.evaluate(()=>{__test.advance('MANUAL','COMPLETED');__test.emit({type:'FOREGROUND_SCAN_STATE',data:{foreground:__test.foreground}})});await page.getByRole('button',{name:'Scan',exact:true}).waitFor();
  db.createNewProject('Project');db.upsertDevice(camera('A'));db.exportProjectJsonForSave();await publish();await action('A','Remove from Current List');await page.getByRole('alertdialog').getByRole('button',{name:'Remove Device',exact:true}).click();await row('A').waitFor({state:'detached'});check(db.getProjectMemberDevices().length===1&&!db.getSession().dirty,'T18/T19 project remains saved and clean');check(set.snapshot().members.length===1,'T48 current removal does not call Remove from Report');
  const calls=[...requests,...await page.evaluate(()=>__test.requests)];check(!calls.some(r=>/credentials|configuration|pair\/(confirm|restore)/.test(r.path)),'T56-T58 no camera/adapter/credential mutations');check(!calls.some(r=>/remove-project|report-set\/remove/.test(r.path)),'T47/T48 separate removal actions never invoked');check(errors.length===0,'no browser runtime errors');
 }finally{await browser.close();await new Promise(resolve=>server.close(resolve))}
 console.log(`Phase 11 browser: ${passed} passed, 0 failed, 0 skipped`);
})().catch(e=>{console.error(e);process.exitCode=1});
