// UI-only Vite; real database, discovery reconciliation and access service, injected transports.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),{mock}=require('./advanced_scan.cjs');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++;console.log('PASS: '+n)};
(async()=>{
 const {SiteProjectDatabase}=await import('../../core/storage/project_db.ts');
 const {Phase4IdentityReconciliation}=await import('../../core/engine/phase4_reconcile.ts');
 const {BatchExecutionPipeline}=await import('../../core/engine/pipeline.ts');
 const {IncrementalDiscoveryMonitor}=await import('../../core/engine/incremental_discovery_monitor.ts');
 const {DuplicateAssistantService}=await import('../../core/edge_cases/duplicate_assistant_service.ts');
 const {ConnectService}=await import('../../core/connect/connect_service.ts');
 const {ReportService}=await import('../../core/reporting/report_service.ts');
 const now=()=>new Date().toISOString(),db=new SiteProjectDatabase(),launches=[],events=[];let cycles=0,allowed=true,fail=false,release;
 const camera=(id,ip='192.168.1.100')=>({id,anchor:{macAddress:id==='A'?'00:50:f9:63:fb:0f':id==='B'?'e4:30:22:cd:68:85':null,onvifEndpointUuid:'uuid-'+id,vendor:id==='B'?'Hanwha Vision':'Fixture',model:id==='B'?'QND-7082R':undefined,serialNumber:id==='A'?'SERIAL-A':undefined},technician:{name:id,notes:'Preserved notes'},network:{ipAddress:ip,subnetMask:'255.255.255.0',port:80,protocol:'ONVIF'},status:'ONLINE',sessionVerification:'VERIFIED',discoveredPhase:3,firstSeenAt:now(),lastSeenAt:now(),reachability:{wsDiscoveryRespondedAt:now(),discoveryInterface:{name:'Ethernet',ipAddress:'192.168.1.205',netmask:'255.255.255.0',interfaceIndex:8}}});
 let observations=[camera('A'),camera('B'),camera('C','192.168.1.200'),camera('D','192.168.1.200')];
 db.createNewProject('Assistant');observations.forEach(d=>db.upsertDevice(d));await Phase4IdentityReconciliation.execute(db);db.exportProjectJsonForSave();
 const monitor=new IncrementalDiscoveryMonitor({canRun:()=>({allowed,reason:'Technician operation active'}),runCycle:async sessionId=>{cycles++;if(fail)throw Error('Injected failure');await new Promise(resolve=>{release=resolve});const pipeline=new BatchExecutionPipeline({passiveDiscovery:{discover:async()=>[]},onvifDiscovery:{discover:async(_n,o)=>{observations.forEach(d=>o.onDevice(structuredClone(d)));return{devices:observations,interfaceErrors:[],cancelled:false}}},deviceEnricher:{enrich:async d=>d}});pipeline.subscribe(e=>events.push(e));pipeline.runPhase1=async()=>{pipeline.currentInterfaces=[{name:'Ethernet',ipAddress:'192.168.1.205',netmask:'255.255.255.0',interfaceIndex:8,isInternal:false,broadcast:'',mac:''}]};await pipeline.runDiscoveryScan({database:db,context:{origin:'MONITORING',sessionId},emitTerminalEvent:false})}});
 const assistantService=new DuplicateAssistantService(db,monitor),access=new ConnectService(db,{available:async()=>['SYSTEM'],launch:async(url,preference,authorize)=>{authorize();launches.push(url);return{used:preference,fallback:false}}});
 const reportIds=()=>new ReportService().build(db.getSession(),[],{type:'DEVICE_INVENTORY',scope:'ALL'}).rows.map(r=>r.deviceId).sort().join(',');const beforeReport=reportIds(),initialIds=db.getDevices().map(d=>d.id).join(',');
 const browser=await chromium.launch({channel:'msedge',headless:true});try{
  const context=await browser.newContext({viewport:{width:1100,height:720},permissions:['clipboard-read','clipboard-write']});const page=await context.newPage(),errors=[],requests=[];page.on('pageerror',e=>errors.push(String(e)));
  await page.route(/^https?:\/\/192\.168\./,route=>route.fulfill({status:200,body:'Intercepted fixture'}));await mock(page);
  await page.exposeFunction('assistantBackend',async(path,body)=>{requests.push({path,body});try{let value;if(path==='/api/project/session')value=db.getSession();else if(path==='/api/project')value=db.getProject();else if(path.endsWith('/recheck'))value=await assistantService.recheck(decodeURIComponent(path.split('/')[4]));else if(path.startsWith('/api/connect/')){const id=decodeURIComponent(path.split('/')[3]);value=path.endsWith('/open')?await access.open(id,body.preference):access.resolve(id)}return{status:200,body:value}}catch(e){return{status:409,body:{error:e.message,accessDecision:e.accessDecision}}}});
  await page.addInitScript(session=>{const old=window.fetch,t=__test;t.project=session.project;t.session=session;t.assistantRequests=[];window.fetch=async(url,o={})=>{const path=new URL(url,location.href).pathname;if(path==='/api/pair/eligibility')return new Response(JSON.stringify(t.project.devices.find(d=>d.id===new URL(url).searchParams.get('deviceId'))));if(path.startsWith('/api/edge/collisions/')||path==='/api/project'||path==='/api/project/session'||(path.startsWith('/api/connect/')&&!path.includes('/credentials')&&!path.endsWith('/browsers'))){t.assistantRequests.push({path,body:o.body});const r=await window.assistantBackend(path,o.body?JSON.parse(o.body):{});if(path==='/api/project')t.project=r.body;return new Response(JSON.stringify(r.body),{status:r.status,headers:{'Content-Type':'application/json'}})}return old(url,o)}},db.getSession());
  await page.goto('http://127.0.0.1:5179/src/test/browser/advanced_scan.html?app');
  const dialog=page.getByRole('dialog',{name:'Duplicate IP Assistant'}),close=()=>dialog.getByRole('button',{name:'Close Duplicate Assistant'}).click();
  const row=id=>page.locator('tbody tr').filter({has:page.getByRole('button',{name:'Actions for '+id,exact:true})});
  const openStatus=async(id)=>{await row(id).getByRole('button',{name:'Duplicate IP',exact:true}).click();await dialog.waitFor()};
  const card=id=>dialog.getByRole('article',{name:'Participant '+id,exact:true});
  const publish=async()=>page.evaluate(session=>{__test.project=session.project;__test.session=session;const s=__test.sockets.at(-1);s.readyState=1;s.onopen?.(new Event('open'));__test.emit({type:'DEVICE_DISCOVERED',data:{project:session.project}})},db.getSession());
  await openStatus('A');check(await dialog.count()===1&&await dialog.locator('article').count()===2,'T01/T02 status opens one two-identity assistant');
  check((await card('A').textContent()).includes('63FB0F')&&(await card('A').textContent()).includes('00:50:f9:63:fb:0f')&&(await card('B').textContent()).includes('CD6885'),'T03/T04 full MAC and Last 6 belong to correct cards');
  check((await card('B').textContent()).includes('Hanwha Vision')&&(await card('B').textContent()).includes('QND-7082R')&&(await card('B').textContent()).includes('Not available'),'T03/T05 real model and honest optional evidence');
  check(await card('A').getByRole('button',{name:'Open',exact:true}).isDisabled()&&await card('B').getByRole('button',{name:'Open',exact:true}).isDisabled()&&await dialog.locator('a[href],iframe').count()===0,'T06/T07/T28 active cards have no raw-IP bypass');
  check(await dialog.getByRole('button',{name:/Pair|Configuration|Apply/}).count()===0,'T29/T30/T32 no ambiguous write or Pair controls');
  check(!/credential|password|secret/i.test(await dialog.textContent()),'T38 no credential controls or material');
  await card('A').getByRole('button',{name:'Copy MAC',exact:true}).click();await dialog.getByText('MAC copied.',{exact:true}).waitFor();check(await page.evaluate(()=>navigator.clipboard.readText())==='00:50:f9:63:fb:0f','Copy MAC is functional');
  await card('A').getByRole('button',{name:'Copy Serial',exact:true}).click();await dialog.getByText('Serial copied.',{exact:true}).waitFor();check(await page.evaluate(()=>navigator.clipboard.readText())==='SERIAL-A','Copy Serial is functional');
  await card('A').getByRole('button',{name:'Copy ID',exact:true}).click();await dialog.getByText('Stable ID copied.',{exact:true}).waitFor();check(await page.evaluate(()=>navigator.clipboard.readText())==='A','Copy stable ID is functional');
  await card('A').getByRole('button',{name:'Diagnose',exact:true}).click();await page.getByRole('dialog',{name:'Device Inspector',exact:true}).waitFor();check(await page.evaluate(()=>__test.requests.some(r=>r.path==='/api/diagnostics/run'&&r.body.deviceIds.join(',')==='A')),'Diagnose routes selected identity to existing workflow');await page.getByRole('dialog',{name:'Device Inspector',exact:true}).getByRole('button',{name:'Close',exact:true}).click();await openStatus('A');
  await card('A').getByRole('button',{name:'Details',exact:true}).click();await page.getByRole('button',{name:'Open Camera',exact:true}).waitFor();check(await dialog.count()===0,'Details opens existing Inspector');
  await page.getByRole('button',{name:'Open Camera',exact:true}).click();const accessModal=page.getByRole('dialog',{name:'Camera Access'});await accessModal.getByRole('button',{name:'Open Duplicate Assistant',exact:true}).click();await dialog.waitFor();check(await dialog.locator('article').count()===2&&await accessModal.count()===0,'T27 blocked embedded access routes to same collision');
  await close();await page.getByRole('button',{name:'Actions for C',exact:true}).click();await page.getByRole('menuitem',{name:'Duplicate Assistant',exact:true}).click();await dialog.waitFor();check(await card('C').count()===1&&await card('D').count()===1&&await card('A').count()===0&&(await dialog.textContent()).includes('192.168.1.200'),'T22/T26 Actions selects independent collision');
  await close();await row('A').getByRole('button',{name:'192.168.1.100',exact:true}).click();await dialog.waitFor();check(launches.length===0&&await card('A').count()===1,'T27 external blocked Open routes to same assistant without launch');
  check(!db.getSession().dirty&&db.getDevices().map(d=>d.id).join(',')===initialIds&&reportIds()===beforeReport,'T12/T33/T34 inspection preserves identities, clean project and report membership');
  // A genuine pipeline cycle is held to inspect progress, then returns an identity move.
  observations=[camera('A','192.168.1.168'),camera('B'),camera('C','192.168.1.200'),camera('D','192.168.1.200')];
  await dialog.getByRole('button',{name:'Refresh / Recheck',exact:true}).click();await dialog.getByRole('button',{name:'Checking…',exact:true}).waitFor();check(await dialog.getByRole('button',{name:'Checking…',exact:true}).isDisabled(),'T08 bounded check exposes progress and prevents duplicate clicks');release();await dialog.getByText('Collision resolved',{exact:true}).waitFor();
  check(cycles===1&&(await card('A').textContent()).includes('192.168.1.168'),'T14 discovery recheck updates current IP and resolves');
  check(await row('A').getByRole('button',{name:'Duplicate IP',exact:true}).count()===0&&await row('B').getByRole('button',{name:'Duplicate IP',exact:true}).count()===0,'T15 row collision statuses clear');
  check(await page.locator('footer').getByText('Collisions: 1',{exact:true}).count()===1,'T16 footer keeps only other active logical collision');
  check(db.getDevices().map(d=>d.id).join(',')===initialIds&&reportIds()===beforeReport&&!db.getSession().dirty,'T17/T34 resolved runtime preserves identities/membership and clean project');
  check(events.length>0&&events.every(e=>e.context?.origin==='MONITORING')&&!events.some(e=>['SCAN_COMPLETE','PIPELINE_COMPLETE'].includes(e.type)),'T13 recheck pipeline has no foreground Task/terminal event');
  check(await card('A').getByRole('button',{name:'Open',exact:true}).isEnabled(),'T18 resolved participant exposes safe Open');
  await card('A').getByRole('button',{name:'Open',exact:true}).click();await page.waitForFunction(()=>__test.assistantRequests.filter(r=>r.path.endsWith('/open')).length===2);await page.waitForTimeout(50);check(launches.length===1&&launches[0]==='http://192.168.1.168','T18 resolved Open uses Phase 6 launcher');
  // Stale selected history remains resolved; background changes update without reopening.
  await page.getByRole('button',{name:'Actions for A',exact:true}).click();await page.getByRole('menuitem',{name:'Details',exact:true}).click();await page.getByRole('button',{name:'Close',exact:true}).click();
  db.upsertDevice(camera('A'),'DEVICE_ADDED',true);await Phase4IdentityReconciliation.execute(db);await publish();await openStatus('A');
  db.upsertDevice(camera('A','192.168.1.168'),'DEVICE_ADDED',true);await Phase4IdentityReconciliation.execute(db);await publish();await dialog.getByText('Collision resolved',{exact:true}).waitFor();check(await card('A').getByRole('button',{name:'Open',exact:true}).isEnabled(),'T19/T20 background resolution updates open assistant');
  const collisionId=db.getCollisions().find(c=>c.ipAddress==='192.168.1.100').id;db.upsertDevice(camera('A'),'DEVICE_ADDED',true);await Phase4IdentityReconciliation.execute(db);await publish();await dialog.getByText('Active collision — access is ambiguous',{exact:true}).waitFor();check(await card('A').getByRole('button',{name:'Open',exact:true}).isDisabled()&&db.getCollisions().find(c=>c.ipAddress==='192.168.1.100').id===collisionId,'T21/T35 reopened collision blocks without duplicate history');
  // Failure and operation guards never fabricate resolution.
  allowed=false;await dialog.getByRole('button',{name:'Refresh / Recheck',exact:true}).click();await dialog.getByText(/Check deferred/).waitFor();check(cycles===1&&await card('A').getByRole('button',{name:'Open',exact:true}).isDisabled(),'guarded refresh explains deferral and preserves collision');
  allowed=true;fail=true;await dialog.getByRole('button',{name:'Refresh / Recheck',exact:true}).click();await dialog.getByText(/Discovery check failed/).waitFor();check(await card('A').getByRole('button',{name:'Open',exact:true}).isDisabled(),'failed refresh keeps access blocked');fail=false;
  for(let i=0;i<10;i++)db.upsertDevice(camera('Extra'+i),'DEVICE_ADDED',true);await Phase4IdentityReconciliation.execute(db);await publish();await dialog.getByRole('article',{name:'Participant Extra9',exact:true}).waitFor();check(await dialog.locator('article').count()===12&&db.getCollisions().filter(c=>!c.resolved).length===2,'T23/T24 three-plus identities preserve logical collision counts');
  await page.setViewportSize({width:800,height:600});const bounds=await dialog.evaluate(el=>{const body=el.querySelector('.overflow-y-auto'),r=el.getBoundingClientRect();return{top:r.top,bottom:r.bottom,height:innerHeight,scroll:body.scrollHeight>body.clientHeight,background:getComputedStyle(el).backgroundColor}});check(bounds.top>=0&&bounds.bottom<=bounds.height&&bounds.scroll&&bounds.background==='rgb(255, 255, 255)','T37 light surface fits viewport with internal scroll');
  const last=dialog.getByRole('article',{name:'Participant Extra9',exact:true});await last.getByRole('button',{name:'Copy ID',exact:true}).scrollIntoViewIfNeeded();check(await dialog.getByRole('button',{name:'Refresh / Recheck',exact:true}).isVisible(),'T37 bottom participant and fixed Refresh remain reachable');
  const unsafe=await page.evaluate(()=>__test.requests.filter(r=>/\/pair\/(confirm|restore)|\/credentials.*|\/configuration|\/discovery\/start/.test(r.path)&&r.body));check(unsafe.length===0&&requests.filter(r=>r.path.endsWith('/recheck')).every(r=>Object.keys(r.body).length===0),'T09-T11 refresh submits no network write or credential payload');
  await close();
  // Backend knows a new collision before the UI receives its discovery event.
  const oldSession=db.getSession();oldSession.project.collisions=[];oldSession.project.devices.forEach(d=>d.status='ONLINE');
  await page.evaluate(session=>{__test.project=session.project;__test.session=session;__test.emit({type:'DEVICE_DISCOVERED',data:{project:session.project}})},oldSession);
  await row('A').getByRole('button',{name:'192.168.1.100',exact:true}).click();await dialog.waitFor();await dialog.getByRole('article',{name:'Participant Extra9',exact:true}).waitFor();
  check(await card('A').getByRole('button',{name:'Open',exact:true}).isDisabled()&&launches.length===1,'late collision broadcast still routes backend block to refreshed correct group');
  check(errors.length===0,'no browser runtime errors');
 }finally{await browser.close()}
 console.log(`Phase 7 browser: ${passed} passed, 0 failed, 0 skipped`);
})().catch(e=>{console.error(e);process.exitCode=1});
