const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');const {mock}=require('./advanced_scan.cjs');let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++;console.log('PASS: '+n)};

(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{

 const page=await browser.newPage({viewport:{width:1280,height:900}});const errors=[];page.on('pageerror',e=>errors.push(String(e)));await mock(page);await page.goto('http://127.0.0.1:5179/src/test/browser/advanced_scan.html?app');await page.getByRole('heading',{name:'CCTV Network Assistant'}).waitFor();

 await page.evaluate(()=>{const t=__test,old=window.fetch.bind(window);t.pair=null;t.networkRequests=[];const adapter={interfaceIndex:8,interfaceAlias:'Ethernet',mediaType:'ETHERNET',operationalStatus:'Up',eligible:true,dhcpEnabled:false,ipv4Addresses:[{address:'192.168.0.124',prefixLength:24}],defaultGateways:[],dnsAutomatic:true,dnsServers:[],capturedAt:'now'};const json=v=>new Response(JSON.stringify(v),{headers:{'Content-Type':'application/json'}});window.fetch=async(url,o={})=>{const path=String(url);if(path.endsWith('/pair/adapters'))return json([t.pair?.adapter||adapter]);if(path.endsWith('/pair/status'))return json(t.pair);if(path.endsWith('/network-match/prepare')){t.networkRequests.push({path,body:JSON.parse(o.body)});const v=JSON.parse(o.body);t.pair={id:'network',purpose:'NETWORK_MATCH',deviceId:'',cameraIp:'',state:'READY_FOR_CONFIRMATION',adapter,originalAdapter:adapter,selectedCandidate:{ipAddress:v.ipAddress,prefixLength:v.prefixLength},candidates:[],recoveryAvailable:false};return json(t.pair)}if(path.endsWith('/pair/confirm')){t.networkRequests.push({path,body:JSON.parse(o.body)});t.pair={...t.pair,state:'PAIRED',adapter:{...adapter,ipv4Addresses:[{address:'192.168.1.130',prefixLength:24}]},adapterConfigurationVerified:true,recoveryAvailable:true};return json(t.pair)}if(path.endsWith('/pair/restore')){t.networkRequests.push({path});t.pair={...t.pair,state:'RESTORED',adapter,recoveryAvailable:false};return json(t.pair)}return old(url,o)};});

 await page.getByRole('button',{name:'Tools',exact:true}).click();await page.getByRole('button',{name:'Network Adapter',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Network Adapter'});await dialog.waitFor();await dialog.getByText('192.168.0.124/24',{exact:true}).waitFor();check(await dialog.getByText('192.168.0.124/24',{exact:true}).isVisible(),'standalone tool shows current Windows address without camera row');check(await page.evaluate(()=>__test.networkRequests.length)===0,'opening tool does not mutate adapter');await page.getByLabel('Temporary IPv4',{exact:true}).fill('224.1.1.1');await page.getByRole('button',{name:'Preview Temporary Configuration'}).click();check(await dialog.getByRole('alert').isVisible()&&await page.evaluate(()=>__test.networkRequests.length)===0,'unsafe input rejected before preview request');await page.getByLabel('Temporary IPv4',{exact:true}).fill('192.168.1.130');await page.getByRole('button',{name:'Preview Temporary Configuration'}).click();await page.getByText('Current / preserved configuration',{exact:true}).waitFor();check(await page.getByText('Temporary configuration',{exact:true}).isVisible(),'before and temporary preview displayed');check(await page.evaluate(()=>__test.networkRequests.length)===1,'preview performs no apply');await page.getByRole('button',{name:'Apply Temporary Configuration'}).click();await page.getByText('Ethernet • 192.168.1.130',{exact:true}).waitFor();check(true,'standalone apply refreshes main badge');check(await page.evaluate(()=>__test.networkRequests[1].body.confirmed===true),'explicit confirmation submitted');check(await page.getByRole('button',{name:'Scan',exact:true}).isVisible(),'apply does not start foreground scan');await page.getByRole('button',{name:'Restore Original Network Configuration',exact:true}).click();await page.getByText('Ethernet • 192.168.0.124',{exact:true}).waitFor();check(true,'standalone Restore refreshes main badge');check(await page.evaluate(()=>__test.requests.every(r=>!r.path.endsWith('/advanced/start')&&!r.path.endsWith('/discovery/start'))),'no automatic Advanced or normal Scan');


 await page.getByRole('button',{name:'Close Network Adapter'}).click();
 await page.evaluate(()=>{const t=__test;t.project={id:'quick',name:'Quick Work',devices:[{id:'contrast',anchor:{macAddress:null,vendor:'Hanwha Vision'},network:{ipAddress:'192.168.1.100',port:80,protocol:'ONVIF'},status:'UNKNOWN',discoveredPhase:3,firstSeenAt:'now',lastSeenAt:'now'}],collisions:[],rogueDhcpEvents:[],auditLogs:[],totalDevices:1};const old=window.fetch;window.fetch=(url,o)=>String(url).includes('/pair/eligibility')?Promise.resolve(new Response(JSON.stringify(t.project.devices[0]),{headers:{'Content-Type':'application/json'}})):old(url,o);const socket=t.sockets.at(-1);socket.readyState=1;socket.onopen?.(new Event('open'));t.emit({type:'DEVICE_DISCOVERED',data:{project:t.project}});document.documentElement.classList.remove('dark')});
 await page.getByRole('button',{name:'Actions for Hanwha Vision'}).click();const menu=page.getByRole('menu',{name:'Actions for Hanwha Vision'});await menu.waitFor();const item=menu.getByRole('menuitem',{name:'Open',exact:true});
 const contrast=async()=>item.evaluate(el=>{const s=getComputedStyle(el);const parse=v=>v.match(/\d+/g).slice(0,3).map(Number).map(n=>{const c=n/255;return c<=0.04045?c/12.92:((c+0.055)/1.055)**2.4});const lum=v=>{const c=parse(v);return .2126*c[0]+.7152*c[1]+.0722*c[2]};const a=lum(s.color),b=lum(s.backgroundColor==='rgba(0, 0, 0, 0)'?getComputedStyle(el.parentElement).backgroundColor:s.backgroundColor);return (Math.max(a,b)+.05)/(Math.min(a,b)+.05)});
 check(await menu.evaluate(el=>getComputedStyle(el).backgroundColor)==='rgb(255, 255, 255)','Actions menu uses light surface in light theme');await item.hover();check(await contrast()>=4.5,'light-theme hover text contrast meets 4.5:1');await item.focus();await page.keyboard.press('Tab');check(await menu.getByRole('menuitem',{name:'Details',exact:true}).evaluate(el=>el===document.activeElement&&getComputedStyle(el).outlineStyle!=='none'),'keyboard focus remains visible');await page.evaluate(()=>document.documentElement.classList.add('dark'));check(await contrast()>=4.5,'dark-theme hover contrast preserved');await page.keyboard.press('Escape');check(await menu.count()===0,'Escape closes menu with structure and behavior preserved');
 await page.goto('http://127.0.0.1:5179/src/test/browser/field_workflow.html');await page.getByText('Factory credential suggestions',{exact:true}).click();await page.getByRole('button',{name:'Use Credentials',exact:true}).waitFor();check(await page.getByLabel('Username',{exact:true}).inputValue()===''&&await page.getByLabel('Password',{exact:true}).inputValue()==='','suggestion is never prefilled');const requests=await page.evaluate(()=>__test.requests.length);await page.getByRole('button',{name:'Use Credentials',exact:true}).click();check(await page.getByLabel('Username',{exact:true}).inputValue()==='root'&&await page.getByLabel('Password',{exact:true}).inputValue()==='pass','explicit legacy suggestion fills fields');check(await page.evaluate(()=>__test.requests.length)===requests,'selection sends no request or authentication');check(!await page.getByLabel('Remember this credential').isChecked(),'selection does not request saving');check(await page.getByRole('button',{name:'Update',exact:true}).isDisabled(),'saved Credential Manager remains separate');check(await page.getByText('Suggestions are not guaranteed.',{exact:false}).count()>0,'uncertainty is visible');await page.evaluate(()=>document.querySelector('button').click());await page.getByText('Password: Initial setup/password creation required',{exact:true}).waitFor();check(await page.getByRole('button',{name:'Use Credentials',exact:true}).count()===0,'Hanwha initial setup has no invented password');await page.getByRole('button',{name:'Use Username',exact:true}).click();check(await page.getByLabel('Username',{exact:true}).inputValue()==='admin'&&await page.getByLabel('Password',{exact:true}).inputValue()==='','Hanwha partial identity supports username-only selection');check(await page.evaluate(()=>__test.requests.every(r=>!r.path.includes('/credentials/select')&&!r.path.endsWith('/open')&&!r.path.endsWith('/recheck'))),'hints never cycle, authenticate, open or save');check(errors.length===0,'no browser runtime errors');

 console.log(`Field workflow browser: ${passed} passed, 0 failed, 0 skipped`);

 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
