const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),{mock}=require('./advanced_scan.cjs');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++;console.log('PASS: '+n)};
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(String(e)));await mock(page);
 await page.addInitScript(()=>{
  const original=fetch.bind(window),json=v=>new Response(JSON.stringify(v));
  const adapter={interfaceIndex:8,interfaceAlias:'Ethernet',mediaType:'ETHERNET',operationalStatus:'Up',eligible:true,dhcpEnabled:true,ipv4Addresses:[{address:'192.0.2.10',prefixLength:24}],defaultGateways:[],dnsAutomatic:true,dnsServers:[],capturedAt:'now'};
  __test.project={id:'empty',name:'Quick Work',devices:[],collisions:[],rogueDhcpEvents:[],auditLogs:[],totalDevices:0};
  window.__field={refreshes:0,bad:false,project:false,support:0};
  window.fetch=async(url,options={})=>{const path=String(url);
   if(path.includes('/system/preflight')){if(path.includes('refresh=1'))__field.refreshes++;if(__field.bad)return json({});return json({overall:'WARNING',version:'1.6.0',runtime:'v22.18.0',build:{commit:'a'.repeat(40),dirty:false,sourceDigest:'b'.repeat(64),runtimeMode:'production'},checks:[{id:'elevation',label:'Adapter change privileges',state:'WARNING',detail:'Elevation is required only for Pair/Match apply and Restore.',critical:false},{id:'network-recovery',label:'Network recovery',state:'READY',detail:'No temporary adapter recovery is required.',critical:false}]});}
   if(path.includes('/system/support-bundle')){__field.support++;return json({manifest:{format:'CCTV_SAFE_SUPPORT_BUNDLE'},application:{version:'1.6.0'},devices:[]});}
   if(path.endsWith('/pair/adapters'))return json([adapter]);
   if(path.endsWith('/api/tasks'))return json({tasks:[],active:0,attention:0});
   if(path.endsWith('/project/new')){__field.project=true;__test.project.name='Field rehearsal';return json({mode:'PROJECT',dirty:false,project:__test.project});}
   if(path.endsWith('/project/session'))return json({mode:__field.project?'PROJECT':'QUICK_WORK',dirty:false,project:__test.project});
   if(path.includes('/project/history'))return json({events:[]});
   if(path.endsWith('/reports/preview'))return new Response(JSON.stringify({error:'No selected devices.'}),{status:400});
   return original(url,options);
  };
 });
 await page.goto('http://127.0.0.1:5179/src/test/browser/advanced_scan.html?app');await page.getByRole('button',{name:'Scan',exact:true}).waitFor();check(await page.getByText('Quick Work',{exact:false}).count()>0,'no-camera startup is Quick Work');check(await page.getByText('No devices discovered.',{exact:true}).isVisible(),'zero-camera inventory intentional');
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Diagnostics & Support',exact:true}).click();await page.getByText('Adapter change privileges',{exact:true}).waitFor();check(await page.getByText('Elevation is required only for Pair/Match apply and Restore.',{exact:true}).isVisible(),'readiness warning scoped to adapter changes');
 await page.evaluate(()=>document.documentElement.classList.remove('dark'));check(await page.getByRole('menu',{name:'Settings',exact:true}).evaluate(el=>getComputedStyle(el).backgroundColor)==='rgb(255, 255, 255)','readiness retains readable light surface');await page.getByRole('button',{name:'Refresh Field Readiness'}).focus();check(await page.getByRole('button',{name:'Refresh Field Readiness'}).evaluate(el=>el===document.activeElement),'readiness refresh keyboard focus is available');await page.getByRole('button',{name:'Refresh Field Readiness'}).click();await page.waitForFunction(()=>__field.refreshes===1);await page.getByRole('button',{name:'Refresh Field Readiness'}).waitFor();check(true,'Field Readiness refresh invokes authoritative endpoint');
 await page.evaluate(()=>__field.bad=true);await page.getByRole('button',{name:'Refresh Field Readiness'}).click();await page.getByText(/Previous results may be stale/).waitFor();check(true,'malformed readiness gives safe retry feedback');await page.evaluate(()=>__field.bad=false);
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download Safe Support Bundle'}).click();check((await download).suggestedFilename()==='CCTV_Safe_Support_Bundle.json','support download available without cameras');
 await page.keyboard.press('Escape');check(await page.getByRole('button',{name:'Scan',exact:true}).isEnabled(),'non-elevated readiness does not disable Scan');
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'About',exact:true}).click();check(await page.getByText(/Build: a{40}/).isVisible(),'About exposes supplied build identity');await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Scan',exact:true}).click();await page.getByRole('button',{name:'Stop',exact:true}).waitFor();check(true,'no-camera Scan starts with foreground ownership');await page.getByRole('button',{name:'Stop',exact:true}).click();await page.getByRole('button',{name:'Scan',exact:true}).waitFor();check(true,'no-camera Stop returns control');
 await page.getByRole('button',{name:'Scan',exact:true}).click();await page.getByRole('button',{name:'Stop',exact:true}).waitFor();await page.evaluate(()=>__test.advance('MANUAL','COMPLETED',__test.foreground.session.sessionId));await page.getByRole('button',{name:'Scan',exact:true}).waitFor();check(await page.getByText('No devices found.',{exact:true}).isVisible(),'zero-result completion never inserts a target');
 await page.getByRole('button',{name:'Tasks',exact:true}).click();await page.getByText('No recent technician tasks.').waitFor();check(true,'no-camera empty Tasks remains usable');await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Scan choices',exact:true}).click();await page.getByRole('button',{name:/Advanced Scan Customize/}).click();await page.getByLabel('Ethernet',{exact:false}).check();await page.getByRole('button',{name:'Add Range',exact:true}).click();await page.getByLabel('Target 1 type').selectOption('RANGE');for(const label of ['Start IP','End IP'])for(const [index,value]of ['192','0','2','55'].entries())await page.getByLabel(`${label} octet ${index+1}`,{exact:true}).fill(value);await page.waitForFunction(()=>!Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='Start Advanced Scan')?.disabled);check(true,'bounded Advanced target validates without cameras');await page.getByRole('button',{name:'Start Advanced Scan',exact:true}).click();await page.getByRole('button',{name:'Stop',exact:true}).waitFor();check(await page.evaluate(()=>__test.foreground.session.origin==='ADVANCED'),'Advanced rehearsal owns its foreground session');await page.evaluate(()=>__test.advance('ADVANCED','COMPLETED',__test.foreground.session.sessionId));await page.getByRole('button',{name:'Scan',exact:true}).waitFor();check(await page.getByText('No devices found.',{exact:true}).isVisible(),'Advanced zero result never creates a fake production row');
 await page.getByRole('button',{name:'Tools',exact:true}).click();await page.getByRole('button',{name:'Network Adapter',exact:true}).click();await page.getByLabel('Temporary IPv4',{exact:true}).fill('224.0.0.1');await page.getByRole('button',{name:'Preview Temporary Configuration'}).click();await page.getByRole('alert').waitFor();check(true,'unsafe Match input rejected without applying');await page.keyboard.press('Escape');
 page.on('dialog',dialog=>dialog.accept(dialog.message().includes('name')?'Field rehearsal':''));await page.getByRole('button',{name:'Project',exact:true}).click();await page.getByRole('button',{name:'New Project',exact:true}).click();await page.getByText('Field rehearsal',{exact:false}).first().waitFor();check(true,'empty new Project works without hardware');
 await page.getByRole('button',{name:'Project',exact:true}).click();await page.getByRole('button',{name:'History',exact:true}).click();await page.getByRole('dialog',{name:'Project History'}).waitFor();check(await page.getByText('No Project history matches this view.').isVisible(),'empty project history intentional');await page.getByRole('button',{name:'Close Project History'}).click();
 await page.getByRole('button',{name:'Tools',exact:true}).click();await page.getByRole('button',{name:'Reports',exact:true}).click();await page.getByText('No selected devices.',{exact:true}).waitFor();check(await page.getByRole('button',{name:'pdf',exact:true}).isDisabled(),'no-selection report cannot export');await page.getByRole('button',{name:'Close reports'}).click();
 check(await page.evaluate(()=>__test.requests.every(r=>!r.path.includes('/pair/confirm')&&!r.path.includes('/network/current'))),'rehearsal performs no adapter or camera mutation');check(errors.length===0,'no-camera rehearsal has no browser runtime error');
 console.log(`Field preparation browser: ${passed} passed, 0 failed, 0 skipped`);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
