const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),{mock}=require('./advanced_scan.cjs');let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++;console.log('PASS: '+n)};
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:1280,height:850}}),errors=[];page.on('pageerror',e=>errors.push(String(e)));await mock(page);await page.goto('http://127.0.0.1:5179/src/test/browser/advanced_scan.html?app');await page.getByRole('heading',{name:'CCTV Network Assistant'}).waitFor();
 await page.evaluate(()=>{const t=__test;t.project={id:'fixture',name:'Quick Work',devices:['ONLINE','COLLISION','PROVISIONING','OFFLINE','ONLINE','AUTHENTICATED','CONFIGURED','DIFFERENT_SUBNET'].map((status,i)=>({id:String(i),anchor:{macAddress:'00:50:f9:63:fb:'+String(i).padStart(2,'0'),onvifEndpointUuid:'uuid-'+i,vendor:i===4?'Lenel':'Fixture',model:'Model-'+i,serialNumber:'Serial-'+i},technician:{name:'Camera-'+i,notes:'Note-'+i},network:{ipAddress:'192.168.1.'+(100+i),port:80,protocol:'ONVIF'},status,discoveredPhase:3,firstSeenAt:'now',lastSeenAt:'now'})),collisions:[],rogueDhcpEvents:[],auditLogs:[],totalDevices:8};const socket=t.sockets.at(-1);socket.readyState=1;socket.onopen?.(new Event('open'));t.emit({type:'DEVICE_DISCOVERED',data:{project:t.project}});t.emit({type:'PHASE_COMPLETE',phaseNumber:1,data:{interfaces:[{name:'Ethernet',ipAddress:'192.168.0.124',netmask:'255.255.255.0',mac:'e0:70:ea:ce:83:42',isInternal:false,interfaceIndex:8}]}})});
 const toolbar=page.getByRole('region',{name:'Device toolbar'}),scan=toolbar.getByRole('button',{name:'Scan',exact:true}),search=toolbar.getByRole('textbox',{name:'Search devices'}),ethernet=toolbar.getByText('Ethernet • 192.168.0.124',{exact:true}),diagnostics=toolbar.getByText(/^Diagnostics:/),filters=toolbar.getByRole('button',{name:'Filters',exact:true}),panel=toolbar.getByRole('group',{name:'Device filters'}),rows=()=>page.locator('tbody tr').filter({has:page.getByRole('button',{name:/^Actions for/})});
 for(const [name,el] of [['Scan',scan],['Search',search],['Ethernet',ethernet],['Diagnostics',diagnostics],['Filters',filters]])check(await el.isVisible(),name+' directly visible with Filters closed');check((await search.boundingBox()).width<=240,'Search compact width');check(await panel.count()===0,'Filters surface initially closed');
 await filters.focus();await page.keyboard.press('Enter');await panel.waitFor();for(const [name,el] of [['Scan',scan],['Search',search],['Ethernet',ethernet],['Diagnostics',diagnostics]])check(await el.isVisible(),name+' stays visible when Filters opens');
 const status=panel.getByRole('combobox',{name:'Status',exact:true}),type=panel.getByRole('combobox',{name:'Type',exact:true});check(await status.isVisible()&&await type.isVisible(),'Status and Type inside Filters');check(await status.evaluate(el=>el===document.activeElement&&getComputedStyle(el).outlineStyle!=='none'),'keyboard opening focuses Status visibly');check(await status.locator('option').allTextContents().then(v=>v.join('|')==='All Statuses|Online|Duplicate IP|Working|Unreachable'),'Status options preserved');check(await type.locator('option').allTextContents().then(v=>v.join('|')==='All Types|Cameras|Access Control'),'Type options preserved');
 for(const [value,count] of [['ONLINE',4],['DUPLICATE',1],['WORKING',1],['UNREACHABLE',2],['ALL',8]]){await status.selectOption(value);check(await rows().count()===count,value+' Status semantics preserved')}
 await type.selectOption('CAMERA');check(await rows().count()===7,'Camera Type semantics');await type.selectOption('ACCESS');check(await rows().count()===1,'Access Control Type semantics');await status.selectOption('ONLINE');check(await filters.textContent().then(t=>t.includes('2 active')),'compact active count truthful');await type.focus();await page.keyboard.press('Escape');check(await panel.count()===0&&await filters.evaluate(el=>el===document.activeElement),'Escape closes and restores focus');check(await filters.textContent().then(t=>t.includes('2 active')),'active indicator persists when closed');await filters.click();check(await status.inputValue()==='ONLINE'&&await type.inputValue()==='ACCESS','reopening preserves both filters');await status.selectOption('ALL');await type.selectOption('ALL');check(await rows().count()===8&&!((await filters.textContent()).includes('active')),'All selections clear filtering and indicator');
 for(const query of ['Camera-0','192.168.1.100','Serial-0','Model-0','Note-0']){await search.fill(query);check(await rows().count()===1,query+' search preserved')}await search.fill('');check(await rows().count()===8,'clearing Search restores matching rows');
 for(const width of [900,640,440]){await page.setViewportSize({width,height:850});const boxes=await Promise.all([scan,search,ethernet,diagnostics,filters].map(el=>el.boundingBox()));check(boxes.every(b=>b&&b.x>=0&&b.x+b.width<=width+1)&&boxes.every((a,i)=>boxes.every((b,j)=>i===j||a.x+a.width<=b.x+1||b.x+b.width<=a.x+1||a.y+a.height<=b.y+1||b.y+b.height<=a.y+1)),width+'px controls wrap without overlap or clipping')}
 check(await toolbar.evaluate(el=>getComputedStyle(el).backgroundColor==='rgb(255, 255, 255)'),'light toolbar surface preserved');check(!errors.length,'no browser runtime errors');console.log(`Phase 13C toolbar: ${passed} passed, 0 failed, 0 skipped`);
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
