// UI-only server. Actual access policy/service; injected launcher and intercepted camera navigation.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');const {mock}=require('./advanced_scan.cjs');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++;console.log('PASS: '+n)};
(async()=>{
 const {SiteProjectDatabase}=await import('../../core/storage/project_db.ts');const {ConnectService}=await import('../../core/connect/connect_service.ts');const {Phase4IdentityReconciliation}=await import('../../core/engine/phase4_reconcile.ts');
 const now=()=>new Date().toISOString(),db=new SiteProjectDatabase(),launches=[];db.createNewProject('Access safety');
 for(const id of ['A','B'])db.upsertDevice({id,anchor:{macAddress:id==='A'?'00:50:f9:63:fb:0f':'e4:30:22:cd:68:85',onvifEndpointUuid:'uuid-'+id,vendor:id},technician:{name:id},network:{ipAddress:'192.168.1.100',subnetMask:'255.255.255.0',port:80,protocol:'ONVIF'},status:'ONLINE',sessionVerification:'VERIFIED',discoveredPhase:3,firstSeenAt:now(),lastSeenAt:now(),reachability:{wsDiscoveryRespondedAt:now(),subnetClassification:'LOCAL'}});
 await Phase4IdentityReconciliation.execute(db);db.exportProjectJsonForSave();
 const service=new ConnectService(db,{available:async()=>['SYSTEM','EDGE','CHROME','EMBEDDED'],launch:async(url,preference,authorize)=>{authorize();launches.push({url,preference});return{used:preference,fallback:false}}});
 const browser=await chromium.launch({channel:'msedge',headless:true});try{
  const page=await browser.newPage(),alerts=[],errors=[],navigations=[];page.on('dialog',async d=>{alerts.push(d.message());await d.accept()});page.on('pageerror',e=>errors.push(String(e)));
  await page.route(/^https?:\/\/192\.168\./,async route=>{navigations.push(route.request().url());await route.fulfill({status:200,contentType:'text/html',body:'<p>Intercepted camera fixture</p>'})});
  await mock(page);await page.exposeFunction('accessBackend',async(path,body)=>{try{const id=decodeURIComponent(path.split('/')[3]);return{status:200,body:path.endsWith('/open')?await service.open(id,body.preference):service.resolve(id)}}catch(error){return{status:409,body:{error:error.message,accessDecision:error.accessDecision}}}});
  await page.addInitScript(session=>{const t=__test,old=window.fetch;t.project=session.project;t.session=session;t.accessResponses=[];window.fetch=async(url,o={})=>{const path=new URL(url,location.href).pathname;let body;if(path.endsWith('/pair/eligibility'))return new Response(JSON.stringify(t.project.devices.find(d=>d.id===new URL(url).searchParams.get('deviceId'))),{headers:{'Content-Type':'application/json'}});if(path.startsWith('/api/connect/')&&!path.includes('/credentials')&&!path.endsWith('/browsers')){const value=await window.accessBackend(path,o.body?JSON.parse(o.body):{});t.accessResponses.push({path,...value});return new Response(JSON.stringify(value.body),{status:value.status,headers:{'Content-Type':'application/json'}})}if(path.endsWith('/api/project/session'))body=t.session;else if(path.endsWith('/api/project'))body=t.project;else return old(url,o);return new Response(JSON.stringify(body),{headers:{'Content-Type':'application/json'}})}},db.getSession());
  const url='http://127.0.0.1:5179/src/test/browser/advanced_scan.html?app';await page.goto(url);
  const ip=page.locator('tbody').getByRole('button',{name:'192.168.1.100',exact:true});await ip.first().waitFor();
  for(let i=0;i<2;i++){const shown=page.waitForEvent('dialog');await ip.nth(i).click();await shown;await page.waitForFunction(n=>__test.accessResponses.filter(r=>r.path.endsWith('/open')).length>=n,i+1);check(launches.length===0,'IP hyperlink row '+(i?'B':'A')+' does not launch shared address');}
  check(alerts.length===2&&alerts.every(message=>message.includes('cannot safely determine')),'blocked external attempts explain ambiguity');
  await page.getByRole('button',{name:'Actions for A',exact:true}).click();await page.getByRole('menuitem',{name:'Open',exact:true}).click();await page.waitForFunction(()=>__test.accessResponses.filter(r=>r.path.endsWith('/open')).length===3);check(launches.length===0,'Actions Open uses same block');
  check(!db.getSession().dirty&&db.getDevices().length===2,'blocked project access preserves clean state and identities');
  await page.getByRole('button',{name:'Actions for A',exact:true}).click();await page.getByRole('menuitem',{name:'Details',exact:true}).click();await page.getByRole('button',{name:'Open Camera',exact:true}).click();
  const modal=page.getByRole('dialog',{name:'Camera Access'});await modal.getByRole('alert').waitFor();check(await modal.locator('iframe').count()===0,'Inspector embedded path never navigates collided address');check(await modal.getByRole('button',{name:'Open External',exact:true}).isDisabled(),'embedded Open External has no ambiguous bypass');check(navigations.length===0,'no camera navigation for any blocked path');
  const publish=async()=>page.evaluate(session=>{__test.project=session.project;__test.session=session;const s=__test.sockets.at(-1);s.readyState=1;s.onopen?.(new Event('open'));__test.emit({type:'DEVICE_DISCOVERED',data:{project:session.project}})},db.getSession());
  db.getDeviceById('A').network.ipAddress='192.168.1.168';await Phase4IdentityReconciliation.execute(db);await publish();await modal.locator('iframe').waitFor();check((await modal.locator('iframe').getAttribute('src'))==='http://192.168.1.168','resolved collision permits selected current address in iframe');
  await modal.getByRole('button',{name:'Open External',exact:true}).click();await page.waitForFunction(()=>__test.accessResponses.some(r=>r.path.endsWith('/open')&&r.status===200));check(launches.length===1&&launches[0].url==='http://192.168.1.168','safe Open External reaches injected launcher');await modal.getByText(/Page and device response are not verified/).waitFor();check(await modal.getByText(/Page and device response are not verified/).count()>0,'launch acknowledgment does not claim camera verification');
  db.getDeviceById('A').network.ipAddress='192.168.1.100';await Phase4IdentityReconciliation.execute(db);await publish();await modal.locator('iframe').waitFor({state:'detached'});check(await modal.getByRole('button',{name:'Open External',exact:true}).isDisabled(),'reopened collision removes live embedded access');
  await modal.getByRole('button',{name:'Close Camera Access'}).click();await page.getByRole('button',{name:'Close',exact:true}).click();
  await page.evaluate(()=>localStorage.setItem('cctv-network-assistant-preferences',JSON.stringify({version:1,browserPreference:'EMBEDDED'})));await page.reload();await page.locator('tbody').getByRole('button',{name:'192.168.1.100',exact:true}).first().click();await modal.waitFor();check(await modal.locator('iframe').count()===0&&launches.length===1,'Embedded preference cannot bypass collision block');
  check(errors.length===0,'no browser runtime errors');
 }finally{await browser.close()}
 console.log(`Phase 6 browser: ${passed} passed, 0 failed, 0 skipped`);
})().catch(error=>{console.error(error);process.exitCode=1});
