const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),{mock}=require('./advanced_scan.cjs');let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++;console.log('PASS: '+n)};
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:800,height:480}}),errors=[];page.on('pageerror',e=>errors.push(String(e)));await mock(page);await page.addInitScript(()=>{const old=fetch;window.fetch=(url,o)=>String(url).endsWith('/api/pair/adapters')?Promise.resolve(new Response('[]',{headers:{'Content-Type':'application/json'}})):old(url,o)});await page.goto('http://127.0.0.1:5179/src/test/browser/modal_containment.html');
 await page.evaluate(()=>{document.body.style.overflow='auto'});
 for(const name of ['Configuration','Pair','Credentials','Manual','Adapter','Project']){
  await page.getByRole('button',{name,exact:true}).click();const overlay=page.locator('.modal-viewport').last(),panel=overlay.locator(':scope > :first-child'),body=panel.locator('.modal-body').first();await body.waitFor();
  await body.evaluate(el=>{const stress=document.createElement('div');stress.dataset.stress='true';for(let i=0;i<40;i++){const p=document.createElement('p');p.textContent='Long field content '+i;p.style.height='28px';stress.appendChild(p)}el.appendChild(stress)});
  check(await panel.evaluate(el=>{const r=el.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight+1}),name+' panel fits small viewport');
  check(await body.evaluate(el=>el.clientHeight>0&&el.scrollHeight>el.clientHeight&&getComputedStyle(el).overflowY==='auto'),name+' body owns long-content scrolling');
  await page.setViewportSize({width:640,height:360});check(await panel.evaluate(el=>{const r=el.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight+1}),name+' remains contained after viewport shrink');await page.setViewportSize({width:800,height:480});
  check(await panel.evaluate(el=>['rgb(255, 255, 255)','rgb(248, 250, 252)'].includes(getComputedStyle(el).backgroundColor)),name+' light surface preserved');
  const header=panel.locator(':scope > :first-child');const initial=await header.boundingBox();await body.hover();await page.mouse.wheel(0,700);await page.waitForTimeout(150);check(await body.evaluate(el=>el.scrollTop>0),name+' wheel scrolls body');const after=await header.boundingBox();check(Math.abs(initial.y-after.y)<1&&after.y>=0,name+' header stays visible');
  check(await page.evaluate(()=>document.body.style.overflow==='hidden'&&scrollY===0),name+' background remains locked');
  const footer=panel.locator('footer');if(await footer.count()){check(await footer.last().evaluate(el=>{const r=el.getBoundingClientRect();return r.bottom<=innerHeight&&r.top>=0}),name+' existing footer stays reachable');}
  const close=header.getByRole('button').last();await close.focus();check(await close.evaluate(el=>el===document.activeElement),name+' keyboard reaches close control');await page.keyboard.press('Enter');await overlay.waitFor({state:'detached'});check(await page.evaluate(()=>document.body.style.overflow==='auto'),name+' closing restores original overflow');
 }
 await page.getByRole('button',{name:'Short',exact:true}).click();check(await page.locator('.modal-body').evaluate(el=>el.scrollHeight===el.clientHeight),'short body has no unnecessary scrolling');await page.locator('.modal-body').evaluate(el=>{const horizontal=document.createElement('div');horizontal.id='horizontal';horizontal.style.cssText='overflow-x:auto;width:200px;height:30px';horizontal.innerHTML='<div style="width:800px">Wide field evidence</div>';el.appendChild(horizontal)});await page.locator('#horizontal').hover();await page.mouse.wheel(400,0);await page.waitForTimeout(150);check(await page.locator('#horizontal').evaluate(el=>el.scrollLeft>0),'horizontal evidence scrolling remains available');await page.getByRole('button',{name:'Nested',exact:true}).click();await page.getByRole('button',{name:'Close nested',exact:true}).click();check(await page.evaluate(()=>document.body.style.overflow==='hidden'),'closing nested modal preserves outer lock');await page.getByRole('button',{name:'Close short',exact:true}).click();check(await page.evaluate(()=>document.body.style.overflow==='auto'),'last modal releases lock');
 await page.getByRole('button',{name:'Manual',exact:true}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();check(await page.locator('.modal-viewport').count()===0,'existing manual Cancel still closes');check(await page.evaluate(()=>__test.requests.every(r=>!r.body)),'layout checks submit no camera/network/credential payload');check(!errors.length,'no browser runtime errors');console.log(`Modal containment: ${passed} passed, 0 failed, 0 skipped`);
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
