const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');const {mock}=require('./advanced_scan.cjs');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++;console.log('PASS: '+n)};
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:1280,height:850}});const errors=[];page.on('pageerror',e=>errors.push(String(e)));await mock(page);await page.clock.install();
 await page.goto('http://127.0.0.1:5179/src/test/browser/advanced_scan.html?app');await page.getByRole('heading',{name:'CCTV Network Assistant'}).waitFor();await page.clock.runFor(100);
 await page.evaluate(()=>{
  const t=window.__test,originalFetch=window.fetch.bind(window);const original={interfaceIndex:8,interfaceAlias:'Ethernet',mediaType:'ETHERNET',operationalStatus:'Up',eligible:true,dhcpEnabled:false,ipv4Addresses:[{address:'192.168.0.124',prefixLength:24}],defaultGateways:[],dnsAutomatic:true,dnsServers:[],capturedAt:'now'};
  t.project={id:'quick',name:'Quick Work',devices:[{id:'onvif:5a524b4c-3656-344c-3330-303037395a00',anchor:{macAddress:null,onvifEndpointUuid:'5a524b4c-3656-344c-3330-303037395a00',vendor:'Hanwha Vision',model:'QND-7082R'},network:{ipAddress:'192.168.1.100',subnetMask:null,port:80,protocol:'ONVIF'},status:'DIFFERENT_SUBNET',sessionVerification:'NOT_VERIFIED',reachability:{subnetClassification:'DIFFERENT_SUBNET',pairEligibility:{eligible:true,adapterIndexes:[8]}},firstSeenAt:'now',lastSeenAt:'now',discoveredPhase:3}],collisions:[],rogueDhcpEvents:[],auditLogs:[],totalDevices:1};
  t.pair=null;t.pairWrites=[];
  const json=value=>new Response(JSON.stringify(value),{headers:{'Content-Type':'application/json'}});
  window.fetch=async(url,options={})=>{
   const path=String(url);if(!path.includes('/api/pair/'))return originalFetch(url,options);
   if(path.includes('/eligibility'))return json(t.project.devices[0]);if(path.endsWith('/adapters'))return json([original]);if(path.endsWith('/status'))return json(t.pair);
   if(path.endsWith('/prepare')){const candidate={ipAddress:'192.168.1.137',prefixLength:24,confidence:'AVAILABLE',evidence:['Software availability fixture']};t.pair={id:'pair',deviceId:t.project.devices[0].id,cameraIp:'192.168.1.100',cameraSubnetMask:'255.255.255.0',adapter:original,originalAdapter:original,state:'READY_FOR_CONFIRMATION',selectedCandidate:candidate,candidates:[candidate],recoveryAvailable:false,createdAt:'now',updatedAt:'now'};return json(t.pair);}
   if(path.endsWith('/confirm')){t.pairWrites.push(JSON.parse(options.body));t.pair={...t.pair,state:'VERIFYING',adapter:{...original,ipv4Addresses:[{address:'192.168.1.137',prefixLength:24}]},adapterConfigurationVerified:true,recoveryAvailable:true};t.emit({type:'PAIR_STATE_CHANGED',data:{pair:t.pair,project:t.project}});return new Promise(resolve=>{t.completePair=()=>{t.project.devices[0]={...t.project.devices[0],anchor:{...t.project.devices[0].anchor,macAddress:'e4:30:22:cd:68:85'},status:'ONLINE',sessionVerification:'VERIFIED'};t.pair={...t.pair,state:'PAIRED',cameraReachabilityVerified:true};t.emit({type:'PAIR_STATE_CHANGED',data:{pair:t.pair,project:t.project}});resolve(json(t.pair));};});}
   if(path.endsWith('/restore')){t.pair={...t.pair,state:'RESTORED',adapter:original,recoveryAvailable:false};t.project.devices[0].status='DIFFERENT_SUBNET';t.emit({type:'PAIR_STATE_CHANGED',data:{pair:t.pair,project:t.project}});return json(t.pair);}
   return json({});
  };
  const socket=t.sockets.at(-1);socket.readyState=1;socket.onopen?.(new Event('open'));
  t.emit({type:'DEVICE_DISCOVERED',context:{origin:'MONITORING'},data:{project:t.project}});t.emit({type:'PHASE_COMPLETE',phaseNumber:1,data:{interfaces:[{name:'Ethernet',interfaceIndex:8,ipAddress:'192.168.0.124',netmask:'255.255.255.0',broadcast:'',mac:'',isInternal:false}]}});
 });
 await page.getByText('Ethernet • 192.168.0.124',{exact:true}).waitFor();check(true,'initial authoritative Ethernet badge');
 await page.getByRole('button',{name:'Actions for Hanwha Vision'}).click();await page.getByRole('menuitem',{name:'Pair PC to Camera Network'}).click();await page.getByRole('button',{name:'Check Addresses and Prepare Preview'}).click();await page.getByText('Confirmation preview',{exact:true}).waitFor();check(await page.getByText('IPv4: 192.168.1.137/24',{exact:true}).isVisible(),'Pair preview preserves expected candidate');check(await page.evaluate(()=>__test.pairWrites.length)===0,'preview performs no network write');
 await page.getByRole('button',{name:'Confirm and Pair'}).click();await page.getByText('Ethernet • 192.168.1.137',{exact:true}).waitFor();check(true,'badge updates during VERIFYING before camera retry completes');check(await page.evaluate(()=>__test.pairWrites[0].confirmed===true),'explicit confirmation sent');check(await page.getByRole('button',{name:'Scan',exact:true}).isVisible(),'Pair verification never becomes foreground Scan');
 await page.evaluate(()=>__test.completePair());await page.getByText('Camera responded',{exact:true}).waitFor();check(await page.getByText('Camera responded',{exact:true}).locator('..').getByText('Yes',{exact:true}).isVisible(),'delayed response shows Camera responded Yes');check(await page.getByText('Online',{exact:true}).count()>0,'Online appears without waiting for monitoring');check(await page.getByText('CD6885',{exact:true}).count()===1,'MAC Last 6 updates in same row');check(await page.getByRole('button',{name:'Actions for Hanwha Vision'}).count()===1,'no duplicate device row');
 await page.getByRole('button',{name:'Restore Original Network Configuration',exact:true}).click();await page.getByText('Ethernet • 192.168.0.124',{exact:true}).waitFor();check(true,'Restore immediately restores adapter badge');check(await page.getByText('Different Subnet',{exact:true}).count()>0,'Restore refreshes relationship');check(await page.getByText('CD6885',{exact:true}).count()===1,'Restore retains enriched row');check(await page.getByRole('button',{name:'Scan',exact:true}).isVisible(),'Restore preserves foreground separation');check(errors.length===0,'no browser runtime errors');
 console.log(`Post Pair browser: ${passed} passed, 0 failed, 0 skipped`);
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
