// UI-only Vite and the actual isolated Report Set/report HTTP routes. No physical operations.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),{mock}=require('./advanced_scan.cjs');let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++;console.log('PASS: '+n)};
(async()=>{
 const {default:express}=await import('express'),{createServer}=await import('node:http'),{SiteProjectDatabase}=await import('../../core/storage/project_db.ts'),{ReportSet}=await import('../../core/reporting/report_set.ts'),{createReportSetRouter}=await import('../../server/report_set_routes.ts'),{createReportRouter}=await import('../../server/report_routes.ts'),{TaskManager}=await import('../../core/tasks/task_manager.ts'),{taskHttpIntegration}=await import('../../server/task_routes.ts');
 const db=new SiteProjectDatabase(),set=new ReportSet(()=>db.getSession()),tasks=new TaskManager(),requests=[];db.startQuickWork();const camera=(id)=>({id,anchor:{macAddress:id==='A'?'00:50:f9:63:fb:0f':id==='B'?'e4:30:22:cd:68:85':null,onvifEndpointUuid:'uuid-'+id,vendor:'Fixture',model:'Camera',serialNumber:'Serial-'+id},technician:{name:id,notes:'Installation notes'},network:{ipAddress:'192.168.1.100',subnetMask:'255.255.255.0',port:80,protocol:'ONVIF'},status:'ONLINE',sessionVerification:'VERIFIED',discoveredPhase:3,firstSeenAt:new Date().toISOString(),lastSeenAt:new Date().toISOString()});['A','B','Excluded'].forEach(id=>db.upsertDevice(camera(id)));
 const app=express();app.use(express.json());app.use(taskHttpIntegration(tasks,{refresh:()=>{},monitoring:()=>({}),bulk:()=>undefined,cancelBulk:()=>false,cancelReverify:()=>false}).middleware);app.use('/api/report-set',createReportSetRouter(set));app.use('/api/reports',createReportRouter({getSession:()=>db.getSession(),getAuditLogs:()=>[],reportSet:set}));const server=createServer(app);await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({channel:'msedge',headless:true});try{
  const page=await browser.newPage({viewport:{width:1280,height:800},timezoneId:'America/New_York'}),errors=[];page.on('pageerror',e=>errors.push(String(e)));await mock(page);
  await page.exposeFunction('reportBackend',async(path,body,method)=>{requests.push({path,body,method});if(path==='/api/reports/preview')body.generatedAt='2026-09-20T03:59:00Z';if(path.startsWith('/api/report-set')||path.startsWith('/api/reports/')){const response=await fetch(base+path,{method,headers:{'Content-Type':'application/json'},body:method==='POST'?JSON.stringify(body):undefined});return{status:response.status,headers:Object.fromEntries(response.headers.entries()),bytes:Array.from(new Uint8Array(await response.arrayBuffer()))}}if(path==='/api/project/session')return{body:db.getSession()};if(path==='/api/project')return{body:db.getProject()};if(path==='/api/tasks')return{body:tasks.snapshot()};if(path.endsWith('/remove-current')){set.snapshot();db.removeDeviceFromCurrentList(decodeURIComponent(path.split('/')[3]));return{body:db.getSession()}}if(path==='/api/pair/eligibility')return{body:db.getDevices()[0]};return{body:{}}});
  await page.addInitScript(()=>{const old=fetch;window.fetch=async(url,o={})=>{const path=new URL(url,location.href).pathname;if(path.startsWith('/api/report-set')||path.startsWith('/api/reports/')||['/api/project/session','/api/project','/api/tasks','/api/pair/eligibility'].includes(path)||path.endsWith('/remove-current')){const r=await reportBackend(path,o.body?JSON.parse(o.body):{},o.method||'GET');return new Response(r.bytes?new Uint8Array(r.bytes):JSON.stringify(r.body),{status:r.status||200,headers:r.headers||{'Content-Type':'application/json'}})}return old(url,o)}});
  await page.goto('http://127.0.0.1:5179/src/test/browser/advanced_scan.html?app');
  const row=id=>page.locator('tbody tr').filter({has:page.getByRole('button',{name:'Actions for '+id,exact:true})}),panel=page.getByRole('dialog',{name:'Report Set',exact:true});
  const action=async(id,name)=>{await page.getByRole('button',{name:'Actions for '+id,exact:true}).click();await page.getByRole('menuitem',{name,exact:true}).click()};
  const openSet=async()=>{await page.getByRole('button',{name:'Tools',exact:true}).click();await page.getByRole('button',{name:/^Report Set \(/}).click();await panel.waitFor()};
  const publish=async()=>page.evaluate(session=>{const s=__test.sockets.at(-1);s.readyState=1;s.onopen?.(new Event('open'));__test.emit({type:'PROJECT_SESSION_CHANGED',data:{session}})},db.getSession());
  await action('A','Add to Report');await row('A').getByText('In Report',{exact:true}).waitFor();check(set.snapshot().members.length===1,'T01/T28 individual add and table membership badge');await action('B','Add to Report');await row('B').getByText('In Report',{exact:true}).waitFor();check(set.snapshot().members.length===2,'T04 same-IP cameras have separate memberships');
  await action('B','Remove from Report');await row('B').getByText('In Report',{exact:true}).waitFor({state:'detached'});check(await row('B').count()===1&&set.snapshot().members.length===1,'T08/T09/T27 removing report membership keeps row');
  await row('A').getByRole('checkbox').check();await row('B').getByRole('checkbox').check();await page.getByRole('button',{name:'Add to Report',exact:true}).click();await row('B').getByText('In Report',{exact:true}).waitFor();await page.getByRole('button',{name:'Add to Report',exact:true}).click();check(set.snapshot().members.length===2,'T24/T25 bulk add idempotent');await page.getByRole('button',{name:'Remove from Report',exact:true}).click();await row('A').getByText('In Report',{exact:true}).waitFor({state:'detached'});check(set.snapshot().members.length===0&&await page.locator('tbody tr').count()===3,'T26 bulk removal affects only report membership');await page.getByRole('button',{name:'Add to Report',exact:true}).click();await row('A').getByText('In Report',{exact:true}).waitFor();await page.getByRole('button',{name:'Deselect All',exact:true}).click();
  await openSet();check(await panel.locator('article').count()===2&&(await panel.textContent()).includes('63FB0F')&&(await panel.textContent()).includes('CD6885'),'T05/T06 view exposes correct identities');check(await panel.getByText('In Current List',{exact:true}).count()===2,'T29/T30 current-list presence is explicit');await panel.getByRole('button',{name:'Close Report Set'}).click();
  await action('A','Remove Device');await page.getByRole('alertdialog').getByRole('button',{name:'Remove Device',exact:true}).click();await row('A').waitFor({state:'detached'});await openSet();check(await panel.locator('article').count()===2&&await panel.getByText('Retained snapshot — no longer in Current List',{exact:true}).count()===1,'T15 current-list removal retains report member');
  await panel.getByRole('button',{name:'Create Report',exact:true}).click();const reports=page.getByRole('dialog').filter({has:page.getByRole('heading',{name:'Reports & Field Documentation',exact:true})});await reports.locator('tbody tr').first().waitFor();check(await panel.count()===0&&await reports.getByLabel(/^Scope/).inputValue()==='REPORT_SET','Report Set Create Report selects accumulated scope');check(await reports.locator('tbody tr').count()===2&&!(await reports.locator('tbody').textContent()).includes('Excluded'),'T31/T32 preview contains retained members only');

  check((await reports.locator('thead th').allTextContents()).join('|')==='Camera Name|Status|IP|MAC Last 6|Manufacturer / Model|Serial|Notes','T09 exact fresh default column order');
  check(await reports.getByRole('group',{name:'Report Information'}).isVisible()&&await reports.getByText('Device Columns',{exact:true}).isVisible(),'report-level information separated from columns');
  check(await reports.getByLabel('Technician Name',{exact:true}).count()===1&&await reports.getByLabel('Site Location',{exact:true}).count()===1,'T11/T12 metadata is not repeated per camera');
  check(!await reports.getByLabel('Configured',{exact:true}).isChecked()&&!await reports.getByLabel('Camera Location',{exact:true}).isChecked(),'T13/T14 optional fields initially off');
  await reports.getByLabel('Configured',{exact:true}).check();await reports.getByRole('button',{name:'Update Preview'}).click();await reports.getByRole('columnheader',{name:'Configured',exact:true}).waitFor();check(true,'T24 optional column included');
  await reports.getByRole('button',{name:'Reset to Defaults'}).click();await reports.getByRole('button',{name:'Update Preview'}).click();await reports.getByRole('columnheader',{name:'Notes',exact:true}).waitFor();check((await reports.locator('thead th').allTextContents()).join('|')==='Camera Name|Status|IP|MAC Last 6|Manufacturer / Model|Serial|Notes','T23 reset restores exact defaults');
  await reports.getByLabel(/^Report type/).selectOption('DIAGNOSTIC_SUMMARY');await reports.getByRole('button',{name:'Update Preview'}).click();await reports.getByRole('columnheader',{name:'Diagnostic Summary',exact:true}).waitFor();check(await reports.getByRole('columnheader',{name:'Last Verified',exact:true}).isVisible(),'T39-T41 purpose-specific diagnostic defaults');
  await reports.getByLabel(/^Report type/).selectOption('DEVICE_INVENTORY');await reports.getByLabel('Technician Name',{exact:true}).fill('Alex');await reports.getByLabel('Site Location',{exact:true}).fill('Building');await reports.getByRole('button',{name:'Update Preview'}).click();await reports.getByText('Site Location: Building · Technician: Alex',{exact:true}).waitFor();check(true,'metadata preview uses report-only edits');
  check((await reports.textContent()).includes('September 19, 2026')&&!(await reports.textContent()).includes('Devices detected'),'T01/T26 local generated timestamp and truthful count');
  const downloaded=page.waitForEvent('download');await reports.getByRole('button',{name:'json',exact:true}).click();const download=await downloaded;check(download.suggestedFilename().endsWith('_2026-09-19.json'),'T02 UI filename uses preview local date');check(tasks.snapshot().tasks[0].reportGeneration.instant==='2026-09-20T03:59:00.000Z'&&tasks.snapshot().tasks[0].reportGeneration.timeZone==='America/New_York','T08 UI export history reuses generation context');check(tasks.snapshot().tasks.filter(t=>t.kind==='REPORT').length===1,'T43 export retains existing generated-report Task history');await reports.getByRole('button',{name:'Close reports'}).click();
  await page.getByRole('button',{name:'Tools',exact:true}).click();await page.getByRole('button',{name:'Reports',exact:true}).click();await reports.locator('tbody tr').first().waitFor();check(await reports.getByLabel(/^Scope/).inputValue()==='REPORT_SET'&&await reports.locator('tbody tr').count()===2,'general Reports defaults to nonempty Report Set');await reports.getByRole('button',{name:'Close reports'}).click();
  await row('Excluded').getByRole('checkbox').check();await page.getByRole('button',{name:'Create Report from Selected',exact:true}).click();await reports.locator('tbody tr').first().waitFor();check(await reports.getByLabel(/^Scope/).inputValue()==='SELECTED'&&await reports.locator('tbody tr').count()===1&&(await reports.locator('tbody').textContent()).includes('Excluded')&&set.snapshot().members.length===2,'selected Create Report preserves accumulated membership');await reports.getByRole('button',{name:'Close reports'}).click();await page.getByRole('button',{name:'Deselect All'}).click();
  await openSet();await panel.getByRole('button',{name:'Clear Report Set',exact:true}).click();check(set.snapshot().members.length===2&&await panel.getByRole('button',{name:'Confirm Clear Report Set',exact:true}).isVisible(),'T33 clear requires explicit confirmation');await panel.getByRole('button',{name:'Cancel',exact:true}).click();await panel.getByRole('article',{name:'Report member A',exact:true}).getByRole('button',{name:'Remove from Report',exact:true}).click();await panel.getByRole('article',{name:'Report member A',exact:true}).waitFor({state:'detached'});check(set.snapshot().members.length===1,'T48 retained member removed without active row');await panel.getByRole('button',{name:'Clear Report Set',exact:true}).click();await panel.getByRole('button',{name:'Confirm Clear Report Set',exact:true}).click();await panel.getByText(/No devices have been added/).waitFor();check(set.snapshot().members.length===0&&db.getDevices().length===3,'T34 confirmed clear leaves inventory');check(await panel.getByRole('button',{name:'Create Report',exact:true}).isDisabled(),'empty Report Set cannot fabricate report members');await panel.getByRole('button',{name:'Close Report Set'}).click();
  db.createNewProject('Project');db.upsertDevice(camera('ProjectCamera'));db.exportProjectJsonForSave();await publish();await action('ProjectCamera','Add to Report');await row('ProjectCamera').getByText('In Report',{exact:true}).waitFor();check(!db.getSession().dirty&&db.getProjectMemberDevices().length===1,'T12/T14 Project membership action stays clean');
  for(let i=0;i<14;i++)db.upsertDevice(camera('Extra'+i),'DEVICE_ADDED',true);set.add(Array.from({length:14},(_,i)=>'Extra'+i));await publish();await openSet();await panel.getByRole('article',{name:'Report member Extra13',exact:true}).waitFor();await page.setViewportSize({width:800,height:600});check(await panel.evaluate(el=>{const r=el.getBoundingClientRect(),body=el.querySelector('.overflow-y-auto');return r.top>=0&&r.bottom<=innerHeight&&body.scrollHeight>body.clientHeight}),'T47 bounded internal scrolling for 15 members');await panel.getByRole('article',{name:'Report member Extra13',exact:true}).getByRole('button',{name:'Remove from Report',exact:true}).scrollIntoViewIfNeeded();check(await panel.getByRole('button',{name:'Create Report',exact:true}).isVisible(),'T47 last member and fixed actions reachable');check(await panel.evaluate(el=>getComputedStyle(el).backgroundColor)==='rgb(255, 255, 255)','Report Set uses readable light surface');
  const taskCount=tasks.snapshot().tasks.length;await panel.getByRole('button',{name:'Close Report Set'}).click();await openSet();check(tasks.snapshot().tasks.length===taskCount&&!db.getSession().dirty,'T37/T41/T42 opening/viewing creates no Tasks or persistent edits');check(!requests.some(r=>/credentials|configuration|pair\/(confirm|restore)/.test(r.path)),'T38-T40 membership submits no credentials or configuration');check(errors.length===0,'no browser runtime errors');
 }finally{await browser.close();await new Promise(resolve=>server.close(resolve))}
 console.log(`Phase 10 browser: ${passed} passed, 0 failed, 0 skipped`);
})().catch(e=>{console.error(e);process.exitCode=1});
