const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const {mock,configure}=require('./advanced_scan.cjs');
let passed=0;const check=(v,name)=>{assert.ok(v,name);passed++;console.log('PASS: '+name)};
(async()=>{const browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:700,height:720}});const errors=[];page.on('pageerror',e=>errors.push(String(e)));await mock(page);await page.clock.install();
 await page.goto('http://127.0.0.1:5179/src/test/browser/advanced_scan.html?app');await page.getByRole('heading',{name:'CCTV Network Assistant'}).waitFor();await page.clock.runFor(100);
 await page.evaluate(()=>{const s=__test.sockets[0];s.readyState=1;s.onopen?.(new Event('open'));});
 const scan=()=>page.getByRole('button',{name:'Scan',exact:true}),stop=()=>page.getByRole('button',{name:'Stop',exact:true});
 const scanning=()=>page.locator('footer').getByText('Scanning\u2026',{exact:true});
 check(await scan().isVisible()&&await stop().count()===0,'launch with enabled monitoring leaves main Scan idle');
 await page.evaluate(()=>{let cycle=0;window.monitorTimer=setInterval(()=>{const context={origin:'MONITORING',sessionId:'monitor-'+(++cycle)};__test.monitoring={enabled:true,running:true,intervalMs:30000,status:'ACTIVE'};__test.emit({type:'MONITORING_STATE',context,data:{monitoring:__test.monitoring}});__test.emit({type:'PHASE_START',context,phaseNumber:3});setTimeout(()=>{__test.monitoring={...__test.monitoring,running:false,status:'WAITING'};__test.emit({type:'MONITORING_STATE',context,data:{monitoring:__test.monitoring}});__test.emit({type:'SCAN_COMPLETE',context});},5000)},30000)});
 await page.clock.runFor(30000);
 check(await scan().isVisible()&&await scanning().count()===0,'background cycle start never presents foreground Stop/Scanning');
 check(await page.getByText(/Diagnostics: Active.*checking/).count()===1,'Diagnostics truthfully shows background checking');
 await page.clock.runFor(5100);check(await scan().isVisible()&&await scanning().count()===0,'monitor completion leaves foreground unchanged');
 await page.clock.runFor(24900);check(await scan().isVisible()&&await scanning().count()===0,'second 30-second monitoring cycle cannot hijack Scan');
 await page.getByRole('button',{name:'Scan choices'}).click();await page.getByRole('button',{name:/^Advanced Scan/}).click();
 check(await page.getByRole('dialog',{name:'Advanced Scan'}).isVisible(),'Advanced Scan opens while monitoring is checking');
 await configure(page);check(await page.getByRole('button',{name:'Start Advanced Scan',exact:true}).isEnabled(),'Advanced configuration validates during monitor activity');
 await page.clock.runFor(30000);check(await page.getByLabel('Target 1 type').inputValue()==='RANGE'&&await page.getByLabel('Start IP octet 4',{exact:true}).inputValue()==='100'&&await page.getByLabel('Ethernet',{exact:false}).isChecked(),'monitor updates cannot reset Advanced target or selected adapter');
 await page.getByRole('button',{name:'Cancel',exact:true}).click();await scan().click();await stop().waitFor();
 check(await stop().isVisible()&&await scanning().isVisible(),'explicit manual start shows Stop and foreground Scanning');
 const manual=await page.evaluate(()=>structuredClone(__test.foreground));
 await page.evaluate(()=>{__test.emit({type:'SCAN_COMPLETE',context:{origin:'MONITORING',sessionId:'old-monitor'}});__test.emit({type:'SCAN_CANCELLED'});__test.emit({type:'PHASE_PROGRESS',data:{running:false}})});
 check(await stop().isVisible()&&await scanning().isVisible(),'stale monitoring and unclassified events cannot terminate manual scan');
 await stop().click();await scan().waitFor();check(await scan().isVisible()&&await scanning().count()===0,'manual Stop returns foreground UI to Scan');
 check(await page.evaluate(id=>__test.requests.filter(r=>r.path.endsWith('/discovery/stop')).at(-1).body.sessionId===id,manual.session.sessionId),'Stop request carries exact foreground session ID');
 check(await page.evaluate(()=>__test.monitoring.enabled),'manual Stop preserves background monitoring');
 await page.clock.runFor(30000);check(await scan().isVisible()&&await scanning().count()===0,'next scheduled cycle after Stop remains background-only');
 await scan().click();await stop().waitFor();const newer=await page.evaluate(()=>structuredClone(__test.foreground));
 await page.evaluate(old=>__test.emit({type:'FOREGROUND_SCAN_STATE',context:old.session,data:{foreground:{...old,session:{...old.session,state:'COMPLETED'}}}}),manual);
 check(await stop().isVisible(),'stale manual terminal snapshot cannot overwrite newer scan');
 await page.evaluate(()=>{const s=__test.foreground.session;const foreground=__test.advance(s.origin,'COMPLETED',s.sessionId);__test.emit({type:'FOREGROUND_SCAN_STATE',context:s,data:{foreground}})});await scan().waitFor();check(await scan().isVisible(),'current manual completion returns Scan through classified WS');
 await page.clock.runFor(30000);check(await scan().isVisible()&&await page.evaluate(()=>__test.monitoring.enabled),'monitor continues after successful manual completion');
 await page.getByRole('button',{name:'Scan choices'}).click();await page.getByRole('button',{name:/^Advanced Scan/}).click();await page.getByRole('button',{name:'Start Advanced Scan',exact:true}).waitFor();await page.clock.runFor(400);await page.getByRole('button',{name:'Start Advanced Scan',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});await stop().waitFor();
 await page.clock.runFor(3200);check(await page.getByText(/Monitor:.*discovery deferred/).count()===1,'foreground ownership visibly defers discovery without disabling Diagnostics');
 check(await page.evaluate(()=>__test.foreground.session.origin==='ADVANCED')&&await scanning().isVisible(),'accepted Advanced start owns explicit foreground progress');
 await page.evaluate(old=>__test.emit({type:'FOREGROUND_SCAN_STATE',context:old.session,data:{foreground:{...old,session:{...old.session,state:'CANCELLED'}}}}),newer);check(await stop().isVisible(),'old manual event cannot finish current Advanced scan');
 await stop().click();await scan().waitFor();check(await page.evaluate(()=>__test.requests.filter(r=>r.path.endsWith('/discovery/stop')).at(-1).body.sessionId===__test.foreground.session.sessionId),'Advanced Stop targets the displayed Advanced session only');
 await page.evaluate(()=>{__test.advance('MANUAL','SCANNING');const s=__test.sockets.at(-1);s.onclose?.(new Event('close'))});await page.clock.runFor(3200);await stop().waitFor();check(await stop().isVisible(),'HTTP fallback recovers explicit foreground session after socket loss');
 await page.evaluate(()=>{const s=__test.foreground.session;__test.advance('MANUAL','COMPLETED',s.sessionId);__test.monitoring.running=true;});await page.clock.runFor(3200);await scan().waitFor();check(await scan().isVisible()&&await scanning().count()===0,'HTTP completion with monitor running does not retain foreground Stop');
 await page.evaluate(()=>__test.quickMode='hold');await scan().click();await page.evaluate(()=>{clearInterval(window.monitorTimer);document.dispatchEvent(new Event('unmount-test'))});await page.evaluate(()=>__test.pending.forEach(p=>p.resolve()));check(await page.evaluate(()=>__test.aborts>0),'shutdown aborts pending foreground HTTP action and ignores late success');const before=await page.evaluate(()=>__test.requests.length);await page.clock.runFor(20000);check(await page.evaluate(()=>__test.requests.length)===before,'App shutdown cancels HTTP poll timers');check(errors.length===0,'monitor/manual/Advanced transitions produce no browser runtime errors');
 console.log(`Scan monitoring browser: ${passed} passed, 0 failed, 0 skipped`);
 }finally{await browser.close()}})().catch(error=>{console.error(error);process.exitCode=1});
