// UI-only Vite; actual in-memory Tasks, diagnostic engine, project storage and collision reconciliation.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),{mock}=require('./advanced_scan.cjs');let passed=0;
const check=(v,n)=>{assert.ok(v,n);passed++;console.log('PASS: '+n)};
(async()=>{
 const {SiteProjectDatabase}=await import('../../core/storage/project_db.ts'),{TaskManager}=await import('../../core/tasks/task_manager.ts'),{DeviceDiagnosticEngine}=await import('../../core/engine/diagnostic_engine.ts'),{Phase4IdentityReconciliation}=await import('../../core/engine/phase4_reconcile.ts');
 const db=new SiteProjectDatabase(),tasks=new TaskManager();let requests=0,saves=0,mode='ok',taskOffline=false,gates=[],runs=[];const backendRequests=[];
 const camera=(id,ip='192.168.1.100')=>({id,anchor:{macAddress:null,onvifEndpointUuid:'uuid-'+id,vendor:'Fixture'},technician:{name:id},network:{ipAddress:ip,subnetMask:'255.255.255.0',port:80,protocol:'ONVIF'},status:'ONLINE',sessionVerification:'VERIFIED',discoveredPhase:3,firstSeenAt:new Date().toISOString(),lastSeenAt:new Date().toISOString(),reachability:{subnetClassification:'LOCAL'}});
 db.createNewProject('Attention');[camera('A'),camera('B')].forEach(d=>db.upsertDevice(d));await Phase4IdentityReconciliation.execute(db);db.exportProjectJsonForSave();
 const browser=await chromium.launch({channel:'msedge',headless:true});try{
  const page=await browser.newPage({viewport:{width:1100,height:720}}),errors=[];page.on('pageerror',e=>errors.push(String(e)));await mock(page);
  const publish=async(event)=>page.evaluate(event=>{const s=__test.sockets.at(-1);s.readyState=1;s.onopen?.(new Event('open'));__test.emit(event)},event);
  const publishProject=()=>publish({type:'PROJECT_SESSION_CHANGED',data:{session:db.getSession()}});
  const release=async()=>{gates.splice(0).forEach(fn=>fn());await Promise.all(runs.splice(0));};
  await page.exposeFunction('attentionBackend',async(path,body)=>{
   backendRequests.push({path,body});if(path==='/api/tasks'){if(taskOffline)throw Error('Task service unavailable');return{body:tasks.snapshot()};}if(path==='/api/project/session')return{body:db.getSession()};if(path==='/api/project')return{body:db.getProject()};
   if(path==='/api/project/save-content'){saves++;return{body:{content:db.exportProjectJsonForSave()}}}
   if(path==='/api/diagnostics/run'){
    requests++;if(mode==='reject')return{status:500,body:{error:'Injected request failure'}};
    const ids=[...new Set(body.deviceIds)],id=tasks.begin('DIAGNOSTICS'),cancelled=mode==='cancel',failed=mode==='fail';tasks.diagnosticTargets(id,ids);tasks.update(id,{state:'RUNNING',phase:'WORKING',progress:{completed:0,total:ids.length}});
    let finished=0;for(const deviceId of ids){const device=structuredClone(db.getDeviceById(deviceId));const gate=new Promise(resolve=>gates.push(resolve));const evidence=async(type,ip,success,extra={})=>{await gate;if(failed)throw Error('private provider failure');return{type,targetIp:ip,success,timestamp:new Date().toISOString(),...extra}};
     const engine=new DeviceDiagnosticEngine({ping:{check:ip=>evidence('PING',ip,false,{errorCategory:'TIMEOUT'})},http:{check:(ip,o)=>evidence(o.protocol==='https'?'HTTPS':'HTTP',ip,true,{httpStatus:200,responseTimeMs:12,certificateTrusted:o.protocol!=='https',certificateWarning:o.protocol==='https'?'Untrusted certificate':undefined})},tcp:{check:(ip,o)=>evidence('TCP',ip,true,{port:o.port})}});
     const work=engine.diagnose(device,{ambiguousIdentity:true,onEvidence:(e,d)=>void publish({type:'DIAGNOSTIC_EVIDENCE',data:{taskId:id,device:d,evidence:e}})}).then(async d=>{if(!cancelled){db.applyDiagnosticRefresh(d);await publish({type:'DEVICE_DIAGNOSTICS_UPDATED',data:{device:d,project:db.getProject()}})}tasks.diagnosticResult(id,deviceId,cancelled?'CANCELLED':'COMPLETED')}).catch(()=>tasks.diagnosticResult(id,deviceId,'FAILED')).finally(()=>{finished++;tasks.update(id,{state:finished<ids.length?'RUNNING':failed?'FAILED':cancelled?'CANCELLED':'COMPLETED',phase:finished<ids.length?'WORKING':failed?'FAILED':cancelled?'CANCELLED':'DONE',progress:{completed:finished,total:ids.length}})});runs.push(work);
    }return{status:202,body:{taskId:id,started:ids}};
   }return{body:{}};
  });
  await page.addInitScript(()=>{const old=fetch;window.fetch=async(url,o={})=>{const path=new URL(url,location.href).pathname;if(['/api/tasks','/api/project','/api/project/session','/api/project/save-content','/api/diagnostics/run'].includes(path)){const r=await attentionBackend(path,o.body?JSON.parse(o.body):{});return new Response(JSON.stringify(r.body),{status:r.status||200,headers:{'Content-Type':'application/json'}})}if(path==='/api/pair/eligibility')return new Response(JSON.stringify({id:new URL(url).searchParams.get('deviceId'),network:{ipAddress:'192.168.1.100'},anchor:{vendor:'Fixture'},status:'COLLISION'}));return old(url,o)}});
  await page.goto('http://127.0.0.1:5179/src/test/browser/advanced_scan.html?app');
  const inspector=page.getByRole('dialog',{name:'Device Inspector',exact:true}),assistant=page.getByRole('dialog',{name:'Duplicate IP Assistant',exact:true}),taskPanel=page.getByRole('dialog',{name:'Tasks',exact:true});
  const row=id=>page.locator('tbody tr').filter({has:page.getByRole('button',{name:'Actions for '+id,exact:true})});
  const diagnose=async(id)=>{await page.getByRole('button',{name:'Actions for '+id,exact:true}).click();await page.getByRole('menuitem',{name:'Diagnose',exact:true}).click();await inspector.waitFor();};
  await diagnose('A');await inspector.getByText('Diagnostics: Running',{exact:true}).waitFor();check(requests===1&&tasks.snapshot().tasks.length===1,'T01/T09/T15 row Diagnose starts exactly one operation');
  check((await inspector.textContent()).includes('A')&&await inspector.getByRole('button',{name:'Diagnostics',exact:true}).evaluate(e=>e===document.activeElement),'T02/T03 correct Inspector Diagnostics focused');
  check(await inspector.getByRole('button',{name:'Diagnose Now',exact:true}).isDisabled(),'T04 running progress visible and repeated action disabled');await release();await inspector.getByText('Diagnostics: Completed',{exact:true}).waitFor();
  check(await inspector.getByText('HTTP 200',{exact:true}).count()===2&&await inspector.getByText(/TLS: Untrusted/).count()===1,'T05 completion shows real HTTP/HTTPS and TLS evidence without Tasks');
  check(db.getDeviceById('A').status==='COLLISION'&&(await inspector.textContent()).includes('does not establish browser, login'),'T07/T08 failed ping does not rewrite status or imply login');check(!db.getSession().dirty,'T16 diagnostic completion leaves saved project clean');
  await inspector.getByRole('button',{name:'Identity & Network',exact:true}).click();await inspector.getByRole('button',{name:'Diagnostics',exact:true}).click();mode='fail';await inspector.getByRole('button',{name:'Diagnose Now',exact:true}).click();await inspector.getByText('Diagnostics: Running',{exact:true}).waitFor();await release();await inspector.getByText('Diagnostics: Failed',{exact:true}).waitFor();check(requests===2,'T06/T10 Inspector uses same path and shows failure');
  mode='cancel';await inspector.getByRole('button',{name:'Diagnose Now',exact:true}).click();await inspector.getByText('Diagnostics: Running',{exact:true}).waitFor();await release();await inspector.getByText('Diagnostics: Cancelled',{exact:true}).waitFor();check(true,'cancelled state distinct from completion');
  mode='reject';await inspector.getByRole('button',{name:'Diagnose Now',exact:true}).click();await inspector.getByText(/request failed or was not acknowledged/).waitFor();check(true,'request rejection visibly explains unavailable acknowledgment');mode='ok';
  await inspector.getByRole('button',{name:'Close',exact:true}).click();const footer=page.locator('footer').filter({hasText:'Monitor:'});const collisions=footer.getByRole('button',{name:'Collisions: 1',exact:true});await collisions.focus();await page.keyboard.press('Enter');await assistant.waitFor();check(await assistant.locator('article').count()===2,'T18/T19/T40 collision attention keyboard opens single group');
  await assistant.getByRole('article',{name:'Participant A',exact:true}).getByRole('button',{name:'Diagnose',exact:true}).click();await inspector.waitFor();await inspector.getByText('Diagnostics: Running',{exact:true}).waitFor();check(await assistant.count()===0&&requests===5,'T11 Duplicate Assistant routes cleanly to participant Inspector');await release();await inspector.getByText('Diagnostics: Completed',{exact:true}).waitFor();
  await inspector.getByRole('button',{name:'Open Camera',exact:true}).click();const access=page.getByRole('dialog',{name:'Camera Access',exact:true});await access.waitFor();check(await access.locator('iframe').count()===0&&await access.getByRole('button',{name:'Open External',exact:true}).isDisabled(),'T12/T49 diagnostics cannot bypass shared-IP Open block');await access.getByRole('button',{name:'Close Camera Access'}).click();await inspector.getByRole('button',{name:'Close',exact:true}).click();
  db.upsertDevice(camera('C','192.168.1.200'),'DEVICE_ADDED',true);db.upsertDevice(camera('D','192.168.1.200'),'DEVICE_ADDED',true);db.upsertDevice(camera('E'),'DEVICE_ADDED',true);await Phase4IdentityReconciliation.execute(db);await publishProject();
  await footer.getByRole('button',{name:'Collisions: 2',exact:true}).click();const chooser=page.getByRole('dialog',{name:'Choose collision'});await chooser.waitFor();check(await assistant.count()===0,'T20/T21 multiple collisions open chooser without arbitrary selection');check(await chooser.getByRole('button',{name:'192.168.1.100 — 3 devices',exact:true}).count()===1,'T23 three participants produce one choice');await chooser.getByRole('button',{name:'192.168.1.200 — 2 devices',exact:true}).focus();await page.keyboard.press('Space');await assistant.waitFor();check(await assistant.getByRole('article',{name:'Participant C',exact:true}).count()===1&&await chooser.count()===0,'T22/T41 accessible chooser opens correct group');await assistant.getByRole('button',{name:'Close Duplicate Assistant'}).click();
  db.upsertDevice(camera('A','192.168.1.168'),'DEVICE_ADDED',true);db.upsertDevice(camera('E','192.168.1.169'),'DEVICE_ADDED',true);db.upsertDevice(camera('C','192.168.1.201'),'DEVICE_ADDED',true);await Phase4IdentityReconciliation.execute(db);await publishProject();await footer.getByText('Collisions: 0',{exact:true}).waitFor();check(await footer.getByRole('button',{name:/Collisions/}).count()===0&&db.getCollisions().length===2,'T24/T25/T26 resolved history excluded; zero passive');
  check(await footer.getByText(/Devices:/).evaluate(e=>!e.closest('button'))&&await footer.getByText(/Monitor:/).evaluate(e=>!e.closest('button')),'T42 devices and monitor remain informational');
  await row('A').getByRole('checkbox').check();await row('B').getByRole('checkbox').check();await page.getByRole('button',{name:'Diagnose Selected',exact:true}).click();await taskPanel.waitFor();await taskPanel.getByRole('region',{name:'Task details'}).waitFor();check(await inspector.count()===0&&requests===6,'T13/T14 bulk opens one existing Tasks summary');
  await release();const detail=taskPanel.getByRole('region',{name:'Task details'});await detail.getByRole('button',{name:/Inspect A — COMPLETED/}).waitFor();await detail.getByRole('button',{name:/Inspect A — COMPLETED/}).click();await inspector.waitFor();check(await taskPanel.count()===0&&requests===6,'bulk device selection opens evidence without new diagnostic Task');await inspector.getByRole('button',{name:'Close',exact:true}).click();
  const taskCount=tasks.snapshot().tasks.length;await footer.getByRole('button',{name:/Tasks:/}).focus();await page.keyboard.press('Enter');await taskPanel.waitFor();check(tasks.snapshot().tasks.length===taskCount,'T27/T28 Tasks attention opens existing history without operation');
  // Put enough existing tasks above details to require a scroll; selection must reveal detail.
  for(let i=0;i<15;i++){const id=tasks.begin('SCAN');tasks.update(id,{state:'COMPLETED',phase:'DONE'});}await page.waitForTimeout(1700);await taskPanel.getByRole('button',{name:/Quick Scan COMPLETED/}).first().click();await detail.waitFor();check(await detail.evaluate(e=>e===document.activeElement),'T29 Task detail receives focus');check(await detail.evaluate(e=>{const r=e.getBoundingClientRect(),p=e.parentElement.getBoundingClientRect();return r.top>=p.top&&r.top<p.bottom}),'T30 selected Task detail scrolls into view');await taskPanel.getByRole('button',{name:/Quick Scan COMPLETED/}).first().click();check(await detail.evaluate(e=>e===document.activeElement),'reselecting the same Task still foregrounds its detail');check(tasks.snapshot().tasks.length===taskCount+15,'T31 selection preserves Task state/history');await taskPanel.getByRole('button',{name:'Close Tasks'}).click();
  check(await footer.getByRole('button',{name:'Unsaved changes',exact:true}).count()===0,'T37 clean Project has no Save attention');db.updateDeviceTechnicianFields('A',{notes:'Persistent technician edit'});await publishProject();const unsaved=footer.getByRole('button',{name:'Unsaved changes',exact:true});await unsaved.focus();await page.keyboard.press('Enter');const save=page.getByRole('dialog',{name:'Unsaved project changes'});await save.waitFor();check(saves===0&&await save.getByRole('button',{name:'Save Project',exact:true}).count()===1,'T32/T33/T34 indicator reveals existing Save without saving');
  const download=page.waitForEvent('download');await save.getByRole('button',{name:'Save Project',exact:true}).click();await download;await save.waitFor({state:'detached'});check(saves===1&&!db.getSession().dirty&&await unsaved.count()===0,'T35 explicit Save downloads and clears real dirty state');
  db.updateDeviceTechnicianFields('A',{notes:'Another edit'});await publishProject();await unsaved.click();page.once('dialog',d=>d.accept('Attention-copy.cctvproj'));const saveAs=page.waitForEvent('download');await save.getByRole('button',{name:'Save As',exact:true}).click();check((await saveAs).suggestedFilename()==='Attention-copy.cctvproj'&&saves===2,'T36 Save As retains filename prompt/download');
  const ids=db.getDevices().map(d=>d.id).join(','),members=db.getProjectMemberDevices().map(d=>d.id).join(',');check(ids==='A,B,C,D,E'&&members==='A,B','T46/T47 navigation preserves identity and saved membership');
  check(!backendRequests.some(r=>/pair\/(confirm|restore)|configuration|credentials/.test(r.path)),'T43-T45 navigation has no adapter/camera/credential calls');await diagnose('A');await inspector.getByText('Diagnostics: Running',{exact:true}).waitFor();await release();await inspector.getByText('Diagnostics: Completed',{exact:true}).waitFor();await inspector.getByRole('button',{name:'Identity & Network',exact:true}).click();await inspector.getByRole('button',{name:'Close',exact:true}).click();await diagnose('B');await inspector.getByText('Diagnostics: Running',{exact:true}).waitFor();check(await inspector.getByRole('button',{name:'Diagnostics',exact:true}).getAttribute('aria-pressed')==='true'&&await inspector.getByRole('button',{name:'Diagnostics',exact:true}).evaluate(e=>e===document.activeElement),'Diagnose resets a previously selected Identity tab and focuses Diagnostics');await release();await inspector.getByText('Diagnostics: Completed',{exact:true}).waitFor();taskOffline=true;await inspector.getByText('Diagnostics: Unavailable',{exact:true}).waitFor();check(true,'lost Tasks status cannot imply stale completion or ongoing progress');taskOffline=false;await inspector.getByText('Diagnostics: Completed',{exact:true}).waitFor();await inspector.getByRole('button',{name:'Close',exact:true}).click();db.startQuickWork();await publishProject();await page.waitForTimeout(50);check(await footer.getByRole('button',{name:'Unsaved changes',exact:true}).count()===0,'T39 Quick Work has no false Save attention');
  check(errors.length===0,'no browser runtime errors');
 }finally{await browser.close()}
 console.log(`Phase 8 browser: ${passed} passed, 0 failed, 0 skipped`);
})().catch(e=>{console.error(e);process.exitCode=1});
