const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');const {mock}=require('./advanced_scan.cjs');
let passed=0;const check=(v,n)=>{assert.ok(v,n);passed++;console.log('PASS: '+n)};
async function setup(page){await mock(page);await page.addInitScript(()=>{
 const base=window.fetch.bind(window),json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}});
 const adapter={interfaceIndex:8,interfaceAlias:'Ethernet',mediaType:'ETHERNET',operationalStatus:'Up',eligible:true,dhcpEnabled:false,ipv4Addresses:[{address:'192.168.0.124',prefixLength:24}],defaultGateways:[],dnsAutomatic:true,dnsServers:[],capturedAt:'now'};
 const t=window.__v1={adapter,adapterMode:'ok',pair:null,prepareFailed:false,plan:null,planCalls:0,applies:0,historyHeld:false,oldHeld:false};
 __test.project={id:'quick',name:'Quick Work',devices:[],collisions:[],rogueDhcpEvents:[],auditLogs:[],totalDevices:0};
 window.fetch=async(url,options={})=>{const path=String(url);const body=options.body?JSON.parse(options.body):{};
  if(path.endsWith('/pair/adapters'))return json(t.adapterMode==='malformed'?{}:t.adapterMode==='empty'?[]:[adapter]);
  if(path.endsWith('/pair/status')){if(t.prepareFailed)throw Error('status unavailable');return json(t.pair)}
  if(path.endsWith('/network-match/prepare')){t.prepareFailed=true;return json({presentation:{message:'Administrator privileges are required.',reference:'OP-V1TEST01'},error:'private stack'},403)}
  if(path.endsWith('/api/tasks'))return json({tasks:t.pair?[{id:'preview',correlationId:t.pair.id,title:'Pair PC to Camera Network',kind:'PAIR',state:'NEEDS_ATTENTION',phase:'Review the preview and explicitly confirm',startedAt:new Date().toISOString(),updatedAt:new Date().toISOString(),cancellable:false,result:'NETWORK_RECOVERY'}]:[],active:0,attention:t.pair?1:0,monitoring:{enabled:true,status:'WAITING'}});
  if(path.includes('/api/project/history')){const event={id:'new',title:'Current filter',summary:'Safe history',timestamp:new Date().toISOString(),type:'DEVICE_ADDED'};if(!path.includes('filter=ALL'))return json({events:[event]});if(t.historyHeld)return new Promise(resolve=>{t.releaseHistory=()=>resolve(json({events:[{...event,title:'Stale history'}]}))});return json({events:[]});}
  if(path.endsWith('/reports/preview'))return json({error:'No valid selection is available for this fixture.'},400);
  if(path.endsWith('/bulk/network/plan')){t.planCalls++;t.plan={batchId:'batch-v1',state:'READY',totalSelected:2,eligibleCount:2,blockedCount:0,readyCount:2,estimatedOperationCount:6,items:['a','b'].map((id,index)=>({deviceId:id,name:id,currentIp:`192.0.2.${index+10}`,targetIp:body.manualTargets?.[id]||`192.168.1.${index+101}`,targetPrefix:24,eligibility:'ELIGIBLE',validation:'READY',state:'PENDING',errors:[],order:index}))};return json(t.plan);}
  if(path.endsWith('/bulk/network/batch-v1/apply')){t.applies++;t.plan.state='EXECUTING';return new Promise(resolve=>{t.releaseApply=()=>{t.plan={...t.plan,state:'COMPLETED'};resolve(json(t.plan));}})}
  if(path.endsWith('/bulk/network/batch-v1')){if(t.holdPoll)return new Promise(resolve=>{const old={...t.plan};t.releasePoll=()=>resolve(json(old))});return json(t.plan)}
  if(path.includes('/api/connect/')){if(path.includes('/credentials'))return json({references:[],selectedCredentialId:''});if(path.endsWith('/old')&&t.oldHeld)return new Promise(resolve=>{t.releaseOld=()=>resolve(json({endpoint:{url:'https://192.0.2.99'},readiness:{warning:'STALE DEVICE'}}))});return json({endpoint:{url:'about:blank',verified:false,source:'fixture'},readiness:{warning:'Current device'}});}
  return base(url,options);
 };
 });}
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(String(e)));await setup(page);await page.goto('http://127.0.0.1:5179/src/test/browser/advanced_scan.html?app');
 await page.getByText('Ethernet • 192.168.0.124',{exact:true}).waitFor();check(true,'fresh adapter badge resolves without a foreground Scan');
 check(await page.getByRole('button',{name:'Scan',exact:true}).isVisible(),'fresh foreground Scan idle');
 check(await page.getByText('Quick Work',{exact:false}).count()>0,'fresh Quick Work requires no project');
 check(await page.getByRole('dialog').count()===0,'startup shows no unnecessary recovery modal');
 check(await page.locator('tbody tr').count()<=1,'fresh inventory contains no seeded camera');
 await page.getByRole('button',{name:'Tasks',exact:true}).click();await page.getByText('No recent technician tasks.').waitFor();check(true,'empty Tasks is intentional');await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Tools',exact:true}).click();await page.getByRole('button',{name:'Network Adapter',exact:true}).click();const network=page.getByRole('dialog',{name:'Network Adapter'});await network.getByText('192.168.0.124/24',{exact:true}).waitFor();
 check(await network.evaluate(e=>e.contains(document.activeElement)),'Network Adapter receives keyboard focus');await page.keyboard.press('Escape');check(await network.count()===0,'Network Adapter Escape closes and clears overlay');
 await page.getByRole('button',{name:'Tools',exact:true}).click();await page.getByRole('button',{name:'Add Device Manually'}).click();await page.getByRole('heading',{name:'Add Device Manually'}).waitFor();check(true,'manual onboarding opens without hardware');await page.getByRole('button',{name:/Close/}).click();
 await page.getByRole('button',{name:'Tools',exact:true}).click();await page.getByRole('button',{name:'Reports',exact:true}).click();await page.getByRole('heading',{name:'Reports & Field Documentation'}).waitFor();check(await page.getByRole('button',{name:'pdf',exact:true}).isDisabled(),'empty/invalid report selection cannot export stale preview');await page.getByRole('button',{name:'Close reports'}).click();
 await page.evaluate(()=>__test.statusMode='network');await page.getByText('Diagnostics: Unavailable',{exact:true}).waitFor();check(true,'unavailable monitoring overrides stale enabled state');await page.evaluate(()=>__test.statusMode='ok');await page.getByText(/^Diagnostics: Active/).waitFor();
 for(const name of ['General','Device Table / Columns','Diagnostics & Support','About']){await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name,exact:true}).click();check(await page.getByRole('button',{name:'Back to Settings'}).isVisible(),`Settings ${name} opens and has Back`);await page.keyboard.press('Escape');}
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'General',exact:true}).click();await page.getByLabel('Browser preference').selectOption('EDGE');await page.keyboard.press('Escape');await page.reload();await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'General',exact:true}).click();check(await page.getByLabel('Browser preference').inputValue()==='EDGE','visible browser preference persists');await page.keyboard.press('Escape');
 await page.evaluate(()=>{__v1.adapterMode='malformed'});await page.getByRole('button',{name:'Tools',exact:true}).click();await page.getByRole('button',{name:'Network Adapter',exact:true}).click();await network.getByRole('alert').waitFor();check(await network.getByRole('button',{name:'Preview Temporary Configuration'}).isDisabled(),'malformed adapter data fails safely without rendering crash');
 await page.evaluate(()=>__v1.adapterMode='ok');await network.getByRole('button',{name:'Reload Adapters'}).click();await network.getByText('192.168.0.124/24',{exact:true}).waitFor();await network.getByLabel('Temporary IPv4',{exact:true}).fill('192.168.1.130');await network.getByRole('button',{name:'Preview Temporary Configuration'}).click();await network.getByRole('alert').filter({hasText:'OP-V1TEST01'}).waitFor();check(!(await network.innerText()).includes('private stack'),'failed mutation/status read keeps safe reference without raw error');await page.keyboard.press('Escape');
 await page.evaluate(()=>{__v1.prepareFailed=false;__v1.pair={id:'pair-preview',purpose:'CAMERA_PAIR',state:'READY_FOR_CONFIRMATION',deviceId:'missing-row',cameraIp:'192.168.1.100',adapter:{interfaceIndex:8,interfaceAlias:'Ethernet',ipv4Addresses:[{address:'192.168.0.124',prefixLength:24}]},originalAdapter:structuredClone(__v1.adapter),candidates:[{ipAddress:'192.168.1.137',prefixLength:24,confidence:'AVAILABLE',evidence:[]}],selectedCandidate:{ipAddress:'192.168.1.137',prefixLength:24,confidence:'AVAILABLE',evidence:[]},recoveryAvailable:false}});
 await page.getByRole('button',{name:'Tasks • 1 need attention',exact:true}).waitFor();await page.getByRole('button',{name:'Tasks • 1 need attention',exact:true}).click();await page.getByRole('button',{name:/Pair PC to Camera Network NEEDS ATTENTION/}).click();await page.getByRole('button',{name:'View Network Recovery'}).click();await page.getByRole('heading',{name:'Pair PC to Camera Network'}).waitFor();check(true,'Tasks reopens authoritative Pair preview without inventory row');
 check(errors.length===0,'primary shell navigation produces no browser runtime errors');await page.close();

 const bulk=await browser.newPage();await setup(bulk);await bulk.goto('http://127.0.0.1:5179/src/test/browser/v1_integration.html?bulk');await bulk.getByRole('button',{name:'Build & Validate Plan'}).click();await bulk.getByRole('checkbox').check();const apply=bulk.getByRole('button',{name:'Apply Network Changes'});check(await apply.isEnabled(),'validated confirmed bulk plan can apply');
 await bulk.getByLabel('Target IP for a').fill('192.168.1.150');check(await apply.isDisabled(),'editing target disables Apply');check(!(await bulk.getByRole('checkbox').isChecked()),'editing target clears confirmation');await bulk.getByRole('button',{name:'Validate Overrides'}).click();await bulk.waitForFunction(()=>__v1.planCalls===2);await bulk.getByRole('checkbox').check();await bulk.evaluate(()=>__v1.holdPoll=true);await apply.click();await bulk.waitForFunction(()=>__v1.releaseApply&&__v1.releasePoll);await bulk.evaluate(()=>__v1.releaseApply());await bulk.getByText('Batch state: COMPLETED').waitFor();await bulk.evaluate(()=>__v1.releasePoll());await bulk.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));check(await bulk.getByText('Batch state: COMPLETED').isVisible(),'late bulk progress cannot overwrite completion');check(await bulk.evaluate(()=>__v1.applies===1&&__v1.plan.items[0].targetIp==='192.168.1.150'),'one Apply uses revalidated target');await bulk.close();

 const access=await browser.newPage();await setup(access);await access.addInitScript(()=>__v1.oldHeld=true);await access.goto('http://127.0.0.1:5179/src/test/browser/v1_integration.html');await access.waitForFunction(()=>__v1.releaseOld);await access.getByRole('button',{name:'Switch device'}).click();await access.getByText('Current device',{exact:true}).waitFor();await access.evaluate(()=>__v1.releaseOld());await access.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));check(await access.getByText('STALE DEVICE').count()===0,'late Camera Access result cannot replace another device');check(await access.locator('input[type=password]').inputValue()==='','new device has no retained password');await access.close();
 const history=await browser.newPage();await setup(history);await history.addInitScript(()=>__v1.historyHeld=true);await history.goto('http://127.0.0.1:5179/src/test/browser/v1_integration.html?history');await history.waitForFunction(()=>__v1.releaseHistory);await history.getByRole('button',{name:'Device',exact:true}).click();await history.getByText('Current filter',{exact:true}).waitFor();await history.evaluate(()=>__v1.releaseHistory());await history.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));check(await history.getByText('Stale history').count()===0,'late Project History filter response ignored');await history.close();
 console.log(`V1 browser integration: ${passed} passed, 0 failed, 0 skipped`);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
