import type{CameraConfigurationOperation}from'./camera_configuration.ts';
export type BulkCapabilityId='NETWORK_IP'|'SUBNET_MASK'|'GATEWAY'|CameraConfigurationOperation|'REPORT_SELECTED';export type BulkCapabilityClassification='PRODUCTION_READY'|'IMPLEMENTABLE_EXISTING_PROVIDER'|'PROVIDER_HARDWARE_DEPENDENT'|'NOT_BULK_CONFIGURATION';
export interface BulkCapabilityDefinition{id:BulkCapabilityId;label:string;classification:BulkCapabilityClassification;executableInBulkConfigure:boolean;providerAware:boolean;requiresAuthentication:boolean;requiresReachableNetwork:boolean;requiresUniqueIdentity:boolean;blockedByDuplicateIp:boolean;verificationAvailable:boolean;safeForMultiDevice:boolean;softwareValidated:boolean;hardwareValidationPending:boolean;reason:string}
export const V1_BULK_CAPABILITIES:readonly BulkCapabilityDefinition[]=[
 {id:'NETWORK_IP',label:'Network / IP',classification:'PRODUCTION_READY',executableInBulkConfigure:false,providerAware:true,requiresAuthentication:true,requiresReachableNetwork:true,requiresUniqueIdentity:true,blockedByDuplicateIp:true,verificationAvailable:true,safeForMultiDevice:true,softwareValidated:true,hardwareValidationPending:true,reason:'Executed through the dedicated safe Bulk Re-IP workflow.'},
 {id:'SUBNET_MASK',label:'Subnet mask',classification:'PRODUCTION_READY',executableInBulkConfigure:false,providerAware:true,requiresAuthentication:true,requiresReachableNetwork:true,requiresUniqueIdentity:true,blockedByDuplicateIp:true,verificationAvailable:true,safeForMultiDevice:true,softwareValidated:true,hardwareValidationPending:true,reason:'Configured and verified as part of each target in the dedicated safe Bulk Re-IP workflow.'},
 {id:'GATEWAY',label:'Gateway',classification:'PRODUCTION_READY',executableInBulkConfigure:false,providerAware:true,requiresAuthentication:true,requiresReachableNetwork:true,requiresUniqueIdentity:true,blockedByDuplicateIp:true,verificationAvailable:true,safeForMultiDevice:true,softwareValidated:true,hardwareValidationPending:true,reason:'Configured and verified as part of each target in the dedicated safe Bulk Re-IP workflow.'},
 {id:'DEVICE_NAME',label:'Physical camera hostname',classification:'IMPLEMENTABLE_EXISTING_PROVIDER',executableInBulkConfigure:true,providerAware:true,requiresAuthentication:true,requiresReachableNetwork:true,requiresUniqueIdentity:true,blockedByDuplicateIp:true,verificationAvailable:true,safeForMultiDevice:true,softwareValidated:true,hardwareValidationPending:true,reason:'Provider capability must be authenticated and verified per camera; this is distinct from technician-local Name.'},
 {id:'NTP',label:'NTP configuration',classification:'PRODUCTION_READY',executableInBulkConfigure:true,providerAware:true,requiresAuthentication:true,requiresReachableNetwork:true,requiresUniqueIdentity:true,blockedByDuplicateIp:true,verificationAvailable:true,safeForMultiDevice:true,softwareValidated:true,hardwareValidationPending:true,reason:'Authenticated provider read/write/reread verification is available.'},
 {id:'TIME_ZONE',label:'Timezone configuration',classification:'PRODUCTION_READY',executableInBulkConfigure:true,providerAware:true,requiresAuthentication:true,requiresReachableNetwork:true,requiresUniqueIdentity:true,blockedByDuplicateIp:true,verificationAvailable:true,safeForMultiDevice:true,softwareValidated:true,hardwareValidationPending:true,reason:'Authenticated provider read/write/reread verification is available.'},
 {id:'REBOOT',label:'Reboot',classification:'PRODUCTION_READY',executableInBulkConfigure:true,providerAware:true,requiresAuthentication:true,requiresReachableNetwork:true,requiresUniqueIdentity:true,blockedByDuplicateIp:true,verificationAvailable:true,safeForMultiDevice:true,softwareValidated:true,hardwareValidationPending:true,reason:'Explicit confirmation and bounded provider reverification are required.'},
 {id:'ONVIF_ENABLE',label:'ONVIF enable / disable',classification:'PROVIDER_HARDWARE_DEPENDENT',executableInBulkConfigure:false,providerAware:true,requiresAuthentication:true,requiresReachableNetwork:true,requiresUniqueIdentity:true,blockedByDuplicateIp:true,verificationAvailable:false,safeForMultiDevice:false,softwareValidated:false,hardwareValidationPending:true,reason:'Vendor commands exist for limited models, but reliable post-write verification is not yet production-complete.'},
 {id:'PASSWORD',label:'Camera password change',classification:'PROVIDER_HARDWARE_DEPENDENT',executableInBulkConfigure:false,providerAware:true,requiresAuthentication:true,requiresReachableNetwork:true,requiresUniqueIdentity:true,blockedByDuplicateIp:true,verificationAvailable:true,safeForMultiDevice:false,softwareValidated:false,hardwareValidationPending:true,reason:'Partial-success recovery and credential rollover are not safe enough for V1 bulk execution.'},
 {id:'REPORT_SELECTED',label:'Report / export selected devices',classification:'NOT_BULK_CONFIGURATION',executableInBulkConfigure:false,providerAware:false,requiresAuthentication:false,requiresReachableNetwork:false,requiresUniqueIdentity:true,blockedByDuplicateIp:false,verificationAvailable:false,safeForMultiDevice:true,softwareValidated:true,hardwareValidationPending:false,reason:'This remains in Reports and does not execute camera configuration.'}
]as const;
export const BULK_EXECUTABLE_CONFIG_OPERATIONS=V1_BULK_CAPABILITIES.filter((cap):cap is BulkCapabilityDefinition&{id:CameraConfigurationOperation}=>cap.executableInBulkConfigure).map(cap=>cap.id);
export const bulkCapability=(id:BulkCapabilityId)=>V1_BULK_CAPABILITIES.find(cap=>cap.id===id);
