import{Device,IPCollisionRecord}from'../../types/index.ts';import{CameraNetworkConfigurationService,CameraNetworkResult,IpCandidate,NetworkPreview,NetworkTarget}from'../network/camera_network_service.ts';import{SiteProjectDatabase,projectDb}from'../storage/project_db.ts';import{OSCredentialVault,osVault}from'../storage/vault.ts';import{appStateDb}from'../storage/app_db.ts';
export class DuplicateRemediationError extends Error{constructor(message:string,public readonly code:string){super(message)}}
export interface DuplicateTargetability{targetable:boolean;provider?:string;reason:string}
export interface DuplicateTargetabilityProvider{assess(device:Device,collision:IPCollisionRecord,activeAtSharedIp:Device[]):Promise<DuplicateTargetability>}
export interface DuplicateNetworkEngine{findCandidates(deviceId:string,prefixLength:number,gateway?:string,signal?:AbortSignal):Promise<IpCandidate[]>;preview(deviceId:string,credentialId:string,target:NetworkTarget,signal?:AbortSignal):Promise<NetworkPreview>;apply(planId:string,confirmed:boolean):Promise<CameraNetworkResult>;cancel(deviceId:string):boolean;authorizeIsolatedDuplicate?(deviceId:string):void;revokeDuplicateAuthorization?(deviceId:string):void}
export class IsolationAwareTargetability implements DuplicateTargetabilityProvider{async assess(device:Device,_collision:IPCollisionRecord,active:Device[]){return active.length===1&&active[0].id===device.id?{targetable:true,provider:'ONVIF (isolated identity-bound session)',reason:'A technician-controlled rescan found only this stable identity active at the shared IP.'}:{targetable:false,reason:'Responses on the shared IP cannot be assigned to one physical camera. Disconnect equipment and Rescan.'}}}
export interface DuplicateRemediationPreview{remediationId:string;collisionId:string;deviceId:string;identity:{name?:string;stableId:string;macAddress:string|null;onvifEndpointUuid?:string;serialNumber?:string;manufacturer:string;model?:string};sharedIp:string;target:NetworkTarget;provider:string;credentialId:string;credentialLabel?:string;targetabilityProven:true;expectedEffect:string;verificationPlan:string;networkPlanId:string;createdAt:string}
const active=(device:Device)=>!['UNREACHABLE','OFFLINE','UNKNOWN'].includes(device.status);
export class DuplicateRemediationService{private previews=new Map<string,DuplicateRemediationPreview>();private executing:string|null=null;private cancelled=new Set<string>();constructor(private db:SiteProjectDatabase=projectDb,private vault:OSCredentialVault=osVault,private network:DuplicateNetworkEngine=new CameraNetworkConfigurationService(),private targeter:DuplicateTargetabilityProvider=new IsolationAwareTargetability()){}
 isActive(){return this.executing!==null}
 private collision(id:string){const collision=this.db.getCollisions().find(c=>c.id===id||c.ipAddress===id);if(!collision)throw new DuplicateRemediationError('Collision not found.','COLLISION_NOT_FOUND');return this.normalize(collision)}
 private normalize(c:IPCollisionRecord){c.id ||= crypto.randomUUID();c.deviceIds ||= c.collidingDevices.map(d=>d.id);c.updatedAt ||= c.detectedAt;c.state ||= c.resolved?'RESOLVED':'AMBIGUOUS';c.ambiguity ||= c.resolved?'CLEAR':'NONE_UNIQUELY_TARGETABLE';c.devices ||= c.deviceIds.map(deviceId=>{const d=this.db.getDeviceById(deviceId)!;return{deviceId,identity:{macAddress:d?.anchor.macAddress||null,onvifEndpointUuid:d?.anchor.onvifEndpointUuid,serialNumber:d?.anchor.serialNumber},targetable:false,targetabilityReason:'Not yet assessed.',credentialAvailable:Boolean(this.vault.getAssociation(deviceId)),state:'PENDING' as const}});return c}
 private device(c:IPCollisionRecord,id:string){if(!c.deviceIds?.includes(id))throw new DuplicateRemediationError('Device is not a member of this collision.','DEVICE_NOT_IN_COLLISION');const d=this.db.getDeviceById(id);if(!d)throw new DuplicateRemediationError('Stable device record not found.','DEVICE_NOT_FOUND');return d}
 async get(id:string){const c=this.collision(id),activeAtShared=this.db.getDevices().filter(d=>d.network.ipAddress===c.ipAddress&&active(d));for(const item of c.devices||[]){const d=this.db.getDeviceById(item.deviceId);if(!d)continue;const assessment=await this.targeter.assess(d,c,activeAtShared);item.targetable=assessment.targetable;item.targetabilityReason=assessment.reason;item.provider=assessment.provider;item.credentialAvailable=Boolean(this.vault.getAssociation(d.id));if(!assessment.targetable&&item.state==='PENDING')item.state='NEEDS_ISOLATION'}const targetable=(c.devices||[]).filter(x=>x.targetable).length;c.ambiguity=targetable===1?'ONE_UNIQUELY_TARGETABLE':targetable?'IDENTITIES_KNOWN_RESPONSES_AMBIGUOUS':'NONE_UNIQUELY_TARGETABLE';c.state=c.resolved?'RESOLVED':targetable?'IDENTIFIED':'NEEDS_ISOLATION';c.updatedAt=new Date().toISOString();this.db.recordCollision(c);return structuredClone(c)}
 async candidates(collisionId:string,deviceId:string,prefixLength:number,gateway?:string,signal?:AbortSignal){const c=await this.get(collisionId),item=c.devices?.find(x=>x.deviceId===deviceId);if(!item?.targetable)throw new DuplicateRemediationError(item?.targetabilityReason||'Physical target is ambiguous.','TARGET_AMBIGUOUS');this.network.authorizeIsolatedDuplicate?.(deviceId);try{return await this.network.findCandidates(deviceId,prefixLength,gateway,signal)}finally{this.network.revokeDuplicateAuthorization?.(deviceId)}}
 async preview(collisionId:string,deviceId:string,credentialId:string,target:NetworkTarget,signal?:AbortSignal){const c=await this.get(collisionId),d=this.device(c,deviceId),item=c.devices?.find(x=>x.deviceId===deviceId);if(!item?.targetable||!item.provider)throw new DuplicateRemediationError(item?.targetabilityReason||'Physical target is ambiguous.','TARGET_AMBIGUOUS');const credential=credentialId||this.vault.getAssociation(deviceId)||'';if(!credential||!this.vault.hasCredential(credential))throw new DuplicateRemediationError('A saved credential is required.','CREDENTIAL_NOT_FOUND');this.network.authorizeIsolatedDuplicate?.(deviceId);let networkPlan:NetworkPreview;try{networkPlan=await this.network.preview(deviceId,credential,target,signal)}catch(error){this.network.revokeDuplicateAuthorization?.(deviceId);throw error}const remediationId=crypto.randomUUID();const preview:DuplicateRemediationPreview={remediationId,collisionId:c.id!,deviceId,identity:{name:d.technician?.name,stableId:d.id,macAddress:d.anchor.macAddress,onvifEndpointUuid:d.anchor.onvifEndpointUuid,serialNumber:d.anchor.serialNumber,manufacturer:d.anchor.vendor,model:d.anchor.model},sharedIp:c.ipAddress,target,provider:item.provider,credentialId:credential,credentialLabel:this.vault.getCredential(credential)?.label,targetabilityProven:true,expectedEffect:'One identity-bound camera will move; the PC network will not change automatically.',verificationPlan:'Reverify the same stable identity at the target IP, then recheck active identities at the original shared IP.',networkPlanId:networkPlan.planId,createdAt:new Date().toISOString()};this.previews.set(remediationId,preview);item.proposedIp=target.ipAddress;item.provider=item.provider;item.state='READY';c.state='READY';c.updatedAt=new Date().toISOString();this.db.recordCollision(c);return structuredClone(preview)}
 async apply(remediationId:string,confirmed:boolean){const p=this.previews.get(remediationId);if(!p)throw new DuplicateRemediationError('A current remediation preview is required.','PREVIEW_REQUIRED');if(!confirmed)throw new DuplicateRemediationError('Explicit technician confirmation is required.','CONFIRMATION_REQUIRED');if(this.executing)throw new DuplicateRemediationError('Duplicate remediation runs one device at a time.','SERIAL_EXECUTION_REQUIRED');const c=await this.get(p.collisionId),d=this.device(c,p.deviceId),item=c.devices!.find(x=>x.deviceId===d.id)!;if(!item.targetable||item.provider!==p.provider)throw new DuplicateRemediationError('Targetability or provider changed; build a new preview.','TARGETABILITY_LOST');this.executing=remediationId;item.state='APPLYING';c.state='APPLYING';this.db.recordCollision(c);try{if(this.cancelled.has(remediationId))throw new DuplicateRemediationError('Remediation cancelled before write.','CANCELLED');const result=await this.network.apply(p.networkPlanId,true);c.state='VERIFYING';const current=this.db.getDeviceById(d.id),identityMatched=Boolean(result.verified&&current?.id===d.id&&current.network.ipAddress===p.target.ipAddress),remaining=this.db.getDevices().filter(x=>x.id!==d.id&&x.network.ipAddress===p.sharedIp&&active(x)),originalIpRechecked=true,verified=identityMatched;item.verification={verified,identityMatched,originalIpRechecked,message:verified?'Stable identity verified at the replacement IP.':'Write result did not prove the expected identity at the replacement IP.',at:new Date().toISOString()};item.state=verified?'VERIFIED':'FAILED';c.collidingDevices=c.deviceIds!.map(id=>this.db.getDeviceById(id)).filter((x):x is Device=>Boolean(x));c.resolved=verified&&remaining.length<2;c.state=c.resolved?'RESOLVED':verified?'PARTIALLY_RESOLVED':'FAILED';c.ambiguity=c.resolved?'CLEAR':remaining.length>1?'IDENTITIES_KNOWN_RESPONSES_AMBIGUOUS':'ONE_UNIQUELY_TARGETABLE';c.updatedAt=new Date().toISOString();this.db.recordCollision(c);this.audit(c,p,result,verified);return{collision:structuredClone(c),result,verified,identityMatched,originalIpRechecked,pairRequired:false}}catch(error){item.state=(error as DuplicateRemediationError).code==='CANCELLED'?'CANCELLED':'FAILED';c.state=item.state==='CANCELLED'?'CANCELLED':'FAILED';c.updatedAt=new Date().toISOString();this.db.recordCollision(c);this.audit(c,p,undefined,false,(error as Error).message);throw error}finally{this.executing=null;this.previews.delete(remediationId);this.cancelled.delete(remediationId)}}
 cancel(remediationId:string){const p=this.previews.get(remediationId);if(!p)return false;if(this.executing===remediationId){this.cancelled.add(remediationId);return false}this.network.cancel(p.deviceId);this.network.revokeDuplicateAuthorization?.(p.deviceId);this.previews.delete(remediationId);this.cancelled.add(remediationId);return true}
 async retry(collisionId:string,deviceId:string,credentialId:string,target:NetworkTarget){const c=this.collision(collisionId),item=c.devices?.find(x=>x.deviceId===deviceId);if(item?.state==='VERIFIED')throw new DuplicateRemediationError('A verified remediation is not repeated.','ALREADY_VERIFIED');return this.preview(collisionId,deviceId,credentialId,target)}
 async afterRescan(collisionId:string){return this.get(collisionId)}
 private audit(c:IPCollisionRecord,p:DuplicateRemediationPreview,result?:CameraNetworkResult,verified=false,error?:string){appStateDb.logAudit({id:crypto.randomUUID(),timestamp:new Date().toISOString(),category:'EDGE_CASE',level:verified?'SUCCESS':error?'ERROR':'WARNING',message:'Duplicate IP remediation.',deviceId:p.deviceId,details:{collisionId:c.id,oldSharedIp:p.sharedIp,targetIp:p.target.ipAddress,provider:p.provider,confirmed:true,applyResult:result?.state,verified,collisionResult:c.state,error}})}
}
